// @generated by @trezor/protobuf/protoc-gen-plugin 1.0.0
// source: messages-ripple.proto
// DO NOT EDIT
import type { DescFile } from '@bufbuild/protobuf';

export declare const file_messages_ripple: DescFile;
