// @generated by @trezor/protobuf/protoc-gen-plugin 1.0.0
// source: messages-authdb.proto
// DO NOT EDIT
import { type Static, Type } from '@trezor/schema-utils';

export type AuthDbSetRoot = Static<typeof AuthDbSetRoot>;
export const AuthDbSetRoot = Type.Object(
    {
        root: Type.String(),
    },
    { $id: 'AuthDbSetRoot' },
);

export type AuthDbSetRootResponse = Static<typeof AuthDbSetRootResponse>;
export const AuthDbSetRootResponse = Type.Object(
    {
        counter: Type.Number(),
        identifier: Type.Optional(Type.String()),
    },
    { $id: 'AuthDbSetRootResponse' },
);

export type AuthDbLookup = Static<typeof AuthDbLookup>;
export const AuthDbLookup = Type.Object(
    {
        address: Type.String(),
        value: Type.Optional(Type.String()),
        proof: Type.Optional(Type.Array(Type.String())),
        witness_address: Type.Optional(Type.String()),
        witness_value: Type.Optional(Type.String()),
    },
    { $id: 'AuthDbLookup' },
);

export type AuthDbLookupResponse = Static<typeof AuthDbLookupResponse>;
export const AuthDbLookupResponse = Type.Object(
    {
        valid: Type.Boolean(),
        counter: Type.Number(),
        membership: Type.Optional(Type.Boolean()),
        identifier: Type.Optional(Type.String()),
    },
    { $id: 'AuthDbLookupResponse' },
);

export type AuthDbUpdateLeaf = Static<typeof AuthDbUpdateLeaf>;
export const AuthDbUpdateLeaf = Type.Object(
    {
        address: Type.String(),
        old_value: Type.String(),
        new_value: Type.String(),
        proof: Type.Optional(Type.Array(Type.String())),
        witness_address: Type.Optional(Type.String()),
        witness_value: Type.Optional(Type.String()),
    },
    { $id: 'AuthDbUpdateLeaf' },
);

export type AuthDbUpdateLeafResponse = Static<typeof AuthDbUpdateLeafResponse>;
export const AuthDbUpdateLeafResponse = Type.Object(
    {
        counter: Type.Number(),
        new_root: Type.Optional(Type.String()),
        identifier: Type.Optional(Type.String()),
    },
    { $id: 'AuthDbUpdateLeafResponse' },
);

export type AuthDbClearRoot = Static<typeof AuthDbClearRoot>;
export const AuthDbClearRoot = Type.Object({}, { $id: 'AuthDbClearRoot' });

export type AuthDbClearRootResponse = Static<typeof AuthDbClearRootResponse>;
export const AuthDbClearRootResponse = Type.Object(
    {
        identifier: Type.Optional(Type.String()),
    },
    { $id: 'AuthDbClearRootResponse' },
);
