// @generated by @trezor/protobuf/protoc-gen-plugin 1.0.0
// source: messages-eos.proto
// DO NOT EDIT
import { type Static, Type } from '@trezor/schema-utils';

export type EosAsset = Static<typeof EosAsset>;
export const EosAsset = Type.Object(
    {
        amount: Type.Uint(),
        symbol: Type.String(),
    },
    { $id: 'EosAsset' },
);

export type EosActionBuyRam = Static<typeof EosActionBuyRam>;
export const EosActionBuyRam = Type.Object(
    {
        payer: Type.String(),
        receiver: Type.String(),
        quantity: EosAsset,
    },
    { $id: 'EosActionBuyRam' },
);

export type EosActionBuyRamBytes = Static<typeof EosActionBuyRamBytes>;
export const EosActionBuyRamBytes = Type.Object(
    {
        payer: Type.String(),
        receiver: Type.String(),
        bytes: Type.Number(),
    },
    { $id: 'EosActionBuyRamBytes' },
);

export type EosPermissionLevel = Static<typeof EosPermissionLevel>;
export const EosPermissionLevel = Type.Object(
    {
        actor: Type.String(),
        permission: Type.String(),
    },
    { $id: 'EosPermissionLevel' },
);

export type EosActionCommon = Static<typeof EosActionCommon>;
export const EosActionCommon = Type.Object(
    {
        account: Type.String(),
        name: Type.String(),
        authorization: Type.Array(EosPermissionLevel),
    },
    { $id: 'EosActionCommon' },
);

export type EosActionDelegate = Static<typeof EosActionDelegate>;
export const EosActionDelegate = Type.Object(
    {
        sender: Type.String(),
        receiver: Type.String(),
        net_quantity: EosAsset,
        cpu_quantity: EosAsset,
        transfer: Type.Boolean(),
    },
    { $id: 'EosActionDelegate' },
);

export type EosActionDeleteAuth = Static<typeof EosActionDeleteAuth>;
export const EosActionDeleteAuth = Type.Object(
    {
        account: Type.String(),
        permission: Type.String(),
    },
    { $id: 'EosActionDeleteAuth' },
);

export type EosActionLinkAuth = Static<typeof EosActionLinkAuth>;
export const EosActionLinkAuth = Type.Object(
    {
        account: Type.String(),
        code: Type.String(),
        type: Type.String(),
        requirement: Type.String(),
    },
    { $id: 'EosActionLinkAuth' },
);

export type EosAuthorizationKey = Static<typeof EosAuthorizationKey>;
export const EosAuthorizationKey = Type.Object(
    {
        type: Type.Optional(Type.Number()),
        key: Type.String(),
        address_n: Type.Optional(Type.Array(Type.Number())),
        weight: Type.Number(),
    },
    { $id: 'EosAuthorizationKey' },
);

export type EosAuthorizationAccount = Static<typeof EosAuthorizationAccount>;
export const EosAuthorizationAccount = Type.Object(
    {
        account: EosPermissionLevel,
        weight: Type.Number(),
    },
    { $id: 'EosAuthorizationAccount' },
);

export type EosAuthorizationWait = Static<typeof EosAuthorizationWait>;
export const EosAuthorizationWait = Type.Object(
    {
        wait_sec: Type.Number(),
        weight: Type.Number(),
    },
    { $id: 'EosAuthorizationWait' },
);

export type EosAuthorization = Static<typeof EosAuthorization>;
export const EosAuthorization = Type.Object(
    {
        threshold: Type.Number(),
        keys: Type.Array(EosAuthorizationKey),
        accounts: Type.Array(EosAuthorizationAccount),
        waits: Type.Array(EosAuthorizationWait),
    },
    { $id: 'EosAuthorization' },
);

export type EosActionNewAccount = Static<typeof EosActionNewAccount>;
export const EosActionNewAccount = Type.Object(
    {
        creator: Type.String(),
        name: Type.String(),
        owner: EosAuthorization,
        active: EosAuthorization,
    },
    { $id: 'EosActionNewAccount' },
);

export type EosActionRefund = Static<typeof EosActionRefund>;
export const EosActionRefund = Type.Object(
    {
        owner: Type.String(),
    },
    { $id: 'EosActionRefund' },
);

export type EosActionSellRam = Static<typeof EosActionSellRam>;
export const EosActionSellRam = Type.Object(
    {
        account: Type.String(),
        bytes: Type.Number(),
    },
    { $id: 'EosActionSellRam' },
);

export type EosActionTransfer = Static<typeof EosActionTransfer>;
export const EosActionTransfer = Type.Object(
    {
        sender: Type.String(),
        receiver: Type.String(),
        quantity: EosAsset,
        memo: Type.String(),
    },
    { $id: 'EosActionTransfer' },
);

export type EosActionUndelegate = Static<typeof EosActionUndelegate>;
export const EosActionUndelegate = Type.Object(
    {
        sender: Type.String(),
        receiver: Type.String(),
        net_quantity: EosAsset,
        cpu_quantity: EosAsset,
    },
    { $id: 'EosActionUndelegate' },
);

export type EosActionUnknown = Static<typeof EosActionUnknown>;
export const EosActionUnknown = Type.Object(
    {
        data_size: Type.Number(),
        data_chunk: Type.String(),
    },
    { $id: 'EosActionUnknown' },
);

export type EosActionUnlinkAuth = Static<typeof EosActionUnlinkAuth>;
export const EosActionUnlinkAuth = Type.Object(
    {
        account: Type.String(),
        code: Type.String(),
        type: Type.String(),
    },
    { $id: 'EosActionUnlinkAuth' },
);

export type EosActionUpdateAuth = Static<typeof EosActionUpdateAuth>;
export const EosActionUpdateAuth = Type.Object(
    {
        account: Type.String(),
        permission: Type.String(),
        parent: Type.String(),
        auth: EosAuthorization,
    },
    { $id: 'EosActionUpdateAuth' },
);

export type EosActionVoteProducer = Static<typeof EosActionVoteProducer>;
export const EosActionVoteProducer = Type.Object(
    {
        voter: Type.String(),
        proxy: Type.String(),
        producers: Type.Array(Type.String()),
    },
    { $id: 'EosActionVoteProducer' },
);

export type EosGetPublicKey = Static<typeof EosGetPublicKey>;
export const EosGetPublicKey = Type.Object(
    {
        address_n: Type.Array(Type.Number()),
        show_display: Type.Optional(Type.Boolean()),
        chunkify: Type.Optional(Type.Boolean()),
    },
    { $id: 'EosGetPublicKey' },
);

export type EosPublicKey = Static<typeof EosPublicKey>;
export const EosPublicKey = Type.Object(
    {
        wif_public_key: Type.String(),
        raw_public_key: Type.String(),
    },
    { $id: 'EosPublicKey' },
);

export type EosSignedTx = Static<typeof EosSignedTx>;
export const EosSignedTx = Type.Object(
    {
        signature: Type.String(),
    },
    { $id: 'EosSignedTx' },
);

export type EosTxHeader = Static<typeof EosTxHeader>;
export const EosTxHeader = Type.Object(
    {
        expiration: Type.Number(),
        ref_block_num: Type.Number(),
        ref_block_prefix: Type.Number(),
        max_net_usage_words: Type.Number(),
        max_cpu_usage_ms: Type.Number(),
        delay_sec: Type.Number(),
    },
    { $id: 'EosTxHeader' },
);

export type EosSignTx = Static<typeof EosSignTx>;
export const EosSignTx = Type.Object(
    {
        address_n: Type.Array(Type.Number()),
        chain_id: Type.String(),
        header: EosTxHeader,
        num_actions: Type.Number(),
        chunkify: Type.Optional(Type.Boolean()),
    },
    { $id: 'EosSignTx' },
);

export type EosTxActionAck = Static<typeof EosTxActionAck>;
export const EosTxActionAck = Type.Object(
    {
        common: EosActionCommon,
        transfer: Type.Optional(EosActionTransfer),
        delegate: Type.Optional(EosActionDelegate),
        undelegate: Type.Optional(EosActionUndelegate),
        refund: Type.Optional(EosActionRefund),
        buy_ram: Type.Optional(EosActionBuyRam),
        buy_ram_bytes: Type.Optional(EosActionBuyRamBytes),
        sell_ram: Type.Optional(EosActionSellRam),
        vote_producer: Type.Optional(EosActionVoteProducer),
        update_auth: Type.Optional(EosActionUpdateAuth),
        delete_auth: Type.Optional(EosActionDeleteAuth),
        link_auth: Type.Optional(EosActionLinkAuth),
        unlink_auth: Type.Optional(EosActionUnlinkAuth),
        new_account: Type.Optional(EosActionNewAccount),
        unknown: Type.Optional(EosActionUnknown),
    },
    { $id: 'EosTxActionAck' },
);

export type EosTxActionRequest = Static<typeof EosTxActionRequest>;
export const EosTxActionRequest = Type.Object(
    {
        data_size: Type.Optional(Type.Number()),
    },
    { $id: 'EosTxActionRequest' },
);
