// @generated by @trezor/protobuf/protoc-gen-plugin 1.0.0
// source: messages-authdb.proto
// DO NOT EDIT
import { type Static, Type } from '@trezor/schema-utils';

export type AuthDbInit = Static<typeof AuthDbInit>;
export const AuthDbInit = Type.Object(
    {
        qm_counter: Type.Number(),
        qm_signature: Type.String(),
        root: Type.Optional(Type.String()),
        counter: Type.Optional(Type.Number()),
        root_mac: Type.Optional(Type.String()),
    },
    { $id: 'AuthDbInit' },
);

export type AuthDbInitResponse = Static<typeof AuthDbInitResponse>;
export const AuthDbInitResponse = Type.Object(
    {
        qm_last_counter: Type.Number(),
        wallet_id: Type.Optional(Type.String()),
        counter: Type.Optional(Type.Number()),
        root: Type.Optional(Type.String()),
        root_mac: Type.Optional(Type.String()),
    },
    { $id: 'AuthDbInitResponse' },
);

export type AuthDbLookup = Static<typeof AuthDbLookup>;
export const AuthDbLookup = Type.Object(
    {
        address: Type.String(),
        value: Type.Optional(Type.String()),
        proof: Type.Array(Type.String()),
        witness_address: Type.Optional(Type.String()),
        witness_value: Type.Optional(Type.String()),
        counter: Type.Optional(Type.Number()),
        witness_counter: Type.Optional(Type.Number()),
    },
    { $id: 'AuthDbLookup' },
);

export type AuthDbLookupResponse = Static<typeof AuthDbLookupResponse>;
export const AuthDbLookupResponse = Type.Object(
    {
        valid: Type.Boolean(),
        counter: Type.Number(),
        membership: Type.Optional(Type.Boolean()),
        wallet_id: Type.Optional(Type.String()),
    },
    { $id: 'AuthDbLookupResponse' },
);

export type AuthDbSetRoot = Static<typeof AuthDbSetRoot>;
export const AuthDbSetRoot = Type.Object(
    {
        root: Type.String(),
        mac: Type.String(),
        device_id: Type.Optional(Type.String()),
        counter: Type.Optional(Type.Number()),
    },
    { $id: 'AuthDbSetRoot' },
);

export type AuthDbSetRootResponse = Static<typeof AuthDbSetRootResponse>;
export const AuthDbSetRootResponse = Type.Object(
    {
        counter: Type.Number(),
        wallet_id: Type.Optional(Type.String()),
        new_root: Type.Optional(Type.String()),
        root_mac: Type.Optional(Type.String()),
    },
    { $id: 'AuthDbSetRootResponse' },
);

export type AuthDbUpdateLeaf = Static<typeof AuthDbUpdateLeaf>;
export const AuthDbUpdateLeaf = Type.Object(
    {
        address: Type.String(),
        old_value: Type.String(),
        new_value: Type.String(),
        proof: Type.Array(Type.String()),
        witness_address: Type.Optional(Type.String()),
        witness_value: Type.Optional(Type.String()),
        old_counter: Type.Optional(Type.Number()),
        new_counter: Type.Number(),
        witness_counter: Type.Optional(Type.Number()),
    },
    { $id: 'AuthDbUpdateLeaf' },
);

export type AuthDbUpdateLeafResponse = Static<typeof AuthDbUpdateLeafResponse>;
export const AuthDbUpdateLeafResponse = Type.Object(
    {
        counter: Type.Number(),
        new_root: Type.Optional(Type.String()),
        wallet_id: Type.Optional(Type.String()),
        mac: Type.Optional(Type.String()),
    },
    { $id: 'AuthDbUpdateLeafResponse' },
);
