// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts,json_types=true"
// @generated from file messages.proto (package hw.trezor.messages, syntax proto2)

import type { GenEnum, GenFile } from '@bufbuild/protobuf/codegenv2';

/**
 * Describes the file messages.proto.
 */
export declare const file_messages: GenFile;

/**
 * *
 * Mapping between Trezor wire identifier (uint) and a protobuf message
 *
 * @generated from enum hw.trezor.messages.MessageType
 */
export enum MessageType {
    /**
     * Management
     *
     * @generated from enum value: MessageType_Initialize = 0;
     */
    MessageType_Initialize = 0,

    /**
     * @generated from enum value: MessageType_Ping = 1;
     */
    MessageType_Ping = 1,

    /**
     * @generated from enum value: MessageType_Success = 2;
     */
    MessageType_Success = 2,

    /**
     * @generated from enum value: MessageType_Failure = 3;
     */
    MessageType_Failure = 3,

    /**
     * @generated from enum value: MessageType_ChangePin = 4;
     */
    MessageType_ChangePin = 4,

    /**
     * @generated from enum value: MessageType_WipeDevice = 5;
     */
    MessageType_WipeDevice = 5,

    /**
     * @generated from enum value: MessageType_GetEntropy = 9;
     */
    MessageType_GetEntropy = 9,

    /**
     * @generated from enum value: MessageType_Entropy = 10;
     */
    MessageType_Entropy = 10,

    /**
     * @generated from enum value: MessageType_LoadDevice = 13;
     */
    MessageType_LoadDevice = 13,

    /**
     * @generated from enum value: MessageType_ResetDevice = 14;
     */
    MessageType_ResetDevice = 14,

    /**
     * @generated from enum value: MessageType_SetBusy = 16;
     */
    MessageType_SetBusy = 16,

    /**
     * @generated from enum value: MessageType_Features = 17;
     */
    MessageType_Features = 17,

    /**
     * @generated from enum value: MessageType_PinMatrixRequest = 18;
     */
    MessageType_PinMatrixRequest = 18,

    /**
     * @generated from enum value: MessageType_PinMatrixAck = 19;
     */
    MessageType_PinMatrixAck = 19,

    /**
     * @generated from enum value: MessageType_Cancel = 20;
     */
    MessageType_Cancel = 20,

    /**
     * @generated from enum value: MessageType_LockDevice = 24;
     */
    MessageType_LockDevice = 24,

    /**
     * @generated from enum value: MessageType_ApplySettings = 25;
     */
    MessageType_ApplySettings = 25,

    /**
     * @generated from enum value: MessageType_ButtonRequest = 26;
     */
    MessageType_ButtonRequest = 26,

    /**
     * @generated from enum value: MessageType_ButtonAck = 27;
     */
    MessageType_ButtonAck = 27,

    /**
     * @generated from enum value: MessageType_ApplyFlags = 28;
     */
    MessageType_ApplyFlags = 28,

    /**
     * @generated from enum value: MessageType_GetNonce = 31;
     */
    MessageType_GetNonce = 31,

    /**
     * @generated from enum value: MessageType_Nonce = 33;
     */
    MessageType_Nonce = 33,

    /**
     * @generated from enum value: MessageType_BackupDevice = 34;
     */
    MessageType_BackupDevice = 34,

    /**
     * @generated from enum value: MessageType_EntropyRequest = 35;
     */
    MessageType_EntropyRequest = 35,

    /**
     * @generated from enum value: MessageType_EntropyAck = 36;
     */
    MessageType_EntropyAck = 36,

    /**
     * @generated from enum value: MessageType_PaymentRequest = 37;
     */
    MessageType_PaymentRequest = 37,

    /**
     * @generated from enum value: MessageType_EntropyCheckReady = 994;
     */
    MessageType_EntropyCheckReady = 994,

    /**
     * @generated from enum value: MessageType_EntropyCheckContinue = 995;
     */
    MessageType_EntropyCheckContinue = 995,

    /**
     * @generated from enum value: MessageType_PassphraseRequest = 41;
     */
    MessageType_PassphraseRequest = 41,

    /**
     * @generated from enum value: MessageType_PassphraseAck = 42;
     */
    MessageType_PassphraseAck = 42,

    /**
     * @generated from enum value: MessageType_RecoveryDevice = 45;
     */
    MessageType_RecoveryDevice = 45,

    /**
     * @generated from enum value: MessageType_WordRequest = 46;
     */
    MessageType_WordRequest = 46,

    /**
     * @generated from enum value: MessageType_WordAck = 47;
     */
    MessageType_WordAck = 47,

    /**
     * @generated from enum value: MessageType_GetFeatures = 55;
     */
    MessageType_GetFeatures = 55,

    /**
     * @generated from enum value: MessageType_SdProtect = 79;
     */
    MessageType_SdProtect = 79,

    /**
     * @generated from enum value: MessageType_ChangeWipeCode = 82;
     */
    MessageType_ChangeWipeCode = 82,

    /**
     * @generated from enum value: MessageType_EndSession = 83;
     */
    MessageType_EndSession = 83,

    /**
     * @generated from enum value: MessageType_DoPreauthorized = 84;
     */
    MessageType_DoPreauthorized = 84,

    /**
     * @generated from enum value: MessageType_PreauthorizedRequest = 85;
     */
    MessageType_PreauthorizedRequest = 85,

    /**
     * @generated from enum value: MessageType_CancelAuthorization = 86;
     */
    MessageType_CancelAuthorization = 86,

    /**
     * @generated from enum value: MessageType_RebootToBootloader = 87;
     */
    MessageType_RebootToBootloader = 87,

    /**
     * @generated from enum value: MessageType_GetFirmwareHash = 88;
     */
    MessageType_GetFirmwareHash = 88,

    /**
     * @generated from enum value: MessageType_FirmwareHash = 89;
     */
    MessageType_FirmwareHash = 89,

    /**
     * @generated from enum value: MessageType_UnlockPath = 93;
     */
    MessageType_UnlockPath = 93,

    /**
     * @generated from enum value: MessageType_UnlockedPathRequest = 94;
     */
    MessageType_UnlockedPathRequest = 94,

    /**
     * @generated from enum value: MessageType_ShowDeviceTutorial = 95;
     */
    MessageType_ShowDeviceTutorial = 95,

    /**
     * @generated from enum value: MessageType_UnlockBootloader = 96;
     */
    MessageType_UnlockBootloader = 96,

    /**
     * @generated from enum value: MessageType_AuthenticateDevice = 97;
     */
    MessageType_AuthenticateDevice = 97,

    /**
     * @generated from enum value: MessageType_AuthenticityProof = 98;
     */
    MessageType_AuthenticityProof = 98,

    /**
     * @generated from enum value: MessageType_AuthenticityProofSizes = 99;
     */
    MessageType_AuthenticityProofSizes = 99,

    /**
     * @generated from enum value: MessageType_ChangeLanguage = 990;
     */
    MessageType_ChangeLanguage = 990,

    /**
     * @generated from enum value: MessageType_DataChunkRequest = 991;
     */
    MessageType_DataChunkRequest = 991,

    /**
     * @generated from enum value: MessageType_DataChunkAck = 992;
     */
    MessageType_DataChunkAck = 992,

    /**
     * @generated from enum value: MessageType_SetBrightness = 993;
     */
    MessageType_SetBrightness = 993,

    /**
     * @generated from enum value: MessageType_GetSerialNumber = 996;
     */
    MessageType_GetSerialNumber = 996,

    /**
     * @generated from enum value: MessageType_SerialNumber = 997;
     */
    MessageType_SerialNumber = 997,

    /**
     * @generated from enum value: MessageType_GetAuthenticityProofChunk = 998;
     */
    MessageType_GetAuthenticityProofChunk = 998,

    /**
     * @generated from enum value: MessageType_AuthenticityProofChunk = 999;
     */
    MessageType_AuthenticityProofChunk = 999,

    /**
     * @generated from enum value: MessageType_SetU2FCounter = 63;
     */
    MessageType_SetU2FCounter = 63,

    /**
     * @generated from enum value: MessageType_GetNextU2FCounter = 80;
     */
    MessageType_GetNextU2FCounter = 80,

    /**
     * @generated from enum value: MessageType_NextU2FCounter = 81;
     */
    MessageType_NextU2FCounter = 81,

    /**
     * Bootloader
     *
     * @generated from enum value: MessageType_FirmwareErase = 6;
     */
    MessageType_FirmwareErase = 6,

    /**
     * @generated from enum value: MessageType_FirmwareUpload = 7;
     */
    MessageType_FirmwareUpload = 7,

    /**
     * @generated from enum value: MessageType_FirmwareRequest = 8;
     */
    MessageType_FirmwareRequest = 8,

    /**
     * @generated from enum value: MessageType_ProdTestT1 = 32;
     */
    MessageType_ProdTestT1 = 32,

    /**
     * BLE
     *
     * @generated from enum value: MessageType_BleUnpair = 8001;
     */
    MessageType_BleUnpair = 8001,

    /**
     * Bitcoin
     *
     * @generated from enum value: MessageType_GetPublicKey = 11;
     */
    MessageType_GetPublicKey = 11,

    /**
     * @generated from enum value: MessageType_PublicKey = 12;
     */
    MessageType_PublicKey = 12,

    /**
     * @generated from enum value: MessageType_SignTx = 15;
     */
    MessageType_SignTx = 15,

    /**
     * @generated from enum value: MessageType_TxRequest = 21;
     */
    MessageType_TxRequest = 21,

    /**
     * @generated from enum value: MessageType_TxAck = 22;
     */
    MessageType_TxAck = 22,

    /**
     * @generated from enum value: MessageType_GetAddress = 29;
     */
    MessageType_GetAddress = 29,

    /**
     * @generated from enum value: MessageType_Address = 30;
     */
    MessageType_Address = 30,

    /**
     * @generated from enum value: MessageType_SignMessage = 38;
     */
    MessageType_SignMessage = 38,

    /**
     * @generated from enum value: MessageType_VerifyMessage = 39;
     */
    MessageType_VerifyMessage = 39,

    /**
     * @generated from enum value: MessageType_MessageSignature = 40;
     */
    MessageType_MessageSignature = 40,

    /**
     * @generated from enum value: MessageType_GetOwnershipId = 43;
     */
    MessageType_GetOwnershipId = 43,

    /**
     * @generated from enum value: MessageType_OwnershipId = 44;
     */
    MessageType_OwnershipId = 44,

    /**
     * @generated from enum value: MessageType_GetOwnershipProof = 49;
     */
    MessageType_GetOwnershipProof = 49,

    /**
     * @generated from enum value: MessageType_OwnershipProof = 50;
     */
    MessageType_OwnershipProof = 50,

    /**
     * @generated from enum value: MessageType_AuthorizeCoinJoin = 51;
     */
    MessageType_AuthorizeCoinJoin = 51,

    /**
     * Crypto
     *
     * @generated from enum value: MessageType_CipherKeyValue = 23;
     */
    MessageType_CipherKeyValue = 23,

    /**
     * @generated from enum value: MessageType_CipheredKeyValue = 48;
     */
    MessageType_CipheredKeyValue = 48,

    /**
     * @generated from enum value: MessageType_SignIdentity = 53;
     */
    MessageType_SignIdentity = 53,

    /**
     * @generated from enum value: MessageType_SignedIdentity = 54;
     */
    MessageType_SignedIdentity = 54,

    /**
     * @generated from enum value: MessageType_GetECDHSessionKey = 61;
     */
    MessageType_GetECDHSessionKey = 61,

    /**
     * @generated from enum value: MessageType_ECDHSessionKey = 62;
     */
    MessageType_ECDHSessionKey = 62,

    /**
     * dropped: CosiCommit, CosiCommitment, CosiSign, CosiSignature
     *
     * @generated from enum value: MessageType_PaymentNotification = 52;
     */
    MessageType_PaymentNotification = 52,

    /**
     * Debug
     *
     * @generated from enum value: MessageType_DebugLinkDecision = 100;
     */
    MessageType_DebugLinkDecision = 100,

    /**
     * @generated from enum value: MessageType_DebugLinkGetState = 101;
     */
    MessageType_DebugLinkGetState = 101,

    /**
     * @generated from enum value: MessageType_DebugLinkState = 102;
     */
    MessageType_DebugLinkState = 102,

    /**
     * @generated from enum value: MessageType_DebugLinkStop = 103;
     */
    MessageType_DebugLinkStop = 103,

    /**
     * @generated from enum value: MessageType_DebugLinkLog = 104;
     */
    MessageType_DebugLinkLog = 104,

    /**
     * @generated from enum value: MessageType_DebugLinkMemoryRead = 110;
     */
    MessageType_DebugLinkMemoryRead = 110,

    /**
     * @generated from enum value: MessageType_DebugLinkMemory = 111;
     */
    MessageType_DebugLinkMemory = 111,

    /**
     * @generated from enum value: MessageType_DebugLinkMemoryWrite = 112;
     */
    MessageType_DebugLinkMemoryWrite = 112,

    /**
     * @generated from enum value: MessageType_DebugLinkFlashErase = 113;
     */
    MessageType_DebugLinkFlashErase = 113,

    /**
     * @generated from enum value: MessageType_DebugLinkLayout = 9001;
     */
    MessageType_DebugLinkLayout = 9001,

    /**
     * @generated from enum value: MessageType_DebugLinkReseedRandom = 9002;
     */
    MessageType_DebugLinkReseedRandom = 9002,

    /**
     * @generated from enum value: MessageType_DebugLinkRecordScreen = 9003;
     */
    MessageType_DebugLinkRecordScreen = 9003,

    /**
     * @generated from enum value: MessageType_DebugLinkEraseSdCard = 9005;
     */
    MessageType_DebugLinkEraseSdCard = 9005,

    /**
     * @generated from enum value: MessageType_DebugLinkWatchLayout = 9006;
     */
    MessageType_DebugLinkWatchLayout = 9006,

    /**
     * @generated from enum value: MessageType_DebugLinkResetDebugEvents = 9007;
     */
    MessageType_DebugLinkResetDebugEvents = 9007,

    /**
     * @generated from enum value: MessageType_DebugLinkOptigaSetSecMax = 9008;
     */
    MessageType_DebugLinkOptigaSetSecMax = 9008,

    /**
     * @generated from enum value: MessageType_DebugLinkGetGcInfo = 9009;
     */
    MessageType_DebugLinkGetGcInfo = 9009,

    /**
     * @generated from enum value: MessageType_DebugLinkGcInfo = 9010;
     */
    MessageType_DebugLinkGcInfo = 9010,

    /**
     * @generated from enum value: MessageType_DebugLinkGetPairingInfo = 9011;
     */
    MessageType_DebugLinkGetPairingInfo = 9011,

    /**
     * @generated from enum value: MessageType_DebugLinkPairingInfo = 9012;
     */
    MessageType_DebugLinkPairingInfo = 9012,

    /**
     * @generated from enum value: MessageType_DebugLinkSetLogFilter = 9013;
     */
    MessageType_DebugLinkSetLogFilter = 9013,

    /**
     * @generated from enum value: MessageType_DebugLinkN4W1Connected = 9014;
     */
    MessageType_DebugLinkN4W1Connected = 9014,

    /**
     * @generated from enum value: MessageType_DebugLinkN4W1Write = 9015;
     */
    MessageType_DebugLinkN4W1Write = 9015,

    /**
     * @generated from enum value: MessageType_DebugLinkN4W1Read = 9016;
     */
    MessageType_DebugLinkN4W1Read = 9016,

    /**
     * @generated from enum value: MessageType_DebugLinkN4W1Response = 9017;
     */
    MessageType_DebugLinkN4W1Response = 9017,

    /**
     * @generated from enum value: MessageType_DebugLinkSetBatteryState = 9018;
     */
    MessageType_DebugLinkSetBatteryState = 9018,

    /**
     * Ethereum
     *
     * @generated from enum value: MessageType_EthereumGetPublicKey = 450;
     */
    MessageType_EthereumGetPublicKey = 450,

    /**
     * @generated from enum value: MessageType_EthereumPublicKey = 451;
     */
    MessageType_EthereumPublicKey = 451,

    /**
     * @generated from enum value: MessageType_EthereumGetAddress = 56;
     */
    MessageType_EthereumGetAddress = 56,

    /**
     * @generated from enum value: MessageType_EthereumAddress = 57;
     */
    MessageType_EthereumAddress = 57,

    /**
     * @generated from enum value: MessageType_EthereumSignTx = 58;
     */
    MessageType_EthereumSignTx = 58,

    /**
     * @generated from enum value: MessageType_EthereumSignTxEIP1559 = 452;
     */
    MessageType_EthereumSignTxEIP1559 = 452,

    /**
     * @generated from enum value: MessageType_EthereumTxRequest = 59;
     */
    MessageType_EthereumTxRequest = 59,

    /**
     * @generated from enum value: MessageType_EthereumTxAck = 60;
     */
    MessageType_EthereumTxAck = 60,

    /**
     * @generated from enum value: MessageType_EthereumSignMessage = 64;
     */
    MessageType_EthereumSignMessage = 64,

    /**
     * @generated from enum value: MessageType_EthereumVerifyMessage = 65;
     */
    MessageType_EthereumVerifyMessage = 65,

    /**
     * @generated from enum value: MessageType_EthereumMessageSignature = 66;
     */
    MessageType_EthereumMessageSignature = 66,

    /**
     * @generated from enum value: MessageType_EthereumSignTypedData = 464;
     */
    MessageType_EthereumSignTypedData = 464,

    /**
     * @generated from enum value: MessageType_EthereumTypedDataStructRequest = 465;
     */
    MessageType_EthereumTypedDataStructRequest = 465,

    /**
     * @generated from enum value: MessageType_EthereumTypedDataStructAck = 466;
     */
    MessageType_EthereumTypedDataStructAck = 466,

    /**
     * @generated from enum value: MessageType_EthereumTypedDataValueRequest = 467;
     */
    MessageType_EthereumTypedDataValueRequest = 467,

    /**
     * @generated from enum value: MessageType_EthereumTypedDataValueAck = 468;
     */
    MessageType_EthereumTypedDataValueAck = 468,

    /**
     * @generated from enum value: MessageType_EthereumTypedDataSignature = 469;
     */
    MessageType_EthereumTypedDataSignature = 469,

    /**
     * @generated from enum value: MessageType_EthereumSignTypedHash = 470;
     */
    MessageType_EthereumSignTypedHash = 470,

    /**
     * @generated from enum value: MessageType_EthereumDefinitionRequest = 471;
     */
    MessageType_EthereumDefinitionRequest = 471,

    /**
     * @generated from enum value: MessageType_EthereumDefinitionAck = 472;
     */
    MessageType_EthereumDefinitionAck = 472,

    /**
     * NEM
     *
     * @generated from enum value: MessageType_NEMGetAddress = 67;
     */
    MessageType_NEMGetAddress = 67,

    /**
     * @generated from enum value: MessageType_NEMAddress = 68;
     */
    MessageType_NEMAddress = 68,

    /**
     * @generated from enum value: MessageType_NEMSignTx = 69;
     */
    MessageType_NEMSignTx = 69,

    /**
     * @generated from enum value: MessageType_NEMSignedTx = 70;
     */
    MessageType_NEMSignedTx = 70,

    /**
     * @generated from enum value: MessageType_NEMDecryptMessage = 75;
     */
    MessageType_NEMDecryptMessage = 75,

    /**
     * @generated from enum value: MessageType_NEMDecryptedMessage = 76;
     */
    MessageType_NEMDecryptedMessage = 76,

    /**
     * Tezos
     *
     * @generated from enum value: MessageType_TezosGetAddress = 150;
     */
    MessageType_TezosGetAddress = 150,

    /**
     * @generated from enum value: MessageType_TezosAddress = 151;
     */
    MessageType_TezosAddress = 151,

    /**
     * @generated from enum value: MessageType_TezosSignTx = 152;
     */
    MessageType_TezosSignTx = 152,

    /**
     * @generated from enum value: MessageType_TezosSignedTx = 153;
     */
    MessageType_TezosSignedTx = 153,

    /**
     * @generated from enum value: MessageType_TezosGetPublicKey = 154;
     */
    MessageType_TezosGetPublicKey = 154,

    /**
     * @generated from enum value: MessageType_TezosPublicKey = 155;
     */
    MessageType_TezosPublicKey = 155,

    /**
     * Stellar
     *
     * @generated from enum value: MessageType_StellarSignTx = 202;
     */
    MessageType_StellarSignTx = 202,

    /**
     * @generated from enum value: MessageType_StellarTxOpRequest = 203;
     */
    MessageType_StellarTxOpRequest = 203,

    /**
     * @generated from enum value: MessageType_StellarGetAddress = 207;
     */
    MessageType_StellarGetAddress = 207,

    /**
     * @generated from enum value: MessageType_StellarAddress = 208;
     */
    MessageType_StellarAddress = 208,

    /**
     * @generated from enum value: MessageType_StellarCreateAccountOp = 210;
     */
    MessageType_StellarCreateAccountOp = 210,

    /**
     * @generated from enum value: MessageType_StellarPaymentOp = 211;
     */
    MessageType_StellarPaymentOp = 211,

    /**
     * @generated from enum value: MessageType_StellarPathPaymentStrictReceiveOp = 212;
     */
    MessageType_StellarPathPaymentStrictReceiveOp = 212,

    /**
     * @generated from enum value: MessageType_StellarManageSellOfferOp = 213;
     */
    MessageType_StellarManageSellOfferOp = 213,

    /**
     * @generated from enum value: MessageType_StellarCreatePassiveSellOfferOp = 214;
     */
    MessageType_StellarCreatePassiveSellOfferOp = 214,

    /**
     * @generated from enum value: MessageType_StellarSetOptionsOp = 215;
     */
    MessageType_StellarSetOptionsOp = 215,

    /**
     * @generated from enum value: MessageType_StellarChangeTrustOp = 216;
     */
    MessageType_StellarChangeTrustOp = 216,

    /**
     * @generated from enum value: MessageType_StellarAllowTrustOp = 217;
     */
    MessageType_StellarAllowTrustOp = 217,

    /**
     * @generated from enum value: MessageType_StellarAccountMergeOp = 218;
     */
    MessageType_StellarAccountMergeOp = 218,

    /**
     * @generated from enum value: MessageType_StellarManageDataOp = 220;
     */
    MessageType_StellarManageDataOp = 220,

    /**
     * @generated from enum value: MessageType_StellarBumpSequenceOp = 221;
     */
    MessageType_StellarBumpSequenceOp = 221,

    /**
     * @generated from enum value: MessageType_StellarManageBuyOfferOp = 222;
     */
    MessageType_StellarManageBuyOfferOp = 222,

    /**
     * @generated from enum value: MessageType_StellarPathPaymentStrictSendOp = 223;
     */
    MessageType_StellarPathPaymentStrictSendOp = 223,

    /**
     * @generated from enum value: MessageType_StellarClaimClaimableBalanceOp = 225;
     */
    MessageType_StellarClaimClaimableBalanceOp = 225,

    /**
     * @generated from enum value: MessageType_StellarSignedTx = 230;
     */
    MessageType_StellarSignedTx = 230,

    /**
     * @generated from enum value: MessageType_CardanoGetPublicKey = 305;
     */
    MessageType_CardanoGetPublicKey = 305,

    /**
     * @generated from enum value: MessageType_CardanoPublicKey = 306;
     */
    MessageType_CardanoPublicKey = 306,

    /**
     * @generated from enum value: MessageType_CardanoGetAddress = 307;
     */
    MessageType_CardanoGetAddress = 307,

    /**
     * @generated from enum value: MessageType_CardanoAddress = 308;
     */
    MessageType_CardanoAddress = 308,

    /**
     * @generated from enum value: MessageType_CardanoTxItemAck = 313;
     */
    MessageType_CardanoTxItemAck = 313,

    /**
     * @generated from enum value: MessageType_CardanoTxAuxiliaryDataSupplement = 314;
     */
    MessageType_CardanoTxAuxiliaryDataSupplement = 314,

    /**
     * @generated from enum value: MessageType_CardanoTxWitnessRequest = 315;
     */
    MessageType_CardanoTxWitnessRequest = 315,

    /**
     * @generated from enum value: MessageType_CardanoTxWitnessResponse = 316;
     */
    MessageType_CardanoTxWitnessResponse = 316,

    /**
     * @generated from enum value: MessageType_CardanoTxHostAck = 317;
     */
    MessageType_CardanoTxHostAck = 317,

    /**
     * @generated from enum value: MessageType_CardanoTxBodyHash = 318;
     */
    MessageType_CardanoTxBodyHash = 318,

    /**
     * @generated from enum value: MessageType_CardanoSignTxFinished = 319;
     */
    MessageType_CardanoSignTxFinished = 319,

    /**
     * @generated from enum value: MessageType_CardanoSignTxInit = 320;
     */
    MessageType_CardanoSignTxInit = 320,

    /**
     * @generated from enum value: MessageType_CardanoTxInput = 321;
     */
    MessageType_CardanoTxInput = 321,

    /**
     * @generated from enum value: MessageType_CardanoTxOutput = 322;
     */
    MessageType_CardanoTxOutput = 322,

    /**
     * @generated from enum value: MessageType_CardanoAssetGroup = 323;
     */
    MessageType_CardanoAssetGroup = 323,

    /**
     * @generated from enum value: MessageType_CardanoToken = 324;
     */
    MessageType_CardanoToken = 324,

    /**
     * @generated from enum value: MessageType_CardanoTxCertificate = 325;
     */
    MessageType_CardanoTxCertificate = 325,

    /**
     * @generated from enum value: MessageType_CardanoTxWithdrawal = 326;
     */
    MessageType_CardanoTxWithdrawal = 326,

    /**
     * @generated from enum value: MessageType_CardanoTxAuxiliaryData = 327;
     */
    MessageType_CardanoTxAuxiliaryData = 327,

    /**
     * @generated from enum value: MessageType_CardanoPoolOwner = 328;
     */
    MessageType_CardanoPoolOwner = 328,

    /**
     * @generated from enum value: MessageType_CardanoPoolRelayParameters = 329;
     */
    MessageType_CardanoPoolRelayParameters = 329,

    /**
     * @generated from enum value: MessageType_CardanoGetNativeScriptHash = 330;
     */
    MessageType_CardanoGetNativeScriptHash = 330,

    /**
     * @generated from enum value: MessageType_CardanoNativeScriptHash = 331;
     */
    MessageType_CardanoNativeScriptHash = 331,

    /**
     * @generated from enum value: MessageType_CardanoTxMint = 332;
     */
    MessageType_CardanoTxMint = 332,

    /**
     * @generated from enum value: MessageType_CardanoTxCollateralInput = 333;
     */
    MessageType_CardanoTxCollateralInput = 333,

    /**
     * @generated from enum value: MessageType_CardanoTxRequiredSigner = 334;
     */
    MessageType_CardanoTxRequiredSigner = 334,

    /**
     * @generated from enum value: MessageType_CardanoTxInlineDatumChunk = 335;
     */
    MessageType_CardanoTxInlineDatumChunk = 335,

    /**
     * @generated from enum value: MessageType_CardanoTxReferenceScriptChunk = 336;
     */
    MessageType_CardanoTxReferenceScriptChunk = 336,

    /**
     * @generated from enum value: MessageType_CardanoTxReferenceInput = 337;
     */
    MessageType_CardanoTxReferenceInput = 337,

    /**
     * @generated from enum value: MessageType_CardanoSignMessageInit = 338;
     */
    MessageType_CardanoSignMessageInit = 338,

    /**
     * @generated from enum value: MessageType_CardanoMessageDataRequest = 339;
     */
    MessageType_CardanoMessageDataRequest = 339,

    /**
     * @generated from enum value: MessageType_CardanoMessageDataResponse = 340;
     */
    MessageType_CardanoMessageDataResponse = 340,

    /**
     * @generated from enum value: MessageType_CardanoMessageSignature = 341;
     */
    MessageType_CardanoMessageSignature = 341,

    /**
     * Ripple
     *
     * @generated from enum value: MessageType_RippleGetAddress = 400;
     */
    MessageType_RippleGetAddress = 400,

    /**
     * @generated from enum value: MessageType_RippleAddress = 401;
     */
    MessageType_RippleAddress = 401,

    /**
     * @generated from enum value: MessageType_RippleSignTx = 402;
     */
    MessageType_RippleSignTx = 402,

    /**
     * @generated from enum value: MessageType_RippleSignedTx = 403;
     */
    MessageType_RippleSignedTx = 403,

    /**
     * Monero
     *
     * @generated from enum value: MessageType_MoneroTransactionInitRequest = 501;
     */
    MessageType_MoneroTransactionInitRequest = 501,

    /**
     * @generated from enum value: MessageType_MoneroTransactionInitAck = 502;
     */
    MessageType_MoneroTransactionInitAck = 502,

    /**
     * @generated from enum value: MessageType_MoneroTransactionSetInputRequest = 503;
     */
    MessageType_MoneroTransactionSetInputRequest = 503,

    /**
     * @generated from enum value: MessageType_MoneroTransactionSetInputAck = 504;
     */
    MessageType_MoneroTransactionSetInputAck = 504,

    /**
     * @generated from enum value: MessageType_MoneroTransactionInputViniRequest = 507;
     */
    MessageType_MoneroTransactionInputViniRequest = 507,

    /**
     * @generated from enum value: MessageType_MoneroTransactionInputViniAck = 508;
     */
    MessageType_MoneroTransactionInputViniAck = 508,

    /**
     * @generated from enum value: MessageType_MoneroTransactionAllInputsSetRequest = 509;
     */
    MessageType_MoneroTransactionAllInputsSetRequest = 509,

    /**
     * @generated from enum value: MessageType_MoneroTransactionAllInputsSetAck = 510;
     */
    MessageType_MoneroTransactionAllInputsSetAck = 510,

    /**
     * @generated from enum value: MessageType_MoneroTransactionSetOutputRequest = 511;
     */
    MessageType_MoneroTransactionSetOutputRequest = 511,

    /**
     * @generated from enum value: MessageType_MoneroTransactionSetOutputAck = 512;
     */
    MessageType_MoneroTransactionSetOutputAck = 512,

    /**
     * @generated from enum value: MessageType_MoneroTransactionAllOutSetRequest = 513;
     */
    MessageType_MoneroTransactionAllOutSetRequest = 513,

    /**
     * @generated from enum value: MessageType_MoneroTransactionAllOutSetAck = 514;
     */
    MessageType_MoneroTransactionAllOutSetAck = 514,

    /**
     * @generated from enum value: MessageType_MoneroTransactionSignInputRequest = 515;
     */
    MessageType_MoneroTransactionSignInputRequest = 515,

    /**
     * @generated from enum value: MessageType_MoneroTransactionSignInputAck = 516;
     */
    MessageType_MoneroTransactionSignInputAck = 516,

    /**
     * @generated from enum value: MessageType_MoneroTransactionFinalRequest = 517;
     */
    MessageType_MoneroTransactionFinalRequest = 517,

    /**
     * @generated from enum value: MessageType_MoneroTransactionFinalAck = 518;
     */
    MessageType_MoneroTransactionFinalAck = 518,

    /**
     * @generated from enum value: MessageType_MoneroKeyImageExportInitRequest = 530;
     */
    MessageType_MoneroKeyImageExportInitRequest = 530,

    /**
     * @generated from enum value: MessageType_MoneroKeyImageExportInitAck = 531;
     */
    MessageType_MoneroKeyImageExportInitAck = 531,

    /**
     * @generated from enum value: MessageType_MoneroKeyImageSyncStepRequest = 532;
     */
    MessageType_MoneroKeyImageSyncStepRequest = 532,

    /**
     * @generated from enum value: MessageType_MoneroKeyImageSyncStepAck = 533;
     */
    MessageType_MoneroKeyImageSyncStepAck = 533,

    /**
     * @generated from enum value: MessageType_MoneroKeyImageSyncFinalRequest = 534;
     */
    MessageType_MoneroKeyImageSyncFinalRequest = 534,

    /**
     * @generated from enum value: MessageType_MoneroKeyImageSyncFinalAck = 535;
     */
    MessageType_MoneroKeyImageSyncFinalAck = 535,

    /**
     * @generated from enum value: MessageType_MoneroGetAddress = 540;
     */
    MessageType_MoneroGetAddress = 540,

    /**
     * @generated from enum value: MessageType_MoneroAddress = 541;
     */
    MessageType_MoneroAddress = 541,

    /**
     * @generated from enum value: MessageType_MoneroGetWatchKey = 542;
     */
    MessageType_MoneroGetWatchKey = 542,

    /**
     * @generated from enum value: MessageType_MoneroWatchKey = 543;
     */
    MessageType_MoneroWatchKey = 543,

    /**
     * @generated from enum value: MessageType_DebugMoneroDiagRequest = 546;
     */
    MessageType_DebugMoneroDiagRequest = 546,

    /**
     * @generated from enum value: MessageType_DebugMoneroDiagAck = 547;
     */
    MessageType_DebugMoneroDiagAck = 547,

    /**
     * @generated from enum value: MessageType_MoneroGetTxKeyRequest = 550;
     */
    MessageType_MoneroGetTxKeyRequest = 550,

    /**
     * @generated from enum value: MessageType_MoneroGetTxKeyAck = 551;
     */
    MessageType_MoneroGetTxKeyAck = 551,

    /**
     * @generated from enum value: MessageType_MoneroLiveRefreshStartRequest = 552;
     */
    MessageType_MoneroLiveRefreshStartRequest = 552,

    /**
     * @generated from enum value: MessageType_MoneroLiveRefreshStartAck = 553;
     */
    MessageType_MoneroLiveRefreshStartAck = 553,

    /**
     * @generated from enum value: MessageType_MoneroLiveRefreshStepRequest = 554;
     */
    MessageType_MoneroLiveRefreshStepRequest = 554,

    /**
     * @generated from enum value: MessageType_MoneroLiveRefreshStepAck = 555;
     */
    MessageType_MoneroLiveRefreshStepAck = 555,

    /**
     * @generated from enum value: MessageType_MoneroLiveRefreshFinalRequest = 556;
     */
    MessageType_MoneroLiveRefreshFinalRequest = 556,

    /**
     * @generated from enum value: MessageType_MoneroLiveRefreshFinalAck = 557;
     */
    MessageType_MoneroLiveRefreshFinalAck = 557,

    /**
     * EOS
     *
     * @generated from enum value: MessageType_EosGetPublicKey = 600;
     */
    MessageType_EosGetPublicKey = 600,

    /**
     * @generated from enum value: MessageType_EosPublicKey = 601;
     */
    MessageType_EosPublicKey = 601,

    /**
     * @generated from enum value: MessageType_EosSignTx = 602;
     */
    MessageType_EosSignTx = 602,

    /**
     * @generated from enum value: MessageType_EosTxActionRequest = 603;
     */
    MessageType_EosTxActionRequest = 603,

    /**
     * @generated from enum value: MessageType_EosTxActionAck = 604;
     */
    MessageType_EosTxActionAck = 604,

    /**
     * @generated from enum value: MessageType_EosSignedTx = 605;
     */
    MessageType_EosSignedTx = 605,

    /**
     * WebAuthn
     *
     * @generated from enum value: MessageType_WebAuthnListResidentCredentials = 800;
     */
    MessageType_WebAuthnListResidentCredentials = 800,

    /**
     * @generated from enum value: MessageType_WebAuthnCredentials = 801;
     */
    MessageType_WebAuthnCredentials = 801,

    /**
     * @generated from enum value: MessageType_WebAuthnAddResidentCredential = 802;
     */
    MessageType_WebAuthnAddResidentCredential = 802,

    /**
     * @generated from enum value: MessageType_WebAuthnRemoveResidentCredential = 803;
     */
    MessageType_WebAuthnRemoveResidentCredential = 803,

    /**
     * @generated from enum value: MessageType_WebAuthnCredentialsAck = 804;
     */
    MessageType_WebAuthnCredentialsAck = 804,

    /**
     * Solana
     *
     * @generated from enum value: MessageType_SolanaGetPublicKey = 900;
     */
    MessageType_SolanaGetPublicKey = 900,

    /**
     * @generated from enum value: MessageType_SolanaPublicKey = 901;
     */
    MessageType_SolanaPublicKey = 901,

    /**
     * @generated from enum value: MessageType_SolanaGetAddress = 902;
     */
    MessageType_SolanaGetAddress = 902,

    /**
     * @generated from enum value: MessageType_SolanaAddress = 903;
     */
    MessageType_SolanaAddress = 903,

    /**
     * @generated from enum value: MessageType_SolanaSignTx = 904;
     */
    MessageType_SolanaSignTx = 904,

    /**
     * @generated from enum value: MessageType_SolanaTxSignature = 905;
     */
    MessageType_SolanaTxSignature = 905,

    /**
     * @generated from enum value: MessageType_SolanaSignMessage = 906;
     */
    MessageType_SolanaSignMessage = 906,

    /**
     * @generated from enum value: MessageType_SolanaMessageSignature = 907;
     */
    MessageType_SolanaMessageSignature = 907,

    /**
     * @generated from enum value: MessageType_SolanaVerifyMessage = 908;
     */
    MessageType_SolanaVerifyMessage = 908,

    /**
     * THP
     *
     * @generated from enum value: MessageType_ThpCreateNewSession = 1000;
     */
    MessageType_ThpCreateNewSession = 1000,

    /**
     * @generated from enum value: MessageType_ThpCredentialRequest = 1016;
     */
    MessageType_ThpCredentialRequest = 1016,

    /**
     * @generated from enum value: MessageType_ThpCredentialResponse = 1017;
     */
    MessageType_ThpCredentialResponse = 1017,

    /**
     * Nostr
     *
     * @generated from enum value: MessageType_NostrGetPubkey = 2001;
     */
    MessageType_NostrGetPubkey = 2001,

    /**
     * @generated from enum value: MessageType_NostrPubkey = 2002;
     */
    MessageType_NostrPubkey = 2002,

    /**
     * @generated from enum value: MessageType_NostrSignEvent = 2003;
     */
    MessageType_NostrSignEvent = 2003,

    /**
     * @generated from enum value: MessageType_NostrEventSignature = 2004;
     */
    MessageType_NostrEventSignature = 2004,

    /**
     * Evolu
     *
     * @generated from enum value: MessageType_EvoluGetNode = 2100;
     */
    MessageType_EvoluGetNode = 2100,

    /**
     * @generated from enum value: MessageType_EvoluNode = 2101;
     */
    MessageType_EvoluNode = 2101,

    /**
     * @generated from enum value: MessageType_EvoluSignRegistrationRequest = 2102;
     */
    MessageType_EvoluSignRegistrationRequest = 2102,

    /**
     * @generated from enum value: MessageType_EvoluRegistrationRequest = 2103;
     */
    MessageType_EvoluRegistrationRequest = 2103,

    /**
     * @generated from enum value: MessageType_EvoluGetDelegatedIdentityKey = 2104;
     */
    MessageType_EvoluGetDelegatedIdentityKey = 2104,

    /**
     * @generated from enum value: MessageType_EvoluDelegatedIdentityKey = 2105;
     */
    MessageType_EvoluDelegatedIdentityKey = 2105,

    /**
     * @generated from enum value: MessageType_EvoluIndexManagement = 2106;
     */
    MessageType_EvoluIndexManagement = 2106,

    /**
     * @generated from enum value: MessageType_EvoluIndexManagementResponse = 2107;
     */
    MessageType_EvoluIndexManagementResponse = 2107,

    /**
     * Tron
     *
     * @generated from enum value: MessageType_TronGetAddress = 2200;
     */
    MessageType_TronGetAddress = 2200,

    /**
     * @generated from enum value: MessageType_TronAddress = 2201;
     */
    MessageType_TronAddress = 2201,

    /**
     * @generated from enum value: MessageType_TronSignTx = 2202;
     */
    MessageType_TronSignTx = 2202,

    /**
     * @generated from enum value: MessageType_TronSignature = 2203;
     */
    MessageType_TronSignature = 2203,

    /**
     * @generated from enum value: MessageType_TronContractRequest = 2204;
     */
    MessageType_TronContractRequest = 2204,

    /**
     * @generated from enum value: MessageType_TronTransferContract = 2205;
     */
    MessageType_TronTransferContract = 2205,

    /**
     * @generated from enum value: MessageType_TronTriggerSmartContract = 2206;
     */
    MessageType_TronTriggerSmartContract = 2206,

    /**
     * @generated from enum value: MessageType_TronFreezeBalanceV2Contract = 2207;
     */
    MessageType_TronFreezeBalanceV2Contract = 2207,

    /**
     * @generated from enum value: MessageType_TronUnfreezeBalanceV2Contract = 2208;
     */
    MessageType_TronUnfreezeBalanceV2Contract = 2208,

    /**
     * @generated from enum value: MessageType_TronWithdrawUnfreeze = 2209;
     */
    MessageType_TronWithdrawUnfreeze = 2209,

    /**
     * @generated from enum value: MessageType_TronVoteWitnessContract = 2210;
     */
    MessageType_TronVoteWitnessContract = 2210,

    /**
     * 2 indexes reserved for (un)delegation. PR in review.
     *
     * @generated from enum value: MessageType_TronWithdrawBalance = 2213;
     */
    MessageType_TronWithdrawBalance = 2213,

    /**
     * AuthDB
     *
     * @generated from enum value: MessageType_AuthDbSetRoot = 2300;
     */
    MessageType_AuthDbSetRoot = 2300,

    /**
     * @generated from enum value: MessageType_AuthDbSetRootResponse = 2301;
     */
    MessageType_AuthDbSetRootResponse = 2301,

    /**
     * @generated from enum value: MessageType_AuthDbLookup = 2302;
     */
    MessageType_AuthDbLookup = 2302,

    /**
     * @generated from enum value: MessageType_AuthDbLookupResponse = 2303;
     */
    MessageType_AuthDbLookupResponse = 2303,

    /**
     * @generated from enum value: MessageType_AuthDbUpdateLeaf = 2304;
     */
    MessageType_AuthDbUpdateLeaf = 2304,

    /**
     * @generated from enum value: MessageType_AuthDbUpdateLeafResponse = 2305;
     */
    MessageType_AuthDbUpdateLeafResponse = 2305,

    /**
     * @generated from enum value: MessageType_AuthDbClearRoot = 2306;
     */
    MessageType_AuthDbClearRoot = 2306,

    /**
     * @generated from enum value: MessageType_AuthDbClearRootResponse = 2307;
     */
    MessageType_AuthDbClearRootResponse = 2307,

    /**
     * @generated from enum value: MessageType_AuthDbApprove = 2308;
     */
    MessageType_AuthDbApprove = 2308,

    /**
     * @generated from enum value: MessageType_AuthDbApproveResponse = 2309;
     */
    MessageType_AuthDbApproveResponse = 2309,

    /**
     * @generated from enum value: MessageType_AuthDbSetCacheEntry = 2310;
     */
    MessageType_AuthDbSetCacheEntry = 2310,

    /**
     * @generated from enum value: MessageType_AuthDbSetCacheEntryResponse = 2311;
     */
    MessageType_AuthDbSetCacheEntryResponse = 2311,

    /**
     * @generated from enum value: MessageType_AuthDbGetCacheEntry = 2312;
     */
    MessageType_AuthDbGetCacheEntry = 2312,

    /**
     * @generated from enum value: MessageType_AuthDbGetCacheEntryResponse = 2313;
     */
    MessageType_AuthDbGetCacheEntryResponse = 2313,

    /**
     * @generated from enum value: MessageType_AuthDbGetAllCache = 2314;
     */
    MessageType_AuthDbGetAllCache = 2314,

    /**
     * @generated from enum value: MessageType_AuthDbGetAllCacheResponse = 2315;
     */
    MessageType_AuthDbGetAllCacheResponse = 2315,

    /**
     * @generated from enum value: MessageType_AuthDbWipeCache = 2316;
     */
    MessageType_AuthDbWipeCache = 2316,

    /**
     * @generated from enum value: MessageType_AuthDbWipeCacheResponse = 2317;
     */
    MessageType_AuthDbWipeCacheResponse = 2317,

    /**
     * @generated from enum value: MessageType_AuthDbSetDeviceId = 2318;
     */
    MessageType_AuthDbSetDeviceId = 2318,

    /**
     * @generated from enum value: MessageType_AuthDbSetDeviceIdResponse = 2319;
     */
    MessageType_AuthDbSetDeviceIdResponse = 2319,

    /**
     * @generated from enum value: MessageType_AuthDbQueueOfflineOperation = 2320;
     */
    MessageType_AuthDbQueueOfflineOperation = 2320,

    /**
     * @generated from enum value: MessageType_AuthDbQueueOfflineOperationResponse = 2321;
     */
    MessageType_AuthDbQueueOfflineOperationResponse = 2321,

    /**
     * @generated from enum value: MessageType_AuthDbGetOfflineOperations = 2322;
     */
    MessageType_AuthDbGetOfflineOperations = 2322,

    /**
     * @generated from enum value: MessageType_AuthDbGetOfflineOperationsResponse = 2323;
     */
    MessageType_AuthDbGetOfflineOperationsResponse = 2323,

    /**
     * @generated from enum value: MessageType_AuthDbApplyOfflineOperations = 2324;
     */
    MessageType_AuthDbApplyOfflineOperations = 2324,

    /**
     * @generated from enum value: MessageType_AuthDbApplyOfflineOperationsResponse = 2325;
     */
    MessageType_AuthDbApplyOfflineOperationsResponse = 2325,

    /**
     * @generated from enum value: MessageType_AuthDbDeleteOfflineOperations = 2326;
     */
    MessageType_AuthDbDeleteOfflineOperations = 2326,

    /**
     * @generated from enum value: MessageType_AuthDbDeleteOfflineOperationsResponse = 2327;
     */
    MessageType_AuthDbDeleteOfflineOperationsResponse = 2327,

    /**
     * @generated from enum value: MessageType_AuthDbFastForwardRoot = 2328;
     */
    MessageType_AuthDbFastForwardRoot = 2328,

    /**
     * @generated from enum value: MessageType_AuthDbFastForwardRootResponse = 2329;
     */
    MessageType_AuthDbFastForwardRootResponse = 2329,

    /**
     * Benchmark
     *
     * @generated from enum value: MessageType_BenchmarkListNames = 9100;
     */
    MessageType_BenchmarkListNames = 9100,

    /**
     * @generated from enum value: MessageType_BenchmarkNames = 9101;
     */
    MessageType_BenchmarkNames = 9101,

    /**
     * @generated from enum value: MessageType_BenchmarkRun = 9102;
     */
    MessageType_BenchmarkRun = 9102,

    /**
     * @generated from enum value: MessageType_BenchmarkResult = 9103;
     */
    MessageType_BenchmarkResult = 9103,

    /**
     * Telemetry
     *
     * @generated from enum value: MessageType_TelemetryGet = 1100;
     */
    MessageType_TelemetryGet = 1100,

    /**
     * @generated from enum value: MessageType_Telemetry = 1101;
     */
    MessageType_Telemetry = 1101,
}

/**
 * *
 * Mapping between Trezor wire identifier (uint) and a protobuf message
 *
 * @generated from enum hw.trezor.messages.MessageType
 */
export declare type MessageTypeJson =
    | 'MessageType_Initialize'
    | 'MessageType_Ping'
    | 'MessageType_Success'
    | 'MessageType_Failure'
    | 'MessageType_ChangePin'
    | 'MessageType_WipeDevice'
    | 'MessageType_GetEntropy'
    | 'MessageType_Entropy'
    | 'MessageType_LoadDevice'
    | 'MessageType_ResetDevice'
    | 'MessageType_SetBusy'
    | 'MessageType_Features'
    | 'MessageType_PinMatrixRequest'
    | 'MessageType_PinMatrixAck'
    | 'MessageType_Cancel'
    | 'MessageType_LockDevice'
    | 'MessageType_ApplySettings'
    | 'MessageType_ButtonRequest'
    | 'MessageType_ButtonAck'
    | 'MessageType_ApplyFlags'
    | 'MessageType_GetNonce'
    | 'MessageType_Nonce'
    | 'MessageType_BackupDevice'
    | 'MessageType_EntropyRequest'
    | 'MessageType_EntropyAck'
    | 'MessageType_PaymentRequest'
    | 'MessageType_EntropyCheckReady'
    | 'MessageType_EntropyCheckContinue'
    | 'MessageType_PassphraseRequest'
    | 'MessageType_PassphraseAck'
    | 'MessageType_RecoveryDevice'
    | 'MessageType_WordRequest'
    | 'MessageType_WordAck'
    | 'MessageType_GetFeatures'
    | 'MessageType_SdProtect'
    | 'MessageType_ChangeWipeCode'
    | 'MessageType_EndSession'
    | 'MessageType_DoPreauthorized'
    | 'MessageType_PreauthorizedRequest'
    | 'MessageType_CancelAuthorization'
    | 'MessageType_RebootToBootloader'
    | 'MessageType_GetFirmwareHash'
    | 'MessageType_FirmwareHash'
    | 'MessageType_UnlockPath'
    | 'MessageType_UnlockedPathRequest'
    | 'MessageType_ShowDeviceTutorial'
    | 'MessageType_UnlockBootloader'
    | 'MessageType_AuthenticateDevice'
    | 'MessageType_AuthenticityProof'
    | 'MessageType_AuthenticityProofSizes'
    | 'MessageType_ChangeLanguage'
    | 'MessageType_DataChunkRequest'
    | 'MessageType_DataChunkAck'
    | 'MessageType_SetBrightness'
    | 'MessageType_GetSerialNumber'
    | 'MessageType_SerialNumber'
    | 'MessageType_GetAuthenticityProofChunk'
    | 'MessageType_AuthenticityProofChunk'
    | 'MessageType_SetU2FCounter'
    | 'MessageType_GetNextU2FCounter'
    | 'MessageType_NextU2FCounter'
    | 'MessageType_FirmwareErase'
    | 'MessageType_FirmwareUpload'
    | 'MessageType_FirmwareRequest'
    | 'MessageType_ProdTestT1'
    | 'MessageType_BleUnpair'
    | 'MessageType_GetPublicKey'
    | 'MessageType_PublicKey'
    | 'MessageType_SignTx'
    | 'MessageType_TxRequest'
    | 'MessageType_TxAck'
    | 'MessageType_GetAddress'
    | 'MessageType_Address'
    | 'MessageType_SignMessage'
    | 'MessageType_VerifyMessage'
    | 'MessageType_MessageSignature'
    | 'MessageType_GetOwnershipId'
    | 'MessageType_OwnershipId'
    | 'MessageType_GetOwnershipProof'
    | 'MessageType_OwnershipProof'
    | 'MessageType_AuthorizeCoinJoin'
    | 'MessageType_CipherKeyValue'
    | 'MessageType_CipheredKeyValue'
    | 'MessageType_SignIdentity'
    | 'MessageType_SignedIdentity'
    | 'MessageType_GetECDHSessionKey'
    | 'MessageType_ECDHSessionKey'
    | 'MessageType_PaymentNotification'
    | 'MessageType_DebugLinkDecision'
    | 'MessageType_DebugLinkGetState'
    | 'MessageType_DebugLinkState'
    | 'MessageType_DebugLinkStop'
    | 'MessageType_DebugLinkLog'
    | 'MessageType_DebugLinkMemoryRead'
    | 'MessageType_DebugLinkMemory'
    | 'MessageType_DebugLinkMemoryWrite'
    | 'MessageType_DebugLinkFlashErase'
    | 'MessageType_DebugLinkLayout'
    | 'MessageType_DebugLinkReseedRandom'
    | 'MessageType_DebugLinkRecordScreen'
    | 'MessageType_DebugLinkEraseSdCard'
    | 'MessageType_DebugLinkWatchLayout'
    | 'MessageType_DebugLinkResetDebugEvents'
    | 'MessageType_DebugLinkOptigaSetSecMax'
    | 'MessageType_DebugLinkGetGcInfo'
    | 'MessageType_DebugLinkGcInfo'
    | 'MessageType_DebugLinkGetPairingInfo'
    | 'MessageType_DebugLinkPairingInfo'
    | 'MessageType_DebugLinkSetLogFilter'
    | 'MessageType_DebugLinkN4W1Connected'
    | 'MessageType_DebugLinkN4W1Write'
    | 'MessageType_DebugLinkN4W1Read'
    | 'MessageType_DebugLinkN4W1Response'
    | 'MessageType_DebugLinkSetBatteryState'
    | 'MessageType_EthereumGetPublicKey'
    | 'MessageType_EthereumPublicKey'
    | 'MessageType_EthereumGetAddress'
    | 'MessageType_EthereumAddress'
    | 'MessageType_EthereumSignTx'
    | 'MessageType_EthereumSignTxEIP1559'
    | 'MessageType_EthereumTxRequest'
    | 'MessageType_EthereumTxAck'
    | 'MessageType_EthereumSignMessage'
    | 'MessageType_EthereumVerifyMessage'
    | 'MessageType_EthereumMessageSignature'
    | 'MessageType_EthereumSignTypedData'
    | 'MessageType_EthereumTypedDataStructRequest'
    | 'MessageType_EthereumTypedDataStructAck'
    | 'MessageType_EthereumTypedDataValueRequest'
    | 'MessageType_EthereumTypedDataValueAck'
    | 'MessageType_EthereumTypedDataSignature'
    | 'MessageType_EthereumSignTypedHash'
    | 'MessageType_EthereumDefinitionRequest'
    | 'MessageType_EthereumDefinitionAck'
    | 'MessageType_NEMGetAddress'
    | 'MessageType_NEMAddress'
    | 'MessageType_NEMSignTx'
    | 'MessageType_NEMSignedTx'
    | 'MessageType_NEMDecryptMessage'
    | 'MessageType_NEMDecryptedMessage'
    | 'MessageType_TezosGetAddress'
    | 'MessageType_TezosAddress'
    | 'MessageType_TezosSignTx'
    | 'MessageType_TezosSignedTx'
    | 'MessageType_TezosGetPublicKey'
    | 'MessageType_TezosPublicKey'
    | 'MessageType_StellarSignTx'
    | 'MessageType_StellarTxOpRequest'
    | 'MessageType_StellarGetAddress'
    | 'MessageType_StellarAddress'
    | 'MessageType_StellarCreateAccountOp'
    | 'MessageType_StellarPaymentOp'
    | 'MessageType_StellarPathPaymentStrictReceiveOp'
    | 'MessageType_StellarManageSellOfferOp'
    | 'MessageType_StellarCreatePassiveSellOfferOp'
    | 'MessageType_StellarSetOptionsOp'
    | 'MessageType_StellarChangeTrustOp'
    | 'MessageType_StellarAllowTrustOp'
    | 'MessageType_StellarAccountMergeOp'
    | 'MessageType_StellarManageDataOp'
    | 'MessageType_StellarBumpSequenceOp'
    | 'MessageType_StellarManageBuyOfferOp'
    | 'MessageType_StellarPathPaymentStrictSendOp'
    | 'MessageType_StellarClaimClaimableBalanceOp'
    | 'MessageType_StellarSignedTx'
    | 'MessageType_CardanoGetPublicKey'
    | 'MessageType_CardanoPublicKey'
    | 'MessageType_CardanoGetAddress'
    | 'MessageType_CardanoAddress'
    | 'MessageType_CardanoTxItemAck'
    | 'MessageType_CardanoTxAuxiliaryDataSupplement'
    | 'MessageType_CardanoTxWitnessRequest'
    | 'MessageType_CardanoTxWitnessResponse'
    | 'MessageType_CardanoTxHostAck'
    | 'MessageType_CardanoTxBodyHash'
    | 'MessageType_CardanoSignTxFinished'
    | 'MessageType_CardanoSignTxInit'
    | 'MessageType_CardanoTxInput'
    | 'MessageType_CardanoTxOutput'
    | 'MessageType_CardanoAssetGroup'
    | 'MessageType_CardanoToken'
    | 'MessageType_CardanoTxCertificate'
    | 'MessageType_CardanoTxWithdrawal'
    | 'MessageType_CardanoTxAuxiliaryData'
    | 'MessageType_CardanoPoolOwner'
    | 'MessageType_CardanoPoolRelayParameters'
    | 'MessageType_CardanoGetNativeScriptHash'
    | 'MessageType_CardanoNativeScriptHash'
    | 'MessageType_CardanoTxMint'
    | 'MessageType_CardanoTxCollateralInput'
    | 'MessageType_CardanoTxRequiredSigner'
    | 'MessageType_CardanoTxInlineDatumChunk'
    | 'MessageType_CardanoTxReferenceScriptChunk'
    | 'MessageType_CardanoTxReferenceInput'
    | 'MessageType_CardanoSignMessageInit'
    | 'MessageType_CardanoMessageDataRequest'
    | 'MessageType_CardanoMessageDataResponse'
    | 'MessageType_CardanoMessageSignature'
    | 'MessageType_RippleGetAddress'
    | 'MessageType_RippleAddress'
    | 'MessageType_RippleSignTx'
    | 'MessageType_RippleSignedTx'
    | 'MessageType_MoneroTransactionInitRequest'
    | 'MessageType_MoneroTransactionInitAck'
    | 'MessageType_MoneroTransactionSetInputRequest'
    | 'MessageType_MoneroTransactionSetInputAck'
    | 'MessageType_MoneroTransactionInputViniRequest'
    | 'MessageType_MoneroTransactionInputViniAck'
    | 'MessageType_MoneroTransactionAllInputsSetRequest'
    | 'MessageType_MoneroTransactionAllInputsSetAck'
    | 'MessageType_MoneroTransactionSetOutputRequest'
    | 'MessageType_MoneroTransactionSetOutputAck'
    | 'MessageType_MoneroTransactionAllOutSetRequest'
    | 'MessageType_MoneroTransactionAllOutSetAck'
    | 'MessageType_MoneroTransactionSignInputRequest'
    | 'MessageType_MoneroTransactionSignInputAck'
    | 'MessageType_MoneroTransactionFinalRequest'
    | 'MessageType_MoneroTransactionFinalAck'
    | 'MessageType_MoneroKeyImageExportInitRequest'
    | 'MessageType_MoneroKeyImageExportInitAck'
    | 'MessageType_MoneroKeyImageSyncStepRequest'
    | 'MessageType_MoneroKeyImageSyncStepAck'
    | 'MessageType_MoneroKeyImageSyncFinalRequest'
    | 'MessageType_MoneroKeyImageSyncFinalAck'
    | 'MessageType_MoneroGetAddress'
    | 'MessageType_MoneroAddress'
    | 'MessageType_MoneroGetWatchKey'
    | 'MessageType_MoneroWatchKey'
    | 'MessageType_DebugMoneroDiagRequest'
    | 'MessageType_DebugMoneroDiagAck'
    | 'MessageType_MoneroGetTxKeyRequest'
    | 'MessageType_MoneroGetTxKeyAck'
    | 'MessageType_MoneroLiveRefreshStartRequest'
    | 'MessageType_MoneroLiveRefreshStartAck'
    | 'MessageType_MoneroLiveRefreshStepRequest'
    | 'MessageType_MoneroLiveRefreshStepAck'
    | 'MessageType_MoneroLiveRefreshFinalRequest'
    | 'MessageType_MoneroLiveRefreshFinalAck'
    | 'MessageType_EosGetPublicKey'
    | 'MessageType_EosPublicKey'
    | 'MessageType_EosSignTx'
    | 'MessageType_EosTxActionRequest'
    | 'MessageType_EosTxActionAck'
    | 'MessageType_EosSignedTx'
    | 'MessageType_WebAuthnListResidentCredentials'
    | 'MessageType_WebAuthnCredentials'
    | 'MessageType_WebAuthnAddResidentCredential'
    | 'MessageType_WebAuthnRemoveResidentCredential'
    | 'MessageType_WebAuthnCredentialsAck'
    | 'MessageType_SolanaGetPublicKey'
    | 'MessageType_SolanaPublicKey'
    | 'MessageType_SolanaGetAddress'
    | 'MessageType_SolanaAddress'
    | 'MessageType_SolanaSignTx'
    | 'MessageType_SolanaTxSignature'
    | 'MessageType_SolanaSignMessage'
    | 'MessageType_SolanaMessageSignature'
    | 'MessageType_SolanaVerifyMessage'
    | 'MessageType_ThpCreateNewSession'
    | 'MessageType_ThpCredentialRequest'
    | 'MessageType_ThpCredentialResponse'
    | 'MessageType_NostrGetPubkey'
    | 'MessageType_NostrPubkey'
    | 'MessageType_NostrSignEvent'
    | 'MessageType_NostrEventSignature'
    | 'MessageType_EvoluGetNode'
    | 'MessageType_EvoluNode'
    | 'MessageType_EvoluSignRegistrationRequest'
    | 'MessageType_EvoluRegistrationRequest'
    | 'MessageType_EvoluGetDelegatedIdentityKey'
    | 'MessageType_EvoluDelegatedIdentityKey'
    | 'MessageType_EvoluIndexManagement'
    | 'MessageType_EvoluIndexManagementResponse'
    | 'MessageType_TronGetAddress'
    | 'MessageType_TronAddress'
    | 'MessageType_TronSignTx'
    | 'MessageType_TronSignature'
    | 'MessageType_TronContractRequest'
    | 'MessageType_TronTransferContract'
    | 'MessageType_TronTriggerSmartContract'
    | 'MessageType_TronFreezeBalanceV2Contract'
    | 'MessageType_TronUnfreezeBalanceV2Contract'
    | 'MessageType_TronWithdrawUnfreeze'
    | 'MessageType_TronVoteWitnessContract'
    | 'MessageType_TronWithdrawBalance'
    | 'MessageType_AuthDbSetRoot'
    | 'MessageType_AuthDbSetRootResponse'
    | 'MessageType_AuthDbLookup'
    | 'MessageType_AuthDbLookupResponse'
    | 'MessageType_AuthDbUpdateLeaf'
    | 'MessageType_AuthDbUpdateLeafResponse'
    | 'MessageType_AuthDbClearRoot'
    | 'MessageType_AuthDbClearRootResponse'
    | 'MessageType_AuthDbApprove'
    | 'MessageType_AuthDbApproveResponse'
    | 'MessageType_AuthDbSetCacheEntry'
    | 'MessageType_AuthDbSetCacheEntryResponse'
    | 'MessageType_AuthDbGetCacheEntry'
    | 'MessageType_AuthDbGetCacheEntryResponse'
    | 'MessageType_AuthDbGetAllCache'
    | 'MessageType_AuthDbGetAllCacheResponse'
    | 'MessageType_AuthDbWipeCache'
    | 'MessageType_AuthDbWipeCacheResponse'
    | 'MessageType_AuthDbSetDeviceId'
    | 'MessageType_AuthDbSetDeviceIdResponse'
    | 'MessageType_AuthDbQueueOfflineOperation'
    | 'MessageType_AuthDbQueueOfflineOperationResponse'
    | 'MessageType_AuthDbGetOfflineOperations'
    | 'MessageType_AuthDbGetOfflineOperationsResponse'
    | 'MessageType_AuthDbApplyOfflineOperations'
    | 'MessageType_AuthDbApplyOfflineOperationsResponse'
    | 'MessageType_AuthDbDeleteOfflineOperations'
    | 'MessageType_AuthDbDeleteOfflineOperationsResponse'
    | 'MessageType_AuthDbFastForwardRoot'
    | 'MessageType_AuthDbFastForwardRootResponse'
    | 'MessageType_BenchmarkListNames'
    | 'MessageType_BenchmarkNames'
    | 'MessageType_BenchmarkRun'
    | 'MessageType_BenchmarkResult'
    | 'MessageType_TelemetryGet'
    | 'MessageType_Telemetry';

/**
 * Describes the enum hw.trezor.messages.MessageType.
 */
export declare const MessageTypeSchema: GenEnum<MessageType, MessageTypeJson>;
