// @generated by @trezor/protobuf/protoc-gen-plugin 1.0.0
// source: messages-authdb.proto
// DO NOT EDIT
import { type Static, Type } from '@trezor/schema-utils';

export type AuthDbSetRoot = Static<typeof AuthDbSetRoot>;
export const AuthDbSetRoot = Type.Object(
    {
        root: Type.String(),
    },
    { $id: 'AuthDbSetRoot' },
);

export type AuthDbSetRootResponse = Static<typeof AuthDbSetRootResponse>;
export const AuthDbSetRootResponse = Type.Object(
    {
        counter: Type.Number(),
    },
    { $id: 'AuthDbSetRootResponse' },
);

export type AuthDbLookup = Static<typeof AuthDbLookup>;
export const AuthDbLookup = Type.Object(
    {
        address: Type.String(),
        value: Type.String(),
        proof: Type.Optional(Type.Array(Type.String())),
    },
    { $id: 'AuthDbLookup' },
);

export type AuthDbLookupResponse = Static<typeof AuthDbLookupResponse>;
export const AuthDbLookupResponse = Type.Object(
    {
        valid: Type.Boolean(),
        counter: Type.Number(),
    },
    { $id: 'AuthDbLookupResponse' },
);
