// @generated by @trezor/protobuf/protoc-get-plugin v1 with parameter "target=dts"
// @generated from file messages-crypto.proto (package hw.trezor.messages.crypto, syntax proto2)

import type { DescFile } from '@bufbuild/protobuf';

export declare const file_messages_crypto: DescFile;
