// @generated by @trezor/protobuf/protoc-gen-plugin 1.0.0
// source: messages-ward.proto
// DO NOT EDIT
import { type Static, Type } from '@trezor/schema-utils';

export type WardChainLink = Static<typeof WardChainLink>;
export const WardChainLink = Type.Object(
    {
        from_counter: Type.Optional(Type.Number()),
        from_root: Type.Optional(Type.String()),
        to_counter: Type.Optional(Type.Number()),
        to_root: Type.Optional(Type.String()),
        auth_commit: Type.Optional(Type.String()),
    },
    { $id: 'WardChainLink' },
);

export type WardDeleteEntry = Static<typeof WardDeleteEntry>;
export const WardDeleteEntry = Type.Object(
    {
        app_id: Type.Optional(Type.String()),
        identifier: Type.Optional(Type.String()),
    },
    { $id: 'WardDeleteEntry' },
);

export type WardEncryptedIdentity = Static<typeof WardEncryptedIdentity>;
export const WardEncryptedIdentity = Type.Object(
    {
        nonce: Type.Optional(Type.String()),
        tag: Type.Optional(Type.String()),
        ct: Type.Optional(Type.String()),
    },
    { $id: 'WardEncryptedIdentity' },
);

export type WardEncryptedLeaf = Static<typeof WardEncryptedLeaf>;
export const WardEncryptedLeaf = Type.Object(
    {
        nonce: Type.Optional(Type.String()),
        tag: Type.Optional(Type.String()),
        ct: Type.Optional(Type.String()),
    },
    { $id: 'WardEncryptedLeaf' },
);

export type WardPlainIdentity = Static<typeof WardPlainIdentity>;
export const WardPlainIdentity = Type.Object(
    {
        identifier: Type.Optional(Type.String()),
        app_id: Type.Optional(Type.String()),
        device_id: Type.Optional(Type.Number()),
    },
    { $id: 'WardPlainIdentity' },
);

export type WardLeafIdentity = Static<typeof WardLeafIdentity>;
export const WardLeafIdentity = Type.Object(
    {
        encoding: Type.Optional(Type.Number()),
        key_type: Type.Optional(Type.String()),
        encrypted: Type.Optional(WardEncryptedIdentity),
        plain: Type.Optional(WardPlainIdentity),
    },
    { $id: 'WardLeafIdentity' },
);

export type WardPlaintextLeaf = Static<typeof WardPlaintextLeaf>;
export const WardPlaintextLeaf = Type.Object(
    {
        content: Type.Optional(Type.String()),
    },
    { $id: 'WardPlaintextLeaf' },
);

export type WardLeafContent = Static<typeof WardLeafContent>;
export const WardLeafContent = Type.Object(
    {
        encoding: Type.Optional(Type.Number()),
        encrypted: Type.Optional(WardEncryptedLeaf),
        plaintext: Type.Optional(WardPlaintextLeaf),
    },
    { $id: 'WardLeafContent' },
);

export type WardEntryAck = Static<typeof WardEntryAck>;
export const WardEntryAck = Type.Object(
    {
        identity: Type.Optional(WardLeafIdentity),
        content: Type.Optional(WardLeafContent),
        proof: Type.Array(Type.String()),
        witness_entry_key: Type.Optional(Type.String()),
        witness_commit: Type.Optional(Type.String()),
    },
    { $id: 'WardEntryAck' },
);

export type WardEntryRequest = Static<typeof WardEntryRequest>;
export const WardEntryRequest = Type.Object(
    {
        entry_key: Type.Optional(Type.String()),
    },
    { $id: 'WardEntryRequest' },
);

export type WardEraseCachedEntry = Static<typeof WardEraseCachedEntry>;
export const WardEraseCachedEntry = Type.Object(
    {
        app_id: Type.Optional(Type.String()),
        identifier: Type.Optional(Type.String()),
    },
    { $id: 'WardEraseCachedEntry' },
);

export type WardFlushQueue = Static<typeof WardFlushQueue>;
export const WardFlushQueue = Type.Record(Type.Never(), Type.Never(), { $id: 'WardFlushQueue' });

export type WardFlushQueueAck = Static<typeof WardFlushQueueAck>;
export const WardFlushQueueAck = Type.Object(
    {
        entry_key: Type.Optional(Type.String()),
        identity: Type.Optional(WardLeafIdentity),
        content: Type.Optional(WardLeafContent),
        counter: Type.Optional(Type.Number()),
        mac: Type.Optional(Type.String()),
        auth_commit: Type.Optional(Type.String()),
        auth_sig: Type.Optional(Type.String()),
        remaining: Type.Number(),
    },
    { $id: 'WardFlushQueueAck' },
);

export type WardGetEntry = Static<typeof WardGetEntry>;
export const WardGetEntry = Type.Object(
    {
        app_id: Type.Optional(Type.String()),
        identifier: Type.Optional(Type.String()),
    },
    { $id: 'WardGetEntry' },
);

export type WardIngestAttestation = Static<typeof WardIngestAttestation>;
export const WardIngestAttestation = Type.Object(
    {
        counter: Type.Optional(Type.Number()),
        mac: Type.Optional(Type.String()),
        wm_signature: Type.Optional(Type.String()),
        timestamp: Type.Optional(Type.Number()),
    },
    { $id: 'WardIngestAttestation' },
);

export type WardIngestAttestationAck = Static<typeof WardIngestAttestationAck>;
export const WardIngestAttestationAck = Type.Object(
    {
        counter: Type.Optional(Type.Number()),
    },
    { $id: 'WardIngestAttestationAck' },
);

export type WardLeafAck = Static<typeof WardLeafAck>;
export const WardLeafAck = Type.Object(
    {
        entry_key: Type.String(),
        identity: Type.Optional(WardLeafIdentity),
        content: Type.Optional(WardLeafContent),
        counter: Type.Optional(Type.Number()),
        mac: Type.Optional(Type.String()),
        auth_commit: Type.Optional(Type.String()),
        auth_sig: Type.Optional(Type.String()),
    },
    { $id: 'WardLeafAck' },
);

export type WardPinCachedEntry = Static<typeof WardPinCachedEntry>;
export const WardPinCachedEntry = Type.Object(
    {
        app_id: Type.Optional(Type.String()),
        identifier: Type.Optional(Type.String()),
    },
    { $id: 'WardPinCachedEntry' },
);

export type WardQueueDeleteAck = Static<typeof WardQueueDeleteAck>;
export const WardQueueDeleteAck = Type.Object(
    {
        entry_key: Type.String(),
        missing: Type.Optional(Type.Boolean()),
    },
    { $id: 'WardQueueDeleteAck' },
);

export type WardQueueDeleteEntry = Static<typeof WardQueueDeleteEntry>;
export const WardQueueDeleteEntry = Type.Object(
    {
        app_id: Type.Optional(Type.String()),
        identifier: Type.Optional(Type.String()),
    },
    { $id: 'WardQueueDeleteEntry' },
);

export type WardQueueGetAck = Static<typeof WardQueueGetAck>;
export const WardQueueGetAck = Type.Object(
    {
        entry_key: Type.String(),
        missing: Type.Optional(Type.Boolean()),
        pending: Type.Optional(Type.Boolean()),
        unreadable: Type.Optional(Type.Boolean()),
        stale: Type.Optional(Type.Boolean()),
        counter: Type.Optional(Type.Number()),
        key_type: Type.Optional(Type.String()),
        app_id: Type.Optional(Type.String()),
        identifier: Type.Optional(Type.String()),
        value: Type.Optional(Type.String()),
        mac: Type.Optional(Type.String()),
    },
    { $id: 'WardQueueGetAck' },
);

export type WardQueueGetEntry = Static<typeof WardQueueGetEntry>;
export const WardQueueGetEntry = Type.Object(
    {
        app_id: Type.Optional(Type.String()),
        identifier: Type.Optional(Type.String()),
    },
    { $id: 'WardQueueGetEntry' },
);

export type WardQueueSetAck = Static<typeof WardQueueSetAck>;
export const WardQueueSetAck = Type.Object(
    {
        entry_key: Type.String(),
    },
    { $id: 'WardQueueSetAck' },
);

export type WardQueueSetEntry = Static<typeof WardQueueSetEntry>;
export const WardQueueSetEntry = Type.Object(
    {
        app_id: Type.Optional(Type.String()),
        identifier: Type.Optional(Type.String()),
        value: Type.Optional(Type.String()),
        mac: Type.Optional(Type.String()),
        counter: Type.Optional(Type.Number()),
        key_type: Type.Optional(Type.String()),
    },
    { $id: 'WardQueueSetEntry' },
);

export type WardReconcile = Static<typeof WardReconcile>;
export const WardReconcile = Type.Object(
    {
        root: Type.Optional(Type.String()),
    },
    { $id: 'WardReconcile' },
);

export type WardReconcileAck = Static<typeof WardReconcileAck>;
export const WardReconcileAck = Type.Object(
    {
        counter: Type.Optional(Type.Number()),
        new_root: Type.Optional(Type.String()),
    },
    { $id: 'WardReconcileAck' },
);

export type WardRecoverCounter = Static<typeof WardRecoverCounter>;
export const WardRecoverCounter = Type.Object(
    {
        counter: Type.Optional(Type.Number()),
        mac: Type.Optional(Type.String()),
        wm_signature: Type.Optional(Type.String()),
        timestamp: Type.Optional(Type.Number()),
    },
    { $id: 'WardRecoverCounter' },
);

export type WardRecoverCounterAck = Static<typeof WardRecoverCounterAck>;
export const WardRecoverCounterAck = Type.Object(
    {
        counter: Type.Optional(Type.Number()),
    },
    { $id: 'WardRecoverCounterAck' },
);

export type WardRollback = Static<typeof WardRollback>;
export const WardRollback = Type.Object(
    {
        to_root: Type.Optional(Type.String()),
        auth_commit: Type.Optional(Type.String()),
        from_counter: Type.Optional(Type.Number()),
        from_root: Type.Optional(Type.String()),
        to_counter: Type.Optional(Type.Number()),
    },
    { $id: 'WardRollback' },
);

export type WardRollbackAck = Static<typeof WardRollbackAck>;
export const WardRollbackAck = Type.Object(
    {
        counter: Type.Optional(Type.Number()),
        new_root: Type.Optional(Type.String()),
        auth_commit: Type.Optional(Type.String()),
        auth_sig: Type.Optional(Type.String()),
    },
    { $id: 'WardRollbackAck' },
);

export type WardSetEntry = Static<typeof WardSetEntry>;
export const WardSetEntry = Type.Object(
    {
        app_id: Type.Optional(Type.String()),
        identifier: Type.Optional(Type.String()),
        value: Type.Optional(Type.String()),
    },
    { $id: 'WardSetEntry' },
);

export type WardSync = Static<typeof WardSync>;
export const WardSync = Type.Record(Type.Never(), Type.Never(), { $id: 'WardSync' });

export type WardSyncAck = Static<typeof WardSyncAck>;
export const WardSyncAck = Type.Object(
    {
        nonce: Type.Optional(Type.String()),
        ward_id: Type.Optional(Type.String()),
        counter: Type.Optional(Type.Number()),
    },
    { $id: 'WardSyncAck' },
);

export type WardVerifyChain = Static<typeof WardVerifyChain>;
export const WardVerifyChain = Type.Object(
    {
        links: Type.Array(WardChainLink),
    },
    { $id: 'WardVerifyChain' },
);

export type WardVerifyChainAck = Static<typeof WardVerifyChainAck>;
export const WardVerifyChainAck = Type.Object(
    {
        counter: Type.Optional(Type.Number()),
        new_root: Type.Optional(Type.String()),
    },
    { $id: 'WardVerifyChainAck' },
);
