// @generated by @trezor/protobuf/protoc-gen-plugin 1.0.0
// source: messages-ward.proto
// DO NOT EDIT
import { type Static, Type } from '@trezor/schema-utils';

export type WardChainLink = Static<typeof WardChainLink>;
export const WardChainLink = Type.Object(
    {
        from_counter: Type.Optional(Type.Number()),
        from_root: Type.Optional(Type.String()),
        to_counter: Type.Optional(Type.Number()),
        to_root: Type.Optional(Type.String()),
        auth_commit: Type.Optional(Type.String()),
    },
    { $id: 'WardChainLink' },
);

export type WardDeleteEntry = Static<typeof WardDeleteEntry>;
export const WardDeleteEntry = Type.Object(
    {
        app_id: Type.Optional(Type.String()),
        identifier: Type.Optional(Type.String()),
    },
    { $id: 'WardDeleteEntry' },
);

export type WardEncryptedIdentity = Static<typeof WardEncryptedIdentity>;
export const WardEncryptedIdentity = Type.Object(
    {
        nonce: Type.Optional(Type.String()),
        tag: Type.Optional(Type.String()),
        ct: Type.Optional(Type.String()),
    },
    { $id: 'WardEncryptedIdentity' },
);

export type WardEncryptedLeaf = Static<typeof WardEncryptedLeaf>;
export const WardEncryptedLeaf = Type.Object(
    {
        nonce: Type.Optional(Type.String()),
        tag: Type.Optional(Type.String()),
        ct: Type.Optional(Type.String()),
    },
    { $id: 'WardEncryptedLeaf' },
);

export type WardPlainIdentity = Static<typeof WardPlainIdentity>;
export const WardPlainIdentity = Type.Object(
    {
        identifier: Type.Optional(Type.String()),
        app_id: Type.Optional(Type.String()),
        device_id: Type.Optional(Type.Number()),
    },
    { $id: 'WardPlainIdentity' },
);

export type WardLeafIdentity = Static<typeof WardLeafIdentity>;
export const WardLeafIdentity = Type.Object(
    {
        encoding: Type.Optional(Type.Number()),
        key_type: Type.Optional(Type.String()),
        encrypted: Type.Optional(WardEncryptedIdentity),
        plain: Type.Optional(WardPlainIdentity),
    },
    { $id: 'WardLeafIdentity' },
);

export type WardPlaintextLeaf = Static<typeof WardPlaintextLeaf>;
export const WardPlaintextLeaf = Type.Object(
    {
        content: Type.Optional(Type.String()),
    },
    { $id: 'WardPlaintextLeaf' },
);

export type WardLeafContent = Static<typeof WardLeafContent>;
export const WardLeafContent = Type.Object(
    {
        encoding: Type.Optional(Type.Number()),
        encrypted: Type.Optional(WardEncryptedLeaf),
        plaintext: Type.Optional(WardPlaintextLeaf),
    },
    { $id: 'WardLeafContent' },
);

export type WardEntryAck = Static<typeof WardEntryAck>;
export const WardEntryAck = Type.Object(
    {
        identity: Type.Optional(WardLeafIdentity),
        content: Type.Optional(WardLeafContent),
        proof: Type.Array(Type.String()),
        witness_entry_key: Type.Optional(Type.String()),
        witness_commit: Type.Optional(Type.String()),
    },
    { $id: 'WardEntryAck' },
);

export type WardEraseCachedEntry = Static<typeof WardEraseCachedEntry>;
export const WardEraseCachedEntry = Type.Object(
    {
        app_id: Type.Optional(Type.String()),
        identifier: Type.Optional(Type.String()),
    },
    { $id: 'WardEraseCachedEntry' },
);

export type WardFlushQueue = Static<typeof WardFlushQueue>;
export const WardFlushQueue = Type.Object(
    {
        app_id: Type.Optional(Type.String()),
        identifier: Type.Optional(Type.String()),
    },
    { $id: 'WardFlushQueue' },
);

export type WardGetEntry = Static<typeof WardGetEntry>;
export const WardGetEntry = Type.Object(
    {
        app_id: Type.Optional(Type.String()),
        identifier: Type.Optional(Type.String()),
    },
    { $id: 'WardGetEntry' },
);

export type WardPinCachedEntry = Static<typeof WardPinCachedEntry>;
export const WardPinCachedEntry = Type.Object(
    {
        app_id: Type.Optional(Type.String()),
        identifier: Type.Optional(Type.String()),
    },
    { $id: 'WardPinCachedEntry' },
);

export type WardQueueDeleteAck = Static<typeof WardQueueDeleteAck>;
export const WardQueueDeleteAck = Type.Object(
    {
        missing: Type.Optional(Type.Boolean()),
    },
    { $id: 'WardQueueDeleteAck' },
);

export type WardQueueDeleteEntry = Static<typeof WardQueueDeleteEntry>;
export const WardQueueDeleteEntry = Type.Object(
    {
        app_id: Type.Optional(Type.String()),
        identifier: Type.Optional(Type.String()),
    },
    { $id: 'WardQueueDeleteEntry' },
);

export type WardQueueGetAck = Static<typeof WardQueueGetAck>;
export const WardQueueGetAck = Type.Object(
    {
        missing: Type.Optional(Type.Boolean()),
        pending: Type.Optional(Type.Boolean()),
        key_type: Type.Optional(Type.String()),
        app_id: Type.Optional(Type.String()),
        identifier: Type.Optional(Type.String()),
        value: Type.Optional(Type.String()),
        mac: Type.Optional(Type.String()),
    },
    { $id: 'WardQueueGetAck' },
);

export type WardQueueGetEntry = Static<typeof WardQueueGetEntry>;
export const WardQueueGetEntry = Type.Object(
    {
        app_id: Type.Optional(Type.String()),
        identifier: Type.Optional(Type.String()),
    },
    { $id: 'WardQueueGetEntry' },
);

export type WardQueueSetAck = Static<typeof WardQueueSetAck>;
export const WardQueueSetAck = Type.Record(Type.Never(), Type.Never(), { $id: 'WardQueueSetAck' });

export type WardQueueSetEntry = Static<typeof WardQueueSetEntry>;
export const WardQueueSetEntry = Type.Object(
    {
        app_id: Type.Optional(Type.String()),
        identifier: Type.Optional(Type.String()),
        value: Type.Optional(Type.String()),
        mac: Type.Optional(Type.String()),
        compact: Type.Optional(Type.Boolean()),
    },
    { $id: 'WardQueueSetEntry' },
);

export type WardResetApp = Static<typeof WardResetApp>;
export const WardResetApp = Type.Record(Type.Never(), Type.Never(), { $id: 'WardResetApp' });

export type WardResetAppAck = Static<typeof WardResetAppAck>;
export const WardResetAppAck = Type.Object(
    {
        was_bound: Type.Optional(Type.Boolean()),
    },
    { $id: 'WardResetAppAck' },
);

export type WardSetEntry = Static<typeof WardSetEntry>;
export const WardSetEntry = Type.Object(
    {
        app_id: Type.Optional(Type.String()),
        identifier: Type.Optional(Type.String()),
        value: Type.Optional(Type.String()),
    },
    { $id: 'WardSetEntry' },
);
