// @generated by @trezor/protobuf/protoc-get-plugin v1 with parameter "target=dts"
// @generated from file messages-ble.proto (package hw.trezor.messages.ble, syntax proto2)

import type { DescFile } from '@bufbuild/protobuf';

export declare const file_messages_ble: DescFile;
