// @generated by @trezor/protobuf/protoc-gen-plugin 1.0.0
// source: messages-display_address.proto
// DO NOT EDIT
import { type Static, Type } from '@trezor/schema-utils';

import { LeafContent } from './messages-ward';

export type DisplayAddress = Static<typeof DisplayAddress>;
export const DisplayAddress = Type.Object(
    {
        address: Type.String(),
        title: Type.Optional(Type.String()),
        subtitle: Type.Optional(Type.String()),
        case_sensitive: Type.Optional(Type.Boolean()),
        chunkify: Type.Optional(Type.Boolean()),
        app_id: Type.Optional(Type.String()),
    },
    { $id: 'DisplayAddress' },
);

export type DisplayAddressWithProof = Static<typeof DisplayAddressWithProof>;
export const DisplayAddressWithProof = Type.Object(
    {
        address: Type.String(),
        title: Type.Optional(Type.String()),
        subtitle: Type.Optional(Type.String()),
        case_sensitive: Type.Optional(Type.Boolean()),
        chunkify: Type.Optional(Type.Boolean()),
        proof: Type.Array(Type.String()),
        witness_entry_key: Type.Optional(Type.String()),
        witness_commit: Type.Optional(Type.String()),
        app_id: Type.Optional(Type.String()),
        entry_type: Type.Optional(Type.String()),
        content: Type.Optional(LeafContent),
    },
    { $id: 'DisplayAddressWithProof' },
);
