// @generated by @trezor/protobuf/protoc-gen-plugin 1.0.0
// source: messages-debug.proto
// DO NOT EDIT
import { type Static, Type } from '@trezor/schema-utils';

export enum DebugButton {
    NO = 0,
    YES = 1,
    INFO = 2,
}

export type EnumDebugButton = Static<typeof EnumDebugButton>;
export const EnumDebugButton = Type.Enum(DebugButton);

export enum DebugPhysicalButton {
    LEFT_BTN = 0,
    MIDDLE_BTN = 1,
    RIGHT_BTN = 2,
}

export type EnumDebugPhysicalButton = Static<typeof EnumDebugPhysicalButton>;
export const EnumDebugPhysicalButton = Type.Enum(DebugPhysicalButton);

export enum DebugTouchEventType {
    TOUCH_FULL_CLICK = 0,
    TOUCH_START = 1,
    TOUCH_END = 2,
}

export type EnumDebugTouchEventType = Static<typeof EnumDebugTouchEventType>;
export const EnumDebugTouchEventType = Type.Enum(DebugTouchEventType);

export enum DebugWaitType {
    IMMEDIATE = 0,
    NEXT_LAYOUT = 1,
    CURRENT_LAYOUT = 2,
}

export type EnumDebugWaitType = Static<typeof EnumDebugWaitType>;
export const EnumDebugWaitType = Type.Enum(DebugWaitType);

export type DebugLinkGcInfoItem = Static<typeof DebugLinkGcInfoItem>;
export const DebugLinkGcInfoItem = Type.Object(
    {
        name: Type.String(),
        value: Type.Number(),
    },
    { $id: 'DebugLinkGcInfoItem' },
);

export type DebugLinkGcInfo = Static<typeof DebugLinkGcInfo>;
export const DebugLinkGcInfo = Type.Object(
    {
        items: Type.Array(DebugLinkGcInfoItem),
    },
    { $id: 'DebugLinkGcInfo' },
);

export type DebugLinkGetGcInfo = Static<typeof DebugLinkGetGcInfo>;
export const DebugLinkGetGcInfo = Type.Object({}, { $id: 'DebugLinkGetGcInfo' });

export type DebugLinkGetPairingInfo = Static<typeof DebugLinkGetPairingInfo>;
export const DebugLinkGetPairingInfo = Type.Object(
    {
        channel_id: Type.Optional(Type.String()),
        handshake_hash: Type.Optional(Type.String()),
        nfc_secret_host: Type.Optional(Type.String()),
    },
    { $id: 'DebugLinkGetPairingInfo' },
);

export type DebugLinkN4W1Connected = Static<typeof DebugLinkN4W1Connected>;
export const DebugLinkN4W1Connected = Type.Object({}, { $id: 'DebugLinkN4W1Connected' });

export type DebugLinkN4W1Read = Static<typeof DebugLinkN4W1Read>;
export const DebugLinkN4W1Read = Type.Object(
    {
        key: Type.Optional(Type.String()),
    },
    { $id: 'DebugLinkN4W1Read' },
);

export type DebugLinkN4W1Response = Static<typeof DebugLinkN4W1Response>;
export const DebugLinkN4W1Response = Type.Object(
    {
        value: Type.Optional(Type.String()),
    },
    { $id: 'DebugLinkN4W1Response' },
);

export type DebugLinkN4W1Write = Static<typeof DebugLinkN4W1Write>;
export const DebugLinkN4W1Write = Type.Object(
    {
        key: Type.Optional(Type.String()),
        value: Type.Optional(Type.String()),
    },
    { $id: 'DebugLinkN4W1Write' },
);

export type DebugLinkOptigaSetSecMax = Static<typeof DebugLinkOptigaSetSecMax>;
export const DebugLinkOptigaSetSecMax = Type.Object({}, { $id: 'DebugLinkOptigaSetSecMax' });

export type DebugLinkPairingInfo = Static<typeof DebugLinkPairingInfo>;
export const DebugLinkPairingInfo = Type.Object(
    {
        channel_id: Type.Optional(Type.String()),
        handshake_hash: Type.Optional(Type.String()),
        code_entry_code: Type.Optional(Type.Number()),
        code_qr_code: Type.Optional(Type.String()),
        nfc_secret_trezor: Type.Optional(Type.String()),
    },
    { $id: 'DebugLinkPairingInfo' },
);

export type DebugLinkResetDebugEvents = Static<typeof DebugLinkResetDebugEvents>;
export const DebugLinkResetDebugEvents = Type.Object({}, { $id: 'DebugLinkResetDebugEvents' });

export type DebugLinkSetBatteryState = Static<typeof DebugLinkSetBatteryState>;
export const DebugLinkSetBatteryState = Type.Object(
    {
        soc: Type.Optional(Type.Number()),
        usb_connected: Type.Optional(Type.Boolean()),
        wireless_connected: Type.Optional(Type.Boolean()),
        ntc_connected: Type.Optional(Type.Boolean()),
        charging_limited: Type.Optional(Type.Boolean()),
        temp_control_active: Type.Optional(Type.Boolean()),
        battery_connected: Type.Optional(Type.Boolean()),
    },
    { $id: 'DebugLinkSetBatteryState' },
);

export type DebugLinkSetLogFilter = Static<typeof DebugLinkSetLogFilter>;
export const DebugLinkSetLogFilter = Type.Object(
    {
        filter: Type.Optional(Type.String()),
    },
    { $id: 'DebugLinkSetLogFilter' },
);
