// @generated by @trezor/protobuf/protoc-gen-plugin 1.0.0
// source: messages-tezos.proto
// DO NOT EDIT
import { type Static, Type } from '@trezor/schema-utils';

export enum TezosBallotType {
    Yay = 0,
    Nay = 1,
    Pass = 2,
}

export type EnumTezosBallotType = Static<typeof EnumTezosBallotType>;
export const EnumTezosBallotType = Type.Enum(TezosBallotType);

export enum TezosContractType {
    Implicit = 0,
    Originated = 1,
}

export type EnumTezosContractType = Static<typeof EnumTezosContractType>;
export const EnumTezosContractType = Type.Enum(TezosContractType);

export type TezosAddress = Static<typeof TezosAddress>;
export const TezosAddress = Type.Object(
    {
        address: Type.String(),
        mac: Type.Optional(Type.String()),
    },
    { $id: 'TezosAddress' },
);

export type TezosBallotOp = Static<typeof TezosBallotOp>;
export const TezosBallotOp = Type.Object(
    {
        source: Type.String(),
        period: Type.Number(),
        proposal: Type.String(),
        ballot: EnumTezosBallotType,
    },
    { $id: 'TezosBallotOp' },
);

export type TezosContractID = Static<typeof TezosContractID>;
export const TezosContractID = Type.Object(
    {
        tag: Type.Number(),
        hash: Type.Uint8Array(),
    },
    { $id: 'TezosContractID' },
);

export type TezosDelegationOp = Static<typeof TezosDelegationOp>;
export const TezosDelegationOp = Type.Object(
    {
        source: Type.Uint8Array(),
        fee: Type.Uint(),
        counter: Type.Number(),
        gas_limit: Type.Number(),
        storage_limit: Type.Number(),
        delegate: Type.Uint8Array(),
    },
    { $id: 'TezosDelegationOp' },
);

export type TezosGetAddress = Static<typeof TezosGetAddress>;
export const TezosGetAddress = Type.Object(
    {
        address_n: Type.Array(Type.Number()),
        show_display: Type.Optional(Type.Boolean()),
        chunkify: Type.Optional(Type.Boolean()),
    },
    { $id: 'TezosGetAddress' },
);

export type TezosGetPublicKey = Static<typeof TezosGetPublicKey>;
export const TezosGetPublicKey = Type.Object(
    {
        address_n: Type.Array(Type.Number()),
        show_display: Type.Optional(Type.Boolean()),
        chunkify: Type.Optional(Type.Boolean()),
    },
    { $id: 'TezosGetPublicKey' },
);

export type TezosManagerTransfer = Static<typeof TezosManagerTransfer>;
export const TezosManagerTransfer = Type.Object(
    {
        destination: TezosContractID,
        amount: Type.Uint(),
    },
    { $id: 'TezosManagerTransfer' },
);

export type TezosOriginationOp = Static<typeof TezosOriginationOp>;
export const TezosOriginationOp = Type.Object(
    {
        source: Type.Uint8Array(),
        fee: Type.Uint(),
        counter: Type.Number(),
        gas_limit: Type.Number(),
        storage_limit: Type.Number(),
        manager_pubkey: Type.Optional(Type.String()),
        balance: Type.Number(),
        spendable: Type.Optional(Type.Boolean()),
        delegatable: Type.Optional(Type.Boolean()),
        delegate: Type.Optional(Type.Uint8Array()),
        script: Type.Union([Type.String(), Type.Array(Type.Number())]),
    },
    { $id: 'TezosOriginationOp' },
);

export type TezosParametersManager = Static<typeof TezosParametersManager>;
export const TezosParametersManager = Type.Object(
    {
        set_delegate: Type.Optional(Type.Uint8Array()),
        cancel_delegate: Type.Optional(Type.Boolean()),
        transfer: Type.Optional(TezosManagerTransfer),
    },
    { $id: 'TezosParametersManager' },
);

export type TezosProposalOp = Static<typeof TezosProposalOp>;
export const TezosProposalOp = Type.Object(
    {
        source: Type.String(),
        period: Type.Number(),
        proposals: Type.Array(Type.String()),
    },
    { $id: 'TezosProposalOp' },
);

export type TezosPublicKey = Static<typeof TezosPublicKey>;
export const TezosPublicKey = Type.Object(
    {
        public_key: Type.String(),
    },
    { $id: 'TezosPublicKey' },
);

export type TezosRevealOp = Static<typeof TezosRevealOp>;
export const TezosRevealOp = Type.Object(
    {
        source: Type.Uint8Array(),
        fee: Type.Uint(),
        counter: Type.Number(),
        gas_limit: Type.Number(),
        storage_limit: Type.Number(),
        public_key: Type.Uint8Array(),
    },
    { $id: 'TezosRevealOp' },
);

export type TezosSignedTx = Static<typeof TezosSignedTx>;
export const TezosSignedTx = Type.Object(
    {
        signature: Type.String(),
        sig_op_contents: Type.String(),
        operation_hash: Type.String(),
    },
    { $id: 'TezosSignedTx' },
);

export type TezosTransactionOp = Static<typeof TezosTransactionOp>;
export const TezosTransactionOp = Type.Object(
    {
        source: Type.Uint8Array(),
        fee: Type.Uint(),
        counter: Type.Number(),
        gas_limit: Type.Number(),
        storage_limit: Type.Number(),
        amount: Type.Uint(),
        destination: TezosContractID,
        parameters: Type.Optional(Type.Array(Type.Number())),
        parameters_manager: Type.Optional(TezosParametersManager),
    },
    { $id: 'TezosTransactionOp' },
);

export type TezosSignTx = Static<typeof TezosSignTx>;
export const TezosSignTx = Type.Object(
    {
        address_n: Type.Array(Type.Number()),
        branch: Type.Uint8Array(),
        reveal: Type.Optional(TezosRevealOp),
        transaction: Type.Optional(TezosTransactionOp),
        origination: Type.Optional(TezosOriginationOp),
        delegation: Type.Optional(TezosDelegationOp),
        proposal: Type.Optional(TezosProposalOp),
        ballot: Type.Optional(TezosBallotOp),
        chunkify: Type.Optional(Type.Boolean()),
    },
    { $id: 'TezosSignTx' },
);
