// @generated by @trezor/protobuf/protoc-gen-plugin 1.0.0
// source: messages-cardano.proto
// DO NOT EDIT
import { type Static, Type } from '@trezor/schema-utils';

import { HDNodeType, PaymentRequest } from './messages-common';

export enum CardanoAddressType {
    BASE = 0,
    BASE_SCRIPT_KEY = 1,
    BASE_KEY_SCRIPT = 2,
    BASE_SCRIPT_SCRIPT = 3,
    POINTER = 4,
    POINTER_SCRIPT = 5,
    ENTERPRISE = 6,
    ENTERPRISE_SCRIPT = 7,
    BYRON = 8,
    REWARD = 14,
    REWARD_SCRIPT = 15,
}

export type EnumCardanoAddressType = Static<typeof EnumCardanoAddressType>;
export const EnumCardanoAddressType = Type.Enum(CardanoAddressType);

export enum CardanoCertificateType {
    STAKE_REGISTRATION = 0,
    STAKE_DEREGISTRATION = 1,
    STAKE_DELEGATION = 2,
    STAKE_POOL_REGISTRATION = 3,
    STAKE_REGISTRATION_CONWAY = 7,
    STAKE_DEREGISTRATION_CONWAY = 8,
    VOTE_DELEGATION = 9,
}

export type EnumCardanoCertificateType = Static<typeof EnumCardanoCertificateType>;
export const EnumCardanoCertificateType = Type.Enum(CardanoCertificateType);

export enum CardanoCVoteRegistrationFormat {
    CIP15 = 0,
    CIP36 = 1,
}

export type EnumCardanoCVoteRegistrationFormat = Static<typeof EnumCardanoCVoteRegistrationFormat>;
export const EnumCardanoCVoteRegistrationFormat = Type.Enum(CardanoCVoteRegistrationFormat);

export enum CardanoDerivationType {
    LEDGER = 0,
    ICARUS = 1,
    ICARUS_TREZOR = 2,
}

export type EnumCardanoDerivationType = Static<typeof EnumCardanoDerivationType>;
export const EnumCardanoDerivationType = Type.Enum(CardanoDerivationType);

export enum CardanoDRepType {
    KEY_HASH = 0,
    SCRIPT_HASH = 1,
    ABSTAIN = 2,
    NO_CONFIDENCE = 3,
}

export type EnumCardanoDRepType = Static<typeof EnumCardanoDRepType>;
export const EnumCardanoDRepType = Type.Enum(CardanoDRepType);

export enum CardanoNativeScriptHashDisplayFormat {
    HIDE = 0,
    BECH32 = 1,
    POLICY_ID = 2,
}

export type EnumCardanoNativeScriptHashDisplayFormat = Static<
    typeof EnumCardanoNativeScriptHashDisplayFormat
>;
export const EnumCardanoNativeScriptHashDisplayFormat = Type.Enum(
    CardanoNativeScriptHashDisplayFormat,
);

export enum CardanoNativeScriptType {
    PUB_KEY = 0,
    ALL = 1,
    ANY = 2,
    N_OF_K = 3,
    INVALID_BEFORE = 4,
    INVALID_HEREAFTER = 5,
}

export type EnumCardanoNativeScriptType = Static<typeof EnumCardanoNativeScriptType>;
export const EnumCardanoNativeScriptType = Type.Enum(CardanoNativeScriptType);

export enum CardanoPoolRelayType {
    SINGLE_HOST_IP = 0,
    SINGLE_HOST_NAME = 1,
    MULTIPLE_HOST_NAME = 2,
}

export type EnumCardanoPoolRelayType = Static<typeof EnumCardanoPoolRelayType>;
export const EnumCardanoPoolRelayType = Type.Enum(CardanoPoolRelayType);

export enum CardanoTxAuxiliaryDataSupplementType {
    NONE = 0,
    CVOTE_REGISTRATION_SIGNATURE = 1,
}

export type EnumCardanoTxAuxiliaryDataSupplementType = Static<
    typeof EnumCardanoTxAuxiliaryDataSupplementType
>;
export const EnumCardanoTxAuxiliaryDataSupplementType = Type.Enum(
    CardanoTxAuxiliaryDataSupplementType,
);

export enum CardanoTxOutputSerializationFormat {
    ARRAY_LEGACY = 0,
    MAP_BABBAGE = 1,
}

export type EnumCardanoTxOutputSerializationFormat = Static<
    typeof EnumCardanoTxOutputSerializationFormat
>;
export const EnumCardanoTxOutputSerializationFormat = Type.Enum(CardanoTxOutputSerializationFormat);

export enum CardanoTxSigningMode {
    ORDINARY_TRANSACTION = 0,
    POOL_REGISTRATION_AS_OWNER = 1,
    MULTISIG_TRANSACTION = 2,
    PLUTUS_TRANSACTION = 3,
}

export type EnumCardanoTxSigningMode = Static<typeof EnumCardanoTxSigningMode>;
export const EnumCardanoTxSigningMode = Type.Enum(CardanoTxSigningMode);

export enum CardanoTxWitnessType {
    BYRON_WITNESS = 0,
    SHELLEY_WITNESS = 1,
}

export type EnumCardanoTxWitnessType = Static<typeof EnumCardanoTxWitnessType>;
export const EnumCardanoTxWitnessType = Type.Enum(CardanoTxWitnessType);

export type CardanoAddress = Static<typeof CardanoAddress>;
export const CardanoAddress = Type.Object(
    {
        address: Type.String(),
        mac: Type.Optional(Type.String()),
    },
    { $id: 'CardanoAddress' },
);

export type CardanoBlockchainPointerType = Static<typeof CardanoBlockchainPointerType>;
export const CardanoBlockchainPointerType = Type.Object(
    {
        block_index: Type.Number(),
        tx_index: Type.Number(),
        certificate_index: Type.Number(),
    },
    { $id: 'CardanoBlockchainPointerType' },
);

export type CardanoAddressParametersType = Static<typeof CardanoAddressParametersType>;
export const CardanoAddressParametersType = Type.Object(
    {
        address_type: EnumCardanoAddressType,
        address_n: Type.Array(Type.Number()),
        address_n_staking: Type.Array(Type.Number()),
        staking_key_hash: Type.Optional(Type.String()),
        certificate_pointer: Type.Optional(CardanoBlockchainPointerType),
        script_payment_hash: Type.Optional(Type.String()),
        script_staking_hash: Type.Optional(Type.String()),
    },
    { $id: 'CardanoAddressParametersType' },
);

export type CardanoAssetGroup = Static<typeof CardanoAssetGroup>;
export const CardanoAssetGroup = Type.Object(
    {
        policy_id: Type.String(),
        tokens_count: Type.Number(),
    },
    { $id: 'CardanoAssetGroup' },
);

export type CardanoCVoteRegistrationDelegation = Static<typeof CardanoCVoteRegistrationDelegation>;
export const CardanoCVoteRegistrationDelegation = Type.Object(
    {
        vote_public_key: Type.String(),
        weight: Type.Uint(),
    },
    { $id: 'CardanoCVoteRegistrationDelegation' },
);

export type CardanoCVoteRegistrationParametersType = Static<
    typeof CardanoCVoteRegistrationParametersType
>;
export const CardanoCVoteRegistrationParametersType = Type.Object(
    {
        vote_public_key: Type.Optional(Type.String()),
        staking_path: Type.Array(Type.Number()),
        payment_address_parameters: Type.Optional(CardanoAddressParametersType),
        nonce: Type.Uint(),
        format: Type.Optional(EnumCardanoCVoteRegistrationFormat),
        delegations: Type.Optional(Type.Array(CardanoCVoteRegistrationDelegation)),
        voting_purpose: Type.Optional(Type.Uint()),
        payment_address: Type.Optional(Type.String()),
    },
    { $id: 'CardanoCVoteRegistrationParametersType' },
);

export type CardanoDRep = Static<typeof CardanoDRep>;
export const CardanoDRep = Type.Object(
    {
        type: EnumCardanoDRepType,
        key_hash: Type.Optional(Type.String()),
        script_hash: Type.Optional(Type.String()),
    },
    { $id: 'CardanoDRep' },
);

export type CardanoGetAddress = Static<typeof CardanoGetAddress>;
export const CardanoGetAddress = Type.Object(
    {
        show_display: Type.Optional(Type.Boolean()),
        protocol_magic: Type.Number(),
        network_id: Type.Number(),
        address_parameters: CardanoAddressParametersType,
        derivation_type: EnumCardanoDerivationType,
        chunkify: Type.Optional(Type.Boolean()),
    },
    { $id: 'CardanoGetAddress' },
);

export type CardanoNativeScript = Static<typeof CardanoNativeScript>;
export const CardanoNativeScript = Type.Recursive(
    This =>
        Type.Object({
            type: EnumCardanoNativeScriptType,
            scripts: Type.Optional(Type.Array(This)),
            key_hash: Type.Optional(Type.String()),
            key_path: Type.Optional(Type.Array(Type.Number())),
            required_signatures_count: Type.Optional(Type.Number()),
            invalid_before: Type.Optional(Type.Uint()),
            invalid_hereafter: Type.Optional(Type.Uint()),
        }),
    { $id: 'CardanoNativeScript' },
);

export type CardanoGetNativeScriptHash = Static<typeof CardanoGetNativeScriptHash>;
export const CardanoGetNativeScriptHash = Type.Object(
    {
        script: CardanoNativeScript,
        display_format: EnumCardanoNativeScriptHashDisplayFormat,
        derivation_type: EnumCardanoDerivationType,
    },
    { $id: 'CardanoGetNativeScriptHash' },
);

export type CardanoGetPublicKey = Static<typeof CardanoGetPublicKey>;
export const CardanoGetPublicKey = Type.Object(
    {
        address_n: Type.Array(Type.Number()),
        show_display: Type.Optional(Type.Boolean()),
        derivation_type: EnumCardanoDerivationType,
    },
    { $id: 'CardanoGetPublicKey' },
);

export type CardanoMessageDataRequest = Static<typeof CardanoMessageDataRequest>;
export const CardanoMessageDataRequest = Type.Object(
    {
        length: Type.Number(),
        offset: Type.Number(),
    },
    { $id: 'CardanoMessageDataRequest' },
);

export type CardanoMessageDataResponse = Static<typeof CardanoMessageDataResponse>;
export const CardanoMessageDataResponse = Type.Object(
    {
        data: Type.String(),
    },
    { $id: 'CardanoMessageDataResponse' },
);

export type CardanoMessageSignature = Static<typeof CardanoMessageSignature>;
export const CardanoMessageSignature = Type.Object(
    {
        signature: Type.String(),
        address: Type.String(),
        pub_key: Type.String(),
    },
    { $id: 'CardanoMessageSignature' },
);

export type CardanoNativeScriptHash = Static<typeof CardanoNativeScriptHash>;
export const CardanoNativeScriptHash = Type.Object(
    {
        script_hash: Type.String(),
    },
    { $id: 'CardanoNativeScriptHash' },
);

export type CardanoPoolMetadataType = Static<typeof CardanoPoolMetadataType>;
export const CardanoPoolMetadataType = Type.Object(
    {
        url: Type.String(),
        hash: Type.String(),
    },
    { $id: 'CardanoPoolMetadataType' },
);

export type CardanoPoolOwner = Static<typeof CardanoPoolOwner>;
export const CardanoPoolOwner = Type.Object(
    {
        staking_key_path: Type.Optional(Type.Array(Type.Number())),
        staking_key_hash: Type.Optional(Type.String()),
    },
    { $id: 'CardanoPoolOwner' },
);

export type CardanoPoolParametersType = Static<typeof CardanoPoolParametersType>;
export const CardanoPoolParametersType = Type.Object(
    {
        pool_id: Type.String(),
        vrf_key_hash: Type.String(),
        pledge: Type.Uint(),
        cost: Type.Uint(),
        margin_numerator: Type.Uint(),
        margin_denominator: Type.Uint(),
        reward_account: Type.String(),
        metadata: Type.Optional(CardanoPoolMetadataType),
        owners_count: Type.Number(),
        relays_count: Type.Number(),
    },
    { $id: 'CardanoPoolParametersType' },
);

export type CardanoPoolRelayParameters = Static<typeof CardanoPoolRelayParameters>;
export const CardanoPoolRelayParameters = Type.Object(
    {
        type: EnumCardanoPoolRelayType,
        ipv4_address: Type.Optional(Type.String()),
        ipv6_address: Type.Optional(Type.String()),
        host_name: Type.Optional(Type.String()),
        port: Type.Optional(Type.Number()),
    },
    { $id: 'CardanoPoolRelayParameters' },
);

export type CardanoPublicKey = Static<typeof CardanoPublicKey>;
export const CardanoPublicKey = Type.Object(
    {
        xpub: Type.String(),
        node: HDNodeType,
    },
    { $id: 'CardanoPublicKey' },
);

export type CardanoSignMessageInit = Static<typeof CardanoSignMessageInit>;
export const CardanoSignMessageInit = Type.Object(
    {
        protocol_magic: Type.Optional(Type.Number()),
        network_id: Type.Optional(Type.Number()),
        signing_path: Type.Array(Type.Number()),
        payload_size: Type.Number(),
        prefer_hex_display: Type.Boolean(),
        address_parameters: Type.Optional(CardanoAddressParametersType),
        derivation_type: EnumCardanoDerivationType,
    },
    { $id: 'CardanoSignMessageInit' },
);

export type CardanoSignTxFinished = Static<typeof CardanoSignTxFinished>;
export const CardanoSignTxFinished = Type.Object({}, { $id: 'CardanoSignTxFinished' });

export type CardanoSignTxInit = Static<typeof CardanoSignTxInit>;
export const CardanoSignTxInit = Type.Object(
    {
        signing_mode: EnumCardanoTxSigningMode,
        protocol_magic: Type.Number(),
        network_id: Type.Number(),
        inputs_count: Type.Number(),
        outputs_count: Type.Number(),
        fee: Type.Uint(),
        ttl: Type.Optional(Type.Uint()),
        certificates_count: Type.Number(),
        withdrawals_count: Type.Number(),
        has_auxiliary_data: Type.Boolean(),
        validity_interval_start: Type.Optional(Type.Uint()),
        witness_requests_count: Type.Number(),
        minting_asset_groups_count: Type.Number(),
        derivation_type: EnumCardanoDerivationType,
        include_network_id: Type.Optional(Type.Boolean()),
        script_data_hash: Type.Optional(Type.String()),
        collateral_inputs_count: Type.Number(),
        required_signers_count: Type.Number(),
        has_collateral_return: Type.Optional(Type.Boolean()),
        total_collateral: Type.Optional(Type.Uint()),
        reference_inputs_count: Type.Optional(Type.Number()),
        chunkify: Type.Optional(Type.Boolean()),
        tag_cbor_sets: Type.Optional(Type.Boolean()),
        payment_req: Type.Optional(PaymentRequest),
    },
    { $id: 'CardanoSignTxInit' },
);

export type CardanoToken = Static<typeof CardanoToken>;
export const CardanoToken = Type.Object(
    {
        asset_name_bytes: Type.String(),
        amount: Type.Optional(Type.Uint()),
        mint_amount: Type.Optional(Type.Uint({ allowNegative: true })),
    },
    { $id: 'CardanoToken' },
);

export type CardanoTxAuxiliaryData = Static<typeof CardanoTxAuxiliaryData>;
export const CardanoTxAuxiliaryData = Type.Object(
    {
        cvote_registration_parameters: Type.Optional(CardanoCVoteRegistrationParametersType),
        hash: Type.Optional(Type.String()),
    },
    { $id: 'CardanoTxAuxiliaryData' },
);

export type CardanoTxAuxiliaryDataSupplement = Static<typeof CardanoTxAuxiliaryDataSupplement>;
export const CardanoTxAuxiliaryDataSupplement = Type.Object(
    {
        type: EnumCardanoTxAuxiliaryDataSupplementType,
        auxiliary_data_hash: Type.Optional(Type.String()),
        cvote_registration_signature: Type.Optional(Type.String()),
    },
    { $id: 'CardanoTxAuxiliaryDataSupplement' },
);

export type CardanoTxBodyHash = Static<typeof CardanoTxBodyHash>;
export const CardanoTxBodyHash = Type.Object(
    {
        tx_hash: Type.String(),
    },
    { $id: 'CardanoTxBodyHash' },
);

export type CardanoTxCertificate = Static<typeof CardanoTxCertificate>;
export const CardanoTxCertificate = Type.Object(
    {
        type: EnumCardanoCertificateType,
        path: Type.Optional(Type.Array(Type.Number())),
        pool: Type.Optional(Type.String()),
        pool_parameters: Type.Optional(CardanoPoolParametersType),
        script_hash: Type.Optional(Type.String()),
        key_hash: Type.Optional(Type.String()),
        deposit: Type.Optional(Type.Uint()),
        drep: Type.Optional(CardanoDRep),
    },
    { $id: 'CardanoTxCertificate' },
);

export type CardanoTxCollateralInput = Static<typeof CardanoTxCollateralInput>;
export const CardanoTxCollateralInput = Type.Object(
    {
        prev_hash: Type.String(),
        prev_index: Type.Number(),
    },
    { $id: 'CardanoTxCollateralInput' },
);

export type CardanoTxHostAck = Static<typeof CardanoTxHostAck>;
export const CardanoTxHostAck = Type.Object({}, { $id: 'CardanoTxHostAck' });

export type CardanoTxInlineDatumChunk = Static<typeof CardanoTxInlineDatumChunk>;
export const CardanoTxInlineDatumChunk = Type.Object(
    {
        data: Type.String(),
    },
    { $id: 'CardanoTxInlineDatumChunk' },
);

export type CardanoTxInput = Static<typeof CardanoTxInput>;
export const CardanoTxInput = Type.Object(
    {
        prev_hash: Type.String(),
        prev_index: Type.Number(),
    },
    { $id: 'CardanoTxInput' },
);

export type CardanoTxItemAck = Static<typeof CardanoTxItemAck>;
export const CardanoTxItemAck = Type.Object({}, { $id: 'CardanoTxItemAck' });

export type CardanoTxMint = Static<typeof CardanoTxMint>;
export const CardanoTxMint = Type.Object(
    {
        asset_groups_count: Type.Number(),
    },
    { $id: 'CardanoTxMint' },
);

export type CardanoTxOutput = Static<typeof CardanoTxOutput>;
export const CardanoTxOutput = Type.Object(
    {
        address: Type.Optional(Type.String()),
        address_parameters: Type.Optional(CardanoAddressParametersType),
        amount: Type.Uint(),
        asset_groups_count: Type.Number(),
        datum_hash: Type.Optional(Type.String()),
        format: Type.Optional(EnumCardanoTxOutputSerializationFormat),
        inline_datum_size: Type.Optional(Type.Number()),
        reference_script_size: Type.Optional(Type.Number()),
    },
    { $id: 'CardanoTxOutput' },
);

export type CardanoTxReferenceInput = Static<typeof CardanoTxReferenceInput>;
export const CardanoTxReferenceInput = Type.Object(
    {
        prev_hash: Type.String(),
        prev_index: Type.Number(),
    },
    { $id: 'CardanoTxReferenceInput' },
);

export type CardanoTxReferenceScriptChunk = Static<typeof CardanoTxReferenceScriptChunk>;
export const CardanoTxReferenceScriptChunk = Type.Object(
    {
        data: Type.String(),
    },
    { $id: 'CardanoTxReferenceScriptChunk' },
);

export type CardanoTxRequiredSigner = Static<typeof CardanoTxRequiredSigner>;
export const CardanoTxRequiredSigner = Type.Object(
    {
        key_hash: Type.Optional(Type.String()),
        key_path: Type.Optional(Type.Array(Type.Number())),
    },
    { $id: 'CardanoTxRequiredSigner' },
);

export type CardanoTxWithdrawal = Static<typeof CardanoTxWithdrawal>;
export const CardanoTxWithdrawal = Type.Object(
    {
        path: Type.Optional(Type.Array(Type.Number())),
        amount: Type.Uint(),
        script_hash: Type.Optional(Type.String()),
        key_hash: Type.Optional(Type.String()),
    },
    { $id: 'CardanoTxWithdrawal' },
);

export type CardanoTxWitnessRequest = Static<typeof CardanoTxWitnessRequest>;
export const CardanoTxWitnessRequest = Type.Object(
    {
        path: Type.Array(Type.Number()),
    },
    { $id: 'CardanoTxWitnessRequest' },
);

export type CardanoTxWitnessResponse = Static<typeof CardanoTxWitnessResponse>;
export const CardanoTxWitnessResponse = Type.Object(
    {
        type: EnumCardanoTxWitnessType,
        pub_key: Type.String(),
        signature: Type.String(),
        chain_code: Type.Optional(Type.String()),
    },
    { $id: 'CardanoTxWitnessResponse' },
);
