// @generated by @trezor/protobuf/protoc-gen-plugin 1.0.0
// source: messages-extapp.proto
// DO NOT EDIT
import { type Static, Type } from '@trezor/schema-utils';

import { Version } from './messages-common';

export type ExtAppDataChunkAck = Static<typeof ExtAppDataChunkAck>;
export const ExtAppDataChunkAck = Type.Object(
    {
        data: Type.String(),
        hash: Type.String(),
    },
    { $id: 'ExtAppDataChunkAck' },
);

export type ExtAppDataChunkRequest = Static<typeof ExtAppDataChunkRequest>;
export const ExtAppDataChunkRequest = Type.Object(
    {
        index: Type.Number(),
    },
    { $id: 'ExtAppDataChunkRequest' },
);

export type ExtAppHeaderAck = Static<typeof ExtAppHeaderAck>;
export const ExtAppHeaderAck = Type.Object(
    {
        header: Type.String(),
        proof: Type.String(),
        root_packet_timestamp: Type.Number(),
    },
    { $id: 'ExtAppHeaderAck' },
);

export type ExtAppHeaderRequest = Static<typeof ExtAppHeaderRequest>;
export const ExtAppHeaderRequest = Type.Record(Type.Never(), Type.Never(), {
    $id: 'ExtAppHeaderRequest',
});

export type ExtAppLoad = Static<typeof ExtAppLoad>;
export const ExtAppLoad = Type.Object(
    {
        id: Type.String(),
        version: Version,
        fingerprint: Type.String(),
    },
    { $id: 'ExtAppLoad' },
);

export type ExtAppLoaded = Static<typeof ExtAppLoaded>;
export const ExtAppLoaded = Type.Object(
    {
        instance_id: Type.Number(),
    },
    { $id: 'ExtAppLoaded' },
);

export type ExtAppMessage = Static<typeof ExtAppMessage>;
export const ExtAppMessage = Type.Object(
    {
        instance_id: Type.Number(),
        message_id: Type.Number(),
        data: Type.String(),
    },
    { $id: 'ExtAppMessage' },
);

export type ExtAppResponse = Static<typeof ExtAppResponse>;
export const ExtAppResponse = Type.Object(
    {
        message_id: Type.Number(),
        data: Type.String(),
        finished: Type.Optional(Type.Boolean()),
    },
    { $id: 'ExtAppResponse' },
);

export type ExtAppRootPacketAck = Static<typeof ExtAppRootPacketAck>;
export const ExtAppRootPacketAck = Type.Object(
    {
        root_packet: Type.String(),
    },
    { $id: 'ExtAppRootPacketAck' },
);

export type ExtAppRootPacketRequest = Static<typeof ExtAppRootPacketRequest>;
export const ExtAppRootPacketRequest = Type.Object(
    {
        app_ring: Type.Number(),
    },
    { $id: 'ExtAppRootPacketRequest' },
);
