// @generated by @trezor/protobuf/protoc-gen-plugin 1.0.0
// source: messages-thp.proto
// DO NOT EDIT
import { type Static, Type } from '@trezor/schema-utils';

export enum ThpMessageType {
    ThpMessageType_Cancel = 20,
    ThpMessageType_ButtonRequest = 26,
    ThpMessageType_ButtonAck = 27,
    ThpMessageType_ThpPairingRequest = 1008,
    ThpMessageType_ThpPairingRequestApproved = 1009,
    ThpMessageType_ThpSelectMethod = 1010,
    ThpMessageType_ThpPairingPreparationsFinished = 1011,
    ThpMessageType_ThpCredentialRequest = 1016,
    ThpMessageType_ThpCredentialResponse = 1017,
    ThpMessageType_ThpEndRequest = 1018,
    ThpMessageType_ThpEndResponse = 1019,
    ThpMessageType_ThpCodeEntryCommitment = 1024,
    ThpMessageType_ThpCodeEntryChallenge = 1025,
    ThpMessageType_ThpCodeEntryCpaceTrezor = 1026,
    ThpMessageType_ThpCodeEntryCpaceHostTag = 1027,
    ThpMessageType_ThpCodeEntrySecret = 1028,
    ThpMessageType_ThpQrCodeTag = 1032,
    ThpMessageType_ThpQrCodeSecret = 1033,
    ThpMessageType_ThpNfcTagHost = 1040,
    ThpMessageType_ThpNfcTagTrezor = 1041,
}

export type EnumThpMessageType = Static<typeof EnumThpMessageType>;
export const EnumThpMessageType = Type.Enum(ThpMessageType);

export enum ThpPairingMethod {
    SkipPairing = 1,
    CodeEntry = 2,
    QrCode = 3,
    NFC = 4,
}

export type EnumThpPairingMethod = Static<typeof EnumThpPairingMethod>;
export const EnumThpPairingMethod = Type.Enum(ThpPairingMethod);

export type ThpCredentialMetadata = Static<typeof ThpCredentialMetadata>;
export const ThpCredentialMetadata = Type.Object(
    {
        host_name: Type.String(),
        autoconnect: Type.Optional(Type.Boolean()),
        app_name: Type.String(),
    },
    { $id: 'ThpCredentialMetadata' },
);

export type ThpAuthenticatedCredentialData = Static<typeof ThpAuthenticatedCredentialData>;
export const ThpAuthenticatedCredentialData = Type.Object(
    {
        host_static_public_key: Type.String(),
        cred_metadata: ThpCredentialMetadata,
    },
    { $id: 'ThpAuthenticatedCredentialData' },
);

export type ThpCodeEntryChallenge = Static<typeof ThpCodeEntryChallenge>;
export const ThpCodeEntryChallenge = Type.Object(
    {
        challenge: Type.String(),
    },
    { $id: 'ThpCodeEntryChallenge' },
);

export type ThpCodeEntryCommitment = Static<typeof ThpCodeEntryCommitment>;
export const ThpCodeEntryCommitment = Type.Object(
    {
        commitment: Type.String(),
    },
    { $id: 'ThpCodeEntryCommitment' },
);

export type ThpCodeEntryCpaceHostTag = Static<typeof ThpCodeEntryCpaceHostTag>;
export const ThpCodeEntryCpaceHostTag = Type.Object(
    {
        cpace_host_public_key: Type.String(),
        tag: Type.String(),
    },
    { $id: 'ThpCodeEntryCpaceHostTag' },
);

export type ThpCodeEntryCpaceTrezor = Static<typeof ThpCodeEntryCpaceTrezor>;
export const ThpCodeEntryCpaceTrezor = Type.Object(
    {
        cpace_trezor_public_key: Type.String(),
    },
    { $id: 'ThpCodeEntryCpaceTrezor' },
);

export type ThpCodeEntrySecret = Static<typeof ThpCodeEntrySecret>;
export const ThpCodeEntrySecret = Type.Object(
    {
        secret: Type.String(),
    },
    { $id: 'ThpCodeEntrySecret' },
);

export type ThpCreateNewSession = Static<typeof ThpCreateNewSession>;
export const ThpCreateNewSession = Type.Intersect(
    [
        Type.Object({
            derive_cardano: Type.Optional(Type.Boolean()),
        }),
        Type.Union([
            Type.Object({
                passphrase: Type.String(),
                on_device: Type.Optional(Type.Undefined()),
            }),
            Type.Object({
                passphrase: Type.Optional(Type.Undefined()),
                on_device: Type.Boolean(),
            }),
        ]),
    ],
    { $id: 'ThpCreateNewSession' },
);

export type ThpCredentialRequest = Static<typeof ThpCredentialRequest>;
export const ThpCredentialRequest = Type.Object(
    {
        host_static_public_key: Type.String(),
        autoconnect: Type.Optional(Type.Boolean()),
        credential: Type.Optional(Type.String()),
    },
    { $id: 'ThpCredentialRequest' },
);

export type ThpCredentialResponse = Static<typeof ThpCredentialResponse>;
export const ThpCredentialResponse = Type.Object(
    {
        trezor_static_public_key: Type.String(),
        credential: Type.String(),
    },
    { $id: 'ThpCredentialResponse' },
);

export type ThpDeviceProperties = Static<typeof ThpDeviceProperties>;
export const ThpDeviceProperties = Type.Object(
    {
        internal_model: Type.String(),
        model_variant: Type.Optional(Type.Number()),
        protocol_version_major: Type.Number(),
        protocol_version_minor: Type.Number(),
        pairing_methods: Type.Array(Type.KeyOfEnum(ThpPairingMethod)),
    },
    { $id: 'ThpDeviceProperties' },
);

export type ThpEndRequest = Static<typeof ThpEndRequest>;
export const ThpEndRequest = Type.Object({}, { $id: 'ThpEndRequest' });

export type ThpEndResponse = Static<typeof ThpEndResponse>;
export const ThpEndResponse = Type.Object({}, { $id: 'ThpEndResponse' });

export type ThpHandshakeCompletionReqNoisePayload = Static<
    typeof ThpHandshakeCompletionReqNoisePayload
>;
export const ThpHandshakeCompletionReqNoisePayload = Type.Object(
    {
        host_pairing_credential: Type.Optional(Type.String()),
    },
    { $id: 'ThpHandshakeCompletionReqNoisePayload' },
);

export type ThpNfcTagHost = Static<typeof ThpNfcTagHost>;
export const ThpNfcTagHost = Type.Object(
    {
        tag: Type.String(),
    },
    { $id: 'ThpNfcTagHost' },
);

export type ThpNfcTagTrezor = Static<typeof ThpNfcTagTrezor>;
export const ThpNfcTagTrezor = Type.Object(
    {
        tag: Type.String(),
    },
    { $id: 'ThpNfcTagTrezor' },
);

export type ThpPairedCacheEntry = Static<typeof ThpPairedCacheEntry>;
export const ThpPairedCacheEntry = Type.Object(
    {
        mac_addr: Type.String(),
        host_name: Type.String(),
        app_name: Type.String(),
    },
    { $id: 'ThpPairedCacheEntry' },
);

export type ThpPairedCache = Static<typeof ThpPairedCache>;
export const ThpPairedCache = Type.Object(
    {
        entries: Type.Array(ThpPairedCacheEntry),
    },
    { $id: 'ThpPairedCache' },
);

export type ThpPairingCredential = Static<typeof ThpPairingCredential>;
export const ThpPairingCredential = Type.Object(
    {
        cred_metadata: ThpCredentialMetadata,
        mac: Type.String(),
    },
    { $id: 'ThpPairingCredential' },
);

export type ThpPairingPreparationsFinished = Static<typeof ThpPairingPreparationsFinished>;
export const ThpPairingPreparationsFinished = Type.Object(
    {},
    { $id: 'ThpPairingPreparationsFinished' },
);

export type ThpPairingRequest = Static<typeof ThpPairingRequest>;
export const ThpPairingRequest = Type.Object(
    {
        host_name: Type.String(),
        app_name: Type.String(),
    },
    { $id: 'ThpPairingRequest' },
);

export type ThpPairingRequestApproved = Static<typeof ThpPairingRequestApproved>;
export const ThpPairingRequestApproved = Type.Object({}, { $id: 'ThpPairingRequestApproved' });

export type ThpQrCodeSecret = Static<typeof ThpQrCodeSecret>;
export const ThpQrCodeSecret = Type.Object(
    {
        secret: Type.String(),
    },
    { $id: 'ThpQrCodeSecret' },
);

export type ThpQrCodeTag = Static<typeof ThpQrCodeTag>;
export const ThpQrCodeTag = Type.Object(
    {
        tag: Type.String(),
    },
    { $id: 'ThpQrCodeTag' },
);

export type ThpSelectMethod = Static<typeof ThpSelectMethod>;
export const ThpSelectMethod = Type.Object(
    {
        selected_pairing_method: EnumThpPairingMethod,
    },
    { $id: 'ThpSelectMethod' },
);
