// @generated by @trezor/protobuf/protoc-gen-plugin 1.0.0
// source: messages-tron.proto
// DO NOT EDIT
import { type Static, Type } from '@trezor/schema-utils';

export enum TronRawContractType {
    TransferContract = 1,
    VoteWitnessContract = 4,
    TriggerSmartContract = 31,
    FreezeBalanceV2Contract = 54,
    UnfreezeBalanceV2Contract = 55,
    WithdrawExpireUnfreezeContract = 56,
}

export type EnumTronRawContractType = Static<typeof EnumTronRawContractType>;
export const EnumTronRawContractType = Type.Enum(TronRawContractType);

export enum TronResourceCode {
    BANDWIDTH = 0,
    ENERGY = 1,
}

export type EnumTronResourceCode = Static<typeof EnumTronResourceCode>;
export const EnumTronResourceCode = Type.Enum(TronResourceCode);

export type TronAddress = Static<typeof TronAddress>;
export const TronAddress = Type.Object(
    {
        address: Type.String(),
        mac: Type.Optional(Type.String()),
    },
    { $id: 'TronAddress' },
);

export type TronContractRequest = Static<typeof TronContractRequest>;
export const TronContractRequest = Type.Object({}, { $id: 'TronContractRequest' });

export type TronFreezeBalanceV2Contract = Static<typeof TronFreezeBalanceV2Contract>;
export const TronFreezeBalanceV2Contract = Type.Object(
    {
        owner_address: Type.String(),
        balance: Type.Number(),
        resource: Type.Optional(EnumTronResourceCode),
    },
    { $id: 'TronFreezeBalanceV2Contract' },
);

export type TronGetAddress = Static<typeof TronGetAddress>;
export const TronGetAddress = Type.Object(
    {
        address_n: Type.Array(Type.Number()),
        show_display: Type.Optional(Type.Boolean()),
        chunkify: Type.Optional(Type.Boolean()),
    },
    { $id: 'TronGetAddress' },
);

export type TronRawParameter = Static<typeof TronRawParameter>;
export const TronRawParameter = Type.Object(
    {
        type_url: Type.String(),
        value: Type.String(),
    },
    { $id: 'TronRawParameter' },
);

export type TronRawContract = Static<typeof TronRawContract>;
export const TronRawContract = Type.Object(
    {
        type: EnumTronRawContractType,
        parameter: TronRawParameter,
    },
    { $id: 'TronRawContract' },
);

export type TronRawTransaction = Static<typeof TronRawTransaction>;
export const TronRawTransaction = Type.Object(
    {
        ref_block_bytes: Type.String(),
        ref_block_hash: Type.String(),
        expiration: Type.Number(),
        data: Type.Optional(Type.String()),
        contract: Type.Array(TronRawContract),
        timestamp: Type.Number(),
        fee_limit: Type.Optional(Type.Number()),
    },
    { $id: 'TronRawTransaction' },
);

export type TronSignature = Static<typeof TronSignature>;
export const TronSignature = Type.Object(
    {
        signature: Type.String(),
    },
    { $id: 'TronSignature' },
);

export type TronSignTx = Static<typeof TronSignTx>;
export const TronSignTx = Type.Object(
    {
        address_n: Type.Array(Type.Number()),
        ref_block_bytes: Type.String(),
        ref_block_hash: Type.String(),
        expiration: Type.Number(),
        data: Type.Optional(Type.String()),
        timestamp: Type.Number(),
        fee_limit: Type.Optional(Type.Number()),
    },
    { $id: 'TronSignTx' },
);

export type TronTransferContract = Static<typeof TronTransferContract>;
export const TronTransferContract = Type.Object(
    {
        owner_address: Type.String(),
        to_address: Type.String(),
        amount: Type.Uint(),
    },
    { $id: 'TronTransferContract' },
);

export type TronTriggerSmartContract = Static<typeof TronTriggerSmartContract>;
export const TronTriggerSmartContract = Type.Object(
    {
        owner_address: Type.String(),
        contract_address: Type.String(),
        data: Type.String(),
    },
    { $id: 'TronTriggerSmartContract' },
);

export type TronUnfreezeBalanceV2Contract = Static<typeof TronUnfreezeBalanceV2Contract>;
export const TronUnfreezeBalanceV2Contract = Type.Object(
    {
        owner_address: Type.String(),
        balance: Type.Number(),
        resource: Type.Optional(EnumTronResourceCode),
    },
    { $id: 'TronUnfreezeBalanceV2Contract' },
);

export type TronVote = Static<typeof TronVote>;
export const TronVote = Type.Object(
    {
        address: Type.String(),
        count: Type.Number(),
    },
    { $id: 'TronVote' },
);

export type TronVoteWitnessContract = Static<typeof TronVoteWitnessContract>;
export const TronVoteWitnessContract = Type.Object(
    {
        owner_address: Type.String(),
        votes: Type.Array(TronVote),
    },
    { $id: 'TronVoteWitnessContract' },
);

export type TronWithdrawUnfreeze = Static<typeof TronWithdrawUnfreeze>;
export const TronWithdrawUnfreeze = Type.Object(
    {
        owner_address: Type.String(),
    },
    { $id: 'TronWithdrawUnfreeze' },
);
