// @generated by @trezor/protobuf/protoc-gen-plugin 1.0.0
// source: messages-common.proto
// DO NOT EDIT
import { type Static, Type } from '@trezor/schema-utils';

export enum Enum_ButtonRequestType {
    ButtonRequest_Other = 1,
    ButtonRequest_FeeOverThreshold = 2,
    ButtonRequest_ConfirmOutput = 3,
    ButtonRequest_ResetDevice = 4,
    ButtonRequest_ConfirmWord = 5,
    ButtonRequest_WipeDevice = 6,
    ButtonRequest_ProtectCall = 7,
    ButtonRequest_SignTx = 8,
    ButtonRequest_FirmwareCheck = 9,
    ButtonRequest_Address = 10,
    ButtonRequest_PublicKey = 11,
    ButtonRequest_MnemonicWordCount = 12,
    ButtonRequest_MnemonicInput = 13,
    _Deprecated_ButtonRequest_PassphraseType = 14,
    ButtonRequest_UnknownDerivationPath = 15,
    ButtonRequest_RecoveryHomepage = 16,
    ButtonRequest_Success = 17,
    ButtonRequest_Warning = 18,
    ButtonRequest_PassphraseEntry = 19,
    ButtonRequest_PinEntry = 20,
}

export type EnumEnum_ButtonRequestType = Static<typeof EnumEnum_ButtonRequestType>;
export const EnumEnum_ButtonRequestType = Type.Enum(Enum_ButtonRequestType);

export type ButtonRequestType = Static<typeof ButtonRequestType>;
export const ButtonRequestType = Type.KeyOfEnum(Enum_ButtonRequestType, {
    $id: 'ButtonRequestType',
});

export enum Enum_FailureType {
    Failure_UnexpectedMessage = 1,
    Failure_ButtonExpected = 2,
    Failure_DataError = 3,
    Failure_ActionCancelled = 4,
    Failure_PinExpected = 5,
    Failure_PinCancelled = 6,
    Failure_PinInvalid = 7,
    Failure_InvalidSignature = 8,
    Failure_ProcessError = 9,
    Failure_NotEnoughFunds = 10,
    Failure_NotInitialized = 11,
    Failure_PinMismatch = 12,
    Failure_WipeCodeMismatch = 13,
    Failure_InvalidSession = 14,
    Failure_Busy = 15,
    Failure_ThpUnallocatedSession = 16,
    Failure_InvalidProtocol = 17,
    Failure_InProgress = 19,
    Failure_FirmwareError = 99,
}

export type EnumEnum_FailureType = Static<typeof EnumEnum_FailureType>;
export const EnumEnum_FailureType = Type.Enum(Enum_FailureType);

export type FailureType = Static<typeof FailureType>;
export const FailureType = Type.KeyOfEnum(Enum_FailureType, { $id: 'FailureType' });

export enum Enum_PinMatrixRequestType {
    PinMatrixRequestType_Current = 1,
    PinMatrixRequestType_NewFirst = 2,
    PinMatrixRequestType_NewSecond = 3,
    PinMatrixRequestType_WipeCodeFirst = 4,
    PinMatrixRequestType_WipeCodeSecond = 5,
}

export type EnumEnum_PinMatrixRequestType = Static<typeof EnumEnum_PinMatrixRequestType>;
export const EnumEnum_PinMatrixRequestType = Type.Enum(Enum_PinMatrixRequestType);

export type PinMatrixRequestType = Static<typeof PinMatrixRequestType>;
export const PinMatrixRequestType = Type.KeyOfEnum(Enum_PinMatrixRequestType, {
    $id: 'PinMatrixRequestType',
});

export type ButtonAck = Static<typeof ButtonAck>;
export const ButtonAck = Type.Object({}, { $id: 'ButtonAck' });

export type ButtonRequest = Static<typeof ButtonRequest>;
export const ButtonRequest = Type.Object(
    {
        code: Type.Optional(ButtonRequestType),
        pages: Type.Optional(Type.Number()),
        name: Type.Optional(Type.String()),
    },
    { $id: 'ButtonRequest' },
);

export type CoinPurchaseMemo = Static<typeof CoinPurchaseMemo>;
export const CoinPurchaseMemo = Type.Object(
    {
        coin_type: Type.Number(),
        amount: Type.String(),
        address: Type.String(),
        address_n: Type.Array(Type.Number()),
        mac: Type.String(),
    },
    { $id: 'CoinPurchaseMemo' },
);

export type Deprecated_PassphraseStateAck = Static<typeof Deprecated_PassphraseStateAck>;
export const Deprecated_PassphraseStateAck = Type.Object(
    {},
    { $id: 'Deprecated_PassphraseStateAck' },
);

export type Deprecated_PassphraseStateRequest = Static<typeof Deprecated_PassphraseStateRequest>;
export const Deprecated_PassphraseStateRequest = Type.Object(
    {
        state: Type.Optional(Type.String()),
    },
    { $id: 'Deprecated_PassphraseStateRequest' },
);

export type Failure = Static<typeof Failure>;
export const Failure = Type.Object(
    {
        code: Type.Optional(FailureType),
        message: Type.Optional(Type.String()),
    },
    { $id: 'Failure' },
);

export type HDNodeType = Static<typeof HDNodeType>;
export const HDNodeType = Type.Object(
    {
        depth: Type.Number(),
        fingerprint: Type.Number(),
        child_num: Type.Number(),
        chain_code: Type.String(),
        private_key: Type.Optional(Type.String()),
        public_key: Type.String(),
    },
    { $id: 'HDNodeType' },
);

export type PassphraseAck = Static<typeof PassphraseAck>;
export const PassphraseAck = Type.Object(
    {
        passphrase: Type.Optional(Type.String()),
        _state: Type.Optional(Type.String()),
        on_device: Type.Optional(Type.Boolean()),
    },
    { $id: 'PassphraseAck' },
);

export type PassphraseRequest = Static<typeof PassphraseRequest>;
export const PassphraseRequest = Type.Object(
    {
        _on_device: Type.Optional(Type.Boolean()),
    },
    { $id: 'PassphraseRequest' },
);

export type TextMemo = Static<typeof TextMemo>;
export const TextMemo = Type.Object(
    {
        text: Type.String(),
    },
    { $id: 'TextMemo' },
);

export type RefundMemo = Static<typeof RefundMemo>;
export const RefundMemo = Type.Object(
    {
        address: Type.String(),
        address_n: Type.Array(Type.Number()),
        mac: Type.String(),
    },
    { $id: 'RefundMemo' },
);

export type TextDetailsMemo = Static<typeof TextDetailsMemo>;
export const TextDetailsMemo = Type.Object(
    {
        title: Type.String(),
        text: Type.String(),
    },
    { $id: 'TextDetailsMemo' },
);

export type PaymentRequestMemo = Static<typeof PaymentRequestMemo>;
export const PaymentRequestMemo = Type.Object(
    {
        text_memo: Type.Optional(TextMemo),
        refund_memo: Type.Optional(RefundMemo),
        coin_purchase_memo: Type.Optional(CoinPurchaseMemo),
        text_details_memo: Type.Optional(TextDetailsMemo),
    },
    { $id: 'PaymentRequestMemo' },
);

export type PaymentRequest = Static<typeof PaymentRequest>;
export const PaymentRequest = Type.Object(
    {
        nonce: Type.Optional(Type.String()),
        recipient_name: Type.String(),
        memos: Type.Optional(Type.Array(PaymentRequestMemo)),
        amount: Type.Optional(Type.String()),
        signature: Type.String(),
    },
    { $id: 'PaymentRequest' },
);

export type PinMatrixAck = Static<typeof PinMatrixAck>;
export const PinMatrixAck = Type.Object(
    {
        pin: Type.String(),
    },
    { $id: 'PinMatrixAck' },
);

export type PinMatrixRequest = Static<typeof PinMatrixRequest>;
export const PinMatrixRequest = Type.Object(
    {
        type: Type.Optional(PinMatrixRequestType),
    },
    { $id: 'PinMatrixRequest' },
);

export type Success = Static<typeof Success>;
export const Success = Type.Object(
    {
        message: Type.String(),
    },
    { $id: 'Success' },
);
