// @generated by @trezor/protobuf/protoc-get-plugin v1 with parameter "target=dts"
// @generated from file messages.proto (package hw.trezor.messages, syntax proto2)

import type { DescFile } from '@bufbuild/protobuf';

export declare const file_messages: DescFile;
