// @generated by @trezor/protobuf/protoc-gen-plugin 1.0.0
// source: messages-ward-connect.proto
// DO NOT EDIT
import type { DescFile } from '@bufbuild/protobuf';

export declare const file_messages_ward_connect: DescFile;
