// @generated by @trezor/protobuf/protoc-get-plugin v1 with parameter "target=dts"
// @generated from file messages-ethereum.proto (package hw.trezor.messages.ethereum, syntax proto2)

import type { DescFile } from '@bufbuild/protobuf';

export declare const file_messages_ethereum: DescFile;
