// @generated by @trezor/protobuf/protoc-get-plugin v1 with parameter "target=dts"
// @generated from file messages-tezos.proto (package hw.trezor.messages.tezos, syntax proto2)

import type { DescFile } from '@bufbuild/protobuf';

export declare const file_messages_tezos: DescFile;
