// @generated by @trezor/protobuf/protoc-get-plugin v1 with parameter "target=dts"
// @generated from file messages-ethereum-eip712.proto (package hw.trezor.messages.ethereum_eip712, syntax proto2)

import type { DescFile } from '@bufbuild/protobuf';

export declare const file_messages_ethereum_eip712: DescFile;
