/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * Yield.xyz API
 * API Documentation
 * OpenAPI spec version: 1.0
 */
import type {
    ActionDto,
    ActionsControllerEnterYield400,
    ActionsControllerEnterYield401,
    ActionsControllerEnterYield403,
    ActionsControllerEnterYield429,
    ActionsControllerEnterYield500,
    ActionsControllerExitYield400,
    ActionsControllerExitYield401,
    ActionsControllerExitYield403,
    ActionsControllerExitYield429,
    ActionsControllerExitYield500,
    ActionsControllerGetAction400,
    ActionsControllerGetAction401,
    ActionsControllerGetAction429,
    ActionsControllerGetAction500,
    ActionsControllerGetActionPathParameters,
    ActionsControllerGetActions200,
    ActionsControllerGetActions400,
    ActionsControllerGetActions401,
    ActionsControllerGetActions429,
    ActionsControllerGetActions500,
    ActionsControllerGetActionsParams,
    ActionsControllerManageYield400,
    ActionsControllerManageYield401,
    ActionsControllerManageYield403,
    ActionsControllerManageYield429,
    ActionsControllerManageYield500,
    CreateActionDto,
    CreateManageActionDto,
    SubmitHashDto,
    SubmitTransactionDto,
    TransactionDto,
    TransactionsControllerGetTransaction400,
    TransactionsControllerGetTransaction401,
    TransactionsControllerGetTransaction429,
    TransactionsControllerGetTransaction500,
    TransactionsControllerGetTransactionPathParameters,
    TransactionsControllerSubmitTransaction401,
    TransactionsControllerSubmitTransaction429,
    TransactionsControllerSubmitTransaction500,
    TransactionsControllerSubmitTransactionHash401,
    TransactionsControllerSubmitTransactionHash429,
    TransactionsControllerSubmitTransactionHash500,
    TransactionsControllerSubmitTransactionHashPathParameters,
    TransactionsControllerSubmitTransactionPathParameters,
} from './index.schemas';
import { httpClient } from '../httpClient';

/**
 * Retrieve all actions performed by a user, with optional filtering by yield, status, category, etc. In the future, this may include personalized action recommendations.
 * @summary Get user actions
 */
export type GetActionsResponse200 = {
    data: ActionsControllerGetActions200;
    status: 200;
};

export type GetActionsResponse400 = {
    data: ActionsControllerGetActions400;
    status: 400;
};

export type GetActionsResponse401 = {
    data: ActionsControllerGetActions401;
    status: 401;
};

export type GetActionsResponse429 = {
    data: ActionsControllerGetActions429;
    status: 429;
};

export type GetActionsResponse500 = {
    data: ActionsControllerGetActions500;
    status: 500;
};

export type GetActionsResponseSuccess = GetActionsResponse200 & {
    headers: Headers;
};
export type GetActionsResponseError = (
    | GetActionsResponse400
    | GetActionsResponse401
    | GetActionsResponse429
    | GetActionsResponse500
) & {
    headers: Headers;
};

export const getGetActionsUrl = (params: ActionsControllerGetActionsParams) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? 'null' : value.toString());
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0 ? `/v1/actions?${stringifiedParams}` : `/v1/actions`;
};

export const getActions = (
    params: ActionsControllerGetActionsParams,
    options?: RequestInit,
): Promise<GetActionsResponseSuccess> =>
    httpClient<GetActionsResponseSuccess>(getGetActionsUrl(params), {
        ...options,
        method: 'GET',
    });

/**
 * Retrieve detailed information about a specific action including current status, transactions, and execution details.
 * @summary Get action details
 */
export type GetActionResponse200 = {
    data: ActionDto;
    status: 200;
};

export type GetActionResponse400 = {
    data: ActionsControllerGetAction400;
    status: 400;
};

export type GetActionResponse401 = {
    data: ActionsControllerGetAction401;
    status: 401;
};

export type GetActionResponse404 = {
    data: void;
    status: 404;
};

export type GetActionResponse429 = {
    data: ActionsControllerGetAction429;
    status: 429;
};

export type GetActionResponse500 = {
    data: ActionsControllerGetAction500;
    status: 500;
};

export type GetActionResponseSuccess = GetActionResponse200 & {
    headers: Headers;
};
export type GetActionResponseError = (
    | GetActionResponse400
    | GetActionResponse401
    | GetActionResponse404
    | GetActionResponse429
    | GetActionResponse500
) & {
    headers: Headers;
};

export const getGetActionUrl = ({ actionId }: ActionsControllerGetActionPathParameters) =>
    `/v1/actions/${actionId}`;

export const getAction = (
    { actionId }: ActionsControllerGetActionPathParameters,
    options?: RequestInit,
): Promise<GetActionResponseSuccess> =>
    httpClient<GetActionResponseSuccess>(getGetActionUrl({ actionId }), {
        ...options,
        method: 'GET',
    });

/**
 * Generate the transactions needed to enter a yield position with the provided parameters.
 * @summary Enter a yield
 */
export type EnterYieldResponse201 = {
    data: ActionDto;
    status: 201;
};

export type EnterYieldResponse400 = {
    data: ActionsControllerEnterYield400;
    status: 400;
};

export type EnterYieldResponse401 = {
    data: ActionsControllerEnterYield401;
    status: 401;
};

export type EnterYieldResponse403 = {
    data: ActionsControllerEnterYield403;
    status: 403;
};

export type EnterYieldResponse404 = {
    data: void;
    status: 404;
};

export type EnterYieldResponse429 = {
    data: ActionsControllerEnterYield429;
    status: 429;
};

export type EnterYieldResponse500 = {
    data: ActionsControllerEnterYield500;
    status: 500;
};

export type EnterYieldResponseSuccess = EnterYieldResponse201 & {
    headers: Headers;
};
export type EnterYieldResponseError = (
    | EnterYieldResponse400
    | EnterYieldResponse401
    | EnterYieldResponse403
    | EnterYieldResponse404
    | EnterYieldResponse429
    | EnterYieldResponse500
) & {
    headers: Headers;
};

export const getEnterYieldUrl = () => `/v1/actions/enter`;

export const enterYield = (
    createActionDto: CreateActionDto,
    options?: RequestInit,
): Promise<EnterYieldResponseSuccess> =>
    httpClient<EnterYieldResponseSuccess>(getEnterYieldUrl(), {
        ...options,
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...options?.headers },
        body: JSON.stringify(createActionDto),
    });

/**
 * Generate the transactions needed to exit a yield position with the provided parameters.
 * @summary Exit a yield
 */
export type ExitYieldResponse201 = {
    data: ActionDto;
    status: 201;
};

export type ExitYieldResponse400 = {
    data: ActionsControllerExitYield400;
    status: 400;
};

export type ExitYieldResponse401 = {
    data: ActionsControllerExitYield401;
    status: 401;
};

export type ExitYieldResponse403 = {
    data: ActionsControllerExitYield403;
    status: 403;
};

export type ExitYieldResponse404 = {
    data: void;
    status: 404;
};

export type ExitYieldResponse429 = {
    data: ActionsControllerExitYield429;
    status: 429;
};

export type ExitYieldResponse500 = {
    data: ActionsControllerExitYield500;
    status: 500;
};

export type ExitYieldResponseSuccess = ExitYieldResponse201 & {
    headers: Headers;
};
export type ExitYieldResponseError = (
    | ExitYieldResponse400
    | ExitYieldResponse401
    | ExitYieldResponse403
    | ExitYieldResponse404
    | ExitYieldResponse429
    | ExitYieldResponse500
) & {
    headers: Headers;
};

export const getExitYieldUrl = () => `/v1/actions/exit`;

export const exitYield = (
    createActionDto: CreateActionDto,
    options?: RequestInit,
): Promise<ExitYieldResponseSuccess> =>
    httpClient<ExitYieldResponseSuccess>(getExitYieldUrl(), {
        ...options,
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...options?.headers },
        body: JSON.stringify(createActionDto),
    });

/**
 * Generate the transactions needed to perform management actions on a yield position.
 * @summary Manage a yield
 */
export type ManageYieldResponse201 = {
    data: ActionDto;
    status: 201;
};

export type ManageYieldResponse400 = {
    data: ActionsControllerManageYield400;
    status: 400;
};

export type ManageYieldResponse401 = {
    data: ActionsControllerManageYield401;
    status: 401;
};

export type ManageYieldResponse403 = {
    data: ActionsControllerManageYield403;
    status: 403;
};

export type ManageYieldResponse404 = {
    data: void;
    status: 404;
};

export type ManageYieldResponse429 = {
    data: ActionsControllerManageYield429;
    status: 429;
};

export type ManageYieldResponse500 = {
    data: ActionsControllerManageYield500;
    status: 500;
};

export type ManageYieldResponseSuccess = ManageYieldResponse201 & {
    headers: Headers;
};
export type ManageYieldResponseError = (
    | ManageYieldResponse400
    | ManageYieldResponse401
    | ManageYieldResponse403
    | ManageYieldResponse404
    | ManageYieldResponse429
    | ManageYieldResponse500
) & {
    headers: Headers;
};

export const getManageYieldUrl = () => `/v1/actions/manage`;

export const manageYield = (
    createManageActionDto: CreateManageActionDto,
    options?: RequestInit,
): Promise<ManageYieldResponseSuccess> =>
    httpClient<ManageYieldResponseSuccess>(getManageYieldUrl(), {
        ...options,
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...options?.headers },
        body: JSON.stringify(createManageActionDto),
    });

/**
 * Submit the transaction hash after broadcasting a transaction to the blockchain. This updates the transaction status and enables tracking.
 * @summary Submit transaction hash
 */
export type SubmitTransactionHashResponse200 = {
    data: TransactionDto;
    status: 200;
};

export type SubmitTransactionHashResponse400 = {
    data: void;
    status: 400;
};

export type SubmitTransactionHashResponse401 = {
    data: TransactionsControllerSubmitTransactionHash401;
    status: 401;
};

export type SubmitTransactionHashResponse404 = {
    data: void;
    status: 404;
};

export type SubmitTransactionHashResponse429 = {
    data: TransactionsControllerSubmitTransactionHash429;
    status: 429;
};

export type SubmitTransactionHashResponse500 = {
    data: TransactionsControllerSubmitTransactionHash500;
    status: 500;
};

export type SubmitTransactionHashResponseSuccess = SubmitTransactionHashResponse200 & {
    headers: Headers;
};
export type SubmitTransactionHashResponseError = (
    | SubmitTransactionHashResponse400
    | SubmitTransactionHashResponse401
    | SubmitTransactionHashResponse404
    | SubmitTransactionHashResponse429
    | SubmitTransactionHashResponse500
) & {
    headers: Headers;
};

export const getSubmitTransactionHashUrl = ({
    transactionId,
}: TransactionsControllerSubmitTransactionHashPathParameters) =>
    `/v1/transactions/${transactionId}/submit-hash`;

export const submitTransactionHash = (
    { transactionId }: TransactionsControllerSubmitTransactionHashPathParameters,
    submitHashDto: SubmitHashDto,
    options?: RequestInit,
): Promise<SubmitTransactionHashResponseSuccess> =>
    httpClient<SubmitTransactionHashResponseSuccess>(
        getSubmitTransactionHashUrl({ transactionId }),
        {
            ...options,
            method: 'PUT',
            headers: { 'Content-Type': 'application/json', ...options?.headers },
            body: JSON.stringify(submitHashDto),
        },
    );

/**
 * Submit the transaction to the blockchain.
 * @summary Submit transaction
 */
export type SubmitTransactionResponse200 = {
    data: TransactionDto;
    status: 200;
};

export type SubmitTransactionResponse400 = {
    data: void;
    status: 400;
};

export type SubmitTransactionResponse401 = {
    data: TransactionsControllerSubmitTransaction401;
    status: 401;
};

export type SubmitTransactionResponse404 = {
    data: void;
    status: 404;
};

export type SubmitTransactionResponse429 = {
    data: TransactionsControllerSubmitTransaction429;
    status: 429;
};

export type SubmitTransactionResponse500 = {
    data: TransactionsControllerSubmitTransaction500;
    status: 500;
};

export type SubmitTransactionResponseSuccess = SubmitTransactionResponse200 & {
    headers: Headers;
};
export type SubmitTransactionResponseError = (
    | SubmitTransactionResponse400
    | SubmitTransactionResponse401
    | SubmitTransactionResponse404
    | SubmitTransactionResponse429
    | SubmitTransactionResponse500
) & {
    headers: Headers;
};

export const getSubmitTransactionUrl = ({
    transactionId,
}: TransactionsControllerSubmitTransactionPathParameters) =>
    `/v1/transactions/${transactionId}/submit`;

export const submitTransaction = (
    { transactionId }: TransactionsControllerSubmitTransactionPathParameters,
    submitTransactionDto: SubmitTransactionDto,
    options?: RequestInit,
): Promise<SubmitTransactionResponseSuccess> =>
    httpClient<SubmitTransactionResponseSuccess>(getSubmitTransactionUrl({ transactionId }), {
        ...options,
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...options?.headers },
        body: JSON.stringify(submitTransactionDto),
    });

/**
 * Retrieve detailed information about a specific transaction including current status, hash, and execution details.
 * @summary Get transaction details
 */
export type GetTransactionResponse200 = {
    data: TransactionDto;
    status: 200;
};

export type GetTransactionResponse400 = {
    data: TransactionsControllerGetTransaction400;
    status: 400;
};

export type GetTransactionResponse401 = {
    data: TransactionsControllerGetTransaction401;
    status: 401;
};

export type GetTransactionResponse404 = {
    data: void;
    status: 404;
};

export type GetTransactionResponse429 = {
    data: TransactionsControllerGetTransaction429;
    status: 429;
};

export type GetTransactionResponse500 = {
    data: TransactionsControllerGetTransaction500;
    status: 500;
};

export type GetTransactionResponseSuccess = GetTransactionResponse200 & {
    headers: Headers;
};
export type GetTransactionResponseError = (
    | GetTransactionResponse400
    | GetTransactionResponse401
    | GetTransactionResponse404
    | GetTransactionResponse429
    | GetTransactionResponse500
) & {
    headers: Headers;
};

export const getGetTransactionUrl = ({
    transactionId,
}: TransactionsControllerGetTransactionPathParameters) => `/v1/transactions/${transactionId}`;

export const getTransaction = (
    { transactionId }: TransactionsControllerGetTransactionPathParameters,
    options?: RequestInit,
): Promise<GetTransactionResponseSuccess> =>
    httpClient<GetTransactionResponseSuccess>(getGetTransactionUrl({ transactionId }), {
        ...options,
        method: 'GET',
    });
