/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * Yield.xyz API
 * API Documentation
 * OpenAPI spec version: 1.0
 */
import type {
    NetworkDto,
    NetworksControllerGetNetworks400,
    NetworksControllerGetNetworks401,
    NetworksControllerGetNetworks429,
    NetworksControllerGetNetworks500,
    ProviderDto,
    ProvidersControllerGetProvider400,
    ProvidersControllerGetProvider401,
    ProvidersControllerGetProvider429,
    ProvidersControllerGetProvider500,
    ProvidersControllerGetProviderPathParameters,
    ProvidersControllerGetProviders200,
    ProvidersControllerGetProviders400,
    ProvidersControllerGetProviders401,
    ProvidersControllerGetProviders429,
    ProvidersControllerGetProviders500,
    ProvidersControllerGetProvidersParams,
    YieldDto,
    YieldsControllerGetYield400,
    YieldsControllerGetYield401,
    YieldsControllerGetYield429,
    YieldsControllerGetYield500,
    YieldsControllerGetYieldPathParameters,
    YieldsControllerGetYieldValidators200,
    YieldsControllerGetYieldValidators400,
    YieldsControllerGetYieldValidators401,
    YieldsControllerGetYieldValidators429,
    YieldsControllerGetYieldValidators500,
    YieldsControllerGetYieldValidatorsParams,
    YieldsControllerGetYieldValidatorsPathParameters,
    YieldsControllerGetYields200,
    YieldsControllerGetYields400,
    YieldsControllerGetYields401,
    YieldsControllerGetYields429,
    YieldsControllerGetYields500,
    YieldsControllerGetYieldsParams,
} from './index.schemas';
import { httpClient } from '../httpClient';

/**
 * Retrieve a paginated list of available yield opportunities across all supported networks and protocols.
 * @summary List all yield opportunities
 */
export type GetYieldsResponse200 = {
    data: YieldsControllerGetYields200;
    status: 200;
};

export type GetYieldsResponse400 = {
    data: YieldsControllerGetYields400;
    status: 400;
};

export type GetYieldsResponse401 = {
    data: YieldsControllerGetYields401;
    status: 401;
};

export type GetYieldsResponse429 = {
    data: YieldsControllerGetYields429;
    status: 429;
};

export type GetYieldsResponse500 = {
    data: YieldsControllerGetYields500;
    status: 500;
};

export type GetYieldsResponseSuccess = GetYieldsResponse200 & {
    headers: Headers;
};
export type GetYieldsResponseError = (
    | GetYieldsResponse400
    | GetYieldsResponse401
    | GetYieldsResponse429
    | GetYieldsResponse500
) & {
    headers: Headers;
};

export const getGetYieldsUrl = (params?: YieldsControllerGetYieldsParams) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? 'null' : value.toString());
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0 ? `/v1/yields?${stringifiedParams}` : `/v1/yields`;
};

export const getYields = (
    params?: YieldsControllerGetYieldsParams,
    options?: RequestInit,
): Promise<GetYieldsResponseSuccess> =>
    httpClient<GetYieldsResponseSuccess>(getGetYieldsUrl(params), {
        ...options,
        method: 'GET',
    });

/**
 * Retrieve detailed information about a specific yield opportunity including APY, tokens, protocol details, and more.
 * @summary Get yield metadata
 */
export type GetYieldResponse200 = {
    data: YieldDto;
    status: 200;
};

export type GetYieldResponse400 = {
    data: YieldsControllerGetYield400;
    status: 400;
};

export type GetYieldResponse401 = {
    data: YieldsControllerGetYield401;
    status: 401;
};

export type GetYieldResponse404 = {
    data: void;
    status: 404;
};

export type GetYieldResponse429 = {
    data: YieldsControllerGetYield429;
    status: 429;
};

export type GetYieldResponse500 = {
    data: YieldsControllerGetYield500;
    status: 500;
};

export type GetYieldResponseSuccess = GetYieldResponse200 & {
    headers: Headers;
};
export type GetYieldResponseError = (
    | GetYieldResponse400
    | GetYieldResponse401
    | GetYieldResponse404
    | GetYieldResponse429
    | GetYieldResponse500
) & {
    headers: Headers;
};

export const getGetYieldUrl = ({ yieldId }: YieldsControllerGetYieldPathParameters) =>
    `/v1/yields/${yieldId}`;

export const getYield = (
    { yieldId }: YieldsControllerGetYieldPathParameters,
    options?: RequestInit,
): Promise<GetYieldResponseSuccess> =>
    httpClient<GetYieldResponseSuccess>(getGetYieldUrl({ yieldId }), {
        ...options,
        method: 'GET',
    });

/**
 * Retrieve a paginated list of validators available for staking or delegation for this yield opportunity.
 * @summary Get yield validators
 */
export type GetYieldValidatorsResponse200 = {
    data: YieldsControllerGetYieldValidators200;
    status: 200;
};

export type GetYieldValidatorsResponse400 = {
    data: YieldsControllerGetYieldValidators400;
    status: 400;
};

export type GetYieldValidatorsResponse401 = {
    data: YieldsControllerGetYieldValidators401;
    status: 401;
};

export type GetYieldValidatorsResponse404 = {
    data: void;
    status: 404;
};

export type GetYieldValidatorsResponse429 = {
    data: YieldsControllerGetYieldValidators429;
    status: 429;
};

export type GetYieldValidatorsResponse500 = {
    data: YieldsControllerGetYieldValidators500;
    status: 500;
};

export type GetYieldValidatorsResponseSuccess = GetYieldValidatorsResponse200 & {
    headers: Headers;
};
export type GetYieldValidatorsResponseError = (
    | GetYieldValidatorsResponse400
    | GetYieldValidatorsResponse401
    | GetYieldValidatorsResponse404
    | GetYieldValidatorsResponse429
    | GetYieldValidatorsResponse500
) & {
    headers: Headers;
};

export const getGetYieldValidatorsUrl = (
    { yieldId }: YieldsControllerGetYieldValidatorsPathParameters,
    params?: YieldsControllerGetYieldValidatorsParams,
) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? 'null' : value.toString());
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `/v1/yields/${yieldId}/validators?${stringifiedParams}`
        : `/v1/yields/${yieldId}/validators`;
};

export const getYieldValidators = (
    { yieldId }: YieldsControllerGetYieldValidatorsPathParameters,
    params?: YieldsControllerGetYieldValidatorsParams,
    options?: RequestInit,
): Promise<GetYieldValidatorsResponseSuccess> =>
    httpClient<GetYieldValidatorsResponseSuccess>(getGetYieldValidatorsUrl({ yieldId }, params), {
        ...options,
        method: 'GET',
    });

/**
 * Retrieve a list of all supported networks that can be used for filtering yields and other operations.
 * @summary List all available networks
 */
export type GetNetworksResponse200 = {
    data: NetworkDto[];
    status: 200;
};

export type GetNetworksResponse400 = {
    data: NetworksControllerGetNetworks400;
    status: 400;
};

export type GetNetworksResponse401 = {
    data: NetworksControllerGetNetworks401;
    status: 401;
};

export type GetNetworksResponse429 = {
    data: NetworksControllerGetNetworks429;
    status: 429;
};

export type GetNetworksResponse500 = {
    data: NetworksControllerGetNetworks500;
    status: 500;
};

export type GetNetworksResponseSuccess = GetNetworksResponse200 & {
    headers: Headers;
};
export type GetNetworksResponseError = (
    | GetNetworksResponse400
    | GetNetworksResponse401
    | GetNetworksResponse429
    | GetNetworksResponse500
) & {
    headers: Headers;
};

export const getGetNetworksUrl = () => `/v1/networks`;

export const getNetworks = (options?: RequestInit): Promise<GetNetworksResponseSuccess> =>
    httpClient<GetNetworksResponseSuccess>(getGetNetworksUrl(), {
        ...options,
        method: 'GET',
    });

/**
 * Returns a paginated list of all providers, including both protocol and validator providers.
 * @summary Get all providers
 */
export type GetProvidersResponse200 = {
    data: ProvidersControllerGetProviders200;
    status: 200;
};

export type GetProvidersResponse400 = {
    data: ProvidersControllerGetProviders400;
    status: 400;
};

export type GetProvidersResponse401 = {
    data: ProvidersControllerGetProviders401;
    status: 401;
};

export type GetProvidersResponse429 = {
    data: ProvidersControllerGetProviders429;
    status: 429;
};

export type GetProvidersResponse500 = {
    data: ProvidersControllerGetProviders500;
    status: 500;
};

export type GetProvidersResponseSuccess = GetProvidersResponse200 & {
    headers: Headers;
};
export type GetProvidersResponseError = (
    | GetProvidersResponse400
    | GetProvidersResponse401
    | GetProvidersResponse429
    | GetProvidersResponse500
) & {
    headers: Headers;
};

export const getGetProvidersUrl = (params?: ProvidersControllerGetProvidersParams) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? 'null' : value.toString());
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0 ? `/v1/providers?${stringifiedParams}` : `/v1/providers`;
};

export const getProviders = (
    params?: ProvidersControllerGetProvidersParams,
    options?: RequestInit,
): Promise<GetProvidersResponseSuccess> =>
    httpClient<GetProvidersResponseSuccess>(getGetProvidersUrl(params), {
        ...options,
        method: 'GET',
    });

/**
 * Returns detailed information about a specific provider.
 * @summary Get provider by ID
 */
export type GetProviderResponse200 = {
    data: ProviderDto;
    status: 200;
};

export type GetProviderResponse400 = {
    data: ProvidersControllerGetProvider400;
    status: 400;
};

export type GetProviderResponse401 = {
    data: ProvidersControllerGetProvider401;
    status: 401;
};

export type GetProviderResponse429 = {
    data: ProvidersControllerGetProvider429;
    status: 429;
};

export type GetProviderResponse500 = {
    data: ProvidersControllerGetProvider500;
    status: 500;
};

export type GetProviderResponseSuccess = GetProviderResponse200 & {
    headers: Headers;
};
export type GetProviderResponseError = (
    | GetProviderResponse400
    | GetProviderResponse401
    | GetProviderResponse429
    | GetProviderResponse500
) & {
    headers: Headers;
};

export const getGetProviderUrl = ({ providerId }: ProvidersControllerGetProviderPathParameters) =>
    `/v1/providers/${providerId}`;

export const getProvider = (
    { providerId }: ProvidersControllerGetProviderPathParameters,
    options?: RequestInit,
): Promise<GetProviderResponseSuccess> =>
    httpClient<GetProviderResponseSuccess>(getGetProviderUrl({ providerId }), {
        ...options,
        method: 'GET',
    });
