/* eslint-disable import/no-extraneous-dependencies */

import chalk from 'chalk';
import fs from 'fs';
import path from 'path';
import prettier from 'prettier';
import { optimize } from 'svgo';

const iconsFilePath = './src/icons.ts';
const cryptoIconsPath = './src/cryptoIcons.ts';
const networkIconsPath = './src/networkIcons.ts';

const assetTypesConfig = [
    {
        name: 'icons',
        dirname: 'assets',
        typeName: 'IconName',
    },
];

const cryptoAssetsTypesConfig = [
    {
        name: 'cryptoIcons',
        dirname: 'cryptoAssets/cryptoIcons',
        typeName: 'CryptoIconName',
    },
];

const networkAssetsTypesConfig = [
    { name: 'networkIcons', dirname: 'cryptoAssets/networkIcons', typeName: 'NetworkIconName' },
];

// https://github.com/svg/svgo#built-in-plugins
const svgoConfig = {
    multipass: true,
    js2svg: {
        indent: 2,
        pretty: true,
    },
    plugins: [
        { name: 'preset-default' },
        { name: 'removeViewBox', active: false },
        'prefixIds',
        'removeDimensions',
        'removeRasterImages',
        'removeScripts',
    ],
};

// JS reserved words + strict-mode reserved words
const RESERVED_WORDS = new Set([
    'break',
    'case',
    'catch',
    'class',
    'const',
    'continue',
    'debugger',
    'default',
    'delete',
    'do',
    'else',
    'export',
    'extends',
    'finally',
    'for',
    'function',
    'if',
    'import',
    'in',
    'instanceof',
    'new',
    'return',
    'super',
    'switch',
    'this',
    'throw',
    'try',
    'typeof',
    'var',
    'void',
    'while',
    'with',
    'yield',
    'enum',
    'implements',
    'interface',
    'let',
    'package',
    'private',
    'protected',
    'public',
    'static',
    'null',
    'true',
    'false',
]);

const optimizeSvgAssets = assetsDirname => {
    const assetsDir = path.join(import.meta.dirname, assetsDirname);
    const assetFileNames = fs.readdirSync(assetsDir);

    return assetFileNames
        .filter(fileName => fileName.endsWith('.svg'))
        .map(fileName => ({
            fileName,
            content: fs.readFileSync(path.resolve(assetsDir, fileName)).toString(),
        }))
        .map(({ fileName, content }) => ({
            fileName,
            content: optimize(content, svgoConfig).data,
        }));
};

const getOptimizedAssetTypes = assetTypesArray =>
    assetTypesArray.map(config => ({
        ...config,
        assets: optimizeSvgAssets(config.dirname),
    }));

/**
 * Convert file base names to safe TS/JS identifiers for ESM imports.
 * - converts kebab/snake/space to camelCase
 * - prefixes with "_" if starts with a digit
 * - removes invalid characters
 * - prefixes if it becomes a reserved word (e.g. "export" -> "iconExport")
 */
const toSafeIdentifier = input => {
    const trimmed = String(input ?? '').trim();
    const parts = trimmed.split(/[^a-zA-Z0-9]+/g).filter(Boolean);

    const camel =
        parts.length === 0
            ? 'icon'
            : parts
                  .map((p, i) => {
                      const lower = p.length ? p[0].toLowerCase() + p.slice(1) : p;
                      if (i === 0) return lower;
                      return lower.length ? lower[0].toUpperCase() + lower.slice(1) : lower;
                  })
                  .join('');

    const cleaned = camel.replace(/[^a-zA-Z0-9_$]/g, '');
    const digitSafe = /^[0-9]/.test(cleaned) ? `_${cleaned}` : cleaned;
    const nonEmpty = digitSafe || 'icon';

    if (RESERVED_WORDS.has(nonEmpty)) {
        return `icon${nonEmpty[0].toUpperCase()}${nonEmpty.slice(1)}`;
    }

    return nonEmpty;
};

const generateIconsFileContent = assetTypesArray => {
    const blocks = assetTypesArray.map(({ name, assets, dirname, typeName }) => {
        const used = new Map();

        const items = assets.map(({ fileName }) => {
            const key = fileName.replace('.svg', '');
            let ident = toSafeIdentifier(key);

            const count = used.get(ident) ?? 0;
            used.set(ident, count + 1);
            if (count > 0) ident = `${ident}_${count + 1}`;

            const importPath = `../${dirname}/${fileName}`;
            return { key, ident, importPath };
        });

        const importLines = items
            .map(i => `import ${i.ident} from ${JSON.stringify(i.importPath)};`)
            .join('\n');

        const objectLines = items.map(i => `${JSON.stringify(i.key)}: ${i.ident}`).join(',\n    ');

        return `
${importLines}

export const ${name} = {
    ${objectLines}
} as const;

export type ${typeName} = keyof typeof ${name};
`;
    });

    return `
// !!! IMPORTANT: This file is autogenerated !!!
// If you want to add of modify icons please read README.md to find out how to do it

${blocks.join('\n')}
`;
};

const writeOptimizedAssets = assetTypesArray => {
    assetTypesArray.forEach(({ assets, dirname }) => {
        assets.forEach(({ fileName, content }) => {
            const outPath = path.resolve(import.meta.dirname, dirname, fileName);
            fs.writeFileSync(outPath, content);
        });
    });
};

const generateFileForAssetTypes = async (assetTypesArray, outputFilePath) => {
    const assetTypes = getOptimizedAssetTypes(assetTypesArray);

    const iconsFileContent = generateIconsFileContent(assetTypes);

    const prettierConfigPath = await prettier.resolveConfigFile();
    const prettierConfig = {
        ...(await prettier.resolveConfig(prettierConfigPath)),
        parser: 'babel-ts',
    };

    const formatted = await prettier.format(iconsFileContent, prettierConfig);

    const outPath = path.resolve(import.meta.dirname, outputFilePath);
    fs.writeFileSync(outPath, formatted);

    writeOptimizedAssets(assetTypes);
};

(async () => {
    console.log('Generating icons TS file...');
    await generateFileForAssetTypes(assetTypesConfig, iconsFilePath);
    console.log(chalk.green('Icons TS file generated successfully'));

    console.log('Generating crypto icons TS file...');
    await generateFileForAssetTypes(cryptoAssetsTypesConfig, cryptoIconsPath);
    console.log(chalk.green('Crypto icons TS file generated successfully'));

    console.log('Generating network icons TS file...');
    await generateFileForAssetTypes(networkAssetsTypesConfig, networkIconsPath);
    console.log(chalk.green('Network icons TS file generated successfully'));
})();
