/* eslint-disable no-console */
// eslint-disable-next-line import/no-extraneous-dependencies
import chalk from 'chalk';
// eslint-disable-next-line import/no-extraneous-dependencies
import { FontAssetType, OtherAssetType, generateFonts } from 'fantasticon';
import fs, { constants } from 'fs';
import path from 'path';

import { MOBILE_ICON_FONT_NAME } from './src/constants';
import { type IconName as AllAvailableIcons } from './src/icons';

const usedIcons = [
    'arrowBendRightUp',
    'arrowCounterClockwise',
    'arrowDown',
    'arrowDownLeft',
    'arrowFatLinesRight',
    'arrowLeft',
    'arrowLineDown',
    'arrowLineUp',
    'arrowLineUpRight',
    'arrowRight',
    'arrowSquareOut',
    'arrowURightDown',
    'arrowUUpLeft',
    'arrowUp',
    'arrowUpRight',
    'arrowsClockwise',
    'arrowsCounterClockwise',
    'arrowsDownUp',
    'arrowsLeftRight',
    'article',
    'atom',
    'backspace',
    'bank',
    'bluetooth',
    'bluetoothConnected',
    'bluetoothSlash',
    'bookmarkSimple',
    'browsers',
    'bugBeetle',
    'cableUsbC',
    'calendar',
    'calendarBlank',
    'cameraSlash',
    'caretCircleRight',
    'caretDown',
    'caretDownFilled',
    'caretLeft',
    'caretRight',
    'caretUp',
    'caretUpDown',
    'caretUpFilled',
    'change',
    'chatCircle',
    'chatsTeardrop',
    'check',
    'checkCircle',
    'checkCircleFilled',
    'checks',
    'circleDashed',
    'clipboard',
    'clock',
    'clockClockwise',
    'code',
    'coin',
    'coinSlash',
    'coinVerticalCheck',
    'coins',
    'copy',
    'cpu',
    'creditCard',
    'currencyBtc',
    'database',
    'detective',
    'deviceMobileCamera',
    'devices',
    'devicesFilled',
    'discover',
    'discoverFilled',
    'eject',
    'ejectSimple',
    'everstakeLogo',
    'eye',
    'eyeSlash',
    'facebookLogo',
    'file',
    'fileArrowDown',
    'filePdf',
    'fileTxt',
    'fingerprint',
    'fingerprintSimple',
    'flag',
    'flagCheckered',
    'funnelSimple',
    'gasPump',
    'gear',
    'gearFilled',
    'githubLogo',
    'graph',
    'handPalm',
    'handWaving',
    'handshake',
    'heart',
    'hourglass',
    'house',
    'houseFilled',
    'identificationCard',
    'image',
    'info',
    'instagramLogo',
    'lifebuoy',
    'lightbulb',
    'lightning',
    'link',
    'linkBreak',
    'lock',
    'magnifyingGlass',
    'mapPin',
    'minus',
    'money',
    'newspaper',
    'package',
    'palette',
    'password',
    'pencil',
    'pencilSimple',
    'pencilSimpleLine',
    'percent',
    'pictureFrame',
    'piggyBank',
    'piggyBankFilled',
    'plugs',
    'plugsConnected',
    'plus',
    'plusCircle',
    'power',
    'prohibit',
    'puzzlePiece',
    'qrCode',
    'question',
    'questionSimple',
    'repeat',
    'rocketLaunch',
    'rocketLaunchFilled',
    'scroll',
    'seal',
    'selectionSlash',
    'shareNetwork',
    'shield',
    'shieldCheck',
    'shieldCheckered',
    'shieldStar',
    'shieldStarFilled',
    'shieldWarning',
    'shuffle',
    'sliders',
    'slidersHorizontal',
    'slideshow',
    'smiley',
    'spinner',
    'spinnerGap',
    'stack',
    'star',
    'starFilled',
    'starFour',
    'surfaceProtection',
    'swap',
    'tag',
    'textAa',
    'tiktokLogo',
    'timer',
    'translate',
    'trash',
    'trashSimple',
    'treeStructure',
    'trendUp',
    'trezorBackup',
    'trezorDevices',
    'trezorLogo',
    'trezorModelOne',
    'trezorModelOneFilled',
    'trezorModelT',
    'trezorModelTFilled',
    'trezorPassword',
    'trezorSafe3',
    'trezorSafe3Filled',
    'trezorSafe5',
    'trezorSafe5Filled',
    'trezorSafe7',
    'twitterLogo',
    'user',
    'users',
    'wallet',
    'walletConnect',
    'warning',
    'warningCircle',
    'warningOctagon',
    'wifiSlash',
    'wifiX',
    'x',
    'xCircle',
    // Trezor Connect permission + group-badge icons (shared with the web permissions UI).
    'key',
    'signature',
    'notePencil',
    'sealCheck',
    'gearSix',
    'broadcast',
    'cube',
    'circuitry',
] as const satisfies AllAvailableIcons[];

const tempAssetsDir = path.join(__dirname, 'assetsTemp');
const iconFontsMobileDir = path.join(__dirname, 'iconFontsMobile');

(async () => {
    console.log('Generating icon font for mobile...');

    fs.rmSync(tempAssetsDir, { recursive: true, force: true });
    fs.rmSync(iconFontsMobileDir, { recursive: true, force: true });

    fs.mkdirSync(tempAssetsDir);

    // copy used icons to assetsTemp
    usedIcons.forEach(icon => {
        fs.copyFileSync(
            `./assets/${icon}.svg`,
            `${tempAssetsDir}/${icon}.svg`,
            constants.COPYFILE_FICLONE,
        );
    });

    // create iconFontsMobile folder
    fs.mkdirSync('./iconFontsMobile');

    try {
        await generateFonts({
            inputDir: tempAssetsDir,
            outputDir: iconFontsMobileDir,
            name: MOBILE_ICON_FONT_NAME,
            fontTypes: [FontAssetType.TTF],
            assetTypes: [OtherAssetType.JSON],
            formatOptions: { json: { indent: 4 } },
            templates: {},
            pathOptions: {},
            codepoints: {},
            fontHeight: 300,
            round: undefined, // --
            descent: undefined, // Will use `svgicons2svgfont` defaults
            normalize: false, // --
            tag: 'i',
            prefix: 'icon',
            fontsUrl: undefined,
        });
    } catch (error) {
        console.error(error);
        process.exit(1);
    }

    // append newline to the end of the file to satisfy prettier
    fs.appendFileSync(`${iconFontsMobileDir}/${MOBILE_ICON_FONT_NAME}.json`, '\n');

    console.log(chalk.green('Icon font for mobile generated.'));
})();
