/* eslint-disable no-console */
/* eslint-disable import/no-extraneous-dependencies */

import chalk from 'chalk';
import fs from 'fs';
import path from 'path';
import prettier from 'prettier';
import { optimize } from 'svgo';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const iconsFilePath = './src/icons.ts';
const iconNamesFilePath = './src/iconNames.ts';
const cryptoIconsPath = './src/cryptoIcons.ts';
const networkIconsPath = './src/networkIcons.ts';
const paymentMethodLogosPath = './src/paymentMethodLogos.ts';

const assetTypesConfig = [
    {
        name: 'icons',
        dirname: 'assets',
        typeName: 'IconName',
    },
];

const cryptoAssetsTypesConfig = [
    {
        name: 'cryptoIcons',
        dirname: 'cryptoAssets/cryptoIcons',
        typeName: 'CryptoIconName',
    },
];

const paymentMethodLogosAssetsTypesConfig = [
    {
        name: 'paymentMethodLogos',
        dirname: 'paymentMethods',
        typeName: 'PaymentMethodLogoName',
    },
];

const networkAssetsTypesConfig = [
    { name: 'networkIcons', dirname: 'cryptoAssets/networkIcons', typeName: 'NetworkIconName' },
];

// https://github.com/svg/svgo#built-in-plugins
/**
 * @type {import('svgo').Config}
 */
const svgoConfig = {
    multipass: true,
    js2svg: {
        indent: 2, // string with spaces or number of spaces. 4 by default
        pretty: true, // boolean, false by default
    },
    plugins: [
        {
            name: 'preset-default',
        },
        {
            name: 'removeViewBox',
            active: false,
        },
        'prefixIds',
        // it's necessary to remove all dimension tags to allow resizing
        'removeDimensions',
        'removeRasterImages',
        'removeScripts',
        'convertStyleToAttrs',
    ],
};

const optimizeSvgAssets = assetsDirname => {
    const assetsDir = path.join(__dirname, assetsDirname);
    const assetFileNames = fs.readdirSync(assetsDir);

    return assetFileNames
        .filter(fileName => fileName.endsWith('.svg'))
        .map(fileName => ({
            fileName,
            content: fs.readFileSync(path.resolve(assetsDir, fileName)).toString(),
        }))
        .map(({ fileName, content }) => ({
            fileName,
            content: optimize(content, svgoConfig).data,
        }));
};

const getOptimizedAssetTypes = assetTypesArray =>
    assetTypesArray.map(config => ({
        ...config,
        assets: optimizeSvgAssets(config.dirname),
    }));

const generateIconsFileContent = assetTypesArray => {
    const mappedAssetTypes = assetTypesArray.map(
        ({ name, assets, dirname, typeName }) => `
           export const ${name} = {
            ${assets
                .map(
                    ({ fileName }) =>
                        `${fileName.replace('.svg', '')}: require('../${dirname}/${fileName}')`,
                )
                .join(',')}
        } as const;
        export type ${typeName} = keyof typeof ${name};
       `,
    );

    return `
    // !!! IMPORTANT: This file is autogenerated !!!
    // If you want to add of modify icons please read README.md to find out how to do it

    ${mappedAssetTypes.join('')}
    `;
};

const generateIconNamesFileContent = assetTypesArray => {
    const [{ assets, typeName }] = assetTypesArray;
    const names = assets.map(({ fileName }) => `'${fileName.replace('.svg', '')}'`).join(',\n    ');

    return `
    // !!! IMPORTANT: This file is autogenerated !!!
    // If you want to add or modify icons please read README.md to find out how to do it

    export const iconNames = [
        ${names},
    ] as const;

    export type ${typeName} = (typeof iconNames)[number];
    `;
};

const writeOptimizedAssets = assetTypesArray => {
    assetTypesArray.forEach(({ assets, dirname }) => {
        assets.forEach(({ fileName, content }) =>
            fs.writeFileSync(path.resolve(dirname, fileName), content),
        );
    });
};

const generateFileForAssetTypes = async (assetTypesArray, outputFilePath) => {
    const assetTypes = getOptimizedAssetTypes(assetTypesArray);

    const iconsFileContent = generateIconsFileContent(assetTypes);

    const prettierConfigPath = await prettier.resolveConfigFile();
    const prettierConfig = {
        ...(await prettier.resolveConfig(prettierConfigPath)),
        parser: 'babel-ts',
    };

    const formattedIconTypesFileContent = await prettier.format(iconsFileContent, prettierConfig);

    fs.writeFileSync(path.resolve(outputFilePath), formattedIconTypesFileContent);

    writeOptimizedAssets(assetTypes);
};

(async () => {
    console.log('Generating icons TS file...');
    await generateFileForAssetTypes(assetTypesConfig, iconsFilePath);
    console.log(chalk.green('Icons TS file generated successfully'));

    console.log('Generating icon names TS file...');
    const iconAssetTypes = getOptimizedAssetTypes(assetTypesConfig);
    const iconNamesContent = generateIconNamesFileContent(iconAssetTypes);
    const prettierConfigPath = await prettier.resolveConfigFile();
    const prettierConfig = {
        ...(await prettier.resolveConfig(prettierConfigPath)),
        parser: 'babel-ts',
    };
    fs.writeFileSync(
        path.resolve(iconNamesFilePath),
        await prettier.format(iconNamesContent, prettierConfig),
    );
    console.log(chalk.green('Icon names TS file generated successfully'));
    console.log('Generating crypto icons TS file...');
    await generateFileForAssetTypes(cryptoAssetsTypesConfig, cryptoIconsPath);
    console.log(chalk.green('Crypto icons TS file generated successfully'));
    console.log('Generating network icons TS file...');
    await generateFileForAssetTypes(networkAssetsTypesConfig, networkIconsPath);
    console.log(chalk.green('Network icons TS file generated successfully'));
    console.log('Generating payment method logos TS file...');
    await generateFileForAssetTypes(paymentMethodLogosAssetsTypesConfig, paymentMethodLogosPath);
    console.log(chalk.green('Payment method logos TS file generated successfully'));
})();
