/* eslint-disable no-console */
/* eslint-disable import/no-extraneous-dependencies */

import chalk from 'chalk';
import fs from 'fs';
import path from 'path';
import prettier from 'prettier';
import { optimize } from 'svgo';
import { fileURLToPath } from 'url';

import { svgoConfig } from './svgoConfig.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const cryptoIconsPath = './src/cryptoIcons.ts';
const networkIconsPath = './src/networkIcons.ts';
const paymentMethodLogosPath = './src/paymentMethodLogos.ts';

const cryptoAssetsTypesConfig = [
    {
        name: 'cryptoIcons',
        dirname: 'cryptoAssets/cryptoIcons',
        typeName: 'CryptoIconName',
    },
];

const paymentMethodLogosAssetsTypesConfig = [
    {
        name: 'paymentMethodLogos',
        dirname: 'paymentMethods',
        typeName: 'PaymentMethodLogoName',
    },
];

const networkAssetsTypesConfig = [
    { name: 'networkIcons', dirname: 'cryptoAssets/networkIcons', typeName: 'NetworkIconName' },
];

const optimizeSvgAssets = assetsDirname => {
    const assetsDir = path.join(__dirname, assetsDirname);
    const assetFileNames = fs.readdirSync(assetsDir);

    return assetFileNames
        .filter(fileName => fileName.endsWith('.svg'))
        .map(fileName => ({
            fileName,
            content: fs.readFileSync(path.resolve(assetsDir, fileName)).toString(),
        }))
        .map(({ fileName, content }) => ({
            fileName,
            content: optimize(content, svgoConfig).data,
        }));
};

const getOptimizedAssetTypes = assetTypesArray =>
    assetTypesArray.map(config => ({
        ...config,
        assets: optimizeSvgAssets(config.dirname),
    }));

const generateIconsFileContent = assetTypesArray => {
    const mappedAssetTypes = assetTypesArray.map(
        ({ name, assets, dirname, typeName }) => `
           export const ${name} = {
            ${assets
                .map(
                    ({ fileName }) =>
                        `${fileName.replace('.svg', '')}: require('../${dirname}/${fileName}')`,
                )
                .join(',')}
        } as const;
        export type ${typeName} = keyof typeof ${name};
       `,
    );

    return `
    // !!! IMPORTANT: This file is autogenerated !!!
    // If you want to add of modify icons please read README.md to find out how to do it

    ${mappedAssetTypes.join('')}
    `;
};

const writeOptimizedAssets = assetTypesArray => {
    assetTypesArray.forEach(({ assets, dirname }) => {
        assets.forEach(({ fileName, content }) =>
            fs.writeFileSync(path.resolve(dirname, fileName), content),
        );
    });
};

const generateFileForAssetTypes = async (assetTypesArray, outputFilePath) => {
    const assetTypes = getOptimizedAssetTypes(assetTypesArray);

    const iconsFileContent = generateIconsFileContent(assetTypes);

    const prettierConfigPath = await prettier.resolveConfigFile();
    const prettierConfig = {
        ...(await prettier.resolveConfig(prettierConfigPath)),
        parser: 'babel-ts',
    };

    const formattedIconTypesFileContent = await prettier.format(iconsFileContent, prettierConfig);

    fs.writeFileSync(path.resolve(outputFilePath), formattedIconTypesFileContent);

    writeOptimizedAssets(assetTypes);
};

(async () => {
    console.log(chalk.green('Icons TS file generated successfully'));
    console.log('Generating crypto icons TS file...');
    await generateFileForAssetTypes(cryptoAssetsTypesConfig, cryptoIconsPath);
    console.log(chalk.green('Crypto icons TS file generated successfully'));
    console.log('Generating network icons TS file...');
    await generateFileForAssetTypes(networkAssetsTypesConfig, networkIconsPath);
    console.log(chalk.green('Network icons TS file generated successfully'));
    console.log('Generating payment method logos TS file...');
    await generateFileForAssetTypes(paymentMethodLogosAssetsTypesConfig, paymentMethodLogosPath);
    console.log(chalk.green('Payment method logos TS file generated successfully'));
})();
