dist: trusty
language: node_js
node_js:
  - "8"
matrix:
  include:

    - env: BUILD=emscripten-fastxpub
      script:
        - cd fastxpub && make clean && make docker-build && nvm install 8 && nvm use 8 && make test && cd ..
      services:
        - docker
      sudo: required
      install: true
      compiler: true


    - before_script:
        # we need to run xvfb fot the karma tests to work
        - export CHROME_BIN=chromium-browser
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
      env: TEST_SUITE=karma-chrome

    - before_script:
        # we need to run xvfb fot the karma tests to work
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
      env: TEST_SUITE=karma-firefox
      addons:
        firefox: latest

env:
  - TEST_SUITE=eslint
  - TEST_SUITE=flow
  - TEST_SUITE=build-example
  - TEST_SUITE=unit
  - TEST_SUITE=coverage
script: npm run-script $TEST_SUITE

notifications:
  webhooks:
    urls:
      - http://ci-bot.satoshilabs.com:5000/travis
    on_success: always
    on_failure: always
    on_start: always

