export default [
    {
        id: 'btc',
        coinName: 'Bitcoin',
        url: '../?coin=btc',
        order: 1,
    },
    {
        id: 'bch',
        coinName: 'Bitcoin Cash',
        url: '../?coin=bch',
        order: 6,
    },
    {
        id: 'btg',
        coinName: 'Bitcoin Gold',
        url: '../?coin=btg',
        order: 27,
    },
    {
        id: 'dash',
        coinName: 'Dash',
        url: '../?coin=dash',
        order: 15,
    },
    {
        id: 'dgb',
        coinName: 'DigiByte',
        url: '../?coin=dgb',
        order: 42,
    },
    {
        id: 'doge',
        coinName: 'Dogecoin',
        url: '../?coin=doge',
        order: 26,
    },
    {
        id: 'ltc',
        coinName: 'Litecoin',
        url: '../?coin=ltc',
        order: 5,
    },
    {
        id: 'nmc',
        coinName: 'Namecoin',
        url: '../?coin=nmc',
        order: 255,
    },
    {
        id: 'vtc',
        coinName: 'Vertcoin',
        url: '../?coin=vtc',
        order: 154,
    },
    {
        id: 'zec',
        coinName: 'Zcash',
        url: '../?coin=zec',
        order: 20,
    },
    {
        id: 'xem',
        coinName: 'NEM',
        url: 'https://nem.io/downloads/',
        external: true,
        order: 19,
    },
    {
        id: 'xlm',
        coinName: 'Stellar',
        url: 'https://trezor.io/stellar',
        external: true,
        order: 9,
    },
    {
        id: 'ada',
        coinName: 'Cardano',
        url: 'https://adalite.io/app',
        external: true,
        order: 12,
    },
    {
        id: 'xtz',
        coinName: 'Tezos',
        url: 'https://wallet.simplestaking.com/tezos/wallet/start',
        external: true,
        order: 21,
    },
];
