export default {
    valueTickers: [
        {
            network: 'eth',
            url: 'https://api.coingecko.com/api/v3/coins/ethereum',
        },
        {
            network: 'etc',
            url: 'https://api.coingecko.com/api/v3/coins/ethereum-classic',
        },
        {
            network: 'xrp',
            url: 'https://api.coingecko.com/api/v3/coins/ripple',
        },
    ],
    currencies: [
        'usd',
        'aed',
        'ars',
        'aud',
        'bdt',
        'bhd',
        'bmd',
        'brl',
        'cad',
        'chf',
        'clp',
        'cny',
        'czk',
        'dkk',
        'eur',
        'gbp',
        'hkd',
        'huf',
        'idr',
        'ils',
        'inr',
        'jpy',
        'krw',
        'kwd',
        'lkr',
        'mmk',
        'mxn',
        'myr',
        'nok',
        'nzd',
        'php',
        'pkr',
        'pln',
        'rub',
        'sar',
        'sek',
        'sgd',
        'thb',
        'try',
        'twd',
        'vef',
        'vnd',
        'zar',
        'xdr',
        'xag',
        'xau',
    ],
};
