export default {
    tickers: [
        { symbol: 'eth', url: 'https://api.coingecko.com/api/v3/coins/ethereum' },
        { symbol: 'etc', url: 'https://api.coingecko.com/api/v3/coins/ethereum-classic' },
        { symbol: 'xrp', url: 'https://api.coingecko.com/api/v3/coins/ripple' },
        { symbol: 'btc', url: 'https://api.coingecko.com/api/v3/coins/bitcoin' },
    ],
    currencies: [
        'usd',
        'aed',
        'ars',
        'aud',
        'bdt',
        'bhd',
        'bmd',
        'brl',
        'cad',
        'chf',
        'clp',
        'cny',
        'czk',
        'dkk',
        'eur',
        'gbp',
        'hkd',
        'huf',
        'idr',
        'ils',
        'inr',
        'jpy',
        'krw',
        'kwd',
        'lkr',
        'mmk',
        'mxn',
        'myr',
        'nok',
        'nzd',
        'php',
        'pkr',
        'pln',
        'rub',
        'sar',
        'sek',
        'sgd',
        'thb',
        'try',
        'twd',
        'vef',
        'vnd',
        'zar',
        'xdr',
        'xag',
        'xau',
    ],
};
