/* eslint-disable global-require */
export const COINS = {
    ada: require('../../../images/coins/ada.svg'),
    bch: require('../../../images/coins/bch.svg'),
    btc: require('../../../images/coins/btc.svg'),
    test: require('../../../images/coins/btctestnet.svg'),
    btg: require('../../../images/coins/btg.svg'),
    dash: require('../../../images/coins/dash.svg'),
    dgb: require('../../../images/coins/dgb.svg'),
    doge: require('../../../images/coins/doge.svg'),
    etc: require('../../../images/coins/etc.svg'),
    eth: require('../../../images/coins/eth.svg'),
    ltc: require('../../../images/coins/ltc.svg'),
    nem: require('../../../images/coins/nem.svg'),
    nmc: require('../../../images/coins/nmc.svg'),
    rinkeby: require('../../../images/coins/rinkeby.svg'),
    trop: require('../../../images/coins/trop.svg'),
    txrp: require('../../../images/coins/txrp.svg'),
    vtc: require('../../../images/coins/vtc.svg'),
    xem: require('../../../images/coins/xem.svg'),
    xlm: require('../../../images/coins/xlm.svg'),
    xrp: require('../../../images/coins/xrp.svg'),
    xtz: require('../../../images/coins/xtz.svg'),
    zec: require('../../../images/coins/zec.svg'),
    taz: require('../../../images/coins/zec.svg'),
};
