name: "Extract and Upload Trezor-user-env Logs"
description: "Extracts logs from Trezor-user-env and Regtest, then uploads them as artifacts"
inputs:
  test-group:
    description: "Test group name for log file naming"
    required: true
  project:
    description: "Playwright project name. (web|desktop)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Extract Trezor-user-env and Regtest logs
      shell: bash
      run: |
        docker cp docker-trezor-user-env-unix-1:/trezor-user-env/logs/debugging.log trezor-user-env-debugging.log || true
        docker cp docker-trezor-user-env-unix-1:/trezor-user-env/logs/emulator_bridge.log tenv-emulator-bridge-debugging.log || true
        docker cp docker-trezor-user-env-unix-1:/trezor-user-env/docker/version.txt trezor-user-env-version.txt || true
        docker logs docker-electrum-regtest-1 > electrum-regtest.txt || true

    - name: Upload Trezor-user-env and Regtest logs
      uses: actions/upload-artifact@v4
      with:
        name: emulator-logs-${{ inputs.project }}-${{ inputs.test-group }}
        path: |
          trezor-user-env-debugging.log
          tenv-emulator-bridge-debugging.log
          trezor-user-env-version.txt
          electrum-regtest.txt
        retention-days: 30
