// This file is auto generated by @trezor/protobuf package

export enum ThpPairingMethod {
    SkipPairing = 1,
    CodeEntry = 2,
    QrCode = 3,
    NFC = 4,
}

export type ThpDeviceProperties = {
    internal_model: string;
    model_variant: number;
    protocol_version_major: number;
    protocol_version_minor: number;
    pairing_methods: ThpPairingMethod[];
};

export type ThpCredentialResponse = {
    trezor_static_pubkey: string;
    credential: string;
};
