version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "ci"
      - "no-project"
    commit-message:
      prefix: "chore(actions):"
