version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    # Note that this just limits age of the versions that dependabot suggests, not a limit for installation (that's in .yarnrc.yml)
    cooldown:
      default-days: 14
      include:
        - "*"
      exclude:
        - "@evolu/*"
        - "@types/invity-api"
