export enum EventType {
    ConnectPopupCall = 'connect-popup/call',
    ConnectPopupError = 'connect-popup/error',
    ConnectPopupInit = 'connect-popup/init',
    ConnectPopupPermissions = 'connect-popup/permissions',
    DeviceConnectionDeviceConfirmation = 'device-connection/device-confirmation',
    DeviceConnectionDeviceFound = 'device-connection/device-found',
    DeviceConnectionDevicePaired = 'device-connection/device-paired',
    SettingsAppLogExported = 'settings/app-log/exported',
    SettingsDeviceChangeLabel = 'settings/device/change-label',
    SettingsDeviceWipe = 'settings/device/wipe',
    SettingsGeneralLabeling = 'settings/general/labeling',
    WalletConnectInit = 'wallet-connect/init',
    WalletConnectPaired = 'wallet-connect/paired',
    WalletConnectProposal = 'wallet-connect/proposal',
    WalletConnectProposalApproved = 'wallet-connect/proposal-approved',
    WalletConnectProposalRejected = 'wallet-connect/proposal-rejected',
    WalletConnectSessionRequest = 'wallet-connect/session-request',
}
