extends: default

ignore: |
  vendor/
  node_modules/

rules:
  line-length: disable
  # skip "---" at the beginning
  document-start: disable
  comments-indentation: disable
  indentation:
    spaces: 2
