compressionLevel: mixed

enableGlobalCache: false

logFilters:
  - code: YN0002
    level: discard

nodeLinker: node-modules

# false is default since yarn 4.14, do NOT change this. Instead add an exception to root package.json dependenciesMeta
enableScripts: false

# empty [] is the default value (packages are to be installed only from npm). Add a repo here only in exceptional cases.
approvedGitRepositories: []

# Allow only packages older than 14 days (in minutes). Schema declares that "14d" can be entered, but that doesn't have any effect.
# Note that it blocks package resolution, not fetching & linking, so it can installs younger packages if already resolved in yarn.lock.
# Please avoid that, and rather state all exceptions explicitly in npmPreapprovedPackages,
npmMinimalAgeGate: 20160
# Skip age gate for experimental, rapidly changing packages
npmPreapprovedPackages:
  - "@types/invity-api@*"
  # To fix a bug with @sentry/react-native AppStart integration (we want to have more time for QA). Can be removed after 20.8.2026
  - "@sentry/*@*"
  - "@expo/ui@56.0.24"

plugins:
  - checksum: 5e73a1acbb9741fce1e8335e243c9480ea2107b9b4b65ed7643785ddea9e3019aee254a92a853b1cd71023b16fff5b7d3afd5256fe57cd35a54f8785b8c30281
    path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://go.mskelton.dev/yarn-outdated/v4"

yarnPath: .yarn/releases/yarn-4.18.0.cjs
