compressionLevel: mixed

enableGlobalCache: false

logFilters:
  - code: YN0002
    level: discard

nodeLinker: node-modules

# Allow only packages older than 14 days (in minutes). Schema declares that "14d" can be entered, but that doesn't have any effect.
npmMinimalAgeGate: 20160
# Skip age gate for experimental, rapidly changing packages
npmPreapprovedPackages:
  - "@evolu/*"
  # kysely@0.28.15 bugfix needed in Evolu. The exception can be deleted after 2026-04-15
  - "kysely@0.28.15"
  - "@types/invity-api@*"
  # handlebars@4.7.9 fixes Critical severity vulnerabilities. The exception can be deleted after 2026-04-11
  - "handlebars@4.7.9"
  # electron@40.8.5 fixes High severity vulnerabilities. The exception can be deleted after 2026-04-11
  - "electron@40.8.5"
  # lodash@4.18.1 and lodash-es@4.18.1 fixe High severity vulnerabilities. The exception can be deleted after 2026-04-19
  - "lodash@4.18.1"
  - "lodash-es@4.18.1"
  # node-forge@1.4.0 fixes High severity vulnerabilities. The exception can be deleted after 2026-04-09
  - "node-forge@1.4.0"
  # path-to-regexp@8.4.2 fixes High severity vulnerabilities. The exception can be deleted after 2026-04-09
  - "path-to-regexp@8.4.2"
  # defu@6.1.6 fixes High severity vulnerabilities. The exception can be deleted after 2026-04-09
  - "defu@6.1.6"
  # protobufjs@7.5.5 fixes High severity vulnerabilities. The exception can be deleted after 2026-04-29
  - "protobufjs@7.5.5"

plugins:
  - checksum: 5e73a1acbb9741fce1e8335e243c9480ea2107b9b4b65ed7643785ddea9e3019aee254a92a853b1cd71023b16fff5b7d3afd5256fe57cd35a54f8785b8c30281
    path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://go.mskelton.dev/yarn-outdated/v4"

yarnPath: .yarn/releases/yarn-4.12.0.cjs
