/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Yield.xyz API
 * API Documentation
 * OpenAPI spec version: 1.0
 */
import type {
    BalancesRequestDto,
    BalancesResponseDto,
    YieldBalancesDto,
    YieldBalancesRequestDto,
    YieldsControllerGetAggregateBalances400,
    YieldsControllerGetAggregateBalances401,
    YieldsControllerGetAggregateBalances429,
    YieldsControllerGetAggregateBalances500,
    YieldsControllerGetYieldBalances400,
    YieldsControllerGetYieldBalances401,
    YieldsControllerGetYieldBalances429,
    YieldsControllerGetYieldBalances500,
    YieldsControllerGetYieldBalancesPathParameters,
} from './index.schemas';
import { httpClient } from '../httpClient';

/**
 * Retrieve balances for multiple wallet addresses across different networks and yield opportunities. Send an array of balance requests - each request can specify a yieldId (optional for chain scanning), address, network, and custom arguments. This is the same format as the single yield balance endpoint but in array form. Duplicate requests (same yieldId + address + network) are automatically deduplicated, with specific yield requests taking precedence over chain scans.
 * @summary Get balances across multiple yields and networks
 */
export type GetAggregateBalancesResponse200 = {
    data: BalancesResponseDto;
    status: 200;
};

export type GetAggregateBalancesResponse400 = {
    data: YieldsControllerGetAggregateBalances400;
    status: 400;
};

export type GetAggregateBalancesResponse401 = {
    data: YieldsControllerGetAggregateBalances401;
    status: 401;
};

export type GetAggregateBalancesResponse429 = {
    data: YieldsControllerGetAggregateBalances429;
    status: 429;
};

export type GetAggregateBalancesResponse500 = {
    data: YieldsControllerGetAggregateBalances500;
    status: 500;
};

export type GetAggregateBalancesResponseSuccess = GetAggregateBalancesResponse200 & {
    headers: Headers;
};
export type GetAggregateBalancesResponseError = (
    | GetAggregateBalancesResponse400
    | GetAggregateBalancesResponse401
    | GetAggregateBalancesResponse429
    | GetAggregateBalancesResponse500
) & {
    headers: Headers;
};

export const getGetAggregateBalancesUrl = () => `/v1/yields/balances`;

export const getAggregateBalances = (
    balancesRequestDto: BalancesRequestDto,
    options?: RequestInit,
): Promise<GetAggregateBalancesResponseSuccess> =>
    httpClient<GetAggregateBalancesResponseSuccess>(getGetAggregateBalancesUrl(), {
        ...options,
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...options?.headers },
        body: JSON.stringify(balancesRequestDto),
    });

/**
 * Retrieve all balances associated with a yield opportunity for a specific wallet address, including active, pending, claimable, and withdrawable balances. The network is automatically determined from the yield configuration.
 * @summary Get balances for a specific yield
 */
export type GetYieldBalancesResponse200 = {
    data: YieldBalancesDto;
    status: 200;
};

export type GetYieldBalancesResponse400 = {
    data: YieldsControllerGetYieldBalances400;
    status: 400;
};

export type GetYieldBalancesResponse401 = {
    data: YieldsControllerGetYieldBalances401;
    status: 401;
};

export type GetYieldBalancesResponse404 = {
    data: void;
    status: 404;
};

export type GetYieldBalancesResponse429 = {
    data: YieldsControllerGetYieldBalances429;
    status: 429;
};

export type GetYieldBalancesResponse500 = {
    data: YieldsControllerGetYieldBalances500;
    status: 500;
};

export type GetYieldBalancesResponseSuccess = GetYieldBalancesResponse200 & {
    headers: Headers;
};
export type GetYieldBalancesResponseError = (
    | GetYieldBalancesResponse400
    | GetYieldBalancesResponse401
    | GetYieldBalancesResponse404
    | GetYieldBalancesResponse429
    | GetYieldBalancesResponse500
) & {
    headers: Headers;
};

export const getGetYieldBalancesUrl = ({
    yieldId,
}: YieldsControllerGetYieldBalancesPathParameters) => `/v1/yields/${yieldId}/balances`;

export const getYieldBalances = (
    { yieldId }: YieldsControllerGetYieldBalancesPathParameters,
    yieldBalancesRequestDto: YieldBalancesRequestDto,
    options?: RequestInit,
): Promise<GetYieldBalancesResponseSuccess> =>
    httpClient<GetYieldBalancesResponseSuccess>(getGetYieldBalancesUrl({ yieldId }), {
        ...options,
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...options?.headers },
        body: JSON.stringify(yieldBalancesRequestDto),
    });
