// TODO: this file is mostly duplicated with suite-common/message-system/scripts/sign-config.ts
// TODO: maybe we can try to extract some utility???
/* eslint-disable no-console */

import * as fs from 'fs-extra';
import * as jws from 'jws';
import { join, resolve } from 'path';
import {
    JWS_RELEASES_FILENAME_LOCAL,
    JWS_RELEASES_FILENAME_REMOTE,
    JWS_SIGN_ALGORITHM,
    VERSION,
} from '../src/constants';

const RELEASES_FILENAME = `releases.v${VERSION}.json`;
const PACKAGE_ROOT = resolve(__dirname, '..'); // connect-message-releases
const RELEASE_PATH = join(PACKAGE_ROOT, 'releases', RELEASES_FILENAME);

// There must be no extra spaces at the beginning of the line.
const devPrivateKey = `-----BEGIN EC PRIVATE KEY-----
MHQCAQEEINi7lfZE3Y5U9srS58A+AN7Ul7HeBXsHEfzVzijColOkoAcGBSuBBAAKoUQDQgAEbSUHJlr17+NywPS/w+xMkp3dSD8eWXSuAfFKwonZPe5fL63kISipJC+eJP7Mad0WxgyJoiMsZCV6BZPK2jIFdg==
-----END EC PRIVATE KEY-----`;

const getPrivateKey = () => {
    // Only CI jobs flagged with "codesign", sign message releases by production private key. All other branches use development key.
    // The isCodesignBuild() util cannot be used here because the lib is not built at this point. Building libs would make the release script slower.
    if (process.env.IS_CODESIGN_BUILD !== 'true') {
        console.log('Signing releases using develop private key!');

        return devPrivateKey;
    }

    console.log('Signing releases using production private key!');

    const privateKey = process.env.JWS_PRIVATE_KEY_ENV; // available on GitHub

    if (!privateKey) {
        throw Error('Missing private key!');
    }

    return privateKey;
};

const signRelease = () => {
    console.log('Creating a JWS...');

    const release = fs.readFileSync(RELEASE_PATH, 'utf-8');

    const jwsReleases = jws.sign({
        header: { alg: JWS_SIGN_ALGORITHM },
        payload: release,
        secret: getPrivateKey(),
    });

    console.log('JWS created!');

    return jwsReleases;
};

// Save JWS to files/releases.v1.jws for publishing on data.trezor.io
const saveReleasesJws = (jwsReleases: string) => {
    console.log('saveReleasesJws');
    const destination = join(PACKAGE_ROOT, 'files', JWS_RELEASES_FILENAME_REMOTE);
    fs.outputFileSync(destination, jwsReleases);
    console.log(`JWS saved to ${destination}!`);
};

// Save JWS to files/releases.v1.ts for bundling in the app and using as local fallback when offline
const saveReleaseTs = (jwsReleases: string) => {
    const releasesTs = `// Autogenerated by sign-release script.
export const jws = \`${jwsReleases}\`;
`;

    const destination = join(PACKAGE_ROOT, 'files', JWS_RELEASES_FILENAME_LOCAL);
    fs.outputFileSync(destination, releasesTs);
    console.log(`JWS saved to ${destination}!`);
};

const releasesJws = signRelease();

saveReleasesJws(releasesJws);
saveReleaseTs(releasesJws);
