import { type Db } from './createDb';

export const loadStoragePayload = async (db: Db) => {
    // Load state from database in parallel using Promise.all
    const [
        suiteSettings,
        devices,
        thp,
        bluetooth,
        accounts,
        walletSettings,
        tradingTrades,
        historicRates,
        graph,
        analytics,
        metadata,
        txs,
        phishing,
        phishingMetadata,
        messageSystem,
        backendSettings,
        sendFormDrafts,
        receive,
        formDrafts,
        coinjoinAccounts,
        coinjoinDebugSettings,
        tokenManagement,
        persistentDeviceData,
        connect,
        explorer,
        bioAuth,
        firmware,
        suiteSyncSettings,
        suiteSyncOwners,
        suiteSyncQuotaManager,
        featureFeedback,
        discreetMode,
        debug,
        earnOnboarding,
    ] = await Promise.all([
        db.getItemByPK('suiteSettings', 'suite'),
        db.getItemsExtended('devices'),
        db.getItemByPK('thp', 'value'),
        db.getItemByPK('bluetooth', 'value'),
        db.getItemsExtended('accounts'),
        db.getItemByPK('walletSettings', 'wallet'),
        db.getItemsExtended('tradingTrades'),
        db.getItemsWithKeys('historicRates'),
        db.getItemsExtended('graph'),
        db.getItemByPK('analytics', 'suite'),
        db.getItemByPK('metadata', 'state'),
        db.getItemsExtended('txs', 'order'),
        db.getItemsWithKeys('phishing'),
        db.getItemByPK('phishingMetadata', 'phishingMetadata'),
        db.getItemByPK('messageSystem', 'suite'),
        db.getItemsWithKeys('backendSettings'),
        db.getItemsWithKeys('sendFormDrafts'),
        db.getItemsWithKeys('receive'),
        db.getItemsWithKeys('formDrafts'),
        db.getItemsExtended('coinjoinAccounts'),
        db.getItemByPK('coinjoinDebugSettings', 'debug'),
        db.getItemsWithKeys('tokenManagement'),
        db.getItemByPK('persistentDeviceData', 'persistentDeviceData'),
        db.getItemByPK('connect', 'connect'),
        db.getItemsExtended('explorer'),
        db.getItemByPK('bioAuth', 'bioAuth'),
        db.getItemByPK('firmware', 'firmware'),
        db.getItemByPK('suiteSyncSettings', 'suiteSyncSettings'),
        db.getItemsWithKeys('suiteSyncOwners'),
        db.getItemByPK('suiteSyncQuotaManager', 'suiteSyncQuotaManager'),
        db.getItemByPK('featureFeedback', 'featureFeedback'),
        db.getItemByPK('discreetMode', 'discreetMode'),
        db.getItemByPK('debug', 'debug'),
        db.getItemsWithKeys('earnOnboarding'),
    ]);

    return {
        suiteSettings,
        walletSettings,
        devices,
        thp,
        bluetooth,
        accounts,
        txs,
        phishing,
        phishingMetadata,
        graph,
        tradingTrades,
        historicRates,
        sendFormDrafts,
        receive,
        formDrafts,
        analytics,
        metadata,
        messageSystem,
        backendSettings,
        coinjoinAccounts,
        coinjoinDebugSettings,
        tokenManagement,
        persistentDeviceData,
        bioAuth,
        connect,
        explorer,
        firmware,
        suiteSyncSettings,
        suiteSyncOwners,
        suiteSyncQuotaManager,
        featureFeedback,
        discreetMode,
        debug,
        earnOnboarding,
    } as const;
};
