"project_id": 383255
"base_path": "../suite-data/files/translations"
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true
files: [
  {
    "source": "master.json",
    "translation": "%two_letters_code%.json",
    "update_option": "update_as_unapproved",
  }
]
