export default [
    {
        description: '1 input, 1 output, no change',
        request: {
            basePath: [44, 0, 5],
            changeAddress: '1CrwjoKxvdbAnPcGzYjpvZ4no4S71neKXT',
            changeId: 0,
            dustThreshold: 546,
            feeRate: '10',
            height: 100,
            utxos: [
                {
                    addressPath: [3, 4],
                    coinbase: false,
                    height: 100,
                    index: 0,
                    own: true,
                    transactionHash: 'b4dc0ffeee',
                    tsize: 0,
                    value: '102300',
                    vsize: 0,
                },
            ],
            outputs: [
                {
                    address: 'replace-me',
                    amount: '100000',
                    type: 'complete',
                },
            ],
        },
        result: {
            'p2pkh-p2pkh': { bytes: 194 },
            'p2pkh-p2sh': { bytes: 192 },
            'p2pkh-p2tr': { bytes: 203 },
            'p2pkh-p2wpkh': { bytes: 191 },
            'p2pkh-p2wsh': { bytes: 203 },
            'p2sh-p2pkh': { bytes: 137 },
            'p2sh-p2sh': { bytes: 135 },
            'p2sh-p2tr': { bytes: 146 },
            'p2sh-p2wpkh': { bytes: 134 },
            'p2sh-p2wsh': { bytes: 146 },
            'p2tr-p2pkh': { bytes: 103 },
            'p2tr-p2sh': { bytes: 101 },
            'p2tr-p2tr': { bytes: 112 },
            'p2tr-p2wpkh': { bytes: 100 },
            'p2tr-p2wsh': { bytes: 112 },
            'p2wpkh-p2pkh': { bytes: 113 },
            'p2wpkh-p2sh': { bytes: 111 },
            'p2wpkh-p2tr': { bytes: 122 },
            'p2wpkh-p2wpkh': { bytes: 110 },
            'p2wpkh-p2wsh': { bytes: 122 },
        },
    },
    {
        description: '1 input, 1 output, 1 change',
        request: {
            basePath: [44, 0, 5],
            changeAddress: '1CrwjoKxvdbAnPcGzYjpvZ4no4S71neKXT',
            changeId: 0,
            dustThreshold: 546,
            feeRate: '10',
            height: 100,
            utxos: [
                {
                    addressPath: [3, 4],
                    coinbase: false,
                    height: 100,
                    index: 0,
                    own: true,
                    transactionHash: 'b4dc0ffeee',
                    tsize: 0,
                    value: '202300',
                    vsize: 0,
                },
            ],
            outputs: [
                {
                    address: 'replace-me',
                    amount: '100000',
                    type: 'complete',
                },
            ],
        },
        result: {
            'p2pkh-p2pkh': { bytes: 228 },
            'p2pkh-p2sh': { bytes: 226 },
            'p2pkh-p2tr': { bytes: 237 },
            'p2pkh-p2wpkh': { bytes: 225 },
            'p2pkh-p2wsh': { bytes: 237 },
            'p2sh-p2pkh': { bytes: 169 },
            'p2sh-p2sh': { bytes: 167 },
            'p2sh-p2tr': { bytes: 178 },
            'p2sh-p2wpkh': { bytes: 166 },
            'p2sh-p2wsh': { bytes: 178 },
            'p2tr-p2pkh': { bytes: 146 },
            'p2tr-p2sh': { bytes: 144 },
            'p2tr-p2tr': { bytes: 155 },
            'p2tr-p2wpkh': { bytes: 143 },
            'p2tr-p2wsh': { bytes: 155 },
            'p2wpkh-p2pkh': { bytes: 144 },
            'p2wpkh-p2sh': { bytes: 142 },
            'p2wpkh-p2tr': { bytes: 153 },
            'p2wpkh-p2wpkh': { bytes: 141 },
            'p2wpkh-p2wsh': { bytes: 153 },
        },
    },
    {
        description: '2 inputs, 1 output, 1 change',
        request: {
            basePath: [44, 0, 5],
            changeAddress: '1CrwjoKxvdbAnPcGzYjpvZ4no4S71neKXT',
            changeId: 0,
            dustThreshold: 546,
            feeRate: '10',
            height: 100,
            utxos: [
                {
                    addressPath: [3, 4],
                    coinbase: false,
                    height: 100,
                    index: 0,
                    own: true,
                    transactionHash: 'b4dc0ffeee',
                    tsize: 0,
                    value: '100000',
                    vsize: 0,
                },
                {
                    addressPath: [4, 5],
                    coinbase: false,
                    height: 100,
                    index: 1,
                    own: true,
                    transactionHash: 'b4dc0ffeee',
                    tsize: 0,
                    value: '50000',
                    vsize: 0,
                },
            ],
            outputs: [
                {
                    address: 'replace-me',
                    amount: '100000',
                    type: 'complete',
                },
            ],
        },
        result: {
            'p2pkh-p2pkh': { bytes: 378 },
            'p2pkh-p2sh': { bytes: 376 },
            'p2pkh-p2tr': { bytes: 387 },
            'p2pkh-p2wpkh': { bytes: 375 },
            'p2pkh-p2wsh': { bytes: 387 },
            'p2sh-p2pkh': { bytes: 261 },
            'p2sh-p2sh': { bytes: 259 },
            'p2sh-p2tr': { bytes: 270 },
            'p2sh-p2wpkh': { bytes: 258 },
            'p2sh-p2wsh': { bytes: 270 },
            'p2tr-p2pkh': { bytes: 204 },
            'p2tr-p2sh': { bytes: 202 },
            'p2tr-p2tr': { bytes: 213 },
            'p2tr-p2wpkh': { bytes: 201 },
            'p2tr-p2wsh': { bytes: 213 },
            'p2wpkh-p2pkh': { bytes: 213 },
            'p2wpkh-p2sh': { bytes: 211 },
            'p2wpkh-p2tr': { bytes: 222 },
            'p2wpkh-p2wpkh': { bytes: 210 },
            'p2wpkh-p2wsh': { bytes: 222 },
        },
    },
];
