export type RouterApp =
    | 'start'
    | 'dashboard'
    | 'earn'
    | 'earn-yield'
    | 'earn-staking'
    | 'version'
    | 'bridge-requested'
    | 'bridge'
    | 'bridge-deprecated'
    | 'connect-popup'
    | 'udev'
    | 'switch-device'
    | 'onboarding'
    | 'password-manager'
    | 'settings'
    | 'recovery'
    | 'backup'
    | 'firmware'
    | 'firmware-type'
    | 'firmware-custom'
    | 'create-multi-share-backup'
    | 'create-wallet-backup'
    | 'wallet'
    | 'notifications'
    // A meta route name as a fallback when no route matches the URL path pattern. Not declared in `routes`, but in RouterAppWithParams
    | 'unknown';
