/* eslint-disable no-console */

import { createPrivateKey } from 'crypto';
import * as fs from 'fs-extra';
import * as jws from 'jws';
import { join, resolve } from 'path';

import {
    JWS_RELEASES_FILENAME_LOCAL,
    JWS_RELEASES_FILENAME_REMOTE,
    JWS_SIGN_ALGORITHM,
    VERSION,
} from '../src/constants';

const RELEASES_FILENAME = `releases.v${VERSION}.json`;
const PACKAGE_ROOT = resolve(__dirname, '..'); // firmware-release-config
const RELEASE_PATH = join(PACKAGE_ROOT, 'releases', RELEASES_FILENAME);

const DEV_PRIVATE_KEY = `
-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIEGiURJVYqYlJZZ5qPFGdJaHCagzTCVNomWcp6yS8P0WoAoGCCqGSM49
AwEHoUQDQgAEEKjWdvv8SJm/UN2lXoEXl3ID35b/hsz3etxANvUgLQ4r0eEhqVUE
L5l+dRMgEv4Ycvr3UEcMkSFRPoA8ktxX1A==
-----END EC PRIVATE KEY-----
`;

const getPrivateKey = () => {
    // Only CI jobs flagged with "codesign", sign firmware release config by production private key. All other branches use development key.
    // The isCodesignBuild() util cannot be used here because the lib is not built at this point. Building libs would make the release script slower.
    if (process.env.IS_CODESIGN_BUILD !== 'true') {
        console.log('Signing releases using develop private key!');
        const privateKey = createPrivateKey(DEV_PRIVATE_KEY);

        return privateKey;
    }

    console.log('Signing releases using production private key!');

    const privateKey = process.env.JWS_PRIVATE_KEY_ENV; // available on GitHub

    if (!privateKey) {
        throw Error('Missing private key!');
    }

    return privateKey;
};

const signRelease = () => {
    console.log('Creating a JWS...');

    const release = fs.readFileSync(RELEASE_PATH, 'utf-8');

    const jwsReleases = jws.sign({
        header: { alg: JWS_SIGN_ALGORITHM },
        payload: release,
        secret: getPrivateKey(),
    });

    console.log('JWS created!');

    return jwsReleases;
};

// Save JWS to files/releases.v1.jws for publishing on data.trezor.io
const saveReleasesJws = (jwsReleases: string) => {
    console.log('saveReleasesJws');
    const destination = join(PACKAGE_ROOT, 'files', JWS_RELEASES_FILENAME_REMOTE);
    try {
        fs.outputFileSync(destination, jwsReleases);
        console.log(`JWS saved to ${destination}!`);
    } catch (err) {
        throw new Error(`Failed to save JWS to ${destination}: ${err.message}`);
    }
};

// Save JWS to files/releases.v1.ts for bundling in the app and using as local fallback when offline
const saveReleaseTs = (jwsReleases: string) => {
    const releasesTs = `// Autogenerated by sign-release script.
export const jws = \`${jwsReleases}\`;
`;

    const destination = join(PACKAGE_ROOT, 'files', JWS_RELEASES_FILENAME_LOCAL);
    try {
        fs.outputFileSync(destination, releasesTs);
        console.log(`JWS saved to ${destination}!`);
    } catch (err) {
        throw new Error(`Failed to save TypeScript file to ${destination}: ${err.message}`);
    }
};

try {
    const releasesJws = signRelease();

    saveReleasesJws(releasesJws);
    saveReleaseTs(releasesJws);

    console.log('Signing process completed successfully.');
} catch (error) {
    console.error(`Error during signing process: ${error.message}`);
    process.exit(1);
}
