export type SvgImage = keyof typeof SVG_IMAGES;

export const SVG_IMAGES = {
    UNI_ERROR: 'uni-error.svg',
    UNI_SUCCESS: 'uni-success.svg',
    UNI_WARNING: 'uni-warning.svg',
    BRIDGE_CHECK_TREZOR_TT: 'bridge-check-trezor-tt.svg',
    DEVICE_CONFIRM_TREZOR_T1: 'device-confirm-trezor-t1.svg',
    DEVICE_CONFIRM_TREZOR_TT: 'device-confirm-trezor-tt.svg',
    DEVICE_CONFIRM_TREZOR_TR: 'device-confirm-trezor-tr.svg',
    SPINNER: 'spinner.svg',
    DEVICE_ANOTHER_SESSION: 'device-another-session.svg',
    CONNECT_DEVICE: 'connect-device.svg',
    ERROR_404: 'error-404.svg',
    EARLY_ACCESS: 'early-access.svg',
    EARLY_ACCESS_DISABLE: 'early-access-disable.svg',
    INVITY_LOGO: 'invity-logo.svg',
    COINMARKET_AVATAR: 'coinmarket-avatar.svg',
    COINMARKET_SUCCESS: 'coinmarket-success.svg',
    COINMARKET_WAITING: 'coinmarket-waiting.svg',
    WARNING: 'warning.svg',
    USER_FOCUS: 'user-focus.svg',
    ONBOARDING_WELCOME_BG: 'onboarding-welcome-bg.svg',
    HOURGLASS: 'hourglass.svg',
    WATCH: 'watch.svg',
    TREZOR_PATTERN: 'trezor-pattern.svg',
    HOLLOW_APP_LOGO: 'hollow-app-logo.svg',
    APP_STORE_BADGE: 'app-store-badge.svg',
    PLAY_STORE_BADGE: 'play-store-badge.svg',
    APP_STORE_TITLE: 'app-store-title.svg',
    PLAY_STORE_TITLE: 'play-store-title.svg',
} as const;

export type PngImage = keyof typeof PNG_IMAGES;

export const PNG_IMAGES = {
    CLOUDY: 'cloudy.png',
    CLOUDY_2x: 'cloudy@2x.png',
    BACKUP: 'backup.png',
    BACKUP_2x: 'backup@2x.png',
    CHECK_SHIELD: 'check-shield.png',
    CHECK_SHIELD_2x: 'check-shield@2x.png',
    CLOCK: 'clock.png',
    CLOCK_2x: 'clock@2x.png',
    COINS: 'coins.png',
    COINS_2x: 'coins@2x.png',
    ERROR: 'error.png',
    ERROR_2x: 'error@2x.png',
    EXTRA_INFO: 'extra-info.png',
    EXTRA_INFO_2x: 'extra-info@2x.png',
    FIRMWARE: 'firmware.png',
    FIRMWARE_2x: 'firmware@2x.png',
    FOLDER: 'folder.png',
    FOLDER_2x: 'folder@2x.png',
    KEY: 'key.png',
    KEY_2x: 'key@2x.png',
    PIN: 'pin.png',
    PIN_2x: 'pin@2x.png',
    PIN_LOCKED: 'pin-locked.png',
    PIN_LOCKED_2x: 'pin-locked@2x.png',
    RECOVERY: 'recovery.png',
    RECOVERY_2x: 'recovery@2x.png',
    UNDERSTAND: 'understand.png',
    UNDERSTAND_2x: 'understand@2x.png',
    WALLET: 'wallet.png',
    WALLET_2x: 'wallet@2x.png',
    DONT_DISCONNECT_TREZOR_TT: 'dont-disconnect-trezor-tt.png',
    DONT_DISCONNECT_TREZOR_TT_2x: 'dont-disconnect-trezor-tt@2x.png',
    DONT_DISCONNECT_TREZOR_T1: 'dont-disconnect-trezor-t1.png',
    DONT_DISCONNECT_TREZOR_T1_2x: 'dont-disconnect-trezor-t1@2x.png',
    DONT_DISCONNECT_TREZOR_TR: 'dont-disconnect-trezor-tr.png',
    DONT_DISCONNECT_TREZOR_TR_2x: 'dont-disconnect-trezor-tr@2x.png',
    TREZOR_T1: 'trezor-t1.png',
    TREZOR_T1_2x: 'trezor-t1.png',
    TREZOR_TT: 'trezor-tt.png',
    TREZOR_TT_2x: 'trezor-tt.png',
    TREZOR_TR: 'trezor-tr.png',
    TREZOR_TR_2x: 'trezor-tr.png',
} as const;
