export const supportedFiatCurrenciesList = [
    { code: 'aed', label: 'United Arab Emirates Dirham' },
    { code: 'amd', label: 'Armenian Dram' },
    { code: 'ars', label: 'Argentine Peso' },
    { code: 'aud', label: 'Australian Dollar' },
    { code: 'azn', label: 'Azerbaijan Manat' },
    { code: 'bdt', label: 'Bangladeshi Taka' },
    { code: 'bgn', label: 'Bulgarian Lev' },
    { code: 'bhd', label: 'Bahraini Dinar' },
    { code: 'brl', label: 'Brazilian Real' },
    { code: 'cad', label: 'Canadian Dollar' },
    { code: 'chf', label: 'Swiss Franc' },
    { code: 'clp', label: 'Chilean Peso' },
    { code: 'cny', label: 'Chinese Yuan' },
    { code: 'cop', label: 'Colombian Peso' },
    { code: 'crc', label: 'Costa Rican Colón' },
    { code: 'czk', label: 'Czech Koruna' },
    { code: 'dkk', label: 'Danish Krone' },
    { code: 'dop', label: 'Dominican Peso' },
    { code: 'dzd', label: 'Algerian Dinar' },
    { code: 'egp', label: 'Egyptian Pound' },
    { code: 'eur', label: 'Euro' },
    { code: 'gbp', label: 'British Pound Sterling' },
    { code: 'gel', label: 'Georgian Lari' },
    { code: 'ghs', label: 'Ghanaian Cedi' },
    { code: 'hkd', label: 'Hong Kong Dollar' },
    { code: 'huf', label: 'Hungarian Forint' },
    { code: 'idr', label: 'Indonesian Rupiah' },
    { code: 'ils', label: 'Israeli Shekel' },
    { code: 'inr', label: 'Indian Rupee' },
    { code: 'isk', label: 'Icelandic Króna' },
    { code: 'jod', label: 'Jordanian Dinar' },
    { code: 'jpy', label: 'Japanese Yen' },
    { code: 'kes', label: 'Kenyan Shilling' },
    { code: 'krw', label: 'South Korean Won' },
    { code: 'kwd', label: 'Kuwaiti Dinar' },
    { code: 'kzt', label: 'Kazakhstani Tenge' },
    { code: 'lkr', label: 'Sri Lankan Rupee' },
    { code: 'mad', label: 'Moroccan Dirham' },
    { code: 'mxn', label: 'Mexican Peso' },
    { code: 'myr', label: 'Malaysian Ringgit' },
    { code: 'ngn', label: 'Nigerian Naira' },
    { code: 'nok', label: 'Norwegian Krone' },
    { code: 'nzd', label: 'New Zealand Dollar' },
    { code: 'omr', label: 'Omani Rial' },
    { code: 'pen', label: 'Peruvian Sol' },
    { code: 'php', label: 'Philippine Peso' },
    { code: 'pln', label: 'Polish Złoty' },
    { code: 'qar', label: 'Qatari Riyal' },
    { code: 'ron', label: 'Romanian Leu' },
    { code: 'rub', label: 'Russian Ruble' },
    { code: 'sar', label: 'Saudi Riyal' },
    { code: 'sek', label: 'Swedish Krona' },
    { code: 'sgd', label: 'Singapore Dollar' },
    { code: 'thb', label: 'Thai Baht' },
    { code: 'tnd', label: 'Tunisian Dinar' },
    { code: 'try', label: 'Turkish Lira' },
    { code: 'twd', label: 'New Taiwan Dollar' },
    { code: 'tzs', label: 'Tanzanian Shilling' },
    { code: 'uah', label: 'Ukrainian Hryvnia' },
    { code: 'ugx', label: 'Ugandan Shilling' },
    { code: 'usd', label: 'United States Dollar' },
    { code: 'uyu', label: 'Uruguayan Peso' },
    { code: 'vnd', label: 'Vietnamese Đồng' },
    { code: 'xaf', label: 'Central African CFA Franc' },
    { code: 'xof', label: 'West African CFA Franc' },
    { code: 'zar', label: 'South African Rand' },
];

export const supportedFiatCurrenciesMap = new Map<
    string,
    (typeof supportedFiatCurrenciesList)[number]
>(supportedFiatCurrenciesList.map(currency => [currency.code, currency]));
