import { colors, THEME, intermediaryTheme, SuiteThemeColors } from './config/colors';

export * as variables from './config/variables';
export * as animations from './config/animations';
export { motionAnimation, motionEasing } from './config/motion';
export * from './support/ThemeProvider';

export * from './components/Badge/Badge';
export * from './components/buttons/Button/Button';
export * from './components/buttons/IconButton/IconButton';
export * from './components/buttons/TextButton/TextButton';
export * from './components/buttons/ButtonGroup/ButtonGroup';
export * from './components/buttons/PinButton/PinButton';
export * from './components/buttons/TooltipButton/TooltipButton';
export * from './components/assets/Flag/Flag';
export * from './components/Dropdown/Dropdown';
export * from './components/form/Input/Input';
export * from './components/form/Textarea/Textarea';
export * from './components/form/Select/Select';
export { Checkbox, type CheckboxProps } from './components/form/Checkbox/Checkbox';
export * from './components/form/Radio/Radio';
export * from './components/form/Range/Range';
export * from './components/form/Switch/Switch';
export * from './components/form/InputStyles';
export * from './components/assets/Icon/Icon';
export * from './components/typography/Heading/Heading';
export * from './components/typography/Paragraph/Paragraph';
export * from './components/typography/Link/Link';
export * from './components/Warning/Warning';
export * from './components/Box/Box';
export * from './components/Card/Card';
export * from './components/ConfirmOnDevice/ConfirmOnDevice';
export * from './components/modals/Modal/Modal';
export * from './components/modals/Modal/Backdrop';
export * from './components/modals/DialogModal/DialogModal';
export * from './components/assets/CoinLogo/CoinLogo';
export * from './components/assets/TrezorLogo/TrezorLogo';
export * from './components/loaders/Spinner/Spinner';
export * from './components/loaders/ProgressBar/ProgressBar';
export * from './components/loaders/ProgressPie/ProgressPie';
export * from './components/loaders/LoadingContent/LoadingContent';
export * from './components/loaders/Stepper/Stepper';
export * from './components/Tooltip/Tooltip';
export * from './components/Timerange/Timerange';
export * from './components/Truncate/Truncate';
export * from './components/form/SelectBar/SelectBar';
export * from './components/Image/Image';
export * from './components/Image/images';
export * from './components/CollapsibleBox/CollapsibleBox';
export * from './components/Passphrase/PassphraseTypeCard';
export * from './components/DataAnalytics';
export * from './components/animations/DeviceAnimation';
export * from './components/animations/LottieAnimation';
export * from './components/Note/Note';

export * from './constants/keyboardEvents';

export { colors, THEME, intermediaryTheme, type SuiteThemeColors };
