import fixtures from './__fixtures__.json';
import {
    EMPTY_ROOT,
    Trie,
    branchHash,
    computeRoot,
    encPrefix,
    fromHex,
    keyHash,
    leafHash,
    provesExistence,
    provesNonexistence,
    recomputeAdd,
    recomputeDelete,
    recomputeUpdate,
    toHex,
} from './trie';
import type { TrieProof } from './trie';

// The fixtures are generated by .context/poc-labeling/trie_ref.py and are the
// SAME vectors the firmware unit test asserts against — so passing here proves
// the Suite trie hashes byte-for-byte identically to the device.

const enc = (s: string) => new TextEncoder().encode(s);

const parseProof = (p: any): TrieProof => ({
    empty: !!p.empty,
    leaf: p.leaf
        ? {
              key_hash: fromHex(p.leaf.key_hash),
              label_type: p.leaf.label_type,
              label_value: fromHex(p.leaf.label_value),
              counter: p.leaf.counter,
          }
        : undefined,
    branch: p.branch
        ? {
              prefix: fromHex(p.branch.prefix),
              prefix_bits: p.branch.prefix_bits,
              child_hash_0: fromHex(p.branch.child_hash_0),
              child_hash_1: fromHex(p.branch.child_hash_1),
          }
        : undefined,
    path: p.path.map((s: any) => ({
        prefix: fromHex(s.prefix),
        prefix_bits: s.prefix_bits,
        sibling_hash: fromHex(s.sibling_hash),
    })),
});

describe('authlabel trie primitives', () => {
    it('matches firmware primitive vectors', () => {
        expect(toHex(EMPTY_ROOT)).toBe(fixtures.empty_root);
        expect(toHex(keyHash(1, enc('key-0')))).toBe(fixtures.primitives['key_hash__1__key-0']);
        expect(toHex(leafHash(keyHash(1, enc('key-0')), 1, enc('label-0'), 0))).toBe(
            fixtures.primitives['leaf_hash__kh0__1__label-0__0'],
        );
        expect(toHex(encPrefix(5, fromHex('ff')))).toBe(fixtures.primitives['enc_prefix__5__ff']);
        expect(
            toHex(
                branchHash(
                    3,
                    fromHex('ab'),
                    new Uint8Array(32).fill(0),
                    new Uint8Array(32).fill(0x11),
                ),
            ),
        ).toBe(fixtures.primitives['branch__3__ab__z32__z32']);
    });
});

describe('authlabel trie proofs (firmware vectors)', () => {
    it('verifies existence proofs and recomputes update/delete', () => {
        fixtures.existence.forEach((c: any) => {
            const kh = keyHash(c.key_type, fromHex(c.key_bytes));
            expect(toHex(kh)).toBe(c.key_hash);
            const proof = parseProof(c.proof);
            expect(provesExistence(proof, kh)).toBe(true);
            expect(toHex(computeRoot(proof))).toBe(c.root);
            expect(
                toHex(
                    recomputeUpdate(
                        proof,
                        kh,
                        c.update.label_type,
                        fromHex(c.update.value),
                        c.update.counter,
                    ),
                ),
            ).toBe(c.update.new_root);
            expect(toHex(recomputeDelete(proof, kh))).toBe(c.delete.new_root);
        });
    });

    it('verifies non-existence proofs and recomputes add', () => {
        fixtures.nonexistence.forEach((c: any) => {
            const kh = keyHash(c.key_type, fromHex(c.key_bytes));
            const proof = parseProof(c.proof);
            expect(provesExistence(proof, kh)).toBe(false);
            expect(provesNonexistence(proof, kh)).toBe(true);
            expect(toHex(computeRoot(proof))).toBe(c.root);
            expect(
                toHex(
                    recomputeAdd(proof, kh, c.add.label_type, fromHex(c.add.value), c.add.counter),
                ),
            ).toBe(c.add.new_root);
        });
    });
});

describe('authlabel trie builder', () => {
    it('rebuilds the fixture trie root and produces verifiable proofs', () => {
        const t = new Trie();
        for (let i = 0; i < 6; i++) {
            const kh = keyHash((i % 5) + 1, enc(`key-${i}`));
            t.set(kh, 1, enc(`label-${i}`), i);
        }
        expect(toHex(t.root())).toBe(fixtures.root);

        // existence proof for a present key round-trips to the same root
        const present = keyHash(3, enc('key-2'));
        const p1 = t.proof(present);
        expect(provesExistence(p1, present)).toBe(true);
        expect(toHex(computeRoot(p1))).toBe(fixtures.root);

        // non-existence proof for an absent key verifies
        const absent = keyHash(1, enc('key-100'));
        const p2 = t.proof(absent);
        expect(provesNonexistence(p2, absent)).toBe(true);
        expect(toHex(computeRoot(p2))).toBe(fixtures.root);
    });

    it('add then delete returns to the original root', () => {
        const t = new Trie();
        t.set(keyHash(5, enc('a')), 1, enc('A'), 1);
        t.set(keyHash(5, enc('b')), 1, enc('B'), 2);
        const before = toHex(t.root());
        const kh = keyHash(5, enc('c'));
        t.set(kh, 1, enc('C'), 3);
        expect(toHex(t.root())).not.toBe(before);
        t.delete(kh);
        expect(toHex(t.root())).toBe(before);
    });
});
