export const GLOBAL_RECEIVE_LIST_HEIGHT = 464;
export const GLOBAL_RECEIVE_LIST_MIN_HEIGHT = 260;

const GLOBAL_RECEIVE_MODAL_CHROME_HEIGHT = 206;

export const GLOBAL_RECEIVE_MODAL_HEIGHT =
    GLOBAL_RECEIVE_LIST_HEIGHT + GLOBAL_RECEIVE_MODAL_CHROME_HEIGHT;
