/* eslint-disable no-console */
/* eslint-disable import/no-extraneous-dependencies */

import chalk from 'chalk';
import fs from 'fs';
import path from 'path';
import prettier from 'prettier';
import { optimize } from 'svgo';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const illustrationsFilePath = './src/illustrations.ts';

const assetTypesConfig = [
    {
        name: 'illustrations',
        dirname: 'assets',
        typeName: 'IllustrationName',
    },
];

// https://github.com/svg/svgo#built-in-plugins
/**
 * @type {import('svgo').Config}
 */
const svgoConfig = {
    multipass: true,
    js2svg: {
        indent: 2,
        pretty: true,
    },
    plugins: [
        {
            name: 'preset-default',
            params: {
                overrides: {
                    // Preserve class attributes for color slot targeting
                    removeUnknownsAndDefaults: {
                        keepRoleAttr: true,
                    },
                },
            },
        },
        'removeDimensions',
        'removeRasterImages',
        'removeScripts',
    ],
};

const optimizeSvgAssets = assetsDirname => {
    const assetsDir = path.join(__dirname, assetsDirname);
    const assetFileNames = fs.readdirSync(assetsDir);

    return assetFileNames
        .filter(fileName => fileName.endsWith('.svg'))
        .map(fileName => ({
            fileName,
            content: fs.readFileSync(path.resolve(assetsDir, fileName)).toString(),
        }))
        .map(({ fileName, content }) => ({
            fileName,
            content: optimize(content, svgoConfig).data,
        }));
};

const getOptimizedAssetTypes = assetTypesArray =>
    assetTypesArray.map(config => ({
        ...config,
        assets: optimizeSvgAssets(config.dirname),
    }));

const generateFileContent = assetTypesArray => {
    const mappedAssetTypes = assetTypesArray.map(
        ({ name, assets, dirname, typeName }) => `
           export const ${name} = {
            ${assets
                .map(
                    ({ fileName }) =>
                        `${fileName.replace('.svg', '')}: require('../${dirname}/${fileName}')`,
                )
                .join(',')}
        } as const;
        export type ${typeName} = keyof typeof ${name};
       `,
    );

    return `
    // !!! IMPORTANT: This file is autogenerated !!!
    // Run \`yarn generate-illustrations\` to regenerate.

    ${mappedAssetTypes.join('')}
    `;
};

const writeOptimizedAssets = assetTypesArray => {
    assetTypesArray.forEach(({ assets, dirname }) => {
        assets.forEach(({ fileName, content }) =>
            fs.writeFileSync(path.resolve(dirname, fileName), content),
        );
    });
};

const generateFileForAssetTypes = async (assetTypesArray, outputFilePath) => {
    const assetTypes = getOptimizedAssetTypes(assetTypesArray);

    const fileContent = generateFileContent(assetTypes);

    const prettierConfigPath = await prettier.resolveConfigFile();
    const prettierConfig = {
        ...(await prettier.resolveConfig(prettierConfigPath)),
        parser: 'babel-ts',
    };

    const formattedFileContent = await prettier.format(fileContent, prettierConfig);

    fs.writeFileSync(path.resolve(outputFilePath), formattedFileContent);

    writeOptimizedAssets(assetTypes);
};

(async () => {
    console.log('Generating illustrations TS file...');
    await generateFileForAssetTypes(assetTypesConfig, illustrationsFilePath);
    console.log(chalk.green('Illustrations TS file generated successfully'));
})();
