/* eslint-disable global-require */
export const COINS = {
    ada: require('../../../images/coins/ada.svg'),
    bch: require('../../../images/coins/bch.svg'),
    btc: require('../../../images/coins/btc.svg'),
    test: require('../../../images/coins/btctestnet.svg'),
    regtest: require('../../../images/coins/btctestnet.svg'),
    btg: require('../../../images/coins/btg.svg'),
    dash: require('../../../images/coins/dash.svg'),
    dgb: require('../../../images/coins/dgb.svg'),
    doge: require('../../../images/coins/doge.svg'),
    dsol: require('../../../images/coins/dsol.svg'),
    etc: require('../../../images/coins/etc.svg'),
    eth: require('../../../images/coins/eth.svg'),
    ltc: require('../../../images/coins/ltc.svg'),
    nmc: require('../../../images/coins/nmc.svg'),
    tada: require('../../../images/coins/tada.svg'),
    tgor: require('../../../images/coins/tgor.svg'),
    tsep: require('../../../images/coins/tsep.svg'),
    txrp: require('../../../images/coins/txrp.svg'),
    vtc: require('../../../images/coins/vtc.svg'),
    xrp: require('../../../images/coins/xrp.svg'),
    zec: require('../../../images/coins/zec.svg'),
    sol: require('../../../images/coins/sol.svg'),
};
