skip_docs

# Paths
APP_GRADLE_PATH = File.join(ANDROID_PATH, 'app/build.gradle').freeze

platform :android do

  desc "Android: Increments internal build number and version number"
  private_lane :fetch_and_bump_play_version do
    google_play_json_key_file = CredentialsManager::AppfileConfig.try_fetch_value(:json_key_file)
    package_name = CredentialsManager::AppfileConfig.try_fetch_value(:package_name)

    previous_build_number = google_play_track_version_codes(
      package_name: package_name,
      track: "internal",
      json_key: google_play_json_key_file,
    )[0]

    android_set_version_code(gradle_file: APP_GRADLE_PATH, version_code: previous_build_number + 1)
    android_set_version_name(gradle_file: APP_GRADLE_PATH, version_name: VERSION)
  end

  private_lane :fetch_and_bump_firebase_version do
    google_play_json_key_file = CredentialsManager::AppfileConfig.try_fetch_value(:json_key_file)
    latest_release = firebase_app_distribution_get_latest_release(
      app: ANDROID_FIREBASE_APP_ID,
      service_credentials_file: google_play_json_key_file,
    )

    # when there are no Firebase releases yet
    unless latest_release.nil?
      android_set_version_code(gradle_file: APP_GRADLE_PATH, version_code: latest_release[:buildVersion].to_i + 1)
    end
    android_set_version_name(gradle_file: APP_GRADLE_PATH, version_name: VERSION)
  end

  desc "Build and upload the app to Google Play Store."
  private_lane :deploy_android_play_store do |options|
    productFlavor = options[:flavor]

    gradle(task: 'clean', project_dir: ANDROID_PATH)
    fetch_and_bump_play_version

    gradle(
      task: 'bundle',
      flavor: productFlavor,
      build_type: 'Release',
      project_dir: ANDROID_PATH
    )

    # Upload Android App Bundle to PlayStore like Internal testing Release
    upload_to_play_store(
      track: 'internal',
      # set as "draft" to complete the release at some other time in PlayStore
      release_status: 'draft', # <http://docs.fastlane.tools/actions/upload_to_play_store/#parameters>
      skip_upload_apk: true
    )

  end

  desc "Deploy staging build to Google Play Store."
  lane :staging do |options|
    deploy_android_play_store(flavor: "firebaseStaging")
  end

  desc "Deploy production build to Google Play Store."
  lane :production do |options|
    deploy_android_play_store(flavor: "prod")
  end

  desc "Build and deploy the app to Firebase App Distribution for develop build."
  lane :develop do |options|
    google_play_json_key_file = CredentialsManager::AppfileConfig.try_fetch_value(:json_key_file)

    gradle(task: 'clean', project_dir: ANDROID_PATH)
    fetch_and_bump_firebase_version

    gradle(
      task: 'assemble',
      flavor: 'FirebaseDevelop',
      build_type: 'Release',
      project_dir: ANDROID_PATH
    )

    # find apk path
    output_path = File.join(ANDROID_PATH, 'app/build/outputs/apk/firebaseDevelop/release/').freeze
    output_json_path = output_path + "output-metadata.json"
    build_output = load_json(json_path: output_json_path)
    elements = build_output["elements"][0]
    apk_path = output_path + elements["outputFile"]

    firebase_app_distribution(
        app: ANDROID_FIREBASE_APP_ID,
        apk_path: apk_path,
        service_credentials_file: google_play_json_key_file,
        release_notes: CHANGELOG,
        groups: "develop-testers",
        debug: true
    )
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
