"project_id": 383255
"base_path": "./"
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true
files:
  [
    {
      "source": "src/(web|shared)Messages.json",
      "translation": "translations/web/%two_letters_code%.json",
      "update_option": "update_as_unapproved",
    },
    {
      "source": "src/(mobile|shared)Messages.json",
      "translation": "translations/mobile/%two_letters_code%.json",
      "update_option": "update_as_unapproved",
    },
  ]
