/* eslint-disable global-require */

// !!! IMPORTANT: This file is autogenerated !!!
// If you want to add of modify icons please read README.md to find out how to do it

export const icons = {
    accounts: require('../assets/icons/accounts.svg'),
    action: require('../assets/icons/action.svg'),
    actionHorizontal: require('../assets/icons/actionHorizontal.svg'),
    backspace: require('../assets/icons/backspace.svg'),
    biometric: require('../assets/icons/biometric.svg'),
    calendar: require('../assets/icons/calendar.svg'),
    check: require('../assets/icons/check.svg'),
    chevronDown: require('../assets/icons/chevronDown.svg'),
    chevronLeft: require('../assets/icons/chevronLeft.svg'),
    chevronRight: require('../assets/icons/chevronRight.svg'),
    chevronUp: require('../assets/icons/chevronUp.svg'),
    close: require('../assets/icons/close.svg'),
    closeCircle: require('../assets/icons/closeCircle.svg'),
    discover: require('../assets/icons/discover.svg'),
    eject: require('../assets/icons/eject.svg'),
    eyeSlash: require('../assets/icons/eyeSlash.svg'),
    eyeglasses: require('../assets/icons/eyeglasses.svg'),
    flag: require('../assets/icons/flag.svg'),
    ghost: require('../assets/icons/ghost.svg'),
    hiddenWallet: require('../assets/icons/hiddenWallet.svg'),
    home: require('../assets/icons/home.svg'),
    label: require('../assets/icons/label.svg'),
    lock: require('../assets/icons/lock.svg'),
    notifications: require('../assets/icons/notifications.svg'),
    palette: require('../assets/icons/palette.svg'),
    paper: require('../assets/icons/paper.svg'),
    placeholder: require('../assets/icons/placeholder.svg'),
    plus: require('../assets/icons/plus.svg'),
    prices: require('../assets/icons/prices.svg'),
    qrCode: require('../assets/icons/qrCode.svg'),
    question: require('../assets/icons/question.svg'),
    receive: require('../assets/icons/receive.svg'),
    reject: require('../assets/icons/reject.svg'),
    search: require('../assets/icons/search.svg'),
    send: require('../assets/icons/send.svg'),
    settings: require('../assets/icons/settings.svg'),
    standardWallet: require('../assets/icons/standardWallet.svg'),
    tor: require('../assets/icons/tor.svg'),
    trade: require('../assets/icons/trade.svg'),
    trezorT: require('../assets/icons/trezorT.svg'),
    warningCircle: require('../assets/icons/warningCircle.svg'),
} as const;
export type IconName = keyof typeof icons;

export const cryptoIcons = {
    bch: require('../assets/cryptoIcons/bch.svg'),
    btc: require('../assets/cryptoIcons/btc.svg'),
    btg: require('../assets/cryptoIcons/btg.svg'),
    dash: require('../assets/cryptoIcons/dash.svg'),
    dgb: require('../assets/cryptoIcons/dgb.svg'),
    doge: require('../assets/cryptoIcons/doge.svg'),
    etc: require('../assets/cryptoIcons/etc.svg'),
    eth: require('../assets/cryptoIcons/eth.svg'),
    gnt: require('../assets/cryptoIcons/gnt.svg'),
    ltc: require('../assets/cryptoIcons/ltc.svg'),
    name: require('../assets/cryptoIcons/name.svg'),
    test: require('../assets/cryptoIcons/test.svg'),
    trop: require('../assets/cryptoIcons/trop.svg'),
    txrp: require('../assets/cryptoIcons/txrp.svg'),
    vtc: require('../assets/cryptoIcons/vtc.svg'),
    xrp: require('../assets/cryptoIcons/xrp.svg'),
    zec: require('../assets/cryptoIcons/zec.svg'),
} as const;
export type CryptoIconName = keyof typeof cryptoIcons;

export const flagIcons = {
    cz: require('../assets/flags/cz.svg'),
} as const;
export type FlagIconName = keyof typeof flagIcons;
