import { IconType, CoinType } from '../support/types';

export const SCREEN_SIZE = {
    UNAVAILABLE: '260px',
    SM: '576px', // phones
    MD: '768px', // tablets
    LG: '992px', // laptops/desktops
    XL: '1200px', // extra Large laptops/desktops
} as const;

export const LAYOUT_SIZE = {
    MENU_SECONDARY_WIDTH: '300px',
    GUIDE_PANEL_WIDTH: '350px',
} as const;

export const Z_INDEX = {
    MODAL: 10000,
    NAVIGATION_BAR: 30,
    GUIDE_PANEL: 29,
    GUIDE_PANEL_BESIDE_MODAL: 10001,
    BETA_BADGE: 13,
    GUIDE_BUTTON: 10,
    DROPDOWN_MENU: 10002, // should lay above GUIDE_PANEL
} as const;

export const FONT_SIZE = {
    BIG: '18px',
    NORMAL: '16px',
    SMALL: '14px',
    TINY: '12px',
    BUTTON: '14px',
    H1: '36px',
    H2: '24px',
    H3: '20px',
} as const;

export const NEUE_FONT_SIZE = {
    NANO: '10px',
    TINY: '12px',
    SMALL: '14px',
    NORMAL: '16px',
    H1: '24px',
    H2: '20px',
} as const;

export const FONT_WEIGHT = {
    LIGHT: 300,
    REGULAR: 400,
    MEDIUM: 500,
    DEMI_BOLD: 600,
    BOLD: 700,
} as const;

export const FONT_FAMILY = {
    TTHOVES: 'TT Hoves',
} as const;

export const COINS: CoinType[] = [
    'ada',
    'bch',
    'btc',
    'test',
    'btg',
    'dash',
    'dgb',
    'doge',
    'etc',
    'eth',
    'ltc',
    'nmc',
    'trop',
    'txrp',
    'vtc',
    'xrp',
    'zec',
];

export const ICONS: IconType[] = [
    'APP',
    'ARROW_DOWN',
    'ARROW_UP',
    'ARROW_LEFT',
    'ARROW_LEFT_LONG',
    'ARROW_RIGHT',
    'ARROW_RIGHT_LONG',
    'ARTICLE',
    'ATTACHMENT',
    'BROADCAST',
    'CHECK',
    'CHECK_ACTIVE',
    'COIN',
    'COINS',
    'COPY',
    'CROSS',
    'DASHBOARD',
    'DEVICE',
    'EXCHANGE',
    'INFO',
    'INFO_ACTIVE',
    'LOG',
    'LIGHTBULB',
    'MENU',
    'MORE',
    'NON_SUITE',
    'PASSWORDS',
    'PLUS',
    'QR',
    'QUESTION',
    'QUESTION_ACTIVE',
    'RECEIVE',
    'REFRESH',
    'SEARCH',
    'SEND',
    'SETTINGS',
    'SIGN',
    'SIGNATURE',
    'SORT',
    'SUPPORT',
    'TIPS',
    'TRANSACTIONS',
    'TREZOR',
    'WALLET',
    'WALLET_HIDDEN',
    'EXTERNAL_LINK',
    'T1',
    'T2',
    'BACK',
    'SHOW',
    'HIDE',
    'DOWNLOAD',
    'EDIT',
    'WARNING',
    'WARNING_ACTIVE',
    'LABEL',
    'LABEL_ACTIVE',
    'TODO',
    'DISCREET',
    'PIN',
    'BACKUP',
    'COLLAPSE',
    'NOTIFICATION',
    'SHOP',
    'UP',
    'DOWN',
    'CANCEL',
    'GRID',
    'TABLE',
    'ASTERISK',
    'EJECT',
    'RBF',
    'TRANSFER',
    'LOCK',
    'LOCK_ACTIVE',
    'CLOCK',
    'CALENDAR',
    'PDF',
    'CSV',
    'BINARY',
    'IMAGE',
    'MEDIUM',
    'TAG',
    'GAS',
    'DATA',
    'BANK',
    'BUY',
    'CREDIT_CARD',
    'TREZOR_LOGO',
    'FEEDBACK',
    'OS_LINUX',
    'OS_LINUX_ARM64',
    'OS_MAC',
    'OS_WINDOWS',
    'TRADE',
    'TOR',
    'RECOVER',
    'NEW',
    'SEED_SINGLE',
    'SEED_SHAMIR',
    'HOLOGRAM',
    'PACKAGE',
    'VERIFIED',
    'ANCHOR',
    'PENCIL',
    'PENCIL_LINE',
    'KEY',
];
