export const DEVICE_ANIMATION_TYPES = {
    ROTATE: 'ROTATE',
    BOOTLOADER: 'BOOTLOADER',
    BOOTLOADER_TWO_BUTTONS: 'BOOTLOADER_TWO_BUTTONS',
    NORMAL: 'NORMAL',
    HOLOGRAM: 'HOLOGRAM',
    CONNECT_CABLE: 'CONNECT_CABLE',
    CONNECT_BT_INTRO: 'CONNECT_BT_INTRO',
    CONNECT_BT_LOOP: 'CONNECT_BT_LOOP',
    PAIRING_MODE: 'PAIRING_MODE',
} as const;

export type DeviceAnimationType =
    (typeof DEVICE_ANIMATION_TYPES)[keyof typeof DEVICE_ANIMATION_TYPES];
