services:
  trezor-user-env-unix:
    image: ghcr.io/trezor/trezor-user-env:22107ff76993bfd2e0dfb6235c23c32c0665bf1c
    environment:
      - SDL_VIDEODRIVER=dummy
      - XDG_RUNTIME_DIR=/var/tmp
    network_mode: host
  bitcoin-regtest:
    image: ghcr.io/trezor/trezor-user-env-regtest # this is a special image that runs regtest and blockbook
    depends_on:
      - trezor-user-env-unix
    network_mode: service:trezor-user-env-unix
