version: "4.0"
services:
  trezor-user-env-unix:
    image: ghcr.io/trezor/trezor-user-env:c637c2f58e799284f6019481fa0de30457bd6b60
    environment:
      - SDL_VIDEODRIVER=dummy
      - XDG_RUNTIME_DIR=/var/tmp
    ports:
      - "9001:9001"
      - "21325:21325"
      - "21326:21326"

  bitcoin-regtest:
    image: ghcr.io/trezor/trezor-user-env-regtest # this is a special image that runs regtest and blockbook
    depends_on:
      - trezor-user-env-unix
    ports:
      - "50001:50001"
    network_mode: service:trezor-user-env-unix
