services:
  trezor-user-env-unix:
    image: ghcr.io/trezor/trezor-user-env:13f9847c1fc3fa886e1aa04d8f68386931ae8218
    environment:
      - SDL_VIDEODRIVER=dummy
      - XDG_RUNTIME_DIR=/var/tmp
    network_mode: host
    # in case local developement on mac is needed, these ports will be useful
    # ports:
    #   - "9002:9002"
    #   - "9001:9001"
    #   - "21326:21326"
    #   - "21325:21326"
