version: "3.9"
services:
  trezor-user-env-unix:
    image: ghcr.io/trezor/trezor-user-env:4ab0279e7ef628d4548a8ecad38fed8130345c63
    environment:
      - SDL_VIDEODRIVER=dummy
      - XDG_RUNTIME_DIR=/var/tmp
    network_mode: host
