version: "3"
services:
  trezor-user-env-unix:
    image: registry.gitlab.com/satoshilabs/trezor/trezor-user-env/trezor-user-env
    environment:
      - SDL_VIDEODRIVER=dummy
      - XDG_RUNTIME_DIR=/var/tmp
    network_mode: bridge  # this makes docker reuse existing networks
  test-run:
    image: registry.gitlab.com/satoshilabs/trezor/trezor-suite/base:latest
    network_mode: service:trezor-user-env-unix
    working_dir: /trezor-suite
    command: bash -c "docker/wait-for-env.sh && yarn workspace @trezor/integration-tests test:transport"
    volumes:
      - ../:/trezor-suite
