services:
  trezor-user-env-unix:
    image: ghcr.io/trezor/trezor-user-env:4b238368db1e1e710fdabb4eaf210b64b4c5a8ce
    environment:
      - SDL_VIDEODRIVER=dummy
      - XDG_RUNTIME_DIR=/var/tmp
    network_mode: host
  bitcoin-regtest:
    image: ghcr.io/trezor/trezor-user-env-regtest # this is a special image that runs regtest and blockbook
    depends_on:
      - trezor-user-env-unix
    network_mode: service:trezor-user-env-unix
