services:
  trezor-user-env-unix:
    image: ghcr.io/trezor/trezor-user-env:32f7a4dcdc8300497a3c1f37dfb89f3790704741
    environment:
      - SDL_VIDEODRIVER=dummy
      - XDG_RUNTIME_DIR=/var/tmp
    network_mode: host
  bitcoin-regtest:
    image: ghcr.io/trezor/trezor-user-env-regtest # this is a special image that runs regtest and blockbook
    depends_on:
      - trezor-user-env-unix
    network_mode: service:trezor-user-env-unix
  electrum-regtest:
    image: ghcr.io/trezor/electrs:latest
    ports:
      - "50001:50001"
