services:
  trezor-user-env-unix:
    image: ghcr.io/trezor/trezor-user-env:6e4e61bc9da26be6a8b0aa9c368d462d1da53a62
    environment:
      - SDL_VIDEODRIVER=dummy
      - XDG_RUNTIME_DIR=/var/tmp
    network_mode: host
    # in case local developement on mac is needed, these ports will be useful
    # ports:
    #   - "9002:9002"
    #   - "9001:9001"
    #   - "21328:21328"
