services:
  trezor-user-env-unix:
    image: ghcr.io/trezor/trezor-user-env:d699116aef887c0a9094442d0b230e8ff4831dfe
    environment:
      - SDL_VIDEODRIVER=dummy
      - XDG_RUNTIME_DIR=/var/tmp
    network_mode: host
    # in case local developement on mac is needed, these ports will be useful
    # ports:
    #   - "9002:9002"
    #   - "9001:9001"
    #   - "21326:21326"
    #   - "21325:21326"
