version: '3'
services:
  trezor-user-env-unix:
    image: registry.gitlab.com/satoshilabs/trezor/trezor-user-env/trezor-user-env
    environment:
      - SDL_VIDEODRIVER=dummy
      - XDG_RUNTIME_DIR=/var/tmp
    network_mode: bridge # this makes docker reuse existing networks

  electrum-regtest:
    image: ghcr.io/vdovhanych/electrs:latest
    network_mode: service:trezor-user-env-unix

  test-run:
    build:
      context: .
      dockerfile: ./suite/Dockerfile
    depends_on:
      - electrum-regtest
    network_mode: service:trezor-user-env-unix
    environment:
      - NODE_ENV=development
      - LOCAL_USER_ID=$LOCAL_USER_ID
    working_dir: /trezor-suite
    command: bash -c "yarn workspace @trezor/blockchain-link test:integration"
    volumes:
      - ../:/trezor-suite
