services:
  trezor-user-env-unix:
    image: ghcr.io/trezor/trezor-user-env:51efcaf8e2ffd1fc518db7f10fabb7d540c8ccd1
    environment:
      - SDL_VIDEODRIVER=dummy
      - XDG_RUNTIME_DIR=/var/tmp
    volumes:
      - ../:/trezor-suite
    network_mode: host
