version: "3.9"
services:
  trezor-user-env-unix:
    image: ghcr.io/trezor/trezor-user-env
    environment:
      - SDL_VIDEODRIVER=dummy
      - XDG_RUNTIME_DIR=/var/tmp
    network_mode: bridge # this makes docker reuse existing networks
  test-run:
    image: registry.gitlab.com/satoshilabs/trezor/trezor-suite/base:latest
    network_mode: service:trezor-user-env-unix
    working_dir: /trezor-suite
    command: bash -c "yarn workspace @trezor/transport test:e2e"
    volumes:
      - ../:/trezor-suite
