services:
  trezor-user-env-unix:
    image: ghcr.io/trezor/trezor-user-env:97b797fb349737b93a1d2dbe6bda6673dcc9cafb
    environment:
      - SDL_VIDEODRIVER=dummy
      - XDG_RUNTIME_DIR=/var/tmp
    volumes:
      - ../:/trezor-user-env/trezor-suite
    network_mode: host
