version: "3.9"
services:
  trezor-user-env-unix:
    image: ghcr.io/trezor/trezor-user-env:6339d48f1df4f007fe5caee659e4bca3997d480a
    environment:
      - SDL_VIDEODRIVER=dummy
      - XDG_RUNTIME_DIR=/var/tmp
    network_mode: host
  bitcoin-regtest:
    image: ghcr.io/trezor/trezor-user-env-regtest # this is a special image that runs regtest and blockbook
    depends_on:
      - trezor-user-env-unix
    network_mode: service:trezor-user-env-unix
