// !!! IMPORTANT: This file is autogenerated !!!
// If you want to add of modify icons please read README.md to find out how to do it

export const cryptoIcons = {
    ada: require('../cryptoAssets/cryptoIcons/ada.svg'),
    bch: require('../cryptoAssets/cryptoIcons/bch.svg'),
    bnb: require('../cryptoAssets/cryptoIcons/bnb.svg'),
    btc: require('../cryptoAssets/cryptoIcons/btc.svg'),
    btg: require('../cryptoAssets/cryptoIcons/btg.svg'),
    dash: require('../cryptoAssets/cryptoIcons/dash.svg'),
    dgb: require('../cryptoAssets/cryptoIcons/dgb.svg'),
    doge: require('../cryptoAssets/cryptoIcons/doge.svg'),
    dsol: require('../cryptoAssets/cryptoIcons/dsol.svg'),
    etc: require('../cryptoAssets/cryptoIcons/etc.svg'),
    eth: require('../cryptoAssets/cryptoIcons/eth.svg'),
    gnt: require('../cryptoAssets/cryptoIcons/gnt.svg'),
    ltc: require('../cryptoAssets/cryptoIcons/ltc.svg'),
    name: require('../cryptoAssets/cryptoIcons/name.svg'),
    nmc: require('../cryptoAssets/cryptoIcons/nmc.svg'),
    op: require('../cryptoAssets/cryptoIcons/op.svg'),
    pol: require('../cryptoAssets/cryptoIcons/pol.svg'),
    regtest: require('../cryptoAssets/cryptoIcons/regtest.svg'),
    sol: require('../cryptoAssets/cryptoIcons/sol.svg'),
    tada: require('../cryptoAssets/cryptoIcons/tada.svg'),
    test: require('../cryptoAssets/cryptoIcons/test.svg'),
    thol: require('../cryptoAssets/cryptoIcons/thol.svg'),
    tsep: require('../cryptoAssets/cryptoIcons/tsep.svg'),
    txrp: require('../cryptoAssets/cryptoIcons/txrp.svg'),
    vtc: require('../cryptoAssets/cryptoIcons/vtc.svg'),
    xrp: require('../cryptoAssets/cryptoIcons/xrp.svg'),
    zec: require('../cryptoAssets/cryptoIcons/zec.svg'),
} as const;
export type CryptoIconName = keyof typeof cryptoIcons;

export const tokenIcons = {
    cro: require('../cryptoAssets/tokenIcons/cro.svg'),
    dai: require('../cryptoAssets/tokenIcons/dai.svg'),
    erc20: require('../cryptoAssets/tokenIcons/erc20.svg'),
    leo: require('../cryptoAssets/tokenIcons/leo.svg'),
    link: require('../cryptoAssets/tokenIcons/link.svg'),
    okb: require('../cryptoAssets/tokenIcons/okb.svg'),
    shib: require('../cryptoAssets/tokenIcons/shib.svg'),
    uni: require('../cryptoAssets/tokenIcons/uni.svg'),
    usdc: require('../cryptoAssets/tokenIcons/usdc.svg'),
    usdt: require('../cryptoAssets/tokenIcons/usdt.svg'),
    wbtc: require('../cryptoAssets/tokenIcons/wbtc.svg'),
} as const;
export type TokenIconName = keyof typeof tokenIcons;
