// !!! IMPORTANT: This file is autogenerated !!!
// If you want to add of modify icons please read README.md to find out how to do it

export const networkIcons = {
    ada: require('../cryptoAssets/networkIcons/ada.svg'),
    arb: require('../cryptoAssets/networkIcons/arb.svg'),
    avax: require('../cryptoAssets/networkIcons/avax.svg'),
    base: require('../cryptoAssets/networkIcons/base.svg'),
    bch: require('../cryptoAssets/networkIcons/bch.svg'),
    bsc: require('../cryptoAssets/networkIcons/bsc.svg'),
    btc: require('../cryptoAssets/networkIcons/btc.svg'),
    btg: require('../cryptoAssets/networkIcons/btg.svg'),
    dash: require('../cryptoAssets/networkIcons/dash.svg'),
    dgb: require('../cryptoAssets/networkIcons/dgb.svg'),
    doge: require('../cryptoAssets/networkIcons/doge.svg'),
    etc: require('../cryptoAssets/networkIcons/etc.svg'),
    eth: require('../cryptoAssets/networkIcons/eth.svg'),
    ltc: require('../cryptoAssets/networkIcons/ltc.svg'),
    nmc: require('../cryptoAssets/networkIcons/nmc.svg'),
    op: require('../cryptoAssets/networkIcons/op.svg'),
    pol: require('../cryptoAssets/networkIcons/pol.svg'),
    sol: require('../cryptoAssets/networkIcons/sol.svg'),
    trx: require('../cryptoAssets/networkIcons/trx.svg'),
    vtc: require('../cryptoAssets/networkIcons/vtc.svg'),
    xlm: require('../cryptoAssets/networkIcons/xlm.svg'),
    xmr: require('../cryptoAssets/networkIcons/xmr.svg'),
    xrp: require('../cryptoAssets/networkIcons/xrp.svg'),
    xtz: require('../cryptoAssets/networkIcons/xtz.svg'),
    zec: require('../cryptoAssets/networkIcons/zec.svg'),
} as const;
export type NetworkIconName = keyof typeof networkIcons;
