// !!! IMPORTANT: This file is autogenerated !!!
// If you want to add of modify icons please read README.md to find out how to do it

export const networkIcons = {
    ada: require('../cryptoAssets/networkIcons/ada.svg'),
    ada_inverse: require('../cryptoAssets/networkIcons/ada_inverse.svg'),
    arb: require('../cryptoAssets/networkIcons/arb.svg'),
    arb_inverse: require('../cryptoAssets/networkIcons/arb_inverse.svg'),
    base: require('../cryptoAssets/networkIcons/base.svg'),
    base_inverse: require('../cryptoAssets/networkIcons/base_inverse.svg'),
    bsc: require('../cryptoAssets/networkIcons/bsc.svg'),
    bsc_inverse: require('../cryptoAssets/networkIcons/bsc_inverse.svg'),
    btc: require('../cryptoAssets/networkIcons/btc.svg'),
    btc_inverse: require('../cryptoAssets/networkIcons/btc_inverse.svg'),
    eth: require('../cryptoAssets/networkIcons/eth.svg'),
    eth_inverse: require('../cryptoAssets/networkIcons/eth_inverse.svg'),
    op: require('../cryptoAssets/networkIcons/op.svg'),
    op_inverse: require('../cryptoAssets/networkIcons/op_inverse.svg'),
    pol: require('../cryptoAssets/networkIcons/pol.svg'),
    pol_inverse: require('../cryptoAssets/networkIcons/pol_inverse.svg'),
    sol: require('../cryptoAssets/networkIcons/sol.svg'),
    sol_inverse: require('../cryptoAssets/networkIcons/sol_inverse.svg'),
} as const;
export type NetworkIconName = keyof typeof networkIcons;
