// !!! IMPORTANT: This file is autogenerated !!!
// If you want to add of modify icons please read README.md to find out how to do it

export const paymentMethodLogos = {
    applePay: require('../paymentMethods/applePay.webp'),
    googlePay: require('../paymentMethods/googlePay.webp'),
    paypal: require('../paymentMethods/paypal.webp'),
    revolut: require('../paymentMethods/revolut.webp'),
} as const;
export type PaymentMethodLogoName = keyof typeof paymentMethodLogos;
