// Regenerates AUTOGENERATED `paths:` blocks in `.github/workflows/*.yml` from
// the @trezor/* publish dependency graph.
//
// Each generated block is delimited by sentinel markers:
//
//   # >>> AUTOGENERATED:<SENTINEL_NAME> — yarn gen:workflow-paths
//   - "packages/<pkg>/**"
//   ...
//   # <<< AUTOGENERATED:<SENTINEL_NAME>
//
// The set of sentinel names and their root packages is configured in
// `SENTINEL_CONFIGS` below. The generator walks every workflow file, replaces
// each sentinel's body with `computePublishClosure(roots)`, and exits.
//
// In `--check` mode the generator does not write — it exits non-zero if any
// file is out of sync. Wire this into the lint job so drift fails the PR.
//
// Non-package signals (submodules, dockerfiles, build scripts) cannot be
// derived from the dep graph and live in a sibling "Manual additions" block.

import fs from 'node:fs';
import path from 'node:path';

import {
    computePublishClosure,
    createReadWorkspaceDeps,
    listWorkspacePackages,
} from '@trezor/requirements';

const ROOT = path.resolve(import.meta.dirname, '..', '..');
const WORKFLOWS_DIR = path.join(ROOT, '.github', 'workflows');
const readWorkspaceDeps = createReadWorkspaceDeps(ROOT);
const workspaces = listWorkspacePackages(ROOT);

// Kept in sync with `CONNECT_PUBLISH_ROOTS` in
// `scripts/ci/get-connect-dependencies-to-release.ts`. If they diverge,
// either one or both should justify it inline; if they stay identical for
// long enough, extract to a shared module.
const CONNECT_PUBLISH_ROOTS = ['connect', 'connect-web', 'connect-mobile', 'connect-webextension'];

const SENTINEL_CONFIGS: Record<string, { roots: string[] }> = {
    CONNECT_PUBLISH_DEPS: { roots: CONNECT_PUBLISH_ROOTS },
};

const SENTINEL_START_RE = /^(?<indent>\s*)# >>> AUTOGENERATED:(?<name>[A-Z0-9_]+)\b.*$/;

// Resolves each closure entry to its actual workspace location so that
// @trezor/* packages outside `packages/` (e.g. `suite/e2e`) get the right
// glob if they ever land in a closure.
const resolveLocation = (pkg: string): string => {
    const workspace = workspaces.get(`@trezor/${pkg}`);
    if (workspace === undefined) {
        throw new Error(
            `Closure references @trezor/${pkg} but no such workspace exists. Did the package move or get renamed?`,
        );
    }

    return workspace.location;
};

const formatPathLines = (closure: Set<string>, indent: string): string[] =>
    [...closure]
        .map(resolveLocation)
        .sort()
        .map(location => `${indent}- "${location}/**"`);

const regenerate = (content: string, filePath: string): string => {
    const result: string[] = [];

    // While set, we're inside an AUTOGENERATED block: the old body is dropped
    // (the fresh one was already emitted at the start marker) until we hit the
    // matching end marker, which we re-emit and then clear the state.
    let pendingEndMarker: string | null = null;

    for (const line of content.split('\n')) {
        if (pendingEndMarker !== null) {
            if (line === pendingEndMarker) {
                result.push(line);
                pendingEndMarker = null;
            }
            continue;
        }

        const startMatch = line.match(SENTINEL_START_RE);
        if (!startMatch) {
            result.push(line);
            continue;
        }

        const indent = startMatch.groups?.indent ?? '';
        const name = startMatch.groups?.name;
        const config = name === undefined ? undefined : SENTINEL_CONFIGS[name];

        if (!config) {
            throw new Error(
                `Unknown sentinel "${name}" in ${filePath}. Add it to SENTINEL_CONFIGS in scripts/ci/gen-workflow-paths.ts.`,
            );
        }

        const closure = computePublishClosure(config.roots, readWorkspaceDeps);

        result.push(line);
        result.push(...formatPathLines(closure, indent));
        pendingEndMarker = `${indent}# <<< AUTOGENERATED:${name}`;
    }

    if (pendingEndMarker !== null) {
        throw new Error(
            `Sentinel block in ${filePath} has no matching end marker (expected "${pendingEndMarker}").`,
        );
    }

    return result.join('\n');
};

const findWorkflowFiles = (): string[] =>
    fs
        .readdirSync(WORKFLOWS_DIR)
        .filter(name => name.endsWith('.yml') || name.endsWith('.yaml'))
        .map(name => path.join(WORKFLOWS_DIR, name));

const main = () => {
    const checkMode = process.argv.includes('--check');
    const driftedFiles: string[] = [];

    for (const filePath of findWorkflowFiles()) {
        const content = fs.readFileSync(filePath, 'utf-8');
        if (!content.includes('# >>> AUTOGENERATED:')) {
            continue;
        }

        const updated = regenerate(content, filePath);
        if (updated === content) {
            continue;
        }

        if (checkMode) {
            driftedFiles.push(path.relative(ROOT, filePath));
        } else {
            fs.writeFileSync(filePath, updated);
            console.log(`updated ${path.relative(ROOT, filePath)}`);
        }
    }

    if (checkMode && driftedFiles.length > 0) {
        console.error('Workflow path filters are out of date:');
        for (const file of driftedFiles) {
            console.error(`  - ${file}`);
        }
        console.error("\nRun 'yarn gen:workflow-paths' and commit the changes.");
        process.exit(1);
    }
};

main();
