import { NetworkSymbol } from '@suite-common/wallet-config';

import { LegacyNetworkSymbol } from './coins';

export const NETWORK_ICONS: Record<NetworkSymbol | LegacyNetworkSymbol, string> = {
    ada: require('../../images/networks/ada.svg'),
    arb: require('../../images/networks/arb.svg'),
    base: require('../../images/networks/base.svg'),
    bch: require('../../images/networks/bch.svg'),
    bsc: require('../../images/networks/bsc.svg'),
    btc: require('../../images/networks/btc.svg'),
    doge: require('../../images/networks/doge.svg'),
    dsol: require('../../images/networks/dsol.svg'),
    etc: require('../../images/networks/etc.svg'),
    eth: require('../../images/networks/eth.svg'),
    ltc: require('../../images/networks/ltc.svg'),
    op: require('../../images/networks/op.svg'),
    pol: require('../../images/networks/pol.svg'),
    regtest: require('../../images/networks/btc_test.svg'),
    sol: require('../../images/networks/sol.svg'),
    tada: require('../../images/networks/tada.svg'),
    test: require('../../images/networks/btc_test.svg'),
    thol: require('../../images/networks/thol.svg'),
    tsep: require('../../images/networks/tsep.svg'),
    txlm: require('../../images/networks/txlm.svg'),
    txrp: require('../../images/networks/txrp.svg'),
    xrp: require('../../images/networks/xrp.svg'),
    zec: require('../../images/networks/zec.svg'),
    eos: require('../../images/networks/eos.svg'),
    nem: require('../../images/networks/nem.svg'),
    xlm: require('../../images/networks/xlm.svg'),
    xtz: require('../../images/networks/xtz.svg'),
    dash: require('../../images/networks/dash.svg'),
    dgb: require('../../images/networks/dgb.svg'),
    nmc: require('../../images/networks/nmc.svg'),
    vtc: require('../../images/networks/vtc.svg'),
    btg: require('../../images/networks/btg.svg'),
};
