// If you want to add of modify colors, please read README.md to find out more.

import { colorsV2 } from './colorsV2';
import { Elevation } from './elevation';
import { paletteV1 } from './paletteV1';
import { CSSColor } from './types';

type StyledComponentElevationProps = {
    theme: Colors; // this package does not depend on styled-components
    $elevation: Elevation;
};

export const mapElevationToBackgroundToken = ({ $elevation }: { $elevation: Elevation }): Color =>
    `backgroundSurfaceElevation${$elevation === -1 ? 'Negative' : $elevation}`;

export const mapElevationToBackground = ({
    theme,
    $elevation,
}: StyledComponentElevationProps): CSSColor => theme[mapElevationToBackgroundToken({ $elevation })];

export const mapElevationToBorder = ({
    theme,
    $elevation,
}: StyledComponentElevationProps): CSSColor =>
    theme[`borderElevation${$elevation === -1 ? 'Negative' : $elevation}`];

// ---------------------------

const light = {
    transparent: '#00000000',

    // Figma Colors
    backgroundAlertBlueBold: paletteV1.lightAccentBlue600,
    backgroundAlertBlueBoldAlt: paletteV1.lightAccentBlue700,
    backgroundAlertBlueSubtleOnElevationNegative: paletteV1.lightAccentBlue400,
    backgroundAlertBlueSubtleOnElevation0: paletteV1.lightAccentBlue300,
    backgroundAlertBlueSubtleOnElevation1: paletteV1.lightAccentBlue200,
    backgroundAlertBlueSubtleOnElevation2: paletteV1.lightAccentBlue300,
    backgroundAlertPurpleBold: paletteV1.lightAccentPurple600,
    backgroundAlertPurpleBoldAlt: paletteV1.lightAccentPurple700,
    backgroundAlertPurpleSubtleOnElevationNegative: paletteV1.lightAccentPurple400,
    backgroundAlertPurpleSubtleOnElevation0: paletteV1.lightAccentPurple300,
    backgroundAlertPurpleSubtleOnElevation1: paletteV1.lightAccentPurple200,
    backgroundAlertPurpleSubtleOnElevation2: paletteV1.lightAccentPurple300,
    backgroundAlertRedBold: paletteV1.lightAccentRed600,
    backgroundAlertRedBoldAlt: paletteV1.lightAccentRed700,
    backgroundAlertRedSubtleOnElevationNegative: paletteV1.lightAccentRed400,
    backgroundAlertRedSubtleOnElevation0: paletteV1.lightAccentRed300,
    backgroundAlertRedSubtleOnElevation1: paletteV1.lightAccentRed200,
    backgroundAlertRedSubtleOnElevation2: paletteV1.lightAccentRed300,
    backgroundAlertYellowBold: paletteV1.lightAccentYellow600,
    backgroundAlertYellowBoldAlt: paletteV1.lightAccentYellow700,
    backgroundAlertYellowSubtleOnElevationNegative: paletteV1.lightAccentYellow400,
    backgroundAlertYellowSubtleOnElevation0: paletteV1.lightAccentYellow300,
    backgroundAlertYellowSubtleOnElevation1: paletteV1.lightAccentYellow200,
    backgroundAlertYellowSubtleOnElevation2: paletteV1.lightAccentYellow300,
    backgroundNeutralBold: paletteV1.lightGray1000,
    backgroundNeutralBoldInverted: paletteV1.lightWhiteAlpha1000,
    backgroundNeutralDisabled: paletteV1.lightGray200,
    backgroundNeutralSubdued: paletteV1.lightGray500,
    backgroundNeutralSubtleOnElevationNegative: paletteV1.lightGray400,
    backgroundNeutralSubtleOnElevation0: paletteV1.lightGray300,
    backgroundNeutralSubtleOnElevation1: paletteV1.lightGray200,
    backgroundPrimaryDefault: paletteV1.lightPrimaryForest800,
    backgroundPrimaryPressed: paletteV1.lightPrimaryForest900,
    backgroundPrimarySubtleOnElevationNegative: paletteV1.lightPrimaryForest400,
    backgroundPrimarySubtleOnElevation0: paletteV1.lightPrimaryForest300,
    backgroundPrimarySubtleOnElevation1: paletteV1.lightPrimaryForest200,
    backgroundSecondaryDefault: paletteV1.lightSecondaryEmerald800,
    backgroundSecondaryPressed: paletteV1.lightSecondaryEmerald900,
    backgroundSurfaceElevationNegative: paletteV1.lightGray200,
    backgroundSurfaceElevation0: paletteV1.lightGray100,
    backgroundSurfaceElevation1: paletteV1.lightWhiteAlpha1000,
    backgroundSurfaceElevation2: paletteV1.lightGray100,
    backgroundSurfaceElevation3: paletteV1.lightWhiteAlpha1000,
    backgroundTertiaryDefaultOnElevationNegative: paletteV1.lightGray400,
    backgroundTertiaryDefaultOnElevation0: paletteV1.lightGray300,
    backgroundTertiaryDefaultOnElevation1: paletteV1.lightGray200,
    backgroundTertiaryPressedOnElevationNegative: paletteV1.lightGray300,
    backgroundTertiaryPressedOnElevation0: paletteV1.lightGray400,
    backgroundTertiaryPressedOnElevation1: paletteV1.lightGray300,
    borderAlertRed: paletteV1.lightAccentRed600,
    borderDashed: paletteV1.lightGray400,
    borderFocus: paletteV1.lightGray500,
    borderInputDefault: paletteV1.lightGray400,
    borderInverted: paletteV1.lightWhiteAlpha1000,
    borderOnElevationNegative: paletteV1.lightGray400,
    borderOnElevation0: paletteV1.lightGray300,
    borderOnElevation1: paletteV1.lightGray200,
    borderSecondary: paletteV1.lightSecondaryEmerald800,
    borderSubtleInverted: paletteV1.lightWhiteAlpha400,
    iconAlertBlue: paletteV1.lightAccentBlue800,
    iconAlertPurple: paletteV1.lightAccentPurple800,
    iconAlertRed: paletteV1.lightAccentRed700,
    iconAlertYellow: paletteV1.lightAccentYellow800,
    iconDefault: paletteV1.lightGray1000,
    iconDefaultInverted: paletteV1.lightWhiteAlpha1000,
    iconDisabled: paletteV1.lightGray600,
    iconOnBlue: paletteV1.lightWhiteAlpha1000,
    iconOnPrimary: paletteV1.lightWhiteAlpha1000,
    iconOnPurple: paletteV1.lightWhiteAlpha1000,
    iconOnRed: paletteV1.lightWhiteAlpha1000,
    iconOnSecondary: paletteV1.lightWhiteAlpha1000,
    iconOnTertiary: paletteV1.lightGray800,
    iconOnYellow: paletteV1.lightGray1000,
    iconPrimaryDefault: paletteV1.lightPrimaryForest800,
    iconPrimaryPressed: paletteV1.lightPrimaryForest900,
    iconSubdued: paletteV1.lightGray700,
    interactionBackgroundDestructiveDefaultHoverOnElevationNegative: paletteV1.lightAccentRed300,
    interactionBackgroundDestructiveDefaultHoverOnElevation0: paletteV1.lightAccentRed400,
    interactionBackgroundDestructiveDefaultHoverOnElevation1: paletteV1.lightAccentRed300,
    interactionBackgroundDestructiveDefaultHoverOnElevation2: paletteV1.lightAccentRed400,
    interactionBackgroundDestructiveDefaultHoverOnElevation3: paletteV1.lightAccentRed300,
    interactionBackgroundDestructiveDefaultNormalOnElevationNegative: paletteV1.lightAccentRed400,
    interactionBackgroundDestructiveDefaultNormalOnElevation0: paletteV1.lightAccentRed300,
    interactionBackgroundDestructiveDefaultNormalOnElevation1: paletteV1.lightAccentRed200,
    interactionBackgroundDestructiveDefaultNormalOnElevation2: paletteV1.lightAccentRed300,
    interactionBackgroundDestructiveDefaultNormalOnElevation3: paletteV1.lightAccentRed200,
    interactionBackgroundInfoDefaultHoverOnElevationNegative: paletteV1.lightAccentBlue300,
    interactionBackgroundInfoDefaultHoverOnElevation0: paletteV1.lightAccentBlue400,
    interactionBackgroundInfoDefaultHoverOnElevation1: paletteV1.lightAccentBlue300,
    interactionBackgroundInfoDefaultHoverOnElevation2: paletteV1.lightAccentBlue400,
    interactionBackgroundInfoDefaultHoverOnElevation3: paletteV1.lightAccentBlue300,
    interactionBackgroundInfoDefaultNormalOnElevationNegative: paletteV1.lightAccentBlue400,
    interactionBackgroundInfoDefaultNormalOnElevation0: paletteV1.lightAccentBlue300,
    interactionBackgroundInfoDefaultNormalOnElevation1: paletteV1.lightAccentBlue200,
    interactionBackgroundInfoDefaultNormalOnElevation2: paletteV1.lightAccentBlue300,
    interactionBackgroundInfoDefaultNormalOnElevation3: paletteV1.lightAccentBlue200,
    interactionBackgroundTertiaryDefaultHoverOnElevationNegative: paletteV1.lightGray300,
    interactionBackgroundTertiaryDefaultHoverOnElevation0: paletteV1.lightGray400,
    interactionBackgroundTertiaryDefaultHoverOnElevation1: paletteV1.lightGray300,
    interactionBackgroundTertiaryDefaultHoverOnElevation2: paletteV1.lightGray400,
    interactionBackgroundTertiaryDefaultHoverOnElevation3: paletteV1.lightGray300,
    interactionBackgroundTertiaryDefaultNormalOnElevationNegative: paletteV1.lightGray400,
    interactionBackgroundTertiaryDefaultNormalOnElevation0: paletteV1.lightGray300,
    interactionBackgroundTertiaryDefaultNormalOnElevation1: paletteV1.lightGray200,
    interactionBackgroundTertiaryDefaultNormalOnElevation2: paletteV1.lightGray300,
    interactionBackgroundTertiaryDefaultNormalOnElevation3: paletteV1.lightGray200,
    interactionBackgroundWarningDefaultHoverOnElevationNegative: paletteV1.lightAccentYellow300,
    interactionBackgroundWarningDefaultHoverOnElevation0: paletteV1.lightAccentYellow400,
    interactionBackgroundWarningDefaultHoverOnElevation1: paletteV1.lightAccentYellow300,
    interactionBackgroundWarningDefaultHoverOnElevation2: paletteV1.lightAccentYellow400,
    interactionBackgroundWarningDefaultHoverOnElevation3: paletteV1.lightAccentYellow300,
    interactionBackgroundWarningDefaultNormalOnElevationNegative: paletteV1.lightAccentYellow400,
    interactionBackgroundWarningDefaultNormalOnElevation0: paletteV1.lightAccentYellow300,
    interactionBackgroundWarningDefaultNormalOnElevation1: paletteV1.lightAccentYellow200,
    interactionBackgroundWarningDefaultNormalOnElevation2: paletteV1.lightAccentYellow300,
    interactionBackgroundWarningDefaultNormalOnElevation3: paletteV1.lightAccentYellow200,
    textAlertBlue: paletteV1.lightAccentBlue800,
    textAlertPurple: paletteV1.lightAccentPurple800,
    textAlertRed: paletteV1.lightAccentRed700,
    textAlertYellow: paletteV1.lightAccentYellow800,
    textDefault: paletteV1.lightGray1000,
    textDefaultInverted: paletteV1.lightWhiteAlpha1000,
    textDisabled: paletteV1.lightGray600,
    textOnBlue: paletteV1.lightWhiteAlpha1000,
    textOnPrimary: paletteV1.lightWhiteAlpha1000,
    textOnPurple: paletteV1.lightWhiteAlpha1000,
    textOnRed: paletteV1.lightWhiteAlpha1000,
    textOnSecondary: paletteV1.lightWhiteAlpha1000,
    textOnTertiary: paletteV1.lightGray800,
    textOnYellow: paletteV1.lightGray1000,
    textPrimaryDefault: paletteV1.lightPrimaryForest800,
    textPrimaryPressed: paletteV1.lightPrimaryForest900,
    textSecondaryHighlight: paletteV1.lightSecondaryEmerald800,
    textSubdued: paletteV1.lightGray700,

    // non-valid tokens (should be removed)
    backgroundPrimarySubtleOnElevation2: paletteV1.lightPrimaryForest100,
    borderElevation0: paletteV1.lightGray300,
    borderElevation1: paletteV1.lightGray200,
    borderElevation2: paletteV1.lightGray200,
    borderElevation3: paletteV1.lightGray200,
    borderElevationNegative: paletteV1.lightGray400,
    borderInputFocus: paletteV1.lightGray500,
    logoBg: paletteV1.lightGray900,
    logoFg: paletteV1.lightGray100,

    ...colorsV2.light,
};

export type ThemeColorVariant = 'debug' | 'standard' | 'dark';

export type Color = keyof typeof light;
export type Colors = Record<Color, CSSColor>;

export const colorVariants: Record<ThemeColorVariant, Colors> = {
    debug: {
        ...light,
        backgroundSurfaceElevationNegative: '#F09EA7',
        backgroundSurfaceElevation0: '#F6CA94',
        backgroundSurfaceElevation1: '#C1EBC0',
        backgroundSurfaceElevation2: '#C7E5F7',
        backgroundSurfaceElevation3: '#C9B0FF',

        borderElevationNegative: '#FF0000',
        borderElevation0: '#FEB144',
        borderElevation1: '#74DF74',
        borderElevation2: '#0000FF',
        borderElevation3: '#AF4AAF',
    } as Colors,

    standard: light as Colors,

    dark: {
        transparent: '#00000000',

        // Figma Colors
        backgroundAlertBlueBold: paletteV1.darkAccentBlue600,
        backgroundAlertBlueBoldAlt: paletteV1.darkAccentBlue700,
        backgroundAlertBlueSubtleOnElevationNegative: paletteV1.darkAccentBlue100,
        backgroundAlertBlueSubtleOnElevation0: paletteV1.darkAccentBlue200,
        backgroundAlertBlueSubtleOnElevation1: paletteV1.darkAccentBlue300,
        backgroundAlertBlueSubtleOnElevation2: paletteV1.darkAccentBlue400,
        backgroundAlertPurpleBold: paletteV1.darkAccentPurple600,
        backgroundAlertPurpleBoldAlt: paletteV1.darkAccentPurple700,
        backgroundAlertPurpleSubtleOnElevationNegative: paletteV1.darkAccentPurple100,
        backgroundAlertPurpleSubtleOnElevation0: paletteV1.darkAccentPurple200,
        backgroundAlertPurpleSubtleOnElevation1: paletteV1.darkAccentPurple300,
        backgroundAlertPurpleSubtleOnElevation2: paletteV1.darkAccentPurple400,
        backgroundAlertRedBold: paletteV1.darkAccentRed600,
        backgroundAlertRedBoldAlt: paletteV1.darkAccentRed700,
        backgroundAlertRedSubtleOnElevationNegative: paletteV1.darkAccentRed100,
        backgroundAlertRedSubtleOnElevation0: paletteV1.darkAccentRed200,
        backgroundAlertRedSubtleOnElevation1: paletteV1.darkAccentRed300,
        backgroundAlertRedSubtleOnElevation2: paletteV1.darkAccentRed400,
        backgroundAlertYellowBold: paletteV1.darkAccentYellow600,
        backgroundAlertYellowBoldAlt: paletteV1.darkAccentYellow700,
        backgroundAlertYellowSubtleOnElevationNegative: paletteV1.darkAccentYellow100,
        backgroundAlertYellowSubtleOnElevation0: paletteV1.darkAccentYellow200,
        backgroundAlertYellowSubtleOnElevation1: paletteV1.darkAccentYellow300,
        backgroundAlertYellowSubtleOnElevation2: paletteV1.darkAccentYellow400,
        backgroundNeutralBold: paletteV1.darkGray1000,
        backgroundNeutralBoldInverted: paletteV1.darkGray000,
        backgroundNeutralDisabled: paletteV1.darkGray200,
        backgroundNeutralSubdued: paletteV1.darkGray500,
        backgroundNeutralSubtleOnElevationNegative: paletteV1.darkGray100,
        backgroundNeutralSubtleOnElevation0: paletteV1.darkGray200,
        backgroundNeutralSubtleOnElevation1: paletteV1.darkGray300,
        backgroundPrimaryDefault: paletteV1.darkPrimaryForest800,
        backgroundPrimaryPressed: paletteV1.darkPrimaryForest900,
        backgroundPrimarySubtleOnElevationNegative: paletteV1.darkPrimaryForest100,
        backgroundPrimarySubtleOnElevation0: paletteV1.darkPrimaryForest200,
        backgroundPrimarySubtleOnElevation1: paletteV1.darkPrimaryForest300,
        backgroundSecondaryDefault: paletteV1.darkSecondaryGreen800,
        backgroundSecondaryPressed: paletteV1.darkSecondaryGreen900,
        backgroundSurfaceElevationNegative: paletteV1.darkGray000,
        backgroundSurfaceElevation0: paletteV1.darkGray50,
        backgroundSurfaceElevation1: paletteV1.darkGray100,
        backgroundSurfaceElevation2: paletteV1.darkGray200,
        backgroundSurfaceElevation3: paletteV1.darkGray300,
        backgroundTertiaryDefaultOnElevationNegative: paletteV1.darkGray100,
        backgroundTertiaryDefaultOnElevation0: paletteV1.darkGray200,
        backgroundTertiaryDefaultOnElevation1: paletteV1.darkGray300,
        backgroundTertiaryPressedOnElevationNegative: paletteV1.darkGray200,
        backgroundTertiaryPressedOnElevation0: paletteV1.darkGray300,
        backgroundTertiaryPressedOnElevation1: paletteV1.darkGray400,
        borderAlertRed: paletteV1.darkAccentRed600,
        borderDashed: paletteV1.darkGray300,
        borderFocus: paletteV1.darkGray500,
        borderInputDefault: paletteV1.darkGray400,
        borderInverted: paletteV1.darkGray000,
        borderOnElevationNegative: paletteV1.darkGray200,
        borderOnElevation0: paletteV1.darkGray300,
        borderOnElevation1: paletteV1.darkGray400,
        borderSecondary: paletteV1.darkSecondaryGreen800,
        borderSubtleInverted: paletteV1.LightBlackAlpha600,
        iconAlertBlue: paletteV1.darkAccentBlue800,
        iconAlertPurple: paletteV1.darkAccentPurple800,
        iconAlertRed: paletteV1.darkAccentRed800,
        iconAlertYellow: paletteV1.darkAccentYellow700,
        iconDefault: paletteV1.darkGray1000,
        iconDefaultInverted: paletteV1.darkGray000,
        iconDisabled: paletteV1.darkGray600,
        iconOnBlue: paletteV1.darkGray1000,
        iconOnPrimary: paletteV1.darkGray000,
        iconOnPurple: paletteV1.darkGray1000,
        iconOnRed: paletteV1.darkGray1000,
        iconOnSecondary: paletteV1.darkGray000,
        iconOnTertiary: paletteV1.darkGray800,
        iconOnYellow: paletteV1.darkGray000,
        iconPrimaryDefault: paletteV1.darkPrimaryForest800,
        iconPrimaryPressed: paletteV1.darkPrimaryForest900,
        iconSubdued: paletteV1.darkGray700,
        interactionBackgroundDestructiveDefaultHoverOnElevationNegative: paletteV1.darkAccentRed200,
        interactionBackgroundDestructiveDefaultHoverOnElevation0: paletteV1.darkAccentRed300,
        interactionBackgroundDestructiveDefaultHoverOnElevation1: paletteV1.darkAccentRed400,
        interactionBackgroundDestructiveDefaultHoverOnElevation2: paletteV1.darkAccentRed500,
        interactionBackgroundDestructiveDefaultHoverOnElevation3: paletteV1.darkAccentRed400,
        interactionBackgroundDestructiveDefaultNormalOnElevationNegative:
            paletteV1.darkAccentRed100,
        interactionBackgroundDestructiveDefaultNormalOnElevation0: paletteV1.darkAccentRed200,
        interactionBackgroundDestructiveDefaultNormalOnElevation1: paletteV1.darkAccentRed300,
        interactionBackgroundDestructiveDefaultNormalOnElevation2: paletteV1.darkAccentRed400,
        interactionBackgroundDestructiveDefaultNormalOnElevation3: paletteV1.darkAccentRed500,
        interactionBackgroundInfoDefaultHoverOnElevationNegative: paletteV1.darkAccentBlue200,
        interactionBackgroundInfoDefaultHoverOnElevation0: paletteV1.darkAccentBlue300,
        interactionBackgroundInfoDefaultHoverOnElevation1: paletteV1.darkAccentBlue400,
        interactionBackgroundInfoDefaultHoverOnElevation2: paletteV1.darkAccentBlue500,
        interactionBackgroundInfoDefaultHoverOnElevation3: paletteV1.darkAccentBlue400,
        interactionBackgroundInfoDefaultNormalOnElevationNegative: paletteV1.darkAccentBlue100,
        interactionBackgroundInfoDefaultNormalOnElevation0: paletteV1.darkAccentBlue200,
        interactionBackgroundInfoDefaultNormalOnElevation1: paletteV1.darkAccentBlue300,
        interactionBackgroundInfoDefaultNormalOnElevation2: paletteV1.darkAccentBlue400,
        interactionBackgroundInfoDefaultNormalOnElevation3: paletteV1.darkAccentBlue500,
        interactionBackgroundTertiaryDefaultHoverOnElevationNegative: paletteV1.darkGray200,
        interactionBackgroundTertiaryDefaultHoverOnElevation0: paletteV1.darkGray300,
        interactionBackgroundTertiaryDefaultHoverOnElevation1: paletteV1.darkGray400,
        interactionBackgroundTertiaryDefaultHoverOnElevation2: paletteV1.darkGray500,
        interactionBackgroundTertiaryDefaultHoverOnElevation3: paletteV1.darkGray400,
        interactionBackgroundTertiaryDefaultNormalOnElevationNegative: paletteV1.darkGray100,
        interactionBackgroundTertiaryDefaultNormalOnElevation0: paletteV1.darkGray200,
        interactionBackgroundTertiaryDefaultNormalOnElevation1: paletteV1.darkGray300,
        interactionBackgroundTertiaryDefaultNormalOnElevation2: paletteV1.darkGray400,
        interactionBackgroundTertiaryDefaultNormalOnElevation3: paletteV1.darkGray500,
        interactionBackgroundWarningDefaultHoverOnElevationNegative: paletteV1.darkAccentYellow200,
        interactionBackgroundWarningDefaultHoverOnElevation0: paletteV1.darkAccentYellow300,
        interactionBackgroundWarningDefaultHoverOnElevation1: paletteV1.darkAccentYellow400,
        interactionBackgroundWarningDefaultHoverOnElevation2: paletteV1.darkAccentYellow500,
        interactionBackgroundWarningDefaultHoverOnElevation3: paletteV1.darkAccentYellow400,
        interactionBackgroundWarningDefaultNormalOnElevationNegative: paletteV1.darkAccentYellow100,
        interactionBackgroundWarningDefaultNormalOnElevation0: paletteV1.darkAccentYellow200,
        interactionBackgroundWarningDefaultNormalOnElevation1: paletteV1.darkAccentYellow300,
        interactionBackgroundWarningDefaultNormalOnElevation2: paletteV1.darkAccentYellow400,
        interactionBackgroundWarningDefaultNormalOnElevation3: paletteV1.darkAccentYellow500,
        textAlertBlue: paletteV1.darkAccentBlue800,
        textAlertPurple: paletteV1.darkAccentPurple800,
        textAlertRed: paletteV1.darkAccentRed800,
        textAlertYellow: paletteV1.darkAccentYellow700,
        textDefault: paletteV1.darkGray1000,
        textDefaultInverted: paletteV1.darkGray000,
        textDisabled: paletteV1.darkGray600,
        textOnBlue: paletteV1.darkGray1000,
        textOnPrimary: paletteV1.darkGray000,
        textOnPurple: paletteV1.darkGray1000,
        textOnRed: paletteV1.darkGray1000,
        textOnSecondary: paletteV1.darkGray000,
        textOnTertiary: paletteV1.darkGray800,
        textOnYellow: paletteV1.darkGray000,
        textPrimaryDefault: paletteV1.darkPrimaryForest800,
        textPrimaryPressed: paletteV1.darkPrimaryForest900,
        textSecondaryHighlight: paletteV1.darkSecondaryGreen800,
        textSubdued: paletteV1.darkGray700,

        // non-valid tokens (should be removed)
        backgroundPrimarySubtleOnElevation2: paletteV1.darkPrimaryForest400,
        borderElevation0: paletteV1.darkGray100,
        borderElevation1: paletteV1.darkGray200,
        borderElevation2: paletteV1.darkGray300,
        borderElevation3: paletteV1.darkGray400,
        borderElevationNegative: paletteV1.darkGray50,
        borderInputFocus: paletteV1.darkGray500,
        logoBg: paletteV1.darkGray900,
        logoFg: paletteV1.darkGray100,

        ...colorsV2.dark,
    } as Colors,
} as const;
