// Credentials generated by connect/e2e/thpPairing.test.ts

export const THP_CREDENTIALS = [
    {
        host_static_key: '0007070707070707070707070707070707070707070707070707070707070747',
        trezor_static_public_key:
            'ca9a6e4682ac461c59d75a8625c05bf3a4af01e084abc5a7fe8ad126c2d6f772',
        credential:
            '0a1c0a0974657374733a65326510001a0d5472657a6f72436f6e6e65637412203a4826fcf4d107240c1b9aa0c4bec6abab95e50b35950b5da8a648da135ae96d',
        autoconnect: false,
    },
    // since 2.12.1 (new tropic emulator)
    {
        trezor_static_public_key:
            '790de198ef8e9378af05c723f141d2a13b51d21dd6892e46f7ef290a3e289e26',
        credential:
            '0a1c0a0974657374733a65326510001a0d5472657a6f72436f6e6e656374122046559873371a3081450646d75701b270e366889b93e098030409b85a8392a03c',
        autoconnect: false,
        host_static_key: '8154f21fd32368bfaa2912faa8cb8b2eadf09f60b49c49d76c22f787fa8be39a',
    },
    {
        trezor_static_public_key:
            '96308b4f2ed64275e442bf9b3e1fe95d6c5bee1b06ab00e892f5e74591d03015',
        credential:
            '0a1c0a0974657374733a65326510001a0d5472657a6f72436f6e6e65637412201d522728c8285d53b95856c4fd29f911d963e801ed5485a00b9e91239db3e0e4',
        autoconnect: false,
        host_static_key: '5d0cc8f62d19b3faee9f361e88f1753e6f95cd46d053bf48f8770dca2493f91e',
    },
];

export const THP_CREDENTIALS_AUTOCONNECT = [
    {
        host_static_key: '0007070707070707070707070707070707070707070707070707070707070747',
        trezor_static_public_key:
            'ca9a6e4682ac461c59d75a8625c05bf3a4af01e084abc5a7fe8ad126c2d6f772',
        credential:
            '0a1c0a0974657374733a65326510011a0d5472657a6f72436f6e6e65637412204cd0d3ccab3d615430d218e96d78cd5b89a06783581e5948d8cc532e423bd145',
        autoconnect: true,
    },
    // since 2.12.1 (new tropic emulator)
    {
        trezor_static_public_key:
            '790de198ef8e9378af05c723f141d2a13b51d21dd6892e46f7ef290a3e289e26',
        credential:
            '0a1c0a0974657374733a65326510011a0d5472657a6f72436f6e6e656374122025c5bd5495c6908f95bdd1faeace4dbea317ab27991f30f339f57cb51654d33b',
        autoconnect: true,
        host_static_key: '3217c896fa2767becdc1aaac541e4a7e6527e19c1f00d2472dd11d424e2867b2',
    },
    {
        trezor_static_public_key:
            '96308b4f2ed64275e442bf9b3e1fe95d6c5bee1b06ab00e892f5e74591d03015',
        credential:
            '0a1c0a0974657374733a65326510011a0d5472657a6f72436f6e6e65637412202664bddf66b3cd39c5876bfa26881d78f227870a4801ee0a23f4771645a41ee1',
        autoconnect: true,
        host_static_key: '5d0cc8f62d19b3faee9f361e88f1753e6f95cd46d053bf48f8770dca2493f91e',
    },
];
