// Credentials generated by connect/e2e/thpPairing.test.ts

export const THP_CREDENTIALS = [
    {
        host_static_key: '0007070707070707070707070707070707070707070707070707070707070747',
        trezor_static_public_key:
            '566f6976fd42cafadf1b843ce4e6275c930d52efac878217df0ea2a23933b07d',
        credential:
            '0a180a064368726f6d6510001a0c5472657a6f722053756974651220884364860fbccd18f6c14890ee4cf427c6a1e7e7a4cba91866474b4b7d73cb00',
        autoconnect: false,
    },
    // since 2.12.1 (new tropic emulator)
    {
        trezor_static_public_key:
            '790de198ef8e9378af05c723f141d2a13b51d21dd6892e46f7ef290a3e289e26',
        credential:
            '0a1c0a0974657374733a65326510001a0d5472657a6f72436f6e6e656374122046559873371a3081450646d75701b270e366889b93e098030409b85a8392a03c',
        autoconnect: false,
        host_static_key: '8154f21fd32368bfaa2912faa8cb8b2eadf09f60b49c49d76c22f787fa8be39a',
    },
];

export const THP_CREDENTIALS_AUTOCONNECT = [
    {
        host_static_key: '0007070707070707070707070707070707070707070707070707070707070747',
        trezor_static_public_key:
            '566f6976fd42cafadf1b843ce4e6275c930d52efac878217df0ea2a23933b07d',
        credential:
            '0a1c0a0974657374733a65326510011a0d5472657a6f72436f6e6e65637412203fa725f325ba34cce19e39e6c87f573a9db1a532c28f67a363f0ea8317f64af9',
        autoconnect: true,
    },
    // since 2.12.1 (new tropic emulator)
    {
        trezor_static_public_key:
            '790de198ef8e9378af05c723f141d2a13b51d21dd6892e46f7ef290a3e289e26',
        credential:
            '0a1c0a0974657374733a65326510011a0d5472657a6f72436f6e6e656374122025c5bd5495c6908f95bdd1faeace4dbea317ab27991f30f339f57cb51654d33b',
        autoconnect: true,
        host_static_key: '3217c896fa2767becdc1aaac541e4a7e6527e19c1f00d2472dd11d424e2867b2',
    },
];
