/* !!! IMPORTANT: This file is autogenerated !!!
 * make:migration script should be used to add migrations here.
 * more info in /suite/idb-migration-scripts/MIGRATION.md
 */

export { default as m25_7_0 } from './25.7.0';
export { default as m25_8_0 } from './25.8.0';
