/* !!! IMPORTANT: This file is autogenerated !!!
 * make:migration script should be used to add migrations here.
 * more info in /suite/idb-migration-scripts/MIGRATION.md
 */

export { default as m25_7_0 } from './25.7.0';
export { default as m25_8_0 } from './25.8.0';
export { default as m25_9_2 } from './25.9.2';
export { default as m25_10_0 } from './25.10.0';
export { default as m25_11_0 } from './25.11.0';
export { default as m25_11_0_1 } from './25.11.0.1';
export { default as m25_11_3 } from './25.11.3';
export { default as m25_12_0 } from './25.12.0';
export { default as m26_1_0 } from './26.1.0';
export { default as m26_2_0 } from './26.2.0';
export { default as m26_3_0 } from './26.3.0';
export { default as m26_3_0_1 } from './26.3.0.1';
export { default as m26_4_0 } from './26.4.0';
export { default as m26_4_0_1 } from './26.4.0.1';
export { default as m26_5_0 } from './26.5.0';
