import fs from 'fs';
import path from 'path';

const firmwareDir = path.resolve(__dirname, '..', 'files/firmware');

const outputFile = path.resolve(__dirname, '../src/map-releases.ts');

const toVarName = (s: string): string => s.replace(/[^a-zA-Z0-9]/g, '_');

interface FileEntry {
    varName: string;
    importPath: string;
}

const fileEntries: FileEntry[] = [];

const createIndexFromDir = (
    currentPath: string,
    keyParts: string[],
    skipDirs: string[] = [],
): Record<string, any> => {
    const entries = fs.readdirSync(currentPath, { withFileTypes: true });

    return entries.reduce(
        (acc: Record<string, any>, entry: fs.Dirent) => {
            const entryPath = path.join(currentPath, entry.name);

            if (entry.isDirectory()) {
                if (skipDirs.includes(entry.name)) return acc;

                return {
                    ...acc,
                    [entry.name]: createIndexFromDir(entryPath, [...keyParts, entry.name]),
                };
            }

            if (entry.isFile() && entry.name.endsWith('.json')) {
                const outputDir = path.dirname(outputFile);
                const importPath = path.relative(outputDir, entryPath).replace(/\\/g, '/');
                const fileNameWithoutExt = path.parse(entry.name).name;
                const varName = [...keyParts, toVarName(fileNameWithoutExt)].join('_');

                fileEntries.push({ varName, importPath });

                // Use a placeholder that JSON.stringify will quote, then we'll replace it
                return { ...acc, [fileNameWithoutExt]: `__VAR__${varName}` };
            }

            return acc;
        },
        {} as Record<string, any>,
    );
};

// Skip 'release/' — it contains the release config (releases.v1.json), not device firmware.
// That file is imported directly where needed.
const index = createIndexFromDir(firmwareDir, [], ['release']);

// Replace quoted "__VAR__xxx" placeholders with bare variable references
const indexContent = JSON.stringify(index, null, 2).replace(/"__VAR__([^"]+)"/g, '$1');

const imports = fileEntries
    .map(({ varName, importPath }) => `import ${varName} from '${importPath}';`)
    .join('\n');

const fileContent = `// THIS FILE IS AUTO-GENERATED BY a build script. DO NOT EDIT.
${imports}

export const firmwareAssets = ${indexContent};
`;

fs.writeFileSync(outputFile, fileContent, 'utf-8');
