import fs from 'fs';
import path from 'path';

const firmwareDir = path.resolve(__dirname, '..', 'files/firmware');

const outputFile = path.resolve(__dirname, '../src/map-releases.ts');

const createIndexFromDir = (currentPath: string): Record<string, any> => {
    const entries = fs.readdirSync(currentPath, { withFileTypes: true });

    return entries.reduce(
        (acc: Record<string, any>, entry: fs.Dirent) => {
            const entryPath = path.join(currentPath, entry.name);

            if (entry.isDirectory()) {
                // If it is a directory then recursively call and add the resulting object.
                return { ...acc, [entry.name]: createIndexFromDir(entryPath) };
            }

            if (entry.isFile() && entry.name.endsWith('.json')) {
                const outputDir = path.dirname(outputFile);
                const relativePath = path.relative(outputDir, entryPath).replace(/\\/g, '/');

                const fileNameWithoutExt = path.parse(entry.name).name;
                const requireString = `require('${relativePath}')`;

                return { ...acc, [fileNameWithoutExt]: requireString };
            }

            return acc;
        },
        {} as Record<string, any>,
    );
};

const index = createIndexFromDir(firmwareDir);

const indexContent = JSON.stringify(index, null, 2).replace(/"require\(([^)]+)\)"/g, 'require($1)');

const fileContent = `// THIS FILE IS AUTO-GENERATED BY a build script. DO NOT EDIT.
export const firmwareAssets = ${indexContent};
`;

fs.writeFileSync(outputFile, fileContent, 'utf-8');
