"project_id": 383255
"base_path": "../../packages/suite-data/files/translations"
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true
files:
  [
    {
      "source": "master.json",
      "translation": "%locale%.json",
      "update_option": "update_as_unapproved",
    },
  ]
