/* eslint-disable global-require */

// !!! IMPORTANT: This file is autogenerated !!!
// If you want to add of modify icons please read README.md to find out how to do it

export const iconTypes = {
    close: require('./assets/close.svg'),
    warningCircle: require('./assets/warningCircle.svg'),
} as const;

export type IconType = keyof typeof iconTypes;
