// !!! IMPORTANT: This file is autogenerated !!!
// If you want to add of modify videos, please read README.md to find out more.

export const videos = {
    xpubImportBTC: require('../assets/compressed/xpubImportBTC.mp4'),
    xpubImportETH: require('../assets/compressed/xpubImportETH.mp4'),
} as const;
export type VideoName = keyof typeof videos;
