/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * Trezor Earn API
 * OpenAPI spec version: 0.1.0
 */
import type { AdaPoolsPoolsItem } from './adaPoolsPoolsItem';

export type AdaPools = {
    pools: AdaPoolsPoolsItem[];
};
