/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * Trezor Earn API
 * OpenAPI spec version: 0.1.0
 */

export type EthOrSolStats =
    | {
          /** Pool APY as a percentage number (e.g. 3.08). Derived from Everstake pool APR decimal × 100, rounded down to 3 decimal places. */
          apy: number;
          /** Whole days until next reward payout; ceil from upstream seconds (86400). */
          nextRewardPayout: number;
          symbol: 'eth';
      }
    | {
          /** Chain staking APR from Everstake dashboard as decimal fraction (same as Suite `blockchain.apr`). */
          apy: number;
          symbol: 'sol';
      };
