/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * Trezor Earn API
 * OpenAPI spec version: 0.1.0
 */

export type EthOrSolStats =
    | {
          /** Pool APY as a percentage number (e.g. 3.08). */
          apy: number;
          /** Seconds until next reward payout. */
          nextRewardPayout: number;
          symbol: 'eth';
      }
    | {
          /** Chain staking APY from Everstake dashboard (e.g. 2.45). */
          apy: number;
          symbol: 'sol';
      };
