/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * Trezor Earn API
 * OpenAPI spec version: 0.1.0
 */

export type EthValidatorsQueue = {
    /** Seconds — estimated delay before a validator becomes active. */
    activationTime?: number;
    /** Seconds — estimated delay before a validator is exited. */
    exitTime?: number;
    /** Seconds — withdraw period from beacon chain. */
    withdrawTime?: number;
    /** Seconds — delay before validator is known at beacon chain. */
    addingDelay?: number;
    /** Unix timestamp (seconds) of last upstream refresh. */
    updatedAt?: number;
};
