/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Trezor Earn Staking API
 * OpenAPI spec version: 0.1.0
 */

export type ReportStakingTxIdsKind =
    (typeof ReportStakingTxIdsKind)[keyof typeof ReportStakingTxIdsKind];

export const ReportStakingTxIdsKind = {
    freeze: 'freeze',
    vote: 'vote',
} as const;
