/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Trezor Earn Staking API
 * OpenAPI spec version: 0.1.0
 */

export type SolRewardsHistoryRewardsItem = {
    /** Solana epoch index. */
    epoch: number;
    /** Stake account (delegator address). */
    delegator: string;
    /** Reward amount in lamports as string. */
    amount: string;
    /** Currency symbol. */
    currency: string;
    /** ISO 8601 timestamp of the reward. */
    time: string;
};
