/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * Trezor Earn API
 * OpenAPI spec version: 0.1.0
 */

export type SolRewardsTotal = {
    /** Total rewards in lamports as string. */
    total: string;
};
