/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * Trezor Earn API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Error code.
 */
export type StakingBatchErrorsItemCode =
    (typeof StakingBatchErrorsItemCode)[keyof typeof StakingBatchErrorsItemCode];

export const StakingBatchErrorsItemCode = {
    upstream_validation_error: 'upstream_validation_error',
    upstream_unknown_error: 'upstream_unknown_error',
} as const;
