/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Trezor Earn Staking API
 * OpenAPI spec version: 0.1.0
 */

export type StakingBatchDataItem =
    | {
          stats: {
              /** Pool APY as a percentage number (e.g. 3.08). */
              apy: number;
              /** Seconds until next reward payout. */
              nextRewardPayout: number;
          };
          validators: {
              /** Seconds — estimated delay before a validator becomes active. */
              activationTime?: number;
              /** Seconds — estimated delay before a validator is exited. */
              exitTime?: number;
              /** Seconds — withdraw period from beacon chain. */
              withdrawTime?: number;
              /** Seconds — delay before validator is known at beacon chain. */
              addingDelay?: number;
              /** Unix timestamp (seconds) of last upstream refresh. */
              updatedAt?: number;
          };
          symbol: 'eth';
      }
    | {
          /** Solana chain stats. */
          stats: {
              /** Same as SolChainStats.apy. */
              apy: number;
          };
          symbol: 'sol';
      }
    | {
          pools: {
              /** Validator APY percentage value from Everstake stats. */
              apy: number;
              /** Saturation as percentage 0–100 */
              saturation: number;
              /** Cardano validator address (pool id). */
              id: string;
          }[];
          symbol: 'ada';
      }
    | {
          representatives: {
              /** SR address in base58check format. */
              address: string;
              /** Human-readable name, e.g. LugaNodes. */
              name: string;
              /** URL of the SR's website. */
              url: string;
              /** Estimated annual yield for voters in percent. */
              apr: number;
          }[];
          symbol: 'trx';
      };
