/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * Trezor Earn API
 * OpenAPI spec version: 0.1.0
 */

export type StakingBatchDataItem =
    | {
          stats: {
              /** Pool APY as a percentage number (e.g. 3.08). Derived from Everstake pool APR decimal × 100, rounded down to 3 decimal places. */
              apy: number;
              /** Whole days until next reward payout; ceil from upstream seconds (86400). */
              nextRewardPayout: number;
          };
          validators: {
              /** Seconds — estimated delay before a validator becomes active (Everstake `validator_activation_time`). */
              activatedAt?: number;
              /** Seconds — estimated delay before a validator is exited (`validator_exit_time`). */
              exitedAt?: number;
              /** Seconds — withdraw period from beacon chain (`validator_withdraw_time`). */
              withdrewAt?: number;
              /** Seconds — delay before validator is known at beacon chain (`validator_adding_delay`). */
              addingDelay?: number;
              /** Unix timestamp (seconds) of last upstream refresh (`updated_at`). */
              updatedAt?: number;
          };
          symbol: 'eth';
      }
    | {
          /** Solana chain stats. */
          stats: {
              /** Same as SolChainStats.apy. */
              apy: number;
          };
          symbol: 'sol';
      }
    | {
          pools: {
              /** Validator APY percentage value from Everstake stats. */
              apy: number;
              /** Saturation as percentage 0–100 (upstream decimal × 100). */
              saturation: number;
              /** Cardano validator address (pool id). */
              id: string;
          }[];
          symbol: 'ada';
      };
