/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Trezor Earn Staking API
 * OpenAPI spec version: 0.1.0
 */

export type StakingBatchParams = {
    networks?: ('eth' | 'sol' | 'ada' | 'trx')[] | string;
};
