/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Trezor Earn Staking API
 * OpenAPI spec version: 0.1.0
 */
import type { TrxStatsItem } from './trxStatsItem';

export type TrxStats = TrxStatsItem[];
