/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Trezor Earn Staking API
 * OpenAPI spec version: 0.1.0
 */

export type TrxStatsItem = {
    /** SR address in base58check format. */
    address: string;
    /** Human-readable name, e.g. LugaNodes. */
    name: string;
    /** URL of the SR's website. */
    url: string;
    /** Estimated annual yield for voters in percent. */
    apr: number;
};
