import { CryptoId, SellProviderInfo } from 'invity-api';

export const sellInvity = {
    name: 'invity',
    companyName: 'Invity Finance',
    logo: 'invity.svg',
    type: 'Fiat',
    isActive: true,
    tradedCoins: ['bitcoin', 'ethereum', 'eos'] as CryptoId[],
    tradedFiatCurrencies: ['EUR', 'USD', 'CZK'],
    supportedCountries: ['CZ', 'DK', 'US'],
    paymentMethods: ['bankTransfer', 'creditCard'],
    statusUrl: 'https://checkout.invity.io/sell/status/{{paymentId}}',
    supportUrl: 'https://invity.io/sell-crypto/#support',
    flow: 'BANK_ACCOUNT',
    isRefundAddressRequired: true,
    pendingTimeout: 3600,
    lockSendAmount: false,
} as SellProviderInfo;

export const sellMercuryo = {
    name: 'mercuryo',
    companyName: 'Mercuryo',
    logo: 'mercuryo.svg',
    type: 'Fiat',
    isActive: true,
    tradedCoins: ['bitcoin', 'ethereum', 'eos'] as CryptoId[],
    tradedFiatCurrencies: ['EUR', 'USD', 'CZK'],
    supportedCountries: ['CZ', 'DK', 'US'],
    paymentMethods: ['bankTransfer', 'creditCard'],
    statusUrl: 'https://checkout.mercuryo.io/sell/status/{{paymentId}}',
    supportUrl: 'https://mercuryo.io/sell-crypto/#support',
    flow: 'BANK_ACCOUNT',
    isRefundAddressRequired: true,
    pendingTimeout: 3600,
    lockSendAmount: false,
} as SellProviderInfo;

export const sellCexdirect = {
    name: 'cexdirect',
    companyName: 'Cexdirect',
    logo: 'cexdirect.svg',
    type: 'Fiat',
    isActive: true,
    tradedCoins: ['bitcoin', 'ethereum', 'eos'] as CryptoId[],
    tradedFiatCurrencies: ['EUR', 'USD', 'CZK'],
    supportedCountries: ['CZ', 'DK', 'US'],
    paymentMethods: ['bankTransfer', 'creditCard'],
    statusUrl: 'https://checkout.cexdirect.io/sell/status/{{paymentId}}',
    supportUrl: 'https://cexdirect.io/sell-crypto/#support',
    flow: 'BANK_ACCOUNT',
    isRefundAddressRequired: true,
    pendingTimeout: 3600,
    lockSendAmount: false,
} as SellProviderInfo;

export const sellBanxa = {
    name: 'banxa',
    companyName: 'Banxa',
    logo: 'banxa.svg',
    type: 'Fiat',
    isActive: true,
    tradedCoins: ['bitcoin', 'ethereum'] as CryptoId[],
    tradedFiatCurrencies: ['EUR', 'USD', 'AUD'],
    supportedCountries: ['AU', 'EU', 'US'],
    paymentMethods: ['bankTransfer', 'creditCard'],
    statusUrl: 'https://checkout.banxa.com/sell/status/{{paymentId}}',
    supportUrl: 'https://banxa.com/support',
    flow: 'BANK_ACCOUNT',
    isRefundAddressRequired: true,
    pendingTimeout: 7200,
    lockSendAmount: true,
} as SellProviderInfo;

export const sellMoonpay = {
    name: 'moonpay',
    companyName: 'MoonPay',
    logo: 'moonpay.svg',
    type: 'Fiat',
    isActive: true,
    tradedCoins: ['bitcoin', 'ethereum', 'eos'] as CryptoId[],
    tradedFiatCurrencies: ['EUR', 'USD', 'GBP', 'CZK'],
    supportedCountries: ['GB', 'EU', 'US'],
    paymentMethods: ['bankTransfer', 'creditCard'],
    statusUrl: 'https://checkout.moonpay.com/sell/status/{{paymentId}}',
    supportUrl: 'https://moonpay.com/support',
    flow: 'BANK_ACCOUNT',
    isRefundAddressRequired: true,
    pendingTimeout: 3600,
    lockSendAmount: false,
} as SellProviderInfo;
