/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Trezor Earn Yield API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';

/**
 * @summary List yield opportunities (paginated)
 */
export const getYieldsQueryLimitDefault = 20;
export const getYieldsQueryLimitExclusiveMin = 0;
export const getYieldsQueryLimitMax = 100;

export const getYieldsQueryOffsetDefault = 0;
export const getYieldsQueryOffsetMin = 0;
export const getYieldsQueryOffsetMax = 1000000;

export const getYieldsQueryParams = zod.object({
    limit: zod
        .number()
        .gt(getYieldsQueryLimitExclusiveMin)
        .max(getYieldsQueryLimitMax)
        .default(getYieldsQueryLimitDefault)
        .describe('Max 100 (default 20).'),
    offset: zod
        .number()
        .min(getYieldsQueryOffsetMin)
        .max(getYieldsQueryOffsetMax)
        .nullish()
        .default(getYieldsQueryOffsetDefault)
        .describe('Max 1000000 (default 0).'),
    sort: zod
        .enum([
            'statusEnterAsc',
            'statusEnterDesc',
            'statusExitAsc',
            'statusExitDesc',
            'rewardRateAsc',
            'rewardRateDesc',
        ])
        .optional()
        .describe('Sort by yield status or reward rate'),
    providers: zod.union([zod.array(zod.string()), zod.string()]).optional(),
    types: zod
        .union([
            zod.array(
                zod.enum([
                    'staking',
                    'restaking',
                    'lending',
                    'vault',
                    'fixed_yield',
                    'real_world_asset',
                    'concentrated_liquidity_pool',
                    'liquidity_pool',
                ]),
            ),
            zod.string(),
        ])
        .optional(),
});

export const getYieldsHeaderXSuiteVersionRegExp = new RegExp('^(\\d+)\\.(\\d+)\\.(\\d+)$');

export const getYieldsHeader = zod.object({
    'x-suite-version': zod
        .string()
        .regex(getYieldsHeaderXSuiteVersionRegExp)
        .describe('Caller suite semver (e.g. 25.10.0). Used to scope vault allow-list.'),
});

export const getYieldsResponseItemsItemTokenDecimalsMin = 0;

export const getYieldsResponseItemsItemOutputTokenDecimalsMin = 0;

export const getYieldsResponseItemsItemInputTokensItemDecimalsMin = 0;

export const getYieldsResponseItemsItemRewardRateComponentsItemTokenDecimalsMin = 0;

export const getYieldsResponseItemsItemStatePricePerShareStateShareTokenDecimalsMin = 0;

export const getYieldsResponseItemsItemStatePricePerShareStateQuoteTokenDecimalsMin = 0;

export const getYieldsResponseTotalMin = 0;

export const getYieldsResponseOffsetMin = 0;

export const getYieldsResponseLimitExclusiveMin = 0;

export const getYieldsResponse = zod.object({
    items: zod.array(
        zod.object({
            id: zod.string().describe('Unique identifier for this yield opportunity'),
            providerId: zod.string().describe('Yield provider identifier, e.g. morpho.'),
            network: zod
                .enum([
                    'ethereum',
                    'ethereum-goerli',
                    'ethereum-holesky',
                    'ethereum-sepolia',
                    'ethereum-hoodi',
                    'arbitrum',
                    'base',
                    'base-sepolia',
                    'gnosis',
                    'optimism',
                    'polygon',
                    'polygon-amoy',
                    'starknet',
                    'zksync',
                    'linea',
                    'unichain',
                    'monad-testnet',
                    'monad',
                    'avalanche-c',
                    'avalanche-c-atomic',
                    'avalanche-p',
                    'binance',
                    'celo',
                    'fantom',
                    'harmony',
                    'moonriver',
                    'okc',
                    'viction',
                    'core',
                    'sonic',
                    'plasma',
                    'katana',
                    'hyperevm',
                    'agoric',
                    'akash',
                    'axelar',
                    'band-protocol',
                    'bitsong',
                    'canto',
                    'chihuahua',
                    'comdex',
                    'coreum',
                    'cosmos',
                    'crescent',
                    'cronos',
                    'cudos',
                    'desmos',
                    'dydx',
                    'evmos',
                    'fetch-ai',
                    'gravity-bridge',
                    'injective',
                    'irisnet',
                    'juno',
                    'kava',
                    'ki-network',
                    'mars-protocol',
                    'nym',
                    'okex-chain',
                    'onomy',
                    'osmosis',
                    'persistence',
                    'quicksilver',
                    'regen',
                    'secret',
                    'sentinel',
                    'sommelier',
                    'stafi',
                    'stargaze',
                    'stride',
                    'teritori',
                    'tgrade',
                    'umee',
                    'sei',
                    'mantra',
                    'celestia',
                    'saga',
                    'zetachain',
                    'dymension',
                    'humansai',
                    'neutron',
                    'polkadot',
                    'kusama',
                    'westend',
                    'bittensor',
                    'aptos',
                    'binancebeacon',
                    'cardano',
                    'near',
                    'solana',
                    'solana-devnet',
                    'stellar',
                    'stellar-testnet',
                    'sui',
                    'tezos',
                    'tron',
                    'ton',
                    'ton-testnet',
                    'hyperliquid',
                ])
                .describe('The network identifier'),
            chainId: zod.number().describe('EVM chain id this yield lives on'),
            token: zod.object({
                symbol: zod.string().describe('Token symbol'),
                name: zod.string().describe('Token name'),
                decimals: zod
                    .number()
                    .min(getYieldsResponseItemsItemTokenDecimalsMin)
                    .describe('Token decimal places'),
                network: zod
                    .enum([
                        'ethereum',
                        'ethereum-goerli',
                        'ethereum-holesky',
                        'ethereum-sepolia',
                        'ethereum-hoodi',
                        'arbitrum',
                        'base',
                        'base-sepolia',
                        'gnosis',
                        'optimism',
                        'polygon',
                        'polygon-amoy',
                        'starknet',
                        'zksync',
                        'linea',
                        'unichain',
                        'monad-testnet',
                        'monad',
                        'avalanche-c',
                        'avalanche-c-atomic',
                        'avalanche-p',
                        'binance',
                        'celo',
                        'fantom',
                        'harmony',
                        'moonriver',
                        'okc',
                        'viction',
                        'core',
                        'sonic',
                        'plasma',
                        'katana',
                        'hyperevm',
                        'agoric',
                        'akash',
                        'axelar',
                        'band-protocol',
                        'bitsong',
                        'canto',
                        'chihuahua',
                        'comdex',
                        'coreum',
                        'cosmos',
                        'crescent',
                        'cronos',
                        'cudos',
                        'desmos',
                        'dydx',
                        'evmos',
                        'fetch-ai',
                        'gravity-bridge',
                        'injective',
                        'irisnet',
                        'juno',
                        'kava',
                        'ki-network',
                        'mars-protocol',
                        'nym',
                        'okex-chain',
                        'onomy',
                        'osmosis',
                        'persistence',
                        'quicksilver',
                        'regen',
                        'secret',
                        'sentinel',
                        'sommelier',
                        'stafi',
                        'stargaze',
                        'stride',
                        'teritori',
                        'tgrade',
                        'umee',
                        'sei',
                        'mantra',
                        'celestia',
                        'saga',
                        'zetachain',
                        'dymension',
                        'humansai',
                        'neutron',
                        'polkadot',
                        'kusama',
                        'westend',
                        'bittensor',
                        'aptos',
                        'binancebeacon',
                        'cardano',
                        'near',
                        'solana',
                        'solana-devnet',
                        'stellar',
                        'stellar-testnet',
                        'sui',
                        'tezos',
                        'tron',
                        'ton',
                        'ton-testnet',
                        'hyperliquid',
                    ])
                    .describe('The network identifier'),
                address: zod.string().optional().describe('Token address (if applicable)'),
                logoURI: zod.string().optional().describe('Token logo URI'),
                coinGeckoId: zod.string().optional().describe('Token CoinGecko ID'),
            }),
            outputToken: zod
                .object({
                    symbol: zod.string().describe('Token symbol'),
                    name: zod.string().describe('Token name'),
                    decimals: zod
                        .number()
                        .min(getYieldsResponseItemsItemOutputTokenDecimalsMin)
                        .describe('Token decimal places'),
                    network: zod
                        .enum([
                            'ethereum',
                            'ethereum-goerli',
                            'ethereum-holesky',
                            'ethereum-sepolia',
                            'ethereum-hoodi',
                            'arbitrum',
                            'base',
                            'base-sepolia',
                            'gnosis',
                            'optimism',
                            'polygon',
                            'polygon-amoy',
                            'starknet',
                            'zksync',
                            'linea',
                            'unichain',
                            'monad-testnet',
                            'monad',
                            'avalanche-c',
                            'avalanche-c-atomic',
                            'avalanche-p',
                            'binance',
                            'celo',
                            'fantom',
                            'harmony',
                            'moonriver',
                            'okc',
                            'viction',
                            'core',
                            'sonic',
                            'plasma',
                            'katana',
                            'hyperevm',
                            'agoric',
                            'akash',
                            'axelar',
                            'band-protocol',
                            'bitsong',
                            'canto',
                            'chihuahua',
                            'comdex',
                            'coreum',
                            'cosmos',
                            'crescent',
                            'cronos',
                            'cudos',
                            'desmos',
                            'dydx',
                            'evmos',
                            'fetch-ai',
                            'gravity-bridge',
                            'injective',
                            'irisnet',
                            'juno',
                            'kava',
                            'ki-network',
                            'mars-protocol',
                            'nym',
                            'okex-chain',
                            'onomy',
                            'osmosis',
                            'persistence',
                            'quicksilver',
                            'regen',
                            'secret',
                            'sentinel',
                            'sommelier',
                            'stafi',
                            'stargaze',
                            'stride',
                            'teritori',
                            'tgrade',
                            'umee',
                            'sei',
                            'mantra',
                            'celestia',
                            'saga',
                            'zetachain',
                            'dymension',
                            'humansai',
                            'neutron',
                            'polkadot',
                            'kusama',
                            'westend',
                            'bittensor',
                            'aptos',
                            'binancebeacon',
                            'cardano',
                            'near',
                            'solana',
                            'solana-devnet',
                            'stellar',
                            'stellar-testnet',
                            'sui',
                            'tezos',
                            'tron',
                            'ton',
                            'ton-testnet',
                            'hyperliquid',
                        ])
                        .describe('The network identifier'),
                    address: zod.string().optional().describe('Token address (if applicable)'),
                    logoURI: zod.string().optional().describe('Token logo URI'),
                    coinGeckoId: zod.string().optional().describe('Token CoinGecko ID'),
                })
                .optional(),
            inputTokens: zod
                .array(
                    zod.object({
                        symbol: zod.string().describe('Token symbol'),
                        name: zod.string().describe('Token name'),
                        decimals: zod
                            .number()
                            .min(getYieldsResponseItemsItemInputTokensItemDecimalsMin)
                            .describe('Token decimal places'),
                        network: zod
                            .enum([
                                'ethereum',
                                'ethereum-goerli',
                                'ethereum-holesky',
                                'ethereum-sepolia',
                                'ethereum-hoodi',
                                'arbitrum',
                                'base',
                                'base-sepolia',
                                'gnosis',
                                'optimism',
                                'polygon',
                                'polygon-amoy',
                                'starknet',
                                'zksync',
                                'linea',
                                'unichain',
                                'monad-testnet',
                                'monad',
                                'avalanche-c',
                                'avalanche-c-atomic',
                                'avalanche-p',
                                'binance',
                                'celo',
                                'fantom',
                                'harmony',
                                'moonriver',
                                'okc',
                                'viction',
                                'core',
                                'sonic',
                                'plasma',
                                'katana',
                                'hyperevm',
                                'agoric',
                                'akash',
                                'axelar',
                                'band-protocol',
                                'bitsong',
                                'canto',
                                'chihuahua',
                                'comdex',
                                'coreum',
                                'cosmos',
                                'crescent',
                                'cronos',
                                'cudos',
                                'desmos',
                                'dydx',
                                'evmos',
                                'fetch-ai',
                                'gravity-bridge',
                                'injective',
                                'irisnet',
                                'juno',
                                'kava',
                                'ki-network',
                                'mars-protocol',
                                'nym',
                                'okex-chain',
                                'onomy',
                                'osmosis',
                                'persistence',
                                'quicksilver',
                                'regen',
                                'secret',
                                'sentinel',
                                'sommelier',
                                'stafi',
                                'stargaze',
                                'stride',
                                'teritori',
                                'tgrade',
                                'umee',
                                'sei',
                                'mantra',
                                'celestia',
                                'saga',
                                'zetachain',
                                'dymension',
                                'humansai',
                                'neutron',
                                'polkadot',
                                'kusama',
                                'westend',
                                'bittensor',
                                'aptos',
                                'binancebeacon',
                                'cardano',
                                'near',
                                'solana',
                                'solana-devnet',
                                'stellar',
                                'stellar-testnet',
                                'sui',
                                'tezos',
                                'tron',
                                'ton',
                                'ton-testnet',
                                'hyperliquid',
                            ])
                            .describe('The network identifier'),
                        address: zod.string().optional().describe('Token address (if applicable)'),
                        logoURI: zod.string().optional().describe('Token logo URI'),
                        coinGeckoId: zod.string().optional().describe('Token CoinGecko ID'),
                    }),
                )
                .describe('Accepted input tokens (auto-converted as needed)'),
            rewardRate: zod.object({
                total: zod
                    .number()
                    .describe('Estimated reward rate across all sources (e.g. staking, points)'),
                rateType: zod.string().describe('Whether this reward rate is APR or APY'),
                components: zod
                    .array(
                        zod.object({
                            rate: zod
                                .number()
                                .describe('Reward rate as a decimal (e.g. 0.04 = 4%)'),
                            rateType: zod.string().describe('Whether this rate is APR or APY'),
                            token: zod.object({
                                symbol: zod.string().describe('Token symbol'),
                                name: zod.string().describe('Token name'),
                                decimals: zod
                                    .number()
                                    .min(
                                        getYieldsResponseItemsItemRewardRateComponentsItemTokenDecimalsMin,
                                    )
                                    .describe('Token decimal places'),
                                network: zod
                                    .enum([
                                        'ethereum',
                                        'ethereum-goerli',
                                        'ethereum-holesky',
                                        'ethereum-sepolia',
                                        'ethereum-hoodi',
                                        'arbitrum',
                                        'base',
                                        'base-sepolia',
                                        'gnosis',
                                        'optimism',
                                        'polygon',
                                        'polygon-amoy',
                                        'starknet',
                                        'zksync',
                                        'linea',
                                        'unichain',
                                        'monad-testnet',
                                        'monad',
                                        'avalanche-c',
                                        'avalanche-c-atomic',
                                        'avalanche-p',
                                        'binance',
                                        'celo',
                                        'fantom',
                                        'harmony',
                                        'moonriver',
                                        'okc',
                                        'viction',
                                        'core',
                                        'sonic',
                                        'plasma',
                                        'katana',
                                        'hyperevm',
                                        'agoric',
                                        'akash',
                                        'axelar',
                                        'band-protocol',
                                        'bitsong',
                                        'canto',
                                        'chihuahua',
                                        'comdex',
                                        'coreum',
                                        'cosmos',
                                        'crescent',
                                        'cronos',
                                        'cudos',
                                        'desmos',
                                        'dydx',
                                        'evmos',
                                        'fetch-ai',
                                        'gravity-bridge',
                                        'injective',
                                        'irisnet',
                                        'juno',
                                        'kava',
                                        'ki-network',
                                        'mars-protocol',
                                        'nym',
                                        'okex-chain',
                                        'onomy',
                                        'osmosis',
                                        'persistence',
                                        'quicksilver',
                                        'regen',
                                        'secret',
                                        'sentinel',
                                        'sommelier',
                                        'stafi',
                                        'stargaze',
                                        'stride',
                                        'teritori',
                                        'tgrade',
                                        'umee',
                                        'sei',
                                        'mantra',
                                        'celestia',
                                        'saga',
                                        'zetachain',
                                        'dymension',
                                        'humansai',
                                        'neutron',
                                        'polkadot',
                                        'kusama',
                                        'westend',
                                        'bittensor',
                                        'aptos',
                                        'binancebeacon',
                                        'cardano',
                                        'near',
                                        'solana',
                                        'solana-devnet',
                                        'stellar',
                                        'stellar-testnet',
                                        'sui',
                                        'tezos',
                                        'tron',
                                        'ton',
                                        'ton-testnet',
                                        'hyperliquid',
                                    ])
                                    .describe('The network identifier'),
                                address: zod
                                    .string()
                                    .optional()
                                    .describe('Token address (if applicable)'),
                                logoURI: zod.string().optional().describe('Token logo URI'),
                                coinGeckoId: zod.string().optional().describe('Token CoinGecko ID'),
                            }),
                            yieldSource: zod
                                .enum([
                                    'staking',
                                    'restaking',
                                    'protocol_incentive',
                                    'campaign_incentive',
                                    'points',
                                    'lending',
                                    'mev',
                                    'real_world_asset_yield',
                                    'vault',
                                    'lending_interest',
                                ])
                                .describe(
                                    'Structured source of yield (e.g. staking, protocol incentive).',
                                ),
                            description: zod
                                .string()
                                .optional()
                                .describe('Optional human-readable description of this reward'),
                        }),
                    )
                    .describe('Breakdown of reward rates by source'),
            }),
            status: zod.object({
                enter: zod.boolean().describe('Whether the user can currently enter this yield'),
                exit: zod.boolean().describe('Whether the user can currently exit this yield'),
            }),
            metadata: zod.object({
                name: zod.string().describe('Display name of the yield opportunity'),
                description: zod
                    .string()
                    .describe('Markdown-supported short description of this yield opportunity.'),
                underMaintenance: zod
                    .boolean()
                    .describe('Whether this yield is currently under maintenance'),
                deprecated: zod
                    .boolean()
                    .describe('Whether this yield is deprecated and will be discontinued'),
                logoURI: zod.string().optional().describe('Yield opportunity logo URI'),
            }),
            state: zod
                .object({
                    pricePerShareState: zod
                        .object({
                            price: zod
                                .string()
                                .describe(
                                    'Yield-token to underlying-token price ratio (decimal string).',
                                ),
                            shareToken: zod.object({
                                symbol: zod.string().describe('Token symbol'),
                                name: zod.string().describe('Token name'),
                                decimals: zod
                                    .number()
                                    .min(
                                        getYieldsResponseItemsItemStatePricePerShareStateShareTokenDecimalsMin,
                                    )
                                    .describe('Token decimal places'),
                                network: zod
                                    .enum([
                                        'ethereum',
                                        'ethereum-goerli',
                                        'ethereum-holesky',
                                        'ethereum-sepolia',
                                        'ethereum-hoodi',
                                        'arbitrum',
                                        'base',
                                        'base-sepolia',
                                        'gnosis',
                                        'optimism',
                                        'polygon',
                                        'polygon-amoy',
                                        'starknet',
                                        'zksync',
                                        'linea',
                                        'unichain',
                                        'monad-testnet',
                                        'monad',
                                        'avalanche-c',
                                        'avalanche-c-atomic',
                                        'avalanche-p',
                                        'binance',
                                        'celo',
                                        'fantom',
                                        'harmony',
                                        'moonriver',
                                        'okc',
                                        'viction',
                                        'core',
                                        'sonic',
                                        'plasma',
                                        'katana',
                                        'hyperevm',
                                        'agoric',
                                        'akash',
                                        'axelar',
                                        'band-protocol',
                                        'bitsong',
                                        'canto',
                                        'chihuahua',
                                        'comdex',
                                        'coreum',
                                        'cosmos',
                                        'crescent',
                                        'cronos',
                                        'cudos',
                                        'desmos',
                                        'dydx',
                                        'evmos',
                                        'fetch-ai',
                                        'gravity-bridge',
                                        'injective',
                                        'irisnet',
                                        'juno',
                                        'kava',
                                        'ki-network',
                                        'mars-protocol',
                                        'nym',
                                        'okex-chain',
                                        'onomy',
                                        'osmosis',
                                        'persistence',
                                        'quicksilver',
                                        'regen',
                                        'secret',
                                        'sentinel',
                                        'sommelier',
                                        'stafi',
                                        'stargaze',
                                        'stride',
                                        'teritori',
                                        'tgrade',
                                        'umee',
                                        'sei',
                                        'mantra',
                                        'celestia',
                                        'saga',
                                        'zetachain',
                                        'dymension',
                                        'humansai',
                                        'neutron',
                                        'polkadot',
                                        'kusama',
                                        'westend',
                                        'bittensor',
                                        'aptos',
                                        'binancebeacon',
                                        'cardano',
                                        'near',
                                        'solana',
                                        'solana-devnet',
                                        'stellar',
                                        'stellar-testnet',
                                        'sui',
                                        'tezos',
                                        'tron',
                                        'ton',
                                        'ton-testnet',
                                        'hyperliquid',
                                    ])
                                    .describe('The network identifier'),
                                address: zod
                                    .string()
                                    .optional()
                                    .describe('Token address (if applicable)'),
                                logoURI: zod.string().optional().describe('Token logo URI'),
                                coinGeckoId: zod.string().optional().describe('Token CoinGecko ID'),
                            }),
                            quoteToken: zod.object({
                                symbol: zod.string().describe('Token symbol'),
                                name: zod.string().describe('Token name'),
                                decimals: zod
                                    .number()
                                    .min(
                                        getYieldsResponseItemsItemStatePricePerShareStateQuoteTokenDecimalsMin,
                                    )
                                    .describe('Token decimal places'),
                                network: zod
                                    .enum([
                                        'ethereum',
                                        'ethereum-goerli',
                                        'ethereum-holesky',
                                        'ethereum-sepolia',
                                        'ethereum-hoodi',
                                        'arbitrum',
                                        'base',
                                        'base-sepolia',
                                        'gnosis',
                                        'optimism',
                                        'polygon',
                                        'polygon-amoy',
                                        'starknet',
                                        'zksync',
                                        'linea',
                                        'unichain',
                                        'monad-testnet',
                                        'monad',
                                        'avalanche-c',
                                        'avalanche-c-atomic',
                                        'avalanche-p',
                                        'binance',
                                        'celo',
                                        'fantom',
                                        'harmony',
                                        'moonriver',
                                        'okc',
                                        'viction',
                                        'core',
                                        'sonic',
                                        'plasma',
                                        'katana',
                                        'hyperevm',
                                        'agoric',
                                        'akash',
                                        'axelar',
                                        'band-protocol',
                                        'bitsong',
                                        'canto',
                                        'chihuahua',
                                        'comdex',
                                        'coreum',
                                        'cosmos',
                                        'crescent',
                                        'cronos',
                                        'cudos',
                                        'desmos',
                                        'dydx',
                                        'evmos',
                                        'fetch-ai',
                                        'gravity-bridge',
                                        'injective',
                                        'irisnet',
                                        'juno',
                                        'kava',
                                        'ki-network',
                                        'mars-protocol',
                                        'nym',
                                        'okex-chain',
                                        'onomy',
                                        'osmosis',
                                        'persistence',
                                        'quicksilver',
                                        'regen',
                                        'secret',
                                        'sentinel',
                                        'sommelier',
                                        'stafi',
                                        'stargaze',
                                        'stride',
                                        'teritori',
                                        'tgrade',
                                        'umee',
                                        'sei',
                                        'mantra',
                                        'celestia',
                                        'saga',
                                        'zetachain',
                                        'dymension',
                                        'humansai',
                                        'neutron',
                                        'polkadot',
                                        'kusama',
                                        'westend',
                                        'bittensor',
                                        'aptos',
                                        'binancebeacon',
                                        'cardano',
                                        'near',
                                        'solana',
                                        'solana-devnet',
                                        'stellar',
                                        'stellar-testnet',
                                        'sui',
                                        'tezos',
                                        'tron',
                                        'ton',
                                        'ton-testnet',
                                        'hyperliquid',
                                    ])
                                    .describe('The network identifier'),
                                address: zod
                                    .string()
                                    .optional()
                                    .describe('Token address (if applicable)'),
                                logoURI: zod.string().optional().describe('Token logo URI'),
                                coinGeckoId: zod.string().optional().describe('Token CoinGecko ID'),
                            }),
                        })
                        .optional(),
                })
                .optional(),
        }),
    ),
    total: zod.number().min(getYieldsResponseTotalMin).describe('Total number of items available'),
    offset: zod.number().min(getYieldsResponseOffsetMin).describe('Offset of the current page'),
    limit: zod
        .number()
        .gt(getYieldsResponseLimitExclusiveMin)
        .describe('Limit of the current page'),
});

/**
 * @summary Generate transactions to enter a yield position
 */
export const enterYieldHeaderXSuiteVersionRegExp = new RegExp('^(\\d+)\\.(\\d+)\\.(\\d+)$');

export const enterYieldHeader = zod.object({
    'x-suite-version': zod
        .string()
        .regex(enterYieldHeaderXSuiteVersionRegExp)
        .describe('Caller suite semver (e.g. 25.10.0). Used to scope vault allow-list.'),
});

export const enterYieldBody = zod.object({
    yieldId: zod.string().min(1).describe('Yield ID to perform the action on'),
    address: zod.string().min(1).describe('User wallet address'),
    arguments: zod
        .object({
            amount: zod
                .string()
                .min(1)
                .describe(
                    'Amount in human-readable token units (1.5 means 1.5 USDC), not the smallest denomination.',
                ),
        })
        .describe('Arguments for the action'),
});

export const enterYieldResponseOneTransactionsItemStepIndexMin = 0;

export const enterYieldResponse = zod
    .object({
        id: zod.string().describe('Unique action identifier'),
        yieldId: zod.string().describe('Yield ID this action belongs to'),
        address: zod.string().describe('User wallet address'),
        intent: zod.enum(['enter', 'manage', 'exit']).describe('High-level action intent'),
        type: zod
            .enum([
                'STAKE',
                'UNSTAKE',
                'CLAIM_REWARDS',
                'AUTO_SWEEP_UNSTAKE_REWARDS',
                'AUTO_SWEEP_WITHDRAW_REWARDS',
                'RESTAKE_REWARDS',
                'WITHDRAW',
                'WITHDRAW_ALL',
                'RESTAKE',
                'CLAIM_UNSTAKED',
                'UNLOCK_LOCKED',
                'STAKE_LOCKED',
                'VOTE',
                'REVOKE',
                'VOTE_LOCKED',
                'REVOTE',
                'REBOND',
                'MIGRATE',
                'VERIFY_WITHDRAW_CREDENTIALS',
                'DELEGATE',
            ])
            .describe('Specific action type'),
        amount: zod
            .string()
            .nullable()
            .describe(
                'Amount involved in the action, in human-readable token units (not the smallest denomination).',
            ),
        amountRaw: zod
            .string()
            .nullable()
            .describe('Raw smallest-denomination amount (full precision)'),
        amountUsd: zod.string().nullable().describe('USD value of the amount'),
        transactions: zod
            .array(
                zod.object({
                    id: zod.string().describe('Unique transaction identifier'),
                    network: zod
                        .enum([
                            'ethereum',
                            'ethereum-goerli',
                            'ethereum-holesky',
                            'ethereum-sepolia',
                            'ethereum-hoodi',
                            'arbitrum',
                            'base',
                            'base-sepolia',
                            'gnosis',
                            'optimism',
                            'polygon',
                            'polygon-amoy',
                            'starknet',
                            'zksync',
                            'linea',
                            'unichain',
                            'monad-testnet',
                            'monad',
                            'avalanche-c',
                            'avalanche-c-atomic',
                            'avalanche-p',
                            'binance',
                            'celo',
                            'fantom',
                            'harmony',
                            'moonriver',
                            'okc',
                            'viction',
                            'core',
                            'sonic',
                            'plasma',
                            'katana',
                            'hyperevm',
                            'agoric',
                            'akash',
                            'axelar',
                            'band-protocol',
                            'bitsong',
                            'canto',
                            'chihuahua',
                            'comdex',
                            'coreum',
                            'cosmos',
                            'crescent',
                            'cronos',
                            'cudos',
                            'desmos',
                            'dydx',
                            'evmos',
                            'fetch-ai',
                            'gravity-bridge',
                            'injective',
                            'irisnet',
                            'juno',
                            'kava',
                            'ki-network',
                            'mars-protocol',
                            'nym',
                            'okex-chain',
                            'onomy',
                            'osmosis',
                            'persistence',
                            'quicksilver',
                            'regen',
                            'secret',
                            'sentinel',
                            'sommelier',
                            'stafi',
                            'stargaze',
                            'stride',
                            'teritori',
                            'tgrade',
                            'umee',
                            'sei',
                            'mantra',
                            'celestia',
                            'saga',
                            'zetachain',
                            'dymension',
                            'humansai',
                            'neutron',
                            'polkadot',
                            'kusama',
                            'westend',
                            'bittensor',
                            'aptos',
                            'binancebeacon',
                            'cardano',
                            'near',
                            'solana',
                            'solana-devnet',
                            'stellar',
                            'stellar-testnet',
                            'sui',
                            'tezos',
                            'tron',
                            'ton',
                            'ton-testnet',
                            'hyperliquid',
                        ])
                        .describe('The network identifier'),
                    status: zod
                        .enum([
                            'NOT_FOUND',
                            'CREATED',
                            'BLOCKED',
                            'WAITING_FOR_SIGNATURE',
                            'SIGNED',
                            'BROADCASTED',
                            'PENDING',
                            'CONFIRMED',
                            'FAILED',
                            'SKIPPED',
                        ])
                        .describe('Current status of the transaction'),
                    type: zod
                        .enum([
                            'SWAP',
                            'DEPOSIT',
                            'APPROVAL',
                            'STAKE',
                            'CLAIM_UNSTAKED',
                            'CLAIM_REWARDS',
                            'RESTAKE_REWARDS',
                            'UNSTAKE',
                            'SPLIT',
                            'MERGE',
                            'LOCK',
                            'UNLOCK',
                            'SUPPLY',
                            'ADD_LIQUIDITY',
                            'REMOVE_LIQUIDITY',
                            'BRIDGE',
                            'VOTE',
                            'REVOKE',
                            'RESTAKE',
                            'REBOND',
                            'WITHDRAW',
                            'WITHDRAW_ALL',
                            'CREATE_ACCOUNT',
                            'REVEAL',
                            'MIGRATE',
                            'DELEGATE',
                            'UNDELEGATE',
                            'UTXO_P_TO_C_IMPORT',
                            'UTXO_C_TO_P_IMPORT',
                            'WRAP',
                            'UNWRAP',
                            'UNFREEZE_LEGACY',
                            'UNFREEZE_LEGACY_BANDWIDTH',
                            'UNFREEZE_LEGACY_ENERGY',
                            'UNFREEZE_BANDWIDTH',
                            'UNFREEZE_ENERGY',
                            'FREEZE_BANDWIDTH',
                            'FREEZE_ENERGY',
                            'UNDELEGATE_BANDWIDTH',
                            'UNDELEGATE_ENERGY',
                            'P2P_NODE_REQUEST',
                            'CREATE_EIGENPOD',
                            'VERIFY_WITHDRAW_CREDENTIALS',
                            'START_CHECKPOINT',
                            'VERIFY_CHECKPOINT_PROOFS',
                            'QUEUE_WITHDRAWALS',
                            'COMPLETE_QUEUED_WITHDRAWALS',
                            'LZ_DEPOSIT',
                            'LZ_WITHDRAW',
                            'LUGANODES_PROVISION',
                            'LUGANODES_EXIT_REQUEST',
                            'INFSTONES_PROVISION',
                            'INFSTONES_EXIT_REQUEST',
                            'INFSTONES_CLAIM_REQUEST',
                            'BATCH',
                        ])
                        .describe('Type of transaction operation'),
                    hash: zod
                        .string()
                        .nullable()
                        .describe('Transaction hash (available after broadcast)'),
                    unsignedTransaction: zod
                        .union([zod.string(), zod.record(zod.string(), zod.unknown()), zod.null()])
                        .describe('The unsigned transaction data to be signed by the wallet'),
                    signedTransaction: zod
                        .string()
                        .nullish()
                        .describe('Signed transaction data (ready for broadcast)'),
                    stepIndex: zod
                        .number()
                        .min(enterYieldResponseOneTransactionsItemStepIndexMin)
                        .optional()
                        .describe('Zero-based index of the step in the action flow'),
                    isMessage: zod
                        .boolean()
                        .optional()
                        .describe(
                            'Whether this transaction is a message rather than a value transfer',
                        ),
                }),
            )
            .describe('Array of transactions for this action'),
        executionPattern: zod
            .enum(['synchronous', 'asynchronous', 'batch'])
            .describe(
                'Transaction execution pattern - synchronous (submit one by one, wait for each), asynchronous (submit all at once), or batch.',
            ),
        createdAt: zod.string().describe('When the action was created'),
        completedAt: zod.string().nullable().describe('When the action was completed'),
        status: zod
            .enum([
                'CANCELED',
                'CREATED',
                'WAITING_FOR_NEXT',
                'PROCESSING',
                'FAILED',
                'SUCCESS',
                'STALE',
            ])
            .describe('Current status of the action'),
    })
    .and(
        zod.object({
            vaultAddress: zod.string(),
        }),
    );

/**
 * @summary Generate transactions to exit a yield position
 */
export const exitYieldHeaderXSuiteVersionRegExp = new RegExp('^(\\d+)\\.(\\d+)\\.(\\d+)$');

export const exitYieldHeader = zod.object({
    'x-suite-version': zod
        .string()
        .regex(exitYieldHeaderXSuiteVersionRegExp)
        .describe('Caller suite semver (e.g. 25.10.0). Used to scope vault allow-list.'),
});

export const exitYieldBody = zod.object({
    yieldId: zod.string().min(1).describe('Yield ID to perform the action on'),
    address: zod.string().min(1).describe('User wallet address'),
    arguments: zod
        .object({
            amount: zod
                .string()
                .min(1)
                .describe(
                    'Amount in human-readable token units (1.5 means 1.5 USDC), not the smallest denomination.',
                ),
        })
        .describe('Arguments for the action'),
});

export const exitYieldResponseOneTransactionsItemStepIndexMin = 0;

export const exitYieldResponse = zod
    .object({
        id: zod.string().describe('Unique action identifier'),
        yieldId: zod.string().describe('Yield ID this action belongs to'),
        address: zod.string().describe('User wallet address'),
        intent: zod.enum(['enter', 'manage', 'exit']).describe('High-level action intent'),
        type: zod
            .enum([
                'STAKE',
                'UNSTAKE',
                'CLAIM_REWARDS',
                'AUTO_SWEEP_UNSTAKE_REWARDS',
                'AUTO_SWEEP_WITHDRAW_REWARDS',
                'RESTAKE_REWARDS',
                'WITHDRAW',
                'WITHDRAW_ALL',
                'RESTAKE',
                'CLAIM_UNSTAKED',
                'UNLOCK_LOCKED',
                'STAKE_LOCKED',
                'VOTE',
                'REVOKE',
                'VOTE_LOCKED',
                'REVOTE',
                'REBOND',
                'MIGRATE',
                'VERIFY_WITHDRAW_CREDENTIALS',
                'DELEGATE',
            ])
            .describe('Specific action type'),
        amount: zod
            .string()
            .nullable()
            .describe(
                'Amount involved in the action, in human-readable token units (not the smallest denomination).',
            ),
        amountRaw: zod
            .string()
            .nullable()
            .describe('Raw smallest-denomination amount (full precision)'),
        amountUsd: zod.string().nullable().describe('USD value of the amount'),
        transactions: zod
            .array(
                zod.object({
                    id: zod.string().describe('Unique transaction identifier'),
                    network: zod
                        .enum([
                            'ethereum',
                            'ethereum-goerli',
                            'ethereum-holesky',
                            'ethereum-sepolia',
                            'ethereum-hoodi',
                            'arbitrum',
                            'base',
                            'base-sepolia',
                            'gnosis',
                            'optimism',
                            'polygon',
                            'polygon-amoy',
                            'starknet',
                            'zksync',
                            'linea',
                            'unichain',
                            'monad-testnet',
                            'monad',
                            'avalanche-c',
                            'avalanche-c-atomic',
                            'avalanche-p',
                            'binance',
                            'celo',
                            'fantom',
                            'harmony',
                            'moonriver',
                            'okc',
                            'viction',
                            'core',
                            'sonic',
                            'plasma',
                            'katana',
                            'hyperevm',
                            'agoric',
                            'akash',
                            'axelar',
                            'band-protocol',
                            'bitsong',
                            'canto',
                            'chihuahua',
                            'comdex',
                            'coreum',
                            'cosmos',
                            'crescent',
                            'cronos',
                            'cudos',
                            'desmos',
                            'dydx',
                            'evmos',
                            'fetch-ai',
                            'gravity-bridge',
                            'injective',
                            'irisnet',
                            'juno',
                            'kava',
                            'ki-network',
                            'mars-protocol',
                            'nym',
                            'okex-chain',
                            'onomy',
                            'osmosis',
                            'persistence',
                            'quicksilver',
                            'regen',
                            'secret',
                            'sentinel',
                            'sommelier',
                            'stafi',
                            'stargaze',
                            'stride',
                            'teritori',
                            'tgrade',
                            'umee',
                            'sei',
                            'mantra',
                            'celestia',
                            'saga',
                            'zetachain',
                            'dymension',
                            'humansai',
                            'neutron',
                            'polkadot',
                            'kusama',
                            'westend',
                            'bittensor',
                            'aptos',
                            'binancebeacon',
                            'cardano',
                            'near',
                            'solana',
                            'solana-devnet',
                            'stellar',
                            'stellar-testnet',
                            'sui',
                            'tezos',
                            'tron',
                            'ton',
                            'ton-testnet',
                            'hyperliquid',
                        ])
                        .describe('The network identifier'),
                    status: zod
                        .enum([
                            'NOT_FOUND',
                            'CREATED',
                            'BLOCKED',
                            'WAITING_FOR_SIGNATURE',
                            'SIGNED',
                            'BROADCASTED',
                            'PENDING',
                            'CONFIRMED',
                            'FAILED',
                            'SKIPPED',
                        ])
                        .describe('Current status of the transaction'),
                    type: zod
                        .enum([
                            'SWAP',
                            'DEPOSIT',
                            'APPROVAL',
                            'STAKE',
                            'CLAIM_UNSTAKED',
                            'CLAIM_REWARDS',
                            'RESTAKE_REWARDS',
                            'UNSTAKE',
                            'SPLIT',
                            'MERGE',
                            'LOCK',
                            'UNLOCK',
                            'SUPPLY',
                            'ADD_LIQUIDITY',
                            'REMOVE_LIQUIDITY',
                            'BRIDGE',
                            'VOTE',
                            'REVOKE',
                            'RESTAKE',
                            'REBOND',
                            'WITHDRAW',
                            'WITHDRAW_ALL',
                            'CREATE_ACCOUNT',
                            'REVEAL',
                            'MIGRATE',
                            'DELEGATE',
                            'UNDELEGATE',
                            'UTXO_P_TO_C_IMPORT',
                            'UTXO_C_TO_P_IMPORT',
                            'WRAP',
                            'UNWRAP',
                            'UNFREEZE_LEGACY',
                            'UNFREEZE_LEGACY_BANDWIDTH',
                            'UNFREEZE_LEGACY_ENERGY',
                            'UNFREEZE_BANDWIDTH',
                            'UNFREEZE_ENERGY',
                            'FREEZE_BANDWIDTH',
                            'FREEZE_ENERGY',
                            'UNDELEGATE_BANDWIDTH',
                            'UNDELEGATE_ENERGY',
                            'P2P_NODE_REQUEST',
                            'CREATE_EIGENPOD',
                            'VERIFY_WITHDRAW_CREDENTIALS',
                            'START_CHECKPOINT',
                            'VERIFY_CHECKPOINT_PROOFS',
                            'QUEUE_WITHDRAWALS',
                            'COMPLETE_QUEUED_WITHDRAWALS',
                            'LZ_DEPOSIT',
                            'LZ_WITHDRAW',
                            'LUGANODES_PROVISION',
                            'LUGANODES_EXIT_REQUEST',
                            'INFSTONES_PROVISION',
                            'INFSTONES_EXIT_REQUEST',
                            'INFSTONES_CLAIM_REQUEST',
                            'BATCH',
                        ])
                        .describe('Type of transaction operation'),
                    hash: zod
                        .string()
                        .nullable()
                        .describe('Transaction hash (available after broadcast)'),
                    unsignedTransaction: zod
                        .union([zod.string(), zod.record(zod.string(), zod.unknown()), zod.null()])
                        .describe('The unsigned transaction data to be signed by the wallet'),
                    signedTransaction: zod
                        .string()
                        .nullish()
                        .describe('Signed transaction data (ready for broadcast)'),
                    stepIndex: zod
                        .number()
                        .min(exitYieldResponseOneTransactionsItemStepIndexMin)
                        .optional()
                        .describe('Zero-based index of the step in the action flow'),
                    isMessage: zod
                        .boolean()
                        .optional()
                        .describe(
                            'Whether this transaction is a message rather than a value transfer',
                        ),
                }),
            )
            .describe('Array of transactions for this action'),
        executionPattern: zod
            .enum(['synchronous', 'asynchronous', 'batch'])
            .describe(
                'Transaction execution pattern - synchronous (submit one by one, wait for each), asynchronous (submit all at once), or batch.',
            ),
        createdAt: zod.string().describe('When the action was created'),
        completedAt: zod.string().nullable().describe('When the action was completed'),
        status: zod
            .enum([
                'CANCELED',
                'CREATED',
                'WAITING_FOR_NEXT',
                'PROCESSING',
                'FAILED',
                'SUCCESS',
                'STALE',
            ])
            .describe('Current status of the action'),
    })
    .and(
        zod.object({
            vaultAddress: zod.string(),
        }),
    );

/**
 * @summary List claimable Merkl rewards for a user (per chain)
 */
export const getMerkleUserRewardsPathAddressRegExp = new RegExp('^0x[a-fA-F0-9]{40}$');

export const getMerkleUserRewardsParams = zod.object({
    address: zod.string().regex(getMerkleUserRewardsPathAddressRegExp),
});

export const getMerkleUserRewardsQueryParams = zod.object({
    chainId: zod.union([zod.number().nullable(), zod.string(), zod.null()]).optional(),
    claimableOnly: zod.boolean().nullish(),
    reloadChainId: zod.union([zod.number().nullable(), zod.string(), zod.null()]).optional(),
});

export const getMerkleUserRewardsResponseItem = zod.object({
    chain: zod.object({
        id: zod.number().min(1).describe('EVM chain id'),
        name: zod.string().describe('Human-readable chain name'),
    }),
    rewards: zod.array(
        zod.object({
            root: zod.string().describe('Merkle root committing this reward distribution'),
            amount: zod.string().describe('Total reward amount accrued (smallest denomination)'),
            claimed: zod.string().describe('Amount already claimed (smallest denomination)'),
            pending: zod.string().describe('Pending reward amount (smallest denomination)'),
            token: zod.object({
                address: zod.string().describe('ERC-20 token contract address'),
                chainId: zod.number().describe('EVM chain id this token lives on'),
                symbol: zod.string().describe('Token symbol (e.g. USDC)'),
                decimals: zod.number().describe('Token decimals'),
            }),
            proofs: zod.array(zod.string()).describe('Merkle proof nodes for claiming'),
        }),
    ),
});
export const getMerkleUserRewardsResponse = zod.array(getMerkleUserRewardsResponseItem);

/**
 * @summary List allow-listed yield vaults per network
 */
export const getYieldVaultsHeaderXSuiteVersionOneRegExp = new RegExp('^(\\d+)\\.(\\d+)\\.(\\d+)$');

export const getYieldVaultsHeader = zod.object({
    'x-suite-version': zod
        .union([
            zod.string().regex(getYieldVaultsHeaderXSuiteVersionOneRegExp),
            zod.enum(['latest']),
        ])
        .describe(
            'Caller suite semver (e.g. 25.10.0) or the literal `latest` to bypass the vault `suiteVersion` interval.',
        ),
});

export const getYieldVaultsResponse = zod.object({
    eth: zod
        .array(
            zod.object({
                yieldId: zod.string(),
                address: zod.string(),
            }),
        )
        .optional(),
    op: zod
        .array(
            zod.object({
                yieldId: zod.string(),
                address: zod.string(),
            }),
        )
        .optional(),
    arb: zod
        .array(
            zod.object({
                yieldId: zod.string(),
                address: zod.string(),
            }),
        )
        .optional(),
    base: zod
        .array(
            zod.object({
                yieldId: zod.string(),
                address: zod.string(),
            }),
        )
        .optional(),
});

/**
 * @summary Get details of a specific vault by its ID and network symbol
 */
export const getYieldVaultParams = zod.object({
    networkSymbol: zod.enum(['eth', 'op', 'arb', 'base']),
    vaultId: zod.string(),
});

export const getYieldVaultHeaderXSuiteVersionOneRegExp = new RegExp('^(\\d+)\\.(\\d+)\\.(\\d+)$');

export const getYieldVaultHeader = zod.object({
    'x-suite-version': zod
        .union([
            zod.string().regex(getYieldVaultHeaderXSuiteVersionOneRegExp),
            zod.enum(['latest']),
        ])
        .describe(
            'Caller suite semver (e.g. 25.10.0) or the literal `latest` to bypass the vault `suiteVersion` interval.',
        ),
});

export const getYieldVaultResponse = zod.object({
    address: zod.string(),
});
