version: '3.3'
services:
  # trezor-env:
  #   build: '../../docker/trezor-env'
  #   # image: trezor-env:latest
  #   ports:
  #   - "21325:21325"
  #   - "9001:9001"
  # test-source: 
  webserver:
    build: 
      context: .
      dockerfile: ./packages/integration-tests/docker/webserver/Dockerfile
      # args:
      #   tag: "webserver"
    # links:
    # - trezor-env
    # volumes:
    # - "./:/suite"

