export const GET_FEATURES = 'getFeatures';
// export const FIRMWARE_UPDATE = 'firmwareUpdate';
export const RESET_DEVICE = 'resetDevice';
export const BACKUP_DEVICE = 'backupDevice';
export const APPLY_SETTINGS = 'applySettings';
export const APPLY_FLAGS = 'applyFlags';
export const CHANGE_PIN = 'changePin';
export const RECOVER_DEVICE = 'recoveryDevice';
export const WIPE_DEVICE = 'wipeDevice';
