/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Trezor Earn Yield API
 * OpenAPI spec version: 0.1.0
 */

export type MerklChain = {
    /**
     * EVM chain id
     * @minimum 1
     */
    id: number;
    /** Human-readable chain name */
    name: string;
};
