/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Trezor Earn Yield API
 * OpenAPI spec version: 0.1.0
 */
import type { MerkleUserChainRewards } from './merkleUserChainRewards';

export type MerkleUserRewardsResponse = MerkleUserChainRewards[];
