/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Trezor Earn Yield API
 * OpenAPI spec version: 0.1.0
 */
import type { MerklTokenRef } from './merklTokenRef';

export type MerklClaimableReward = {
    /** Merkl root committing this reward distribution */
    root: string;
    /**
     * Total reward amount accrued (smallest denomination)
     * @pattern ^\d+$
     */
    amount: string;
    /**
     * Amount already claimed (smallest denomination)
     * @pattern ^\d+$
     */
    claimed: string;
    /**
     * Pending reward amount (smallest denomination)
     * @pattern ^\d+$
     */
    pending: string;
    token: MerklTokenRef;
    /** Merkl proof nodes for claiming */
    proofs: string[];
};
