/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Trezor Earn Yield API
 * OpenAPI spec version: 0.1.0
 */
import type { MerkleTokenRef } from './merkleTokenRef';

export type MerkleClaimableReward = {
    /** Merkle root committing this reward distribution */
    root: string;
    /** Total reward amount accrued (smallest denomination) */
    amount: string;
    /** Amount already claimed (smallest denomination) */
    claimed: string;
    /** Pending reward amount (smallest denomination) */
    pending: string;
    token: MerkleTokenRef;
    /** Merkle proof nodes for claiming */
    proofs: string[];
};
