/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Trezor Earn Yield API
 * OpenAPI spec version: 0.1.0
 */
import type { NetworkDtoId } from './networkDtoId';

export type TokenDto = {
    /** Token symbol */
    symbol: string;
    /** Token name */
    name: string;
    /**
     * Token decimal places
     * @minimum 0
     */
    decimals: number;
    network: NetworkDtoId;
    /** Token address (if applicable) */
    address?: string;
    /** Token logo URI */
    logoURI?: string;
    /** Token CoinGecko ID */
    coinGeckoId?: string;
};
