/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Trezor Earn Yield API
 * OpenAPI spec version: 0.1.0
 */
import type { NetworkDtoId } from './networkDtoId';
import type { TransactionDtoStatus } from './transactionDtoStatus';
import type { TransactionDtoType } from './transactionDtoType';
import type { TransactionDtoUnsignedTransaction } from './transactionDtoUnsignedTransaction';

export type TransactionDto = {
    /** Unique transaction identifier */
    id: string;
    network: NetworkDtoId;
    /** Current status of the transaction */
    status: TransactionDtoStatus;
    /** Type of transaction operation */
    type: TransactionDtoType;
    /**
     * Transaction hash (available after broadcast)
     * @nullable
     */
    hash: string | null;
    /** The unsigned transaction data to be signed by the wallet */
    unsignedTransaction: TransactionDtoUnsignedTransaction;
    /**
     * Signed transaction data (ready for broadcast)
     * @nullable
     */
    signedTransaction?: string | null;
    /**
     * Zero-based index of the step in the action flow
     * @minimum 0
     */
    stepIndex?: number;
    /** Whether this transaction is a message rather than a value transfer */
    isMessage?: boolean;
};
