/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Trezor Earn Yield API
 * OpenAPI spec version: 0.1.0
 */

/**
 * The unsigned transaction data to be signed by the wallet
 */
export type TransactionDtoUnsignedTransaction = string | { [key: string]: unknown } | null;
