/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Trezor Earn Yield API
 * OpenAPI spec version: 0.1.0
 */
import type { YieldDto } from './yieldDto';

export type YieldsResponse = {
    items: YieldDto[];
    /**
     * Total number of items available
     * @minimum 0
     */
    total: number;
    /**
     * Offset of the current page
     * @minimum 0
     */
    offset: number;
    /**
     * Limit of the current page
     * @exclusiveMinimum 0
     */
    limit: number;
};
