/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Trezor Earn Yield API
 * OpenAPI spec version: 0.1.0
 */
import type { TokenDto } from './tokenDto';

export type YieldDtoStatePricePerShareState = {
    /** Yield-token to underlying-token price ratio (decimal string). */
    price: string;
    shareToken: TokenDto;
    quoteToken: TokenDto;
};
