export const GUIDE_ARTICLE_IDS = {
    addAccount: '/2_dashboard-and-coins/2_add-a-new-account.md',
    activateAssets: '/2_dashboard-and-coins/1_activate-new-coins.md',
    addingTokens: '/2_dashboard-and-coins/6_adding-new-tokens.md',
    application: '/6_suite-settings/application/4_application.md',
    autoEjectWallets: '/1_initialize-and-secure-your-trezor/8_remember-and-eject.md',
    bitcoinOnlyFirmware: '/6_suite-settings/device/2_firmware.md',
    buy: '/4_buy-sell-and-exchange/fiat-to-cryptocurrency/buy.md',
    cardanoStaking: '/2_dashboard-and-coins/advanced-features/cardano-ada-staking.md',
    coinControl: '/3_send-and-receive/transactions-in-depth/coin-control.md',
    connectOwnNode:
        '/2_dashboard-and-coins/advanced-features/connect-own-node-via-electrum-server.md',
    destinationTags: '/3_send-and-receive/transactions-in-depth/destination-tags.md',
    discreetMode: '/2_dashboard-and-coins/3_discreet-mode.md',
    ethereumStaking: '/2_dashboard-and-coins/advanced-features/ethereum-eth-staking.md',
    exchange: '/4_buy-sell-and-exchange/cryptocurrency-to-cryptocurrency/exchange.md',
    experimentalFeatures: '/6_suite-settings/application/5_experimental-features.md',
    installFirmware: '/1_initialize-and-secure-your-trezor/1_install-firmware.md',
    labeling: '/6_suite-settings/application/2_labeling.md',
    localization: '/6_suite-settings/application/1_localization.md',
    locktime: '/3_send-and-receive/transactions-in-depth/locktime.md',
    opReturn: '/3_send-and-receive/transactions-in-depth/op_return.md',
    passphrase: '/1_initialize-and-secure-your-trezor/6_passphrase.md',
    receivingCrypto: '/3_send-and-receive/2_receiving-crypto.md',
    replaceByFee: '/3_send-and-receive/5_replace-by-fee-rbf.md',
    sell: '/4_buy-sell-and-exchange/cryptocurrency-to-fiat/sell.md',
    sendRaw: '/3_send-and-receive/transactions-in-depth/send-raw.md',
    sendingCrypto: '/3_send-and-receive/1_sending-crypto.md',
    signAndVerify: '/3_send-and-receive/4_sign-and-verify.md',
    solanaStaking: '/2_dashboard-and-coins/advanced-features/solana-sol-staking.md',
    supportedCoins: '/1_initialize-and-secure-your-trezor/4_supported-coins.md',
    transactionFees: '/3_send-and-receive/3_transaction-fees.md',
    tor: '/6_suite-settings/application/3_tor.md',
    uriHandlers: '/3_send-and-receive/transactions-in-depth/uri-handlers.md',
    walletBackup: '/6_suite-settings/device/1_wallet-backup.md',
    wipeCode: '/1_initialize-and-secure-your-trezor/9_set-a-wipe-code.md',
} as const;

export type GuideArticleId = (typeof GUIDE_ARTICLE_IDS)[keyof typeof GUIDE_ARTICLE_IDS];
