import { DeviceModelInternal } from '@trezor/connect';

export const homescreens = {
    [DeviceModelInternal.T1B1]: [
        'original_t1b1', // note - has to be first
        'blank',
        'circleweb',
        'circuit',
        'starweb',
        'stars',
        'bitcoin_b2',
        'bitcoin_shade',
        'bitcoin_b',
        'bitcoin_full',
        'bitcat',
        'nyancat',
        'coffee',
        'flower',
        'saturn',
        'jupiter',
        'einstein',
        'piggy',
        'honeybadger',
        'dragon',
        'narwal',
        'rabbit',
        'bunny',
        'rooster',
        'fancy',
        'genesis',
        'my_bank',
        'candle',
        'ancap',
        'anonymous',
        'mushroom',
        'invader',
        'mtgox',
        'electrum',
        'mycelium',
        'multibit',
        'reddit',
        'hacker',
        'polis',
        'carlos',
    ],
    [DeviceModelInternal.T2B1]: [
        'original_t2b1', // note - has to be first
        'blank',
        'circleweb',
        'circuit',
        'jupiter',
        'saturn',
        'starweb',
    ],
    [DeviceModelInternal.T2T1]: [
        'stain-1',
        'stain-2',
        'stain-3',
        'trezor-3d',
        'trezor',
        'pigeon',
        'smile-1',
        'smile-2',
    ],
} as const;
