export const homescreensBW64x128 = [
    'original', // note - has to be first
    'blank',
    'circleweb',
    'circuit',
    'starweb',
    'stars',
    'bitcoin_b2',
    'bitcoin_shade',
    'bitcoin_b',
    'bitcoin_full',
    'bitcat',
    'nyancat',
    'coffee',
    'flower',
    'saturn',
    'jupiter',
    'einstein',
    'piggy',
    'honeybadger',
    'dragon',
    'narwal',
    'rabbit',
    'bunny',
    'rooster',
    'fancy',
    'genesis',
    'my_bank',
    'candle',
    'ancap',
    'anonymous',
    'mushroom',
    'invader',
    'mtgox',
    'electrum',
    'mycelium',
    'multibit',
    'reddit',
    'hacker',
    'polis',
    'carlos',
] as const;

export const homescreensColor240x240 = [
    'stain-1',
    'stain-2',
    'stain-3',
    'trezor-3d',
    'trezor',
    'pigeon',
    'smile-1',
    'smile-2',
] as const;
