export const calculate = [
    {
        description: 'Legacy fee, no token, tx should pass',
        input: {
            availableBalance: '1000000000000000000',
            output: { type: 'payment' as const, address: 'A', amount: '1' },
            feeLevel: { label: 'normal' as const, feePerUnit: '10', feeLimit: '21000', blocks: -1 },
            token: undefined,
        },
        result: {
            max: undefined,
            bytes: 0,
            fee: '210000000000000',
            feeLimit: '21000',
            feePerByte: '10',
            inputs: [],
            maxFeePerGas: undefined,
            maxPriorityFeePerGas: undefined,
            outputs: [
                {
                    address: 'A',
                    amount: '1',
                    script_type: 'PAYTOADDRESS',
                },
            ],
            outputsPermutation: [0],
            token: undefined,
            totalSpent: '210000000000001',
            type: 'final',
        },
    },
    {
        description: 'Legacy fee, no token, balance is not enough',
        input: {
            availableBalance: '1000',
            output: { type: 'payment' as const, address: 'A', amount: '1' },
            feeLevel: { label: 'normal' as const, feePerUnit: '10', feeLimit: '21000', blocks: -1 },
            token: undefined,
        },
        result: {
            type: 'error',
            error: 'AMOUNT_IS_NOT_ENOUGH',
            errorMessage: {
                id: 'AMOUNT_IS_NOT_ENOUGH',
            },
        },
    },
    {
        description: 'Legacy fee, token transfer,  tx should pass',
        input: {
            availableBalance: '1000000000000000000',
            output: { type: 'payment' as const, address: 'A', amount: '1' },
            feeLevel: { label: 'normal' as const, feePerUnit: '10', feeLimit: '21000', blocks: -1 },
            token: {
                type: 'ERC20',
                standard: 'ERC20',
                contract: '0x123',
                symbol: 'test',
                decimals: 18,
                balance: '100',
            },
        },
        result: {
            max: undefined,
            bytes: 0,
            fee: '210000000000000',
            feeLimit: '21000',
            feePerByte: '10',
            inputs: [],
            maxFeePerGas: undefined,
            maxPriorityFeePerGas: undefined,
            outputs: [
                {
                    address: 'A',
                    amount: '1',
                    script_type: 'PAYTOADDRESS',
                },
            ],
            outputsPermutation: [0],
            token: {
                type: 'ERC20',
                standard: 'ERC20',
                contract: '0x123',
                symbol: 'test',
                decimals: 18,
                balance: '100',
            },
            totalSpent: '1',
            type: 'final',
        },
    },
    {
        description: 'Legacy fee, token transfer, ETH balance insufficient for gas fees',
        input: {
            availableBalance: '100000',
            output: { type: 'payment' as const, address: 'A', amount: '101' },
            feeLevel: { label: 'normal' as const, feePerUnit: '10', feeLimit: '21000', blocks: -1 },
            token: {
                type: 'ERC20',
                standard: 'ERC20',
                contract: '0x123',
                symbol: 'test',
                decimals: 18,
                balance: '1',
            },
        },
        result: {
            type: 'error',
            error: 'AMOUNT_NOT_ENOUGH_CURRENCY_FEE_WITH_ETH_AMOUNT',
            errorMessage: {
                id: 'AMOUNT_NOT_ENOUGH_CURRENCY_FEE_WITH_ETH_AMOUNT',
                values: { feeAmount: '0.00021' },
            },
        },
    },
    {
        description: 'Eip1559 fee, no token, tx should pass',
        input: {
            availableBalance: '1000000000000000000',
            output: { type: 'payment' as const, address: 'A', amount: '1' },
            feeLevel: {
                label: 'low' as const,
                feeLimit: '21000',
                feePerUnit: '0',
                maxFeePerGas: '1.191416838',
                maxPriorityFeePerGas: '0.7946902',
                blocks: -1,
            },
            token: undefined,
        },
        result: {
            max: undefined,
            bytes: 0,
            fee: '25019753598000',
            feeLimit: '21000',
            feePerByte: '0',
            inputs: [],
            maxFeePerGas: '1.191416838',
            maxPriorityFeePerGas: '0.7946902',
            outputs: [
                {
                    address: 'A',
                    amount: '1',
                    script_type: 'PAYTOADDRESS',
                },
            ],
            outputsPermutation: [0],
            token: undefined,
            totalSpent: '25019753598001',
            type: 'final',
        },
    },
    {
        description: 'Eip1559 fee, no token, ETH balance insufficient for gas fees',
        input: {
            availableBalance: '1000',
            output: { type: 'payment' as const, address: 'A', amount: '1' },
            feeLevel: {
                label: 'low' as const,
                feeLimit: '21000',
                feePerUnit: '0',
                maxFeePerGas: '1.191416838',
                maxPriorityFeePerGas: '0.7946902',
                blocks: -1,
            },
            token: undefined,
        },
        result: {
            type: 'error',
            error: 'AMOUNT_IS_NOT_ENOUGH',
            errorMessage: {
                id: 'AMOUNT_IS_NOT_ENOUGH',
            },
        },
    },
    {
        description: 'Eip1559 fee, token transfer, should pass',
        input: {
            availableBalance: '1000000000000000000',
            output: { type: 'payment' as const, address: 'A', amount: '1' },
            feeLevel: {
                label: 'low' as const,
                feeLimit: '21000',
                feePerUnit: '0',
                maxFeePerGas: '1.191416838',
                maxPriorityFeePerGas: '0.7946902',
                blocks: -1,
            },
            token: {
                type: 'ERC20',
                standard: 'ERC20',
                contract: '0x123',
                symbol: 'test',
                decimals: 18,
                balance: '100',
            },
        },
        result: {
            max: undefined,
            bytes: 0,
            fee: '25019753598000',
            feeLimit: '21000',
            feePerByte: '0',
            inputs: [],
            maxFeePerGas: '1.191416838',
            maxPriorityFeePerGas: '0.7946902',
            outputs: [
                {
                    address: 'A',
                    amount: '1',
                    script_type: 'PAYTOADDRESS',
                },
            ],
            outputsPermutation: [0],
            token: {
                type: 'ERC20',
                standard: 'ERC20',
                contract: '0x123',
                symbol: 'test',
                decimals: 18,
                balance: '100',
            },
            totalSpent: '1',
            type: 'final',
        },
    },
    {
        description: 'Eip1559 fee, token transfer, balance is not enough',
        input: {
            availableBalance: '1000',
            output: { type: 'payment' as const, address: 'A', amount: '1' },
            feeLevel: {
                label: 'low' as const,
                feeLimit: '21000',
                feePerUnit: '0',
                maxFeePerGas: '1.191416838',
                maxPriorityFeePerGas: '0.7946902',
                blocks: -1,
            },
            token: {
                type: 'ERC20',
                standard: 'ERC20',
                contract: '0x123',
                symbol: 'test',
                decimals: 18,
                balance: '100',
            },
        },
        result: {
            error: 'AMOUNT_NOT_ENOUGH_CURRENCY_FEE_WITH_ETH_AMOUNT',
            errorMessage: {
                id: 'AMOUNT_NOT_ENOUGH_CURRENCY_FEE_WITH_ETH_AMOUNT',
                values: { feeAmount: '0.000025019753598' },
            },
            type: 'error',
        },
    },
];
