# Common Functions and Requirements
# across Android/iOS Fastfiles

# necessary for sed when a branch name includes slash
def escape_slash(string)
  string.gsub('/', '\/')
end

# Path Constants
SUITE_NATIVE_ROOT_PATH = File.expand_path('../', Dir.pwd).freeze

# Android project
ANDROID_PATH = File.join(SUITE_NATIVE_ROOT_PATH, 'android').freeze
ANDROID_FIREBASE_APP_ID = ENV['FIREBASE_APP_ID']

# iOS project
IOS_PATH = File.join(SUITE_NATIVE_ROOT_PATH, 'ios').freeze

# Retrieve version of Suite Native app in package.json
PACKAGE_JSON_PATH = File.join(SUITE_NATIVE_ROOT_PATH, 'package.json').freeze

commit = last_git_commit
commit_message = commit[:message]
commit_hash = commit[:abbreviated_commit_hash]

ENV["COMMIT_HASH"] = "#{commit_hash}"
ENV["CHANGELOG"] = escape_slash "[#{git_branch}] - #{commit_message}".strip
ENV["VERSION"] = load_json(json_path: "package.json")["suiteNativeVersion"]

private_lane :replace_debug_info_environment_variables do |options|
  platform = lane_context[SharedValues::PLATFORM_NAME]
  environment_file_name = ENV["ENVFILE"]
  environment_file = File.join(SUITE_NATIVE_ROOT_PATH, environment_file_name)

  commit_hash_substitute = "s/^(COMMIT_HASH)=(.*)$/\\1=#{ENV["COMMIT_HASH"]}/"
  changelog_substitute = "s/^(CHANGELOG)=(.*)$/\\1=#{ENV["CHANGELOG"]}/"
  version_substitute = "s/^(VERSION)=(.*)$/\\1=#{ENV["VERSION"]}/"
  build_number_substitute = "s/^(BUILD_NUMBER)=(.*)$/\\1=#{ENV["BUILD_NUMBER"]}/"

  if is_ci and platform == :ios
    sh(
      <<-SHELL
      sed -r -i '' '#{commit_hash_substitute}' '#{environment_file}'
      sed -r -i '' '#{changelog_substitute}' '#{environment_file}'
      sed -r -i '' '#{version_substitute}' '#{environment_file}'
      sed -r -i '' '#{build_number_substitute}' '#{environment_file}'
      SHELL
    )
  elsif is_ci and platform == :android
    sh(
      <<-SHELL
      sed -r -i '#{commit_hash_substitute}' '#{environment_file}'
      sed -r -i '#{changelog_substitute}' '#{environment_file}'
      sed -r -i '#{version_substitute}' '#{environment_file}'
      sed -r -i '#{build_number_substitute}' '#{environment_file}'
      SHELL
    )
  end

end

import "../ios/fastlane/Fastfile"
import "../android/fastlane/Fastfile"
