# Common Functions and Requirements
# across Android/iOS Fastfiles

# Path Constants
SUITE_NATIVE_ROOT_PATH = File.expand_path('../', Dir.pwd).freeze

# Android project
ANDROID_PATH = File.join(SUITE_NATIVE_ROOT_PATH, 'android').freeze
ANDROID_FIREBASE_APP_ID = ENV['FIREBASE_APP_ID']

# iOS project
IOS_PATH = File.join(SUITE_NATIVE_ROOT_PATH, 'ios').freeze

# Retrieve version of Suite Native app in package.json
PACKAGE_JSON_PATH = File.join(SUITE_NATIVE_ROOT_PATH, 'package.json').freeze
VERSION = load_json(json_path: "package.json")["suiteNativeVersion"]

commit = last_git_commit
commit_message = commit[:message]
commit_hash = commit[:abbreviated_commit_hash]
release_note_information = "[#{git_branch}] - #{commit_hash} - #{commit_message}"

CHANGELOG = "#{release_note_information}"

import "../ios/fastlane/Fastfile"
import "../android/fastlane/Fastfile"
