import { envUtils } from './envUtils';

const {
    getPlatformLanguages,
    getPlatform,
    getBrowserName,
    getBrowserVersion,
    getOsName,
    getOsVersion,
    getScreenWidth,
    getScreenHeight,
    getWindowWidth,
    getLocationHostname,
    getWindowHeight,
    getProcessPlatform,
    getUserAgent,
    getLocationOrigin,
    isWindows,
    isAndroid,
    isFirefox,
    isIOs,
    isMacOs,
    isChromeOs,
    isLinux,
} = envUtils;

export {
    getPlatformLanguages,
    getPlatform,
    getBrowserName,
    getBrowserVersion,
    getOsName,
    getOsVersion,
    getScreenWidth,
    getScreenHeight,
    getWindowWidth,
    getLocationHostname,
    getWindowHeight,
    getProcessPlatform,
    getUserAgent,
    getLocationOrigin,
    isWindows,
    isAndroid,
    isFirefox,
    isIOs,
    isMacOs,
    isChromeOs,
    isLinux,
};
