// Records which WASM exports of Cardano Serialization Lib @fivebinaries/coin-selection calls while
// the coin-selection tests run against Emurgo's complete asm.js build, writes them to keep-list.json
// and regenerates the pruned build. Run it whenever coin-selection or its use of the library changes.
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const packageDir = path.resolve(scriptDir, '../..');
const traceFilePath = path.resolve(packageDir, 'generated/csl-asmjs/trace.txt');
const keepListPath = path.join(scriptDir, 'keep-list.json');

fs.mkdirSync(path.dirname(traceFilePath), { recursive: true });
fs.rmSync(traceFilePath, { force: true });

execFileSync('yarn', ['g:jest', '-c', 'jest.config.csl-trace.cjs', '--coverage=0'], {
    cwd: packageDir,
    stdio: 'inherit',
    env: { ...process.env, CSL_TRACE_FILE: traceFilePath },
});

// The `__wbg_<class>_free` exports are reached through FinalizationRegistry callbacks and are kept
// by generate.js unconditionally, so they are left out of the list.
const usedExports = [...new Set(fs.readFileSync(traceFilePath, 'utf8').split('\n'))]
    .filter(name => name && name !== '__esModule' && !/^__wbg_[a-z0-9]+_free$/.test(name))
    .sort();
fs.rmSync(traceFilePath);

fs.writeFileSync(
    keepListPath,
    `${JSON.stringify(
        {
            description:
                'WASM exports of Cardano Serialization Lib that @fivebinaries/coin-selection calls on ' +
                'the code paths Suite uses. Generated by scripts/csl-asmjs/trace.js from the ' +
                'coin-selection tests; regenerate when coin-selection or CSL changes.',
            usedExports,
        },
        null,
        4,
    )}\n`,
);
console.log(`csl-asmjs: traced ${usedExports.length} exports into keep-list.json`);

execFileSync(process.execPath, [path.join(scriptDir, 'generate.js')], { stdio: 'inherit' });
