// Records the CSL exports the coin-selection tests touch into keep-list.json and regenerates the
// pruned build. See README.md.
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const packageDir = path.resolve(scriptDir, '../..');
const traceFilePath = path.join(os.tmpdir(), 'csl-asmjs-trace.txt');
const keepListPath = path.join(scriptDir, 'keep-list.json');

fs.rmSync(traceFilePath, { force: true });

execFileSync('yarn', ['g:jest', '-c', 'jest.config.csl-trace.cjs', '--coverage=0'], {
    cwd: packageDir,
    stdio: 'inherit',
    env: { ...process.env, CSL_TRACE_FILE: traceFilePath },
});

// generate.js keeps `__wbg_<class>_free` unconditionally.
const usedExports = [...new Set(fs.readFileSync(traceFilePath, 'utf8').split('\n'))]
    .filter(name => name && name !== '__esModule' && !/^__wbg_[a-z0-9]+_free$/.test(name))
    .sort();
fs.rmSync(traceFilePath);

fs.writeFileSync(
    keepListPath,
    `${JSON.stringify(
        {
            description:
                'WASM exports of Cardano Serialization Lib that @fivebinaries/coin-selection calls on ' +
                'the code paths Suite uses. Generated by scripts/csl-asmjs/trace.js from the ' +
                'coin-selection tests; regenerate when coin-selection or CSL changes.',
            usedExports,
        },
        null,
        4,
    )}\n`,
);
console.log(`csl-asmjs: traced ${usedExports.length} exports into keep-list.json`);

execFileSync(process.execPath, [path.join(scriptDir, 'generate.js')], { stdio: 'inherit' });
