import type { WorkspacePackage } from '../connectClosure';

export const EASIGNORE_FILE = '.easignore';

const MOBILE_APP_PACKAGE = '@suite-native/app';

/**
 * Paths an EAS build needs that no workspace manifest points at: Yarn cannot
 * install without its own release, plugins and patches, and the root
 * `postinstall` runs husky.
 */
const REQUIRED_ROOT_PATHS: ReadonlyArray<string> = [
    '.husky',
    '.nvmrc',
    '.yarn/patches',
    '.yarn/plugins',
    '.yarn/releases',
    '.yarnrc.yml',
    'package.json',
    'tsconfig.base.json',
    'yarn.lock',
];

/**
 * Listed after the allowlist so they also prune generated content out of the
 * allowed directories.
 */
const ALWAYS_EXCLUDED: ReadonlyArray<string> = [
    '**/node_modules/',
    '**/build/',
    '**/build-electron/',
    '**/build-renderer/',
    '**/dist/',
    '**/lib/',
    '**/libDev/',
    '**/coverage/',
    '**/tmp/',
    '**/.expo/',
    '**/.gradle/',
    '**/.cxx/',
    '**/.metro-health-check*',
    '*.tsbuildinfo',
    '*.jsbundle',
    '*.cpuprofile',
    '*.log',
    '.DS_Store',
];

/**
 * EAS uploads the working directory rather than a clean checkout, so every
 * untracked `.env` a developer happens to have would travel to Expo's servers.
 * Only the committed ones are re-included; a new one has to be added here, which
 * fails the mobile build rather than leaking the rest.
 */
const ENV_FILES: ReadonlyArray<string> = [
    '**/.env*',
    '!/suite-native/app/.env.development',
    '!/suite-native/app/.env.test',
];

const PREBUILD_OUTPUT: ReadonlyArray<string> = [
    '/suite-native/app/android/',
    '/suite-native/app/ios/',
];

const collectWorkspaceDependencies = (packageJson: WorkspacePackage['packageJson']) =>
    [
        packageJson.dependencies,
        packageJson.devDependencies,
        packageJson.optionalDependencies,
        packageJson.peerDependencies,
    ].flatMap(dependencies =>
        Object.entries(dependencies ?? {})
            .filter(([, version]) => version.startsWith('workspace:'))
            .map(([name]) => name),
    );

/**
 * Every workspace package the mobile app reaches through workspace ranges of any
 * kind. `devDependencies` are traversed too: a package declaring a dependency in
 * the wrong field still has to be installable, and omitting it would break the
 * build instead of failing a lint rule.
 */
export const collectMobileWorkspaceClosure = (
    packages: ReadonlyMap<string, WorkspacePackage>,
): ReadonlySet<string> => {
    const closure = new Set<string>();
    const rootPackage = packages.get(MOBILE_APP_PACKAGE);

    if (rootPackage === undefined) return closure;

    closure.add(MOBILE_APP_PACKAGE);
    const queue = [rootPackage];

    while (queue.length > 0) {
        const pkg = queue.shift();
        if (pkg === undefined) continue;

        for (const dependency of collectWorkspaceDependencies(pkg.packageJson)) {
            const dependencyPackage = packages.get(dependency);

            if (dependencyPackage === undefined || closure.has(dependency)) continue;

            closure.add(dependency);
            queue.push(dependencyPackage);
        }
    }

    return closure;
};

const getPathDepth = (path: string) => (path === '' ? 0 : path.split('/').length);

/**
 * Gitignore cannot re-include a path whose parent directory is excluded, so an
 * allowlist has to exclude and re-include level by level: `/packages/*` followed
 * by `!/packages/utils`, for every directory on the way down.
 */
const collectAllowedChildrenByParent = (paths: ReadonlyArray<string>) => {
    const childrenByParent = new Map<string, Set<string>>();

    for (const path of paths) {
        const segments = path.split('/');

        for (let depth = 0; depth < segments.length; depth++) {
            const parent = segments.slice(0, depth).join('/');
            const children = childrenByParent.get(parent) ?? new Set<string>();

            children.add(segments.slice(0, depth + 1).join('/'));
            childrenByParent.set(parent, children);
        }
    }

    return childrenByParent;
};

const buildAllowlistLines = (paths: ReadonlyArray<string>): ReadonlyArray<string> => {
    const childrenByParent = collectAllowedChildrenByParent(paths);
    const parents = [...childrenByParent.keys()].sort(
        (current, next) =>
            getPathDepth(current) - getPathDepth(next) || current.localeCompare(next),
    );

    return parents.flatMap(parent => [
        parent === '' ? '/*' : `/${parent}/*`,
        ...[...(childrenByParent.get(parent) ?? [])].sort().map(child => `!/${child}`),
    ]);
};

const HEADER = `# Generated by \`yarn requirements:fix\`. Do not edit by hand.
#
# EAS uploads the project directory as it is on disk and this file replaces every
# .gitignore, so it alone decides what reaches Expo's servers. It is an allowlist:
# everything is excluded, then the workspace closure of ${MOBILE_APP_PACKAGE} is
# re-included. A package the mobile app does not use therefore cannot be uploaded,
# and one it does use cannot be dropped by an unrelated refactor elsewhere in the
# monorepo - a missing entry fails the mobile build instead.`;

export const buildEasignoreContent = (closureDirs: ReadonlyArray<string>): string => {
    const allowlist = buildAllowlistLines([...REQUIRED_ROOT_PATHS, ...closureDirs]);
    const sections: ReadonlyArray<ReadonlyArray<string>> = [
        [HEADER],
        ['# Workspace closure of the mobile app, plus the root files Yarn needs', ...allowlist],
        ['# Never uploaded, including out of the allowed directories', ...ALWAYS_EXCLUDED],
        ['# Written by `expo prebuild`, which EAS runs itself', ...PREBUILD_OUTPUT],
        ['# Local secrets', ...ENV_FILES],
    ];

    return `${sections.map(section => section.join('\n')).join('\n\n')}\n`;
};
