/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Trezor Earn Yield API
 * OpenAPI spec version: 0.1.0
 */

/**
 * High-level action intent
 */
export type ActionDtoIntent = (typeof ActionDtoIntent)[keyof typeof ActionDtoIntent];

export const ActionDtoIntent = {
    enter: 'enter',
    manage: 'manage',
    exit: 'exit',
} as const;
