/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Trezor Earn Yield API
 * OpenAPI spec version: 0.1.0
 */
import type { AllocationDtoNetwork } from './allocationDtoNetwork';
import type { AllocationDtoRewardRate } from './allocationDtoRewardRate';

export type AllocationDto = {
    /** Contract address of the underlying strategy */
    address: string;
    /** Network the underlying strategy is on */
    network: AllocationDtoNetwork;
    /** Display name of the underlying strategy */
    name: string;
    /** Yield ID if this strategy is supported as a separate yield opportunity */
    yieldId?: string;
    /** Provider ID for this strategy (e.g., morpho, aave, lido) */
    providerId?: string;
    /** Amount allocated to this strategy in input token units */
    allocation: string;
    /**
     * USD value of the allocation
     * @nullable
     */
    allocationUsd: string | null;
    /** Current weight of this strategy as a percentage (0-100) */
    weight: number;
    /** Target weight of this strategy as a percentage (0-100) */
    targetWeight: number;
    /**
     * Reward rate of the underlying strategy
     * @nullable
     */
    rewardRate: AllocationDtoRewardRate;
    /**
     * Total value locked in the underlying strategy in input token units
     * @nullable
     */
    tvl: string | null;
    /**
     * Total value locked in USD for the underlying strategy
     * @nullable
     */
    tvlUsd: string | null;
    /**
     * Maximum capacity of the underlying strategy
     * @nullable
     */
    maxCapacity: string | null;
    /**
     * Remaining capacity in the underlying strategy
     * @nullable
     */
    remainingCapacity: string | null;
};
