/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Trezor Earn Yield API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Default value for the field
 */
export type ArgumentFieldDtoDefault = { [key: string]: unknown };
