/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Trezor Earn Yield API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Transaction execution mode
 */
export type CreateActionDtoArgumentsExecutionMode =
    (typeof CreateActionDtoArgumentsExecutionMode)[keyof typeof CreateActionDtoArgumentsExecutionMode];

export const CreateActionDtoArgumentsExecutionMode = {
    individual: 'individual',
    batched: 'batched',
} as const;
