/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Trezor Earn Yield API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Tron resource type for Tron staking
 */
export type CreateActionDtoArgumentsTronResource =
    (typeof CreateActionDtoArgumentsTronResource)[keyof typeof CreateActionDtoArgumentsTronResource];

export const CreateActionDtoArgumentsTronResource = {
    BANDWIDTH: 'BANDWIDTH',
    ENERGY: 'ENERGY',
} as const;
