/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Trezor Earn Yield API
 * OpenAPI spec version: 0.1.0
 */
import type { CreateActionDtoArguments } from './createActionDtoArguments';

export type CreateActionDto = {
    /** Yield ID to perform the action on */
    yieldId: string;
    /** User wallet address */
    address: string;
    /** Arguments for the action */
    arguments?: CreateActionDtoArguments;
};
