/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Trezor Earn Yield API
 * OpenAPI spec version: 0.1.0
 */

/**
 * High-level action intent
 */
export type EnterYield200Intent = (typeof EnterYield200Intent)[keyof typeof EnterYield200Intent];

export const EnterYield200Intent = {
    enter: 'enter',
    manage: 'manage',
    exit: 'exit',
} as const;
