/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Trezor Earn Yield API
 * OpenAPI spec version: 0.1.0
 */

/**
 * High-level action intent
 */
export type ExitYield200Intent = (typeof ExitYield200Intent)[keyof typeof ExitYield200Intent];

export const ExitYield200Intent = {
    enter: 'enter',
    manage: 'manage',
    exit: 'exit',
} as const;
