/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Trezor Earn Yield API
 * OpenAPI spec version: 0.1.0
 */

export type GetMerklUserRewardsParams = {
    chainId?: number | null | number[] | string;
    /**
     * @nullable
     */
    claimableOnly?: boolean | null;
    reloadChainId?: number | null | number[] | string;
};
