/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Trezor Earn Yield API
 * OpenAPI spec version: 0.1.0
 */
import type { GetYield200StateLiquidityStateLiquidity } from './getYield200StateLiquidityStateLiquidity';
import type { GetYield200StateLiquidityStateUtilization } from './getYield200StateLiquidityStateUtilization';

/**
 * Liquidity state (available liquidity, utilization rate)
 */
export type GetYield200StateLiquidityState = {
    /**
     * Available liquidity in underlying token units
     * @nullable
     */
    liquidity?: GetYield200StateLiquidityStateLiquidity;
    /**
     * Utilization rate as a decimal (e.g., 0.8 = 80%)
     * @nullable
     */
    utilization?: GetYield200StateLiquidityStateUtilization;
};
