/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Trezor Earn Yield API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Curator logo URI
 * @nullable
 */
export type GetYield200CuratorLogoURI = { [key: string]: unknown } | null;
