/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Trezor Earn Yield API
 * OpenAPI spec version: 0.1.0
 */
import type { ArgumentSchemaDto } from './argumentSchemaDto';

/**
 * Manage action schemas. Each yield supports different ActionTypes (CLAIM_UNSTAKED, CLAIM_REWARDS, etc.). Keys are ActionTypes enum values.
 */
export type GetYield200MechanicsArgumentsManage = { [key: string]: ArgumentSchemaDto };
