/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Trezor Earn Yield API
 * OpenAPI spec version: 0.1.0
 */

export type GetYield200MechanicsExtraTransactionFormatsSupportedItem =
    (typeof GetYield200MechanicsExtraTransactionFormatsSupportedItem)[keyof typeof GetYield200MechanicsExtraTransactionFormatsSupportedItem];

export const GetYield200MechanicsExtraTransactionFormatsSupportedItem = {
    raw: 'raw',
    default: 'default',
} as const;
