/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Trezor Earn Yield API
 * OpenAPI spec version: 0.1.0
 */

export type GetYieldsSort = (typeof GetYieldsSort)[keyof typeof GetYieldsSort];

export const GetYieldsSort = {
    statusEnterAsc: 'statusEnterAsc',
    statusEnterDesc: 'statusEnterDesc',
    statusExitAsc: 'statusExitAsc',
    statusExitDesc: 'statusExitDesc',
    rewardRateAsc: 'rewardRateAsc',
    rewardRateDesc: 'rewardRateDesc',
} as const;
