/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Trezor Earn Yield API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Entry amount limits for this yield
 */
export type GetYield200MechanicsEntryLimits = {
    /**
     * Minimum amount required to enter this yield in token units (null if no minimum)
     * @nullable
     */
    minimum: string | null;
    /**
     * Maximum amount allowed to enter this yield in token units (null if no limit)
     * @nullable
     */
    maximum: string | null;
};
