/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Trezor Earn Yield API
 * OpenAPI spec version: 0.1.0
 */
import type { RewardDto } from './rewardDto';

/**
 * Total effective yield broken down by source and token.
 */
export type GetYield200RewardRate = {
    /** Estimated reward rate across all sources (e.g. staking, points) */
    total: number;
    /** Whether this reward rate is APR or APY */
    rateType: string;
    /** Breakdown of reward rates by source */
    components: RewardDto[];
};
