/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Trezor Earn Yield API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Lockup period - minimum time before exit can be initiated
 */
export type GetYield200MechanicsLockupPeriod = {
    /** Duration in seconds */
    seconds: number;
};
