/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Trezor Earn Yield API
 * OpenAPI spec version: 0.1.0
 */

export type MerklUsersRewardsRequestBodyItem = {
    /** @pattern ^0x[a-fA-F0-9]{40}$ */
    address: string;
    /** @minimum 1 */
    chainId: number;
    reloadChainId?: number;
};
