/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Trezor Earn Yield API
 * OpenAPI spec version: 0.1.0
 */
import type { MerklUsersRewardsResponseItem } from './merklUsersRewardsResponseItem';

export type MerklUsersRewardsResponse = MerklUsersRewardsResponseItem[];
