/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Trezor Earn Yield API
 * OpenAPI spec version: 0.1.0
 */
import type { RewardDtoToken } from './rewardDtoToken';
import type { RewardDtoYieldSource } from './rewardDtoYieldSource';

export type RewardDto = {
    /** Reward rate as a decimal (e.g. 0.04 = 4%) */
    rate: number;
    /** Whether this rate is APR or APY */
    rateType: string;
    /** Token received as reward */
    token: RewardDtoToken;
    /** Structured source of yield (e.g. staking, protocol incentive) */
    yieldSource: RewardDtoYieldSource;
    /** Optional human-readable description of this reward */
    description?: string;
};
