/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Trezor Earn Yield API
 * OpenAPI spec version: 0.1.0
 */
import type { RewardDtoYieldSource } from './rewardDtoYieldSource';
import type { TokenDto } from './tokenDto';

export type RewardDto = {
    /** Reward rate as a decimal (e.g. 0.04 = 4%) */
    rate: number;
    /** Whether this rate is APR or APY */
    rateType: string;
    token: TokenDto;
    yieldSource: RewardDtoYieldSource;
    /** Optional human-readable description of this reward */
    description?: string;
};
