/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Trezor Earn Yield API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Human-readable breakdown of the transaction for display purposes
 * @nullable
 */
export type TransactionDtoAnnotatedTransaction = { [key: string]: unknown } | null;
