/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Trezor Earn Yield API
 * OpenAPI spec version: 0.1.0
 */
import type { YieldDtoStateLiquidityStateLiquidity } from './yieldDtoStateLiquidityStateLiquidity';
import type { YieldDtoStateLiquidityStateUtilization } from './yieldDtoStateLiquidityStateUtilization';

/**
 * Liquidity state (available liquidity, utilization rate)
 */
export type YieldDtoStateLiquidityState = {
    /**
     * Available liquidity in underlying token units
     * @nullable
     */
    liquidity?: YieldDtoStateLiquidityStateLiquidity;
    /**
     * Utilization rate as a decimal (e.g., 0.8 = 80%)
     * @nullable
     */
    utilization?: YieldDtoStateLiquidityStateUtilization;
};
