/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Trezor Earn Yield API
 * OpenAPI spec version: 0.1.0
 */

export type YieldDtoMechanicsExtraTransactionFormatsSupportedItem =
    (typeof YieldDtoMechanicsExtraTransactionFormatsSupportedItem)[keyof typeof YieldDtoMechanicsExtraTransactionFormatsSupportedItem];

export const YieldDtoMechanicsExtraTransactionFormatsSupportedItem = {
    raw: 'raw',
    default: 'default',
} as const;
