/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Trezor Earn Yield API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Access requirements (e.g. KYC) for this yield
 */
export type YieldDtoMechanicsRequirements = {
    /** Whether off-chain KYC is required before transacting */
    kycRequired: boolean;
    /** Issuer's KYC portal URL */
    kycUrl?: string;
};
