/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Trezor Earn Yield API
 * OpenAPI spec version: 0.1.0
 */
import type { YieldRiskEntryDtoSource } from './yieldRiskEntryDtoSource';

export type YieldRiskEntryDto = {
    /** Provider top-level rating value */
    rating: string;
    /** Provider source label */
    source: YieldRiskEntryDtoSource;
};
