/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Trezor Earn Yield API
 * OpenAPI spec version: 0.1.0
 */
import type { ERCStandards } from './eRCStandards';

/**
 * Descriptive metadata including name, logo, description, and documentation
 */
export type YieldDtoMetadata = {
    /** Display name of the yield opportunity */
    name: string;
    /** Yield opportunity logo URI */
    logoURI: string;
    /** Markdown-supported short description of this yield opportunity, including where rewards come from. */
    description: string;
    /** Link to documentation or integration guide */
    documentation: string;
    /** Whether this yield is currently under maintenance */
    underMaintenance: boolean;
    /** Whether this yield is deprecated and will be discontinued */
    deprecated: boolean;
    supportedStandards: ERCStandards[];
    /** Whether this yield supports campaign creation */
    supportsCampaigns: boolean;
};
