/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Trezor Earn Yield API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Per-action set of on-chain contract addresses that transactions may target (tx.to). Used by policy-enforced custody providers to whitelist execution destinations.
 */
export type YieldsResponseItemsItemExecutionContracts = {
    /** Contract addresses that may appear as tx.to for enter transactions */
    enter?: string[];
    /** Contract addresses that may appear as tx.to for exit transactions */
    exit?: string[];
};
