/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Trezor Earn Yield API
 * OpenAPI spec version: 0.1.0
 */
import type { YieldDtoStatePricePerShareStateQuoteToken } from './yieldDtoStatePricePerShareStateQuoteToken';
import type { YieldDtoStatePricePerShareStateShareToken } from './yieldDtoStatePricePerShareStateShareToken';

export type YieldDtoStatePricePerShareState = {
    /** Price per share for the yield (e.g., LP token price, vault share price) */
    price: string;
    /** Share token (the token you own shares of) */
    shareToken: YieldDtoStatePricePerShareStateShareToken;
    /** Quote token (the token the price is denominated in) */
    quoteToken: YieldDtoStatePricePerShareStateQuoteToken;
};
