/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Trezor Earn Yield API
 * OpenAPI spec version: 0.1.0
 */
import type { RewardClaiming } from './rewardClaiming';
import type { RewardSchedule } from './rewardSchedule';
import type { YieldType } from './yieldType';
import type { YieldsResponseItemsItemMechanicsArguments } from './yieldsResponseItemsItemMechanicsArguments';
import type { YieldsResponseItemsItemMechanicsCooldownPeriod } from './yieldsResponseItemsItemMechanicsCooldownPeriod';
import type { YieldsResponseItemsItemMechanicsEntryLimits } from './yieldsResponseItemsItemMechanicsEntryLimits';
import type { YieldsResponseItemsItemMechanicsExtraTransactionFormatsSupportedItem } from './yieldsResponseItemsItemMechanicsExtraTransactionFormatsSupportedItem';
import type { YieldsResponseItemsItemMechanicsFee } from './yieldsResponseItemsItemMechanicsFee';
import type { YieldsResponseItemsItemMechanicsGasFeeToken } from './yieldsResponseItemsItemMechanicsGasFeeToken';
import type { YieldsResponseItemsItemMechanicsLockupPeriod } from './yieldsResponseItemsItemMechanicsLockupPeriod';
import type { YieldsResponseItemsItemMechanicsPossibleFeeTakingMechanisms } from './yieldsResponseItemsItemMechanicsPossibleFeeTakingMechanisms';
import type { YieldsResponseItemsItemMechanicsRequirements } from './yieldsResponseItemsItemMechanicsRequirements';
import type { YieldsResponseItemsItemMechanicsWarmupPeriod } from './yieldsResponseItemsItemMechanicsWarmupPeriod';

/**
 * Operational mechanics including constraints, fees, and capabilities
 */
export type YieldsResponseItemsItemMechanics = {
    type: YieldType;
    /** Indicates whether this yield requires validator selection */
    requiresValidatorSelection?: boolean;
    rewardSchedule: RewardSchedule;
    rewardClaiming: RewardClaiming;
    /** Token used for gas fees (typically native) */
    gasFeeToken: YieldsResponseItemsItemMechanicsGasFeeToken;
    /** Lockup period - minimum time before exit can be initiated */
    lockupPeriod?: YieldsResponseItemsItemMechanicsLockupPeriod;
    /** Cooldown period required before exit is allowed */
    cooldownPeriod?: YieldsResponseItemsItemMechanicsCooldownPeriod;
    /** Warmup period before rewards start accruing */
    warmupPeriod?: YieldsResponseItemsItemMechanicsWarmupPeriod;
    /** Fees charged to the user for this yield (e.g., deposit, management, performance). */
    fee?: YieldsResponseItemsItemMechanicsFee;
    /** Entry amount limits for this yield */
    entryLimits?: YieldsResponseItemsItemMechanicsEntryLimits;
    /** Access requirements (e.g. KYC) for this yield */
    requirements?: YieldsResponseItemsItemMechanicsRequirements;
    /** Supports Ledger Wallet API (connect via Ledger Live) */
    supportsLedgerWalletApi?: boolean;
    /** Additional transaction formats supported (e.g. safe, batch) */
    extraTransactionFormatsSupported?: YieldsResponseItemsItemMechanicsExtraTransactionFormatsSupportedItem[];
    /** Arguments required for each action (enter, exit, manage, etc.) */
    arguments?: YieldsResponseItemsItemMechanicsArguments;
    /** Possible fee-taking mechanisms for the user or integrator (i.e., what fees the user/integrator can potentially earn from this yield). */
    possibleFeeTakingMechanisms?: YieldsResponseItemsItemMechanicsPossibleFeeTakingMechanisms;
};
