/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Trezor Earn Yield API
 * OpenAPI spec version: 0.1.0
 */
import type { YieldsResponseItemsItemMechanicsGasFeeTokenNetwork } from './yieldsResponseItemsItemMechanicsGasFeeTokenNetwork';

/**
 * Token used for gas fees (typically native)
 */
export type YieldsResponseItemsItemMechanicsGasFeeToken = {
    /** Token symbol */
    symbol: string;
    /** Token name */
    name: string;
    /** Token decimal places */
    decimals: number;
    /** Token network */
    network: YieldsResponseItemsItemMechanicsGasFeeTokenNetwork;
    /** Token address (if applicable) */
    address?: string;
    /** Token logo URI */
    logoURI?: string;
    /** Token is points */
    isPoints?: boolean;
    /** Token CoinGecko ID */
    coinGeckoId?: string;
};
