/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Trezor Earn Yield API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Possible fee-taking mechanisms for the user or integrator (i.e., what fees the user/integrator can potentially earn from this yield).
 */
export type YieldsResponseItemsItemMechanicsPossibleFeeTakingMechanisms = {
    /** User can take (earn) a deposit fee */
    depositFee: boolean;
    /** User can take (earn) a management fee */
    managementFee: boolean;
    /** User can take (earn) a performance fee */
    performanceFee: boolean;
    /** User can take (earn) validator rebates */
    validatorRebates: boolean;
};
