/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Trezor Earn Yield API
 * OpenAPI spec version: 0.1.0
 */
import type { YieldsResponseItemsItemStatePricePerShareStateQuoteToken } from './yieldsResponseItemsItemStatePricePerShareStateQuoteToken';
import type { YieldsResponseItemsItemStatePricePerShareStateShareToken } from './yieldsResponseItemsItemStatePricePerShareStateShareToken';

export type YieldsResponseItemsItemStatePricePerShareState = {
    /** Price per share for the yield (e.g., LP token price, vault share price) */
    price: string;
    /** Share token (the token you own shares of) */
    shareToken: YieldsResponseItemsItemStatePricePerShareStateShareToken;
    /** Quote token (the token the price is denominated in) */
    quoteToken: YieldsResponseItemsItemStatePricePerShareStateQuoteToken;
};
