/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Trezor Earn Yield API
 * OpenAPI spec version: 0.1.0
 */
import type { YieldDtoStatePricePerShareStateShareTokenNetwork } from './yieldDtoStatePricePerShareStateShareTokenNetwork';

/**
 * Share token (the token you own shares of)
 */
export type YieldDtoStatePricePerShareStateShareToken = {
    /** Token symbol */
    symbol: string;
    /** Token name */
    name: string;
    /** Token decimal places */
    decimals: number;
    /** Token network */
    network: YieldDtoStatePricePerShareStateShareTokenNetwork;
    /** Token address (if applicable) */
    address?: string;
    /** Token logo URI */
    logoURI?: string;
    /** Token is points */
    isPoints?: boolean;
    /** Token CoinGecko ID */
    coinGeckoId?: string;
};
