/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Trezor Earn Yield API
 * OpenAPI spec version: 0.1.0
 */
import type { YieldsResponseItemsItemTokenNetwork } from './yieldsResponseItemsItemTokenNetwork';

/**
 * Canonical deposit token - used for balances
 */
export type YieldsResponseItemsItemToken = {
    /** Token symbol */
    symbol: string;
    /** Token name */
    name: string;
    /** Token decimal places */
    decimals: number;
    /** Token network */
    network: YieldsResponseItemsItemTokenNetwork;
    /** Token address (if applicable) */
    address?: string;
    /** Token logo URI */
    logoURI?: string;
    /** Token is points */
    isPoints?: boolean;
    /** Token CoinGecko ID */
    coinGeckoId?: string;
};
