export const GRADIENT_SLIDER_GREEN_START = '#2A9649';
export const GRADIENT_SLIDER_GREEN_END = '#95CDA5';
export const GRADIENT_SLIDER_YELLOW_START = '#C8B883';
export const GRADIENT_SLIDER_YELLOW_END = '#C8B882';
export const GRADIENT_SLIDER_RED_END = '#BF6767';
