#!/usr/bin/env bash
set -euo pipefail

# Build pre-compiled Rust binaries for @emurgo/csl-mobile-bridge.
# Reads version from package.json — no hardcoded versions.
#
# Prerequisites:
#   - Rust toolchain (rustup)
#   - iOS targets: rustup target add aarch64-apple-ios aarch64-apple-ios-sim x86_64-apple-ios
#   - Android targets: rustup target add aarch64-linux-android x86_64-linux-android
#   - cargo-ndk: cargo install cargo-ndk
#
# Usage:
#   yarn workspace @suite-native/react-native-cardano build
#   yarn workspace @suite-native/react-native-cardano build:ios
#   yarn workspace @suite-native/react-native-cardano build:android

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PACKAGE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

VERSION=$(node -e "console.log(require('$PACKAGE_DIR/package.json').dependencies['@emurgo/csl-mobile-bridge'])")
echo "Building csl-mobile-bridge v${VERSION}"

BUILD_DIR="/tmp/csl-mobile-bridge-build"
IOS_ONLY=false
ANDROID_ONLY=false

for arg in "$@"; do
    case $arg in
        --ios-only) IOS_ONLY=true ;;
        --android-only) ANDROID_ONLY=true ;;
    esac
done

# Clone and checkout
if [ -d "$BUILD_DIR" ]; then
    echo "Cleaning previous build directory..."
    rm -rf "$BUILD_DIR"
fi

echo "Cloning csl-mobile-bridge..."
git clone --depth 1 --branch "$VERSION" https://github.com/Emurgo/csl-mobile-bridge.git "$BUILD_DIR"
cd "$BUILD_DIR/rust"

# iOS
if [ "$ANDROID_ONLY" = false ]; then
    echo ""
    echo "=== Building iOS ==="

    echo "Building aarch64-apple-ios (device)..."
    cargo build --target aarch64-apple-ios --release

    echo "Building aarch64-apple-ios-sim (simulator arm64)..."
    cargo build --target aarch64-apple-ios-sim --release

    echo "Building x86_64-apple-ios (simulator x86_64)..."
    cargo build --target x86_64-apple-ios --release

    echo "Creating simulator fat binary..."
    mkdir -p sim_combined
    lipo -create \
        target/aarch64-apple-ios-sim/release/libreact_native_haskell_shelley.a \
        target/x86_64-apple-ios/release/libreact_native_haskell_shelley.a \
        -output sim_combined/libreact_native_haskell_shelley.a

    echo "Creating XCFramework..."
    rm -rf CslMobileBridge.xcframework
    xcodebuild -create-xcframework \
        -library target/aarch64-apple-ios/release/libreact_native_haskell_shelley.a \
        -library sim_combined/libreact_native_haskell_shelley.a \
        -output CslMobileBridge.xcframework

    echo "Copying XCFramework to package..."
    rm -rf "$PACKAGE_DIR/ios/build/CslMobileBridge.xcframework"
    cp -R CslMobileBridge.xcframework "$PACKAGE_DIR/ios/build/"

    echo "iOS build complete."
fi

# Android
if [ "$IOS_ONLY" = false ]; then
    echo ""
    echo "=== Building Android ==="

    echo "Building arm64-v8a + x86_64..."
    cargo ndk -t arm64-v8a -t x86_64 build --release

    echo "Copying .so files to package..."
    cp target/aarch64-linux-android/release/libreact_native_haskell_shelley.so \
        "$PACKAGE_DIR/android/src/main/jniLibs/arm64-v8a/"

    cp target/x86_64-linux-android/release/libreact_native_haskell_shelley.so \
        "$PACKAGE_DIR/android/src/main/jniLibs/x86_64/"

    if command -v llvm-strip &>/dev/null; then
        echo "Stripping debug symbols from .so files..."
        llvm-strip --strip-unneeded "$PACKAGE_DIR/android/src/main/jniLibs/arm64-v8a/libreact_native_haskell_shelley.so"
        llvm-strip --strip-unneeded "$PACKAGE_DIR/android/src/main/jniLibs/x86_64/libreact_native_haskell_shelley.so"
    fi

    echo "Android build complete."
fi

# C header (generated by cbindgen, needed for Android CMake build)
echo ""
echo "=== Copying C header ==="
cp "$BUILD_DIR/rust/include/react_native_haskell_shelley.h" \
    "$PACKAGE_DIR/android/src/main/cpp/"
echo "Copied react_native_haskell_shelley.h"

# Cleanup
echo ""
echo "Cleaning build directory..."
rm -rf "$BUILD_DIR"

echo ""
echo "Done! Pre-compiled binaries are ready."
echo "Commit them via: git add suite-native/react-native-cardano/ios/build/ suite-native/react-native-cardano/android/src/main/jniLibs/ suite-native/react-native-cardano/android/src/main/cpp/"
