import z from 'zod';

import { createHttpClient } from '@suite-common/http-client';
import { commonQueryKeys, useQuery } from '@suite-common/react-query';

import { MERKL_BASE_URL, queriesStaleTime } from '../config';

const merkleHttpClient = createHttpClient({
    baseUrl: MERKL_BASE_URL,
});

const numericStringOrNumberSchema = z.union([z.string(), z.number()]);

const campaignStatusSchema = z.object({
    campaignId: z.string(),
    computedUntil: z.union([z.string(), numericStringOrNumberSchema]),
    processingStarted: z.union([z.string(), numericStringOrNumberSchema]),
    status: z.string(),
    preComputeProcessingStarted: z.union([z.string(), numericStringOrNumberSchema]),
    preComputeStatus: z.string(),
    delay: numericStringOrNumberSchema.optional(),
    error: z.string().optional(),
    details: z.unknown().optional(),
});

const claimableRewardSchema = z.object({
    root: z.string(),
    recipient: z.string(),
    proofs: z.array(z.string()),
    token: z.object({
        address: z.string(),
        chainId: z.number(),
        symbol: z.string(),
        decimals: z.number(),
    }),
    breakdowns: z.array(
        z.object({
            reason: z.string(),
            amount: z.string(),
            claimed: z.string(),
            pending: z.string(),
            campaignId: z.string(),
            campaignStatus: campaignStatusSchema.optional(),
        }),
    ),
    claimed: z.string(),
    amount: z.string(),
    pending: z.string(),
});

/**
 * Generated by a LLM from the API documentation.
 * @url https://api.merkl.xyz/docs#tag/users/GET/v4/users/{address}/rewards
 */
const merkleRewardsResponseSchema = z.array(
    z.object({
        chain: z.object({
            id: z.number().int().min(1),
            name: z.string(),
            icon: z.string(),
            liveCampaigns: z.number(),
            endOfDisputePeriod: z.number(),
            explorers: z
                .array(
                    z.object({
                        type: z.union([z.literal('ETHERSCAN'), z.literal('BLOCKSCOUT')]),
                        url: z.string(),
                        chainId: z.number(),
                    }),
                )
                .optional(),
            lastClaimsOnchainFetchTimestamp: z.union([z.string(), z.null()]).optional(),
        }),
        rewards: z.array(claimableRewardSchema),
    }),
);

export class ChainAddressKey {
    static readonly delimiter = ':';

    static compose(chainId: number, address: string) {
        return `${chainId}${ChainAddressKey.delimiter}${address}` as const;
    }

    static parse(key: string) {
        const [chainId, address] = key.split(ChainAddressKey.delimiter);

        return {
            chainId: Number(chainId),
            address,
        } as const;
    }
}

type MerkleClaimableReward = z.infer<typeof claimableRewardSchema>;

export type MerkleRewardsParams<Address extends string> = {
    address: Address;
    chainId: number;
};

/**
 *
 * @url https://api.merkl.xyz/docs#tag/users/GET/v4/users/{address}/rewards
 */
export function useGetMerkleRewards<Address extends string>(
    queryEntries: MerkleRewardsParams<Address>[],
) {
    return useQuery({
        queryKey: commonQueryKeys.merkleRewards(queryEntries),
        staleTime: queriesStaleTime.getMerkleRewards,
        async queryFn() {
            const fetcher = merkleHttpClient('/v1/users/:address/rewards', {
                method: 'GET',
                schema: merkleRewardsResponseSchema,
                cache: 'no-store',
            });

            const requests = queryEntries.map(entry =>
                fetcher({
                    routeParams: { address: entry.address },
                    params: {
                        chainId: entry.chainId,
                        claimableOnly: true,
                    },
                }),
            );

            const usersChainRewards = await Promise.all(requests);

            // Link the response with the query entries, flatten the rewards, select needed fields
            const rewardsResult = usersChainRewards.map((userChainRewards, index) => {
                const { address, chainId } = queryEntries[index];

                return {
                    address,
                    chainId,
                    rewards: userChainRewards
                        .map(chainRewards =>
                            chainRewards.rewards.map(reward => {
                                const { token, proofs, amount, claimed, pending, root } = reward;

                                return { token, proofs, amount, claimed, pending, root };
                            }),
                        )
                        .flat(1),
                };
            });

            const rewardsByChainAndAddress = rewardsResult.reduce<
                Record<
                    ReturnType<typeof ChainAddressKey.compose>,
                    Pick<
                        MerkleClaimableReward,
                        'token' | 'proofs' | 'amount' | 'claimed' | 'pending' | 'root'
                    >[]
                >
            >((result, { address, chainId, rewards }) => {
                const key = ChainAddressKey.compose(chainId, address);

                result[key] = rewards;

                return result;
            }, {});

            return rewardsByChainAndAddress;
        },
    });
}

export type MerkleRewardsByChainAndAddress = NonNullable<
    Awaited<ReturnType<typeof useGetMerkleRewards>['data']>
>;
