type Country = {
    code: string;
    flag: string;
    name: string;
};

export const countries = {
    AD: { code: 'AD', flag: '🇦🇩', name: 'Andorra' },
    AE: { code: 'AE', flag: '🇦🇪', name: 'United Arab Emirates' },
    AF: { code: 'AF', flag: '🇦🇫', name: 'Afghanistan' },
    AG: { code: 'AG', flag: '🇦🇬', name: 'Antigua and Barbuda' },
    AI: { code: 'AI', flag: '🇦🇮', name: 'Anguilla' },
    AL: { code: 'AL', flag: '🇦🇱', name: 'Albania' },
    AM: { code: 'AM', flag: '🇦🇲', name: 'Armenia' },
    AO: { code: 'AO', flag: '🇦🇴', name: 'Angola' },
    AQ: { code: 'AQ', flag: '🇦🇶', name: 'Antarctica' },
    AR: { code: 'AR', flag: '🇦🇷', name: 'Argentina' },
    AS: { code: 'AS', flag: '🇦🇸', name: 'American Samoa' },
    AT: { code: 'AT', flag: '🇦🇹', name: 'Austria' },
    AU: { code: 'AU', flag: '🇦🇺', name: 'Australia' },
    AW: { code: 'AW', flag: '🇦🇼', name: 'Aruba' },
    AX: { code: 'AX', flag: '🇦🇽', name: 'Åland Islands' },
    AZ: { code: 'AZ', flag: '🇦🇿', name: 'Azerbaijan' },
    BA: { code: 'BA', flag: '🇧🇦', name: 'Bosnia and Herzegovina' },
    BB: { code: 'BB', flag: '🇧🇧', name: 'Barbados' },
    BD: { code: 'BD', flag: '🇧🇩', name: 'Bangladesh' },
    BE: { code: 'BE', flag: '🇧🇪', name: 'Belgium' },
    BF: { code: 'BF', flag: '🇧🇫', name: 'Burkina Faso' },
    BG: { code: 'BG', flag: '🇧🇬', name: 'Bulgaria' },
    BH: { code: 'BH', flag: '🇧🇭', name: 'Bahrain' },
    BI: { code: 'BI', flag: '🇧🇮', name: 'Burundi' },
    BJ: { code: 'BJ', flag: '🇧🇯', name: 'Benin' },
    BL: { code: 'BL', flag: '🇧🇱', name: 'Saint Barthélemy' },
    BM: { code: 'BM', flag: '🇧🇲', name: 'Bermuda' },
    BN: { code: 'BN', flag: '🇧🇳', name: 'Brunei Darussalam' },
    BO: { code: 'BO', flag: '🇧🇴', name: 'Bolivia' },
    BQ: { code: 'BQ', flag: '🇧🇶', name: 'Bonaire, Sint Eustatius and Saba' },
    BR: { code: 'BR', flag: '🇧🇷', name: 'Brazil' },
    BS: { code: 'BS', flag: '🇧🇸', name: 'Bahamas' },
    BT: { code: 'BT', flag: '🇧🇹', name: 'Bhutan' },
    BV: { code: 'BV', flag: '🇧🇻', name: 'Bouvet Island' },
    BW: { code: 'BW', flag: '🇧🇼', name: 'Botswana' },
    BY: { code: 'BY', flag: '🇧🇾', name: 'Belarus' },
    BZ: { code: 'BZ', flag: '🇧🇿', name: 'Belize' },
    CA: { code: 'CA', flag: '🇨🇦', name: 'Canada' },
    CC: { code: 'CC', flag: '🇨🇨', name: 'Cocos (Keeling) Islands' },
    CD: { code: 'CD', flag: '🇨🇩', name: 'Congo' },
    CF: { code: 'CF', flag: '🇨🇫', name: 'Central African Republic' },
    CG: { code: 'CG', flag: '🇨🇬', name: 'Congo' },
    CH: { code: 'CH', flag: '🇨🇭', name: 'Switzerland' },
    CI: { code: 'CI', flag: '🇨🇮', name: `Côte D'Ivoire` },
    CK: { code: 'CK', flag: '🇨🇰', name: 'Cook Islands' },
    CL: { code: 'CL', flag: '🇨🇱', name: 'Chile' },
    CM: { code: 'CM', flag: '🇨🇲', name: 'Cameroon' },
    CN: { code: 'CN', flag: '🇨🇳', name: 'China' },
    CO: { code: 'CO', flag: '🇨🇴', name: 'Colombia' },
    CR: { code: 'CR', flag: '🇨🇷', name: 'Costa Rica' },
    CU: { code: 'CU', flag: '🇨🇺', name: 'Cuba' },
    CV: { code: 'CV', flag: '🇨🇻', name: 'Cape Verde' },
    CW: { code: 'CW', flag: '🇨🇼', name: 'Curaçao' },
    CX: { code: 'CX', flag: '🇨🇽', name: 'Christmas Island' },
    CY: { code: 'CY', flag: '🇨🇾', name: 'Cyprus' },
    CZ: { code: 'CZ', flag: '🇨🇿', name: 'Czech Republic' },
    DE: { code: 'DE', flag: '🇩🇪', name: 'Germany' },
    DJ: { code: 'DJ', flag: '🇩🇯', name: 'Djibouti' },
    DK: { code: 'DK', flag: '🇩🇰', name: 'Denmark' },
    DM: { code: 'DM', flag: '🇩🇲', name: 'Dominica' },
    DO: { code: 'DO', flag: '🇩🇴', name: 'Dominican Republic' },
    DZ: { code: 'DZ', flag: '🇩🇿', name: 'Algeria' },
    EC: { code: 'EC', flag: '🇪🇨', name: 'Ecuador' },
    EE: { code: 'EE', flag: '🇪🇪', name: 'Estonia' },
    EG: { code: 'EG', flag: '🇪🇬', name: 'Egypt' },
    EH: { code: 'EH', flag: '🇪🇭', name: 'Western Sahara' },
    ER: { code: 'ER', flag: '🇪🇷', name: 'Eritrea' },
    ES: { code: 'ES', flag: '🇪🇸', name: 'Spain' },
    ET: { code: 'ET', flag: '🇪🇹', name: 'Ethiopia' },
    FI: { code: 'FI', flag: '🇫🇮', name: 'Finland' },
    FJ: { code: 'FJ', flag: '🇫🇯', name: 'Fiji' },
    FK: { code: 'FK', flag: '🇫🇰', name: 'Falkland Islands (Malvinas)' },
    FM: { code: 'FM', flag: '🇫🇲', name: 'Micronesia' },
    FO: { code: 'FO', flag: '🇫🇴', name: 'Faroe Islands' },
    FR: { code: 'FR', flag: '🇫🇷', name: 'France' },
    GA: { code: 'GA', flag: '🇬🇦', name: 'Gabon' },
    GB: { code: 'GB', flag: '🇬🇧', name: 'United Kingdom' },
    GD: { code: 'GD', flag: '🇬🇩', name: 'Grenada' },
    GE: { code: 'GE', flag: '🇬🇪', name: 'Georgia' },
    GF: { code: 'GF', flag: '🇬🇫', name: 'French Guiana' },
    GG: { code: 'GG', flag: '🇬🇬', name: 'Guernsey' },
    GH: { code: 'GH', flag: '🇬🇭', name: 'Ghana' },
    GI: { code: 'GI', flag: '🇬🇮', name: 'Gibraltar' },
    GL: { code: 'GL', flag: '🇬🇱', name: 'Greenland' },
    GM: { code: 'GM', flag: '🇬🇲', name: 'Gambia' },
    GN: { code: 'GN', flag: '🇬🇳', name: 'Guinea' },
    GP: { code: 'GP', flag: '🇬🇵', name: 'Guadeloupe' },
    GQ: { code: 'GQ', flag: '🇬🇶', name: 'Equatorial Guinea' },
    GR: { code: 'GR', flag: '🇬🇷', name: 'Greece' },
    GS: { code: 'GS', flag: '🇬🇸', name: 'South Georgia' },
    GT: { code: 'GT', flag: '🇬🇹', name: 'Guatemala' },
    GU: { code: 'GU', flag: '🇬🇺', name: 'Guam' },
    GW: { code: 'GW', flag: '🇬🇼', name: 'Guinea-Bissau' },
    GY: { code: 'GY', flag: '🇬🇾', name: 'Guyana' },
    HK: { code: 'HK', flag: '🇭🇰', name: 'Hong Kong' },
    HM: { code: 'HM', flag: '🇭🇲', name: 'Heard Island and Mcdonald Islands' },
    HN: { code: 'HN', flag: '🇭🇳', name: 'Honduras' },
    HR: { code: 'HR', flag: '🇭🇷', name: 'Croatia' },
    HT: { code: 'HT', flag: '🇭🇹', name: 'Haiti' },
    HU: { code: 'HU', flag: '🇭🇺', name: 'Hungary' },
    ID: { code: 'ID', flag: '🇮🇩', name: 'Indonesia' },
    IE: { code: 'IE', flag: '🇮🇪', name: 'Ireland' },
    IL: { code: 'IL', flag: '🇮🇱', name: 'Israel' },
    IM: { code: 'IM', flag: '🇮🇲', name: 'Isle of Man' },
    IN: { code: 'IN', flag: '🇮🇳', name: 'India' },
    IO: { code: 'IO', flag: '🇮🇴', name: 'British Indian Ocean Territory' },
    IQ: { code: 'IQ', flag: '🇮🇶', name: 'Iraq' },
    IR: { code: 'IR', flag: '🇮🇷', name: 'Iran' },
    IS: { code: 'IS', flag: '🇮🇸', name: 'Iceland' },
    IT: { code: 'IT', flag: '🇮🇹', name: 'Italy' },
    JE: { code: 'JE', flag: '🇯🇪', name: 'Jersey' },
    JM: { code: 'JM', flag: '🇯🇲', name: 'Jamaica' },
    JO: { code: 'JO', flag: '🇯🇴', name: 'Jordan' },
    JP: { code: 'JP', flag: '🇯🇵', name: 'Japan' },
    KE: { code: 'KE', flag: '🇰🇪', name: 'Kenya' },
    KG: { code: 'KG', flag: '🇰🇬', name: 'Kyrgyzstan' },
    KH: { code: 'KH', flag: '🇰🇭', name: 'Cambodia' },
    KI: { code: 'KI', flag: '🇰🇮', name: 'Kiribati' },
    KM: { code: 'KM', flag: '🇰🇲', name: 'Comoros' },
    KN: { code: 'KN', flag: '🇰🇳', name: 'Saint Kitts and Nevis' },
    KP: { code: 'KP', flag: '🇰🇵', name: 'North Korea' },
    KR: { code: 'KR', flag: '🇰🇷', name: 'South Korea' },
    KW: { code: 'KW', flag: '🇰🇼', name: 'Kuwait' },
    KY: { code: 'KY', flag: '🇰🇾', name: 'Cayman Islands' },
    KZ: { code: 'KZ', flag: '🇰🇿', name: 'Kazakhstan' },
    LA: { code: 'LA', flag: '🇱🇦', name: `Lao People's Democratic Republic` },
    LB: { code: 'LB', flag: '🇱🇧', name: 'Lebanon' },
    LC: { code: 'LC', flag: '🇱🇨', name: 'Saint Lucia' },
    LI: { code: 'LI', flag: '🇱🇮', name: 'Liechtenstein' },
    LK: { code: 'LK', flag: '🇱🇰', name: 'Sri Lanka' },
    LR: { code: 'LR', flag: '🇱🇷', name: 'Liberia' },
    LS: { code: 'LS', flag: '🇱🇸', name: 'Lesotho' },
    LT: { code: 'LT', flag: '🇱🇹', name: 'Lithuania' },
    LU: { code: 'LU', flag: '🇱🇺', name: 'Luxembourg' },
    LV: { code: 'LV', flag: '🇱🇻', name: 'Latvia' },
    LY: { code: 'LY', flag: '🇱🇾', name: 'Libya' },
    MA: { code: 'MA', flag: '🇲🇦', name: 'Morocco' },
    MC: { code: 'MC', flag: '🇲🇨', name: 'Monaco' },
    MD: { code: 'MD', flag: '🇲🇩', name: 'Moldova' },
    ME: { code: 'ME', flag: '🇲🇪', name: 'Montenegro' },
    MF: { code: 'MF', flag: '🇲🇫', name: 'Saint Martin (French Part)' },
    MG: { code: 'MG', flag: '🇲🇬', name: 'Madagascar' },
    MH: { code: 'MH', flag: '🇲🇭', name: 'Marshall Islands' },
    MK: { code: 'MK', flag: '🇲🇰', name: 'Macedonia' },
    ML: { code: 'ML', flag: '🇲🇱', name: 'Mali' },
    MM: { code: 'MM', flag: '🇲🇲', name: 'Myanmar' },
    MN: { code: 'MN', flag: '🇲🇳', name: 'Mongolia' },
    MO: { code: 'MO', flag: '🇲🇴', name: 'Macao' },
    MP: { code: 'MP', flag: '🇲🇵', name: 'Northern Mariana Islands' },
    MQ: { code: 'MQ', flag: '🇲🇶', name: 'Martinique' },
    MR: { code: 'MR', flag: '🇲🇷', name: 'Mauritania' },
    MS: { code: 'MS', flag: '🇲🇸', name: 'Montserrat' },
    MT: { code: 'MT', flag: '🇲🇹', name: 'Malta' },
    MU: { code: 'MU', flag: '🇲🇺', name: 'Mauritius' },
    MV: { code: 'MV', flag: '🇲🇻', name: 'Maldives' },
    MW: { code: 'MW', flag: '🇲🇼', name: 'Malawi' },
    MX: { code: 'MX', flag: '🇲🇽', name: 'Mexico' },
    MY: { code: 'MY', flag: '🇲🇾', name: 'Malaysia' },
    MZ: { code: 'MZ', flag: '🇲🇿', name: 'Mozambique' },
    NA: { code: 'NA', flag: '🇳🇦', name: 'Namibia' },
    NC: { code: 'NC', flag: '🇳🇨', name: 'New Caledonia' },
    NE: { code: 'NE', flag: '🇳🇪', name: 'Niger' },
    NF: { code: 'NF', flag: '🇳🇫', name: 'Norfolk Island' },
    NG: { code: 'NG', flag: '🇳🇬', name: 'Nigeria' },
    NI: { code: 'NI', flag: '🇳🇮', name: 'Nicaragua' },
    NL: { code: 'NL', flag: '🇳🇱', name: 'Netherlands' },
    NO: { code: 'NO', flag: '🇳🇴', name: 'Norway' },
    NP: { code: 'NP', flag: '🇳🇵', name: 'Nepal' },
    NR: { code: 'NR', flag: '🇳🇷', name: 'Nauru' },
    NU: { code: 'NU', flag: '🇳🇺', name: 'Niue' },
    NZ: { code: 'NZ', flag: '🇳🇿', name: 'New Zealand' },
    OM: { code: 'OM', flag: '🇴🇲', name: 'Oman' },
    PA: { code: 'PA', flag: '🇵🇦', name: 'Panama' },
    PE: { code: 'PE', flag: '🇵🇪', name: 'Peru' },
    PF: { code: 'PF', flag: '🇵🇫', name: 'French Polynesia' },
    PG: { code: 'PG', flag: '🇵🇬', name: 'Papua New Guinea' },
    PH: { code: 'PH', flag: '🇵🇭', name: 'Philippines' },
    PK: { code: 'PK', flag: '🇵🇰', name: 'Pakistan' },
    PL: { code: 'PL', flag: '🇵🇱', name: 'Poland' },
    PM: { code: 'PM', flag: '🇵🇲', name: 'Saint Pierre and Miquelon' },
    PN: { code: 'PN', flag: '🇵🇳', name: 'Pitcairn' },
    PR: { code: 'PR', flag: '🇵🇷', name: 'Puerto Rico' },
    PS: { code: 'PS', flag: '🇵🇸', name: 'Palestinian Territory' },
    PT: { code: 'PT', flag: '🇵🇹', name: 'Portugal' },
    PW: { code: 'PW', flag: '🇵🇼', name: 'Palau' },
    PY: { code: 'PY', flag: '🇵🇾', name: 'Paraguay' },
    QA: { code: 'QA', flag: '🇶🇦', name: 'Qatar' },
    RE: { code: 'RE', flag: '🇷🇪', name: 'Réunion' },
    RO: { code: 'RO', flag: '🇷🇴', name: 'Romania' },
    RS: { code: 'RS', flag: '🇷🇸', name: 'Serbia' },
    RU: { code: 'RU', flag: '🇷🇺', name: 'Russia' },
    RW: { code: 'RW', flag: '🇷🇼', name: 'Rwanda' },
    SA: { code: 'SA', flag: '🇸🇦', name: 'Saudi Arabia' },
    SB: { code: 'SB', flag: '🇸🇧', name: 'Solomon Islands' },
    SC: { code: 'SC', flag: '🇸🇨', name: 'Seychelles' },
    SD: { code: 'SD', flag: '🇸🇩', name: 'Sudan' },
    SE: { code: 'SE', flag: '🇸🇪', name: 'Sweden' },
    SG: { code: 'SG', flag: '🇸🇬', name: 'Singapore' },
    SH: { code: 'SH', flag: '🇸🇭', name: 'Saint Helena, Ascension and Tristan Da Cunha' },
    SI: { code: 'SI', flag: '🇸🇮', name: 'Slovenia' },
    SJ: { code: 'SJ', flag: '🇸🇯', name: 'Svalbard and Jan Mayen' },
    SK: { code: 'SK', flag: '🇸🇰', name: 'Slovakia' },
    SL: { code: 'SL', flag: '🇸🇱', name: 'Sierra Leone' },
    SM: { code: 'SM', flag: '🇸🇲', name: 'San Marino' },
    SN: { code: 'SN', flag: '🇸🇳', name: 'Senegal' },
    SO: { code: 'SO', flag: '🇸🇴', name: 'Somalia' },
    SR: { code: 'SR', flag: '🇸🇷', name: 'Suriname' },
    SS: { code: 'SS', flag: '🇸🇸', name: 'South Sudan' },
    ST: { code: 'ST', flag: '🇸🇹', name: 'Sao Tome and Principe' },
    SV: { code: 'SV', flag: '🇸🇻', name: 'El Salvador' },
    SX: { code: 'SX', flag: '🇸🇽', name: 'Sint Maarten (Dutch Part)' },
    SY: { code: 'SY', flag: '🇸🇾', name: 'Syrian Arab Republic' },
    SZ: { code: 'SZ', flag: '🇸🇿', name: 'Swaziland' },
    TC: { code: 'TC', flag: '🇹🇨', name: 'Turks and Caicos Islands' },
    TD: { code: 'TD', flag: '🇹🇩', name: 'Chad' },
    TF: { code: 'TF', flag: '🇹🇫', name: 'French Southern Territories' },
    TG: { code: 'TG', flag: '🇹🇬', name: 'Togo' },
    TH: { code: 'TH', flag: '🇹🇭', name: 'Thailand' },
    TJ: { code: 'TJ', flag: '🇹🇯', name: 'Tajikistan' },
    TK: { code: 'TK', flag: '🇹🇰', name: 'Tokelau' },
    TL: { code: 'TL', flag: '🇹🇱', name: 'Timor-Leste' },
    TM: { code: 'TM', flag: '🇹🇲', name: 'Turkmenistan' },
    TN: { code: 'TN', flag: '🇹🇳', name: 'Tunisia' },
    TO: { code: 'TO', flag: '🇹🇴', name: 'Tonga' },
    TR: { code: 'TR', flag: '🇹🇷', name: 'Turkey' },
    TT: { code: 'TT', flag: '🇹🇹', name: 'Trinidad and Tobago' },
    TV: { code: 'TV', flag: '🇹🇻', name: 'Tuvalu' },
    TW: { code: 'TW', flag: '🇹🇼', name: 'Taiwan' },
    TZ: { code: 'TZ', flag: '🇹🇿', name: 'Tanzania' },
    UA: { code: 'UA', flag: '🇺🇦', name: 'Ukraine' },
    UG: { code: 'UG', flag: '🇺🇬', name: 'Uganda' },
    UM: { code: 'UM', flag: '🇺🇲', name: 'United States Minor Outlying Islands' },
    US: { code: 'US', flag: '🇺🇸', name: 'United States of America' },
    UY: { code: 'UY', flag: '🇺🇾', name: 'Uruguay' },
    UZ: { code: 'UZ', flag: '🇺🇿', name: 'Uzbekistan' },
    VA: { code: 'VA', flag: '🇻🇦', name: 'Vatican City' },
    VC: { code: 'VC', flag: '🇻🇨', name: 'Saint Vincent and The Grenadines' },
    VE: { code: 'VE', flag: '🇻🇪', name: 'Venezuela' },
    VG: { code: 'VG', flag: '🇻🇬', name: 'Virgin Islands, British' },
    VI: { code: 'VI', flag: '🇻🇮', name: 'Virgin Islands, U.S.' },
    VN: { code: 'VN', flag: '🇻🇳', name: 'Viet Nam' },
    VU: { code: 'VU', flag: '🇻🇺', name: 'Vanuatu' },
    WF: { code: 'WF', flag: '🇼🇫', name: 'Wallis and Futuna' },
    WS: { code: 'WS', flag: '🇼🇸', name: 'Samoa' },
    YE: { code: 'YE', flag: '🇾🇪', name: 'Yemen' },
    YT: { code: 'YT', flag: '🇾🇹', name: 'Mayotte' },
    ZA: { code: 'ZA', flag: '🇿🇦', name: 'South Africa' },
    ZM: { code: 'ZM', flag: '🇿🇲', name: 'Zambia' },
    ZW: { code: 'ZW', flag: '🇿🇼', name: 'Zimbabwe' },
} as const satisfies Record<`${Uppercase<string>}`, Country>;

// European Economic Area (EEA) - https://en.wikipedia.org/wiki/European_Economic_Area
export const EEACountryCodes = [
    'AT',
    'BE',
    'BG',
    'CY',
    'CZ',
    'DE',
    'DK',
    'EE',
    'ES',
    'FI',
    'FR',
    'GR',
    'HR',
    'HU',
    'IE',
    'IS',
    'IT',
    'LI',
    'LT',
    'LU',
    'LV',
    'MT',
    'NL',
    'NO',
    'PL',
    'PT',
    'RO',
    'SE',
    'SI',
    'SK',
] as const;

export type EEACountryCodeType = (typeof EEACountryCodes)[number];

// Add Cloudflare-specific codes "XX" (no country data) and "T1" (Tor network).
// See: https://developers.cloudflare.com/fundamentals/reference/http-headers/#cf-ipcountry
export type CountryCode = keyof typeof countries | 'XX' | 'T1';
