// Gradle's worker limit does not limit Ninja's native compiler processes.
gradle.beforeProject { project ->
    ["com.android.application", "com.android.library"].each { pluginId ->
        project.plugins.withId(pluginId) {
            project.androidComponents.finalizeDsl { android ->
                def jobs = project.property("localNativeBuildJobs")
                android.defaultConfig.externalNativeBuild.cmake.arguments.addAll([
                    "-DCMAKE_JOB_POOLS=local_compile=${jobs};local_link=1".toString(),
                    "-DCMAKE_JOB_POOL_COMPILE=local_compile",
                    "-DCMAKE_JOB_POOL_LINK=local_link"
                ])
            }
        }
    }
}
