// This file is generated by generateIconTypes.mjs.

import type { JSX, SVGProps } from 'react';

type IconComponent = (props: SVGProps<SVGSVGElement>) => JSX.Element;

export declare const IceCreamIcon: IconComponent;
export declare const IceCreamFilledIcon: IconComponent;
export declare const IdentificationBadgeIcon: IconComponent;
export declare const IdentificationBadgeFilledIcon: IconComponent;
export declare const IdentificationCardIcon: IconComponent;
export declare const IdentificationCardFilledIcon: IconComponent;
export declare const ImageIcon: IconComponent;
export declare const ImageFilledIcon: IconComponent;
export declare const ImageSquareIcon: IconComponent;
export declare const ImageSquareFilledIcon: IconComponent;
export declare const ImagesIcon: IconComponent;
export declare const ImagesFilledIcon: IconComponent;
export declare const ImagesSquareIcon: IconComponent;
export declare const ImagesSquareFilledIcon: IconComponent;
export declare const InfinityIcon: IconComponent;
export declare const InfinityFilledIcon: IconComponent;
export declare const InfoIcon: IconComponent;
export declare const InfoFilledIcon: IconComponent;
export declare const InstagramLogoIcon: IconComponent;
export declare const InstagramLogoFilledIcon: IconComponent;
export declare const IntersectIcon: IconComponent;
export declare const IntersectFilledIcon: IconComponent;
export declare const IntersectSquareIcon: IconComponent;
export declare const IntersectSquareFilledIcon: IconComponent;
export declare const IntersectThreeIcon: IconComponent;
export declare const IntersectThreeFilledIcon: IconComponent;
