// This file is generated by generateIconTypes.mjs.

import type { JSX, SVGProps } from 'react';

type IconComponent = (props: SVGProps<SVGSVGElement>) => JSX.Element;

export declare const XIcon: IconComponent;
export declare const XCircleIcon: IconComponent;
export declare const XCircleFilledIcon: IconComponent;
export declare const XFilledIcon: IconComponent;
export declare const XSquareIcon: IconComponent;
export declare const XSquareFilledIcon: IconComponent;
