import fs from 'fs';
import path from 'path';

import { messages } from '../src/messages';
import { flatten } from '../src/utils';

const generatedDirPath = path.join(__dirname, '..', 'src', 'generated');
const generatedFilePath = path.join(generatedDirPath, 'translationKeys.ts');

const flatMessages = flatten(messages);
const translationKeys = Object.keys(flatMessages).sort();

const escapeSingleQuote = (value: string) => value.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
const typeLines = translationKeys.map(key => `    | '${escapeSingleQuote(key)}'`).join('\n');

const fileContent = `// Generated by scripts/generateTranslationKeys.ts.
// Do not edit manually.

export type TxKeyPath =
${typeLines};
`;

fs.mkdirSync(generatedDirPath, { recursive: true });
fs.writeFileSync(generatedFilePath, fileContent);
