import { readdirSync } from 'fs';
import { createRequire } from 'module';
import { resolve } from 'path';
import { fileURLToPath } from 'url';
import { type Plugin } from 'vite';

/**
 * Vite settings shared between the app config in this package and `suite/component-tests`, so the
 * gallery the component tests render resolves modules the same way the shipped app does.
 *
 * `import.meta.url` rather than `__dirname`: depending on the importing config, this file is
 * either bundled or loaded directly as an ES module, and only the former shims `__dirname`.
 */
const require = createRequire(import.meta.url);
const repoRoot = fileURLToPath(new URL('../..', import.meta.url));

const workspaceScopes = {
    packages: '@trezor',
    'suite-common': '@suite-common',
    suite: '@suite',
} as const;

// `suite-web` is the app shell being built; aliasing it to sources would make it import itself.
const excludedWorkspaces = ['suite-web'];

export const createWorkspaceAliases = () =>
    Object.entries(workspaceScopes).flatMap(([dir, scope]) =>
        readdirSync(resolve(repoRoot, dir), { withFileTypes: true })
            .filter(entry => entry.isDirectory() && !excludedWorkspaces.includes(entry.name))
            .map(entry => ({
                find: `${scope}/${entry.name}`,
                replacement: resolve(repoRoot, dir, entry.name),
            })),
    );

export const sharedAliases = [
    { find: 'core-js/actual', replacement: 'noop-core-js-actual' },
    // `packages/suite` imports its own sources as `src/...`.
    { find: 'src', replacement: resolve(repoRoot, 'packages/suite/src') },
    { find: 'crypto', replacement: require.resolve('crypto-browserify') },
    { find: 'buffer', replacement: require.resolve('buffer') },
    { find: 'stream', replacement: require.resolve('stream-browserify') },
    { find: 'vm', replacement: require.resolve('vm-browserify') },
    ...createWorkspaceAliases(),
];

/** A no-op replacement for `core-js/actual`, served as a virtual module. */
export const noopCoreJsPlugin = (): Plugin => {
    const virtualModuleId = 'noop-core-js-actual';
    const resolvedId = `\0${virtualModuleId}`;

    return {
        name: 'noop-core-js-actual',
        resolveId: id => (id === virtualModuleId ? resolvedId : undefined),
        load: id => (id === resolvedId ? 'export default {};' : undefined),
    };
};

/**
 * The autogenerated asset maps in `@suite-common/{icons,flags,illustrations}` and
 * `@trezor/product-components` address assets with CommonJS `require('./x.svg')`, which webpack
 * resolves but Vite leaves as a bare `require` for the browser to choke on.
 *
 * Scoped to those packages: `transform` runs for every module in the graph, and the regex scan
 * would be wasted on the thousands of sources that merely mention `require(`.
 */
const assetRequireDirs = [
    'suite-common/icons',
    'suite-common/flags',
    'suite-common/illustrations',
    'packages/product-components',
].map(dir => `${resolve(repoRoot, dir)}/`);

export const requireAssetPlugin = (): Plugin => ({
    name: 'require-asset-to-url',
    enforce: 'pre',
    transform(code, id) {
        const cleanId = id.split('?')[0] ?? id;
        const isAssetPackageSource = assetRequireDirs.some(dir => cleanId.startsWith(dir));
        if (!isAssetPackageSource || !code.includes('require(')) {
            return null;
        }

        return {
            code: code.replace(
                /require\((['"`])([^'"`]+\.(?:svg|png|gif|jpe?g|webp))\1\)/g,
                'new URL($1$2$1, import.meta.url).href',
            ),
            map: null,
        };
    },
});
