import { ExchangeInfo } from '@wallet-actions/coinmarketExchangeActions';
import { ExchangeTrade } from 'invity-api';

export const EXCHANGE_INFO: ExchangeInfo = {
    exchangeList: [
        {
            name: 'changenow',
            companyName: 'ChangeNOW',
            logo: 'changenow-icon.jpg',
            isActive: true,
            isFixedRate: false,
            isDex: false,
            buyTickers: ['ETH', 'XMR', 'BTC'],
            sellTickers: ['ETH', 'XMR', 'BTC'],
            addressFormats: {
                BCH: 'legacy',
                LTC: 'type3',
            },
            statusUrl: 'https://changenow.io/exchange/txs/{{orderId}}',
            kycUrl: 'https://changenow.io/faq#kyc',
            supportUrl: 'https://support.changenow.io',
            kycPolicy: 'Changenow enforces KYC on suspicious transactions. Refunds without KYC.',
            isRefundRequired: false,
        },
        {
            name: 'changenowfr',
            companyName: 'ChangeNOW',
            logo: 'changenowfr-icon.jpg',
            isActive: true,
            isFixedRate: true,
            isDex: false,
            buyTickers: ['ETH', 'BTC'],
            sellTickers: ['ETH', 'BTC'],
            addressFormats: {
                BCH: 'legacy',
                LTC: 'type3',
            },
            statusUrl: 'https://changenow.io/exchange/txs/{{orderId}}',
            kycUrl: 'https://changenow.io/faq#kyc',
            supportUrl: 'https://support.changenow.io',
            kycPolicy: 'Changenow enforces KYC on suspicious transactions. Refunds without KYC.',
            isRefundRequired: false,
        },
        {
            name: 'changelly',
            companyName: 'Changelly',
            logo: 'changelly-icon.jpg',
            isActive: true,
            isFixedRate: false,
            isDex: false,
            buyTickers: ['BTC', 'ETH'],
            sellTickers: ['BTC', 'ETH'],
            addressFormats: {
                BCH: 'cashaddr',
                LTC: 'type3',
            },
            statusUrl: '',
            kycUrl: 'https://changelly.com/aml-kyc',
            supportUrl: 'https://support.changelly.com',
            kycPolicy:
                'Changelly enforces KYC on suspicious transactions. In such cases, even refunds are with KYC.',
            isRefundRequired: false,
        },
        {
            name: 'changellyfr',
            companyName: 'Changelly',
            logo: 'changellyfr-icon.jpg',
            isActive: true,
            isFixedRate: true,
            isDex: false,
            buyTickers: ['BTC', 'ETH'],
            sellTickers: ['BTC', 'ETH'],
            addressFormats: {
                BCH: 'cashaddr',
                LTC: 'type3',
            },
            statusUrl: '',
            kycUrl: 'https://changelly.com/aml-kyc',
            supportUrl: 'https://support.changelly.com',
            kycPolicy:
                'Changelly enforces KYC on suspicious transactions. In such cases, even refunds are with KYC.',
            isRefundRequired: true,
        },
        {
            name: 'changehero',
            companyName: 'ChangeHero',
            logo: 'changehero-icon.jpg',
            isActive: true,
            isFixedRate: false,
            isDex: false,
            buyTickers: ['BTC'],
            sellTickers: ['BTC'],
            addressFormats: {
                BCH: 'legacy',
                LTC: 'type3',
            },
            statusUrl: '',
            kycUrl: 'https://changehero.io/aml-kyc',
            supportUrl: 'https://support.changehero.io',
            kycPolicy: 'Changehero enforces KYC on suspicious transactions. Refunds without KYC.',
            isRefundRequired: false,
        },
        {
            name: 'changeherofr',
            companyName: 'ChangeHero',
            logo: 'changeherofr-icon.jpg',
            isActive: true,
            isFixedRate: true,
            isDex: false,
            buyTickers: ['BTC'],
            sellTickers: ['BTC'],
            addressFormats: {
                BCH: 'legacy',
                LTC: 'type3',
            },
            statusUrl: '',
            kycUrl: 'https://changehero.io/aml-kyc',
            supportUrl: 'https://support.changehero.io',
            kycPolicy: 'Changehero enforces KYC on suspicious transactions. Refunds without KYC.',
            isRefundRequired: true,
        },
        {
            name: 'foxexchange',
            companyName: 'FoxExchange',
            logo: 'foxexchange-icon.jpg',
            isActive: true,
            isFixedRate: false,
            isDex: false,
            buyTickers: ['BTC'],
            sellTickers: ['BTC'],
            addressFormats: {
                BCH: 'cashaddr',
                LTC: 'type3',
            },
            statusUrl: 'https://fox.exchange/tx/{{orderId}}',
            kycUrl: 'https://fox.exchange',
            supportUrl: 'https://fox.exchange',
            kycPolicy:
                'Foxexchange enforces KYC on suspicious transactions. In such cases, even refunds are with KYC.',
            isRefundRequired: false,
        },
        {
            name: 'foxexchangefr',
            companyName: 'FoxExchange',
            logo: 'foxexchange-icon.jpg',
            isActive: true,
            isFixedRate: true,
            isDex: false,
            buyTickers: ['BTC'],
            sellTickers: ['BTC', 'ETH'],
            addressFormats: {
                BCH: 'cashaddr',
                LTC: 'type3',
            },
            statusUrl: 'https://fox.exchange/tx/{{orderId}}',
            kycUrl: 'https://fox.exchange',
            supportUrl: 'https://fox.exchange',
            kycPolicy:
                'Foxexchange enforces KYC on suspicious transactions. In such cases, even refunds are with KYC.',
            isRefundRequired: false,
        },
        {
            name: 'morphtoken',
            companyName: 'MorphToken',
            logo: 'morphtoken-icon.jpg',
            isActive: true,
            isFixedRate: false,
            isDex: false,
            buyTickers: ['BTC', 'ETH', 'XMR'],
            sellTickers: ['BTC', 'ETH', 'XMR'],
            addressFormats: {
                BCH: 'cashaddr',
                LTC: 'type3',
            },
            statusUrl: '',
            kycUrl: 'https://morphtoken.com',
            supportUrl: 'https://morphtoken.com',
            isRefundRequired: false,
        },
        {
            name: 'coinswitch',
            companyName: 'CoinSwitch',
            logo: 'coinswitch-icon.jpg',
            isActive: true,
            isFixedRate: false,
            isDex: false,
            buyTickers: ['ETH'],
            sellTickers: ['ETH'],
            addressFormats: {
                BCH: 'legacy',
                LTC: 'type3',
            },
            statusUrl: 'https://coinswitch.co/app/exchange/transaction/{{orderId}}',
            kycUrl: 'https://coinswitch.co',
            supportUrl: 'https://coinswitch.co',
            kycPolicy:
                'Coinswitch enforces KYC on suspicious transactions. In such cases, even refunds are with KYC.',
            isRefundRequired: false,
        },
        {
            name: 'coinswitchfr',
            companyName: 'CoinSwitch',
            logo: 'coinswitchfr-icon.jpg',
            isActive: true,
            isFixedRate: true,
            isDex: false,
            buyTickers: ['BTC'],
            sellTickers: ['BTC'],
            addressFormats: {
                BCH: 'legacy',
                LTC: 'type3',
            },
            statusUrl: 'https://coinswitch.co/app/exchange/transaction/{{orderId}}',
            kycUrl: 'https://coinswitch.co',
            supportUrl: 'https://coinswitch.co',
            kycPolicy:
                'Coinswitch enforces KYC on suspicious transactions. In such cases, even refunds are with KYC.',
            isRefundRequired: true,
        },
    ],
    providerInfos: {
        changenow: {
            name: 'changenow',
            companyName: 'ChangeNOW',
            logo: 'changenow-icon.jpg',
            isActive: true,
            isFixedRate: false,
            isDex: false,
            buyTickers: ['ETH', 'XMR', 'BTC'],
            sellTickers: ['ETH', 'XMR', 'BTC'],
            addressFormats: {
                BCH: 'legacy',
                LTC: 'type3',
            },
            statusUrl: 'https://changenow.io/exchange/txs/{{orderId}}',
            kycUrl: 'https://changenow.io/faq#kyc',
            supportUrl: 'https://support.changenow.io',
            kycPolicy: 'Changenow enforces KYC on suspicious transactions. Refunds without KYC.',
            isRefundRequired: false,
        },
        changenowfr: {
            name: 'changenowfr',
            companyName: 'ChangeNOW',
            logo: 'changenowfr-icon.jpg',
            isActive: true,
            isFixedRate: true,
            isDex: false,
            buyTickers: ['ETH', 'XMR', 'BTC'],
            sellTickers: ['ETH', 'XMR', 'BTC'],
            addressFormats: {
                BCH: 'legacy',
                LTC: 'type3',
            },
            statusUrl: 'https://changenow.io/exchange/txs/{{orderId}}',
            kycUrl: 'https://changenow.io/faq#kyc',
            supportUrl: 'https://support.changenow.io',
            kycPolicy: 'Changenow enforces KYC on suspicious transactions. Refunds without KYC.',
            isRefundRequired: false,
        },
        changelly: {
            name: 'changelly',
            companyName: 'Changelly',
            logo: 'changelly-icon.jpg',
            isActive: true,
            isFixedRate: false,
            isDex: false,
            buyTickers: ['BTC', 'ETH'],
            sellTickers: ['BTC', 'ETH'],
            addressFormats: {
                BCH: 'cashaddr',
                LTC: 'type3',
            },
            statusUrl: '',
            kycUrl: 'https://changelly.com/aml-kyc',
            supportUrl: 'https://support.changelly.com',
            kycPolicy:
                'Changelly enforces KYC on suspicious transactions. In such cases, even refunds are with KYC.',
            isRefundRequired: false,
        },
        changellyfr: {
            name: 'changellyfr',
            companyName: 'Changelly',
            logo: 'changellyfr-icon.jpg',
            isActive: true,
            isFixedRate: true,
            isDex: false,
            buyTickers: ['BTC', 'ETH'],
            sellTickers: ['BTC', 'ETH'],
            addressFormats: {
                BCH: 'cashaddr',
                LTC: 'type3',
            },
            statusUrl: '',
            kycUrl: 'https://changelly.com/aml-kyc',
            supportUrl: 'https://support.changelly.com',
            kycPolicy:
                'Changelly enforces KYC on suspicious transactions. In such cases, even refunds are with KYC.',
            isRefundRequired: true,
        },
        changehero: {
            name: 'changehero',
            companyName: 'ChangeHero',
            logo: 'changehero-icon.jpg',
            isActive: true,
            isFixedRate: false,
            isDex: false,
            buyTickers: ['BTC'],
            sellTickers: ['BTC'],
            addressFormats: {
                BCH: 'legacy',
                LTC: 'type3',
            },
            statusUrl: '',
            kycUrl: 'https://changehero.io/aml-kyc',
            supportUrl: 'https://support.changehero.io',
            kycPolicy: 'Changehero enforces KYC on suspicious transactions. Refunds without KYC.',
            isRefundRequired: false,
        },
        changeherofr: {
            name: 'changeherofr',
            companyName: 'ChangeHero',
            logo: 'changeherofr-icon.jpg',
            isActive: true,
            isFixedRate: true,
            isDex: false,
            buyTickers: ['BTC'],
            sellTickers: ['BTC'],
            addressFormats: {
                BCH: 'legacy',
                LTC: 'type3',
            },
            statusUrl: '',
            kycUrl: 'https://changehero.io/aml-kyc',
            supportUrl: 'https://support.changehero.io',
            kycPolicy: 'Changehero enforces KYC on suspicious transactions. Refunds without KYC.',
            isRefundRequired: true,
        },
        foxexchange: {
            name: 'foxexchange',
            companyName: 'FoxExchange',
            logo: 'foxexchange-icon.jpg',
            isActive: true,
            isFixedRate: false,
            isDex: false,
            buyTickers: ['BTC'],
            sellTickers: ['BTC'],
            addressFormats: {
                BCH: 'cashaddr',
                LTC: 'type3',
            },
            statusUrl: 'https://fox.exchange/tx/{{orderId}}',
            kycUrl: 'https://fox.exchange',
            supportUrl: 'https://fox.exchange',
            kycPolicy:
                'Foxexchange enforces KYC on suspicious transactions. In such cases, even refunds are with KYC.',
            isRefundRequired: false,
        },
        foxexchangefr: {
            name: 'foxexchangefr',
            companyName: 'FoxExchange',
            logo: 'foxexchange-icon.jpg',
            isActive: true,
            isFixedRate: true,
            isDex: false,
            buyTickers: ['BTC'],
            sellTickers: ['BTC'],
            addressFormats: {
                BCH: 'cashaddr',
                LTC: 'type3',
            },
            statusUrl: 'https://fox.exchange/tx/{{orderId}}',
            kycUrl: 'https://fox.exchange',
            supportUrl: 'https://fox.exchange',
            kycPolicy:
                'Foxexchange enforces KYC on suspicious transactions. In such cases, even refunds are with KYC.',
            isRefundRequired: false,
        },
        morphtoken: {
            name: 'morphtoken',
            companyName: 'MorphToken',
            logo: 'morphtoken-icon.jpg',
            isActive: true,
            isFixedRate: false,
            isDex: false,
            buyTickers: ['BTC', 'ETH', 'XMR'],
            sellTickers: ['BTC', 'ETH', 'XMR'],
            addressFormats: {
                BCH: 'cashaddr',
                LTC: 'type3',
            },
            statusUrl: '',
            kycUrl: 'https://morphtoken.com',
            supportUrl: 'https://morphtoken.com',
            isRefundRequired: false,
        },
        coinswitch: {
            name: 'coinswitch',
            companyName: 'CoinSwitch',
            logo: 'coinswitch-icon.jpg',
            isActive: true,
            isFixedRate: false,
            isDex: false,
            buyTickers: ['ETH'],
            sellTickers: ['ETH'],
            addressFormats: {
                BCH: 'legacy',
                LTC: 'type3',
            },
            statusUrl: 'https://coinswitch.co/app/exchange/transaction/{{orderId}}',
            kycUrl: 'https://coinswitch.co',
            supportUrl: 'https://coinswitch.co',
            kycPolicy:
                'Coinswitch enforces KYC on suspicious transactions. In such cases, even refunds are with KYC.',
            isRefundRequired: false,
        },
        coinswitchfr: {
            name: 'coinswitchfr',
            companyName: 'CoinSwitch',
            logo: 'coinswitchfr-icon.jpg',
            isActive: true,
            isFixedRate: true,
            isDex: false,
            buyTickers: ['BTC'],
            sellTickers: ['BTC'],
            addressFormats: {
                BCH: 'legacy',
                LTC: 'type3',
            },
            statusUrl: 'https://coinswitch.co/app/exchange/transaction/{{orderId}}',
            kycUrl: 'https://coinswitch.co',
            supportUrl: 'https://coinswitch.co',
            kycPolicy:
                'Coinswitch enforces KYC on suspicious transactions. In such cases, even refunds are with KYC.',
            isRefundRequired: true,
        },
    },
    buySymbols: new Set(''),
    sellSymbols: new Set(''),
};
export const MIN_MAX_QUOTES_OK: ExchangeTrade[] = [
    {
        send: 'LTC',
        sendStringAmount: '12',
        receive: 'BTC',
        receiveStringAmount: '0.0609979',
        rate: 0.005083158333333333,
        min: 0.5688,
        max: 'NONE',
        fee: 'UNKNOWN',
        exchange: 'changelly',
    },
    {
        send: 'LTC',
        sendStringAmount: '12',
        receive: 'BTC',
        receiveStringAmount: '0.0605096167302',
        rate: 0.00504246806085,
        min: 1.68,
        max: 130,
        fee: 'UNKNOWN',
        exchange: 'foxexchange',
        quoteToken: '',
    },
    {
        send: 'LTC',
        sendStringAmount: '12',
        receive: 'BTC',
        receiveStringAmount: '0.06047229',
        rate: 0.0050393575,
        min: 1.68,
        max: 130,
        fee: 'INCLUDED',
        exchange: 'foxexchangefr',
        quoteToken: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9',
    },
    {
        send: 'LTC',
        sendStringAmount: '12',
        receive: 'BTC',
        receiveStringAmount: '0.06036741979259172204',
        rate: 0.005030618316049311,
        min: 0.35206704205749473,
        max: 195.59280114305264,
        fee: 'INCLUDED',
        rateIdentificator: '6ad45ee9-a8fa-4d25-a3c8-05361176b49d',
        exchange: 'changeherofr',
    },
    {
        send: 'LTC',
        sendStringAmount: '12',
        receive: 'BTC',
        receiveStringAmount: '0.060238681',
        rate: 0.005019890083333333,
        min: 0.35121471511608626,
        max: 'NONE',
        fee: 'UNKNOWN',
        exchange: 'changehero',
    },
    {
        send: 'LTC',
        sendStringAmount: '12',
        receive: 'BTC',
        receiveStringAmount: '0.059907672',
        rate: 0.004992305999999999,
        min: 0.5245852799999999,
        max: 'NONE',
        fee: 'UNKNOWN',
        exchange: 'changenow',
    },
    {
        send: 'LTC',
        sendStringAmount: '12',
        receive: 'BTC',
        receiveStringAmount: '0.05984359',
        rate: 0.004986965833333333,
        min: 0.8295,
        max: 719.15,
        fee: 'INCLUDED',
        offerReferenceId: 'db551578-915a-47c9-9197-a656e9372f2c',
        exchange: 'coinswitchfr',
    },
    {
        send: 'LTC',
        sendStringAmount: '12',
        receive: 'BTC',
        receiveStringAmount: '0.05980199613749862984',
        rate: 0.004983499678124886,
        min: 0.85,
        max: 80,
        fee: 'UNKNOWN',
        exchange: 'coinswitch',
    },
    {
        send: 'LTC',
        sendStringAmount: '12',
        receive: 'BTC',
        receiveStringAmount: '0.0595996968',
        rate: 0.0049666414,
        min: 0.948,
        max: 757,
        fee: 'INCLUDED',
        rateIdentificator: 'e98f80e3e29dd57c0356141836c113f1c19ecadf66ee77fde5835796499cfe065e73',
        exchange: 'changellyfr',
    },
    {
        send: 'LTC',
        sendStringAmount: '12',
        receive: 'BTC',
        receiveStringAmount: '0.0595048',
        rate: 0.004958733333333333,
        min: 0.70367472,
        max: 293.1036283,
        fee: 'INCLUDED',
        exchange: 'changenowfr',
    },
];

export const MIN_MAX_QUOTES_LOW: ExchangeTrade[] = [
    {
        send: 'LTC',
        sendStringAmount: '.1',
        receive: 'BTC',
        receiveStringAmount: '0.000503106150246929012',
        rate: 0.00503106150246929,
        min: 0.3520800003243513,
        max: 195.60000018019517,
        fee: 'INCLUDED',
        rateIdentificator: 'ed43e76b-eb1d-4363-bc32-e2e768933de9',
        exchange: 'changeherofr',
    },
    {
        send: 'LTC',
        sendStringAmount: '.1',
        receive: 'BTC',
        receiveStringAmount: '0.000498498993472488582',
        rate: 0.0049849899347248865,
        min: 0.85,
        max: 80,
        fee: 'UNKNOWN',
        exchange: 'coinswitch',
    },
    {
        send: 'LTC',
        sendStringAmount: '.1',
        receive: 'BTC',
        receiveStringAmount: '0.00049665676',
        rate: 0.0049665676,
        min: 0.948,
        max: 757,
        fee: 'INCLUDED',
        rateIdentificator: 'e98f80e3e29dd57c0356141836c113f1c29cccdd66ee77fde58357964a98f5045471',
        exchange: 'changellyfr',
    },
    {
        send: 'LTC',
        sendStringAmount: '.1',
        receive: 'BTC',
        receiveStringAmount: '0.000342342',
        rate: 0.00342342,
        min: 0.5245852799999999,
        max: 'NONE',
        fee: 'UNKNOWN',
        exchange: 'changenow',
    },
    {
        send: 'LTC',
        sendStringAmount: '.1',
        receive: 'BTC',
        receiveStringAmount: '0.00015492504',
        rate: 0.0015492504,
        min: 0.35121471511608626,
        max: 'NONE',
        fee: 'UNKNOWN',
        exchange: 'changehero',
    },
    { error: 'Invalid amount: minimal amount is 0.474', exchange: 'changelly' },
    {
        send: 'LTC',
        sendStringAmount: '.1',
        receive: 'BTC',
        min: 0.7043630399999999,
        max: 293.3972814,
        fee: 'INCLUDED',
        error: 'Amount out of range.',
        exchange: 'changenowfr',
    },
    {
        send: 'LTC',
        sendStringAmount: '.1',
        receive: 'BTC',
        min: 0.8295,
        max: 719.15,
        error: 'Amount out of range.',
        exchange: 'coinswitchfr',
    },
    {
        send: 'LTC',
        sendStringAmount: '.1',
        receive: 'BTC',
        min: 1.68,
        max: 130,
        fee: 'UNKNOWN',
        error: 'Amount out of range.',
        exchange: 'foxexchange',
        quoteToken: '',
    },
    {
        send: 'LTC',
        sendStringAmount: '.1',
        receive: 'BTC',
        min: 1.68,
        max: 130,
        fee: 'INCLUDED',
        error: 'Amount out of range.',
        exchange: 'foxexchangefr',
    },
];

export const MIN_MAX_QUOTES_CANNOT_TRADE: ExchangeTrade[] = [
    { error: 'Cannot trade pair LTC-DATA.', exchange: 'changehero' },
    { error: 'Cannot trade pair LTC-DATA.', exchange: 'changeherofr' },
    { error: 'Cannot trade pair LTC-DATA.', exchange: 'changelly' },
    { error: 'Cannot trade pair LTC-DATA.', exchange: 'changellyfr' },
    { error: 'Cannot trade pair LTC-DATA.', exchange: 'changenow' },
    { error: 'Cannot trade pair LTC-DATA.', exchange: 'changenowfr' },
    { error: 'Cannot trade pair LTC-DATA.', exchange: 'coinswitch' },
    { error: 'Cannot trade pair LTC-DATA.', exchange: 'coinswitchfr' },
    { error: 'Cannot trade pair LTC-DATA.', exchange: 'foxexchange' },
    { error: 'Cannot trade pair LTC-DATA.', exchange: 'foxexchangefr' },
];
