import { readdir, rm, writeFile } from 'node:fs/promises';
import { extname } from 'node:path';

import { getIconExportName } from './getIconExportName.mjs';

const generatedIconsDirectory = new URL('./src/generated/icons/', import.meta.url);
const iconTypesDirectory = new URL('./src/types/', import.meta.url);
const iconTypesIndex = new URL('./src/index.ts', import.meta.url);

const generatedIconFileNames = (await readdir(generatedIconsDirectory))
    .filter(fileName => extname(fileName) === '.tsx')
    .sort();

const generatedFileHeader = '// This file is generated by generateIconTypes.mjs.';
const iconTypeExports = generatedIconFileNames.map(
    fileName => `export declare const ${getIconExportName(fileName)}: IconComponent;`,
);
const iconTypesIndexContent = [
    generatedFileHeader,
    '',
    "import type { JSX, SVGProps } from 'react';",
    '',
    'type IconComponent = (props: SVGProps<SVGSVGElement>) => JSX.Element;',
    '',
    ...iconTypeExports,
    '',
].join('\n');

await rm(iconTypesDirectory, { recursive: true, force: true });
await writeFile(iconTypesIndex, iconTypesIndexContent);
