export enum EventType {
    AccountsActions = 'accounts/actions',
    AccountsActiveStaking = 'accounts/active-staking',
    AccountsEmptyAccountReceive = 'accounts/empty-account/receive',
    AccountsNewAccount = 'accounts/new-account',
    AccountsNonZeroBalance = 'accounts/non-zero-balance',
    AccountsStatus = 'accounts/status',
    AccountsTokensStatus = 'accounts/tokens-status',
    AccountsTransactionsExport = 'accounts/transactions-export',
    // eslint-disable-next-line local-rules/analytics-event-name
    AddToken = 'add-token',
    AppFormPercentButtons = 'app/form-percent-buttons',
    // eslint-disable-next-line local-rules/analytics-event-name
    AppUpdate = 'app-update',
    AppUriHandler = 'app/uri-handler',
    // eslint-disable-next-line local-rules/analytics-event-name
    AutostartModal = 'autostart-modal',
    // eslint-disable-next-line local-rules/analytics-event-name
    CoinjoinAnonymityGain = 'coinjoin/anonymity-gain',
    // eslint-disable-next-line local-rules/analytics-event-name
    CreateBackup = 'create-backup',
    // eslint-disable-next-line local-rules/analytics-event-name
    CreateReceiveAddressConfirmOnTrezor = 'create-receive-address/confirm-on-trezor',
    // eslint-disable-next-line local-rules/analytics-event-name
    CreateReceiveAddressCopyAddress = 'create-receive-address/copy-address',
    // eslint-disable-next-line local-rules/analytics-event-name
    CreateReceiveAddressShowAddress = 'create-receive-address/show-address',
    DashboardActions = 'dashboard/actions',
    DashboardActivateAssetsModal = 'dashboard/activate-assets-modal',
    DashboardReceiveModal = 'dashboard/receive-modal',
    DashboardReceiveModalOptions = 'dashboard/receive-modal/options',
    DashboardSendModal = 'dashboard/send-modal',
    DashboardSendModalOptions = 'dashboard/send-modal/options',
    // eslint-disable-next-line local-rules/analytics-event-name
    DeviceConnect = 'device-connect',
    // eslint-disable-next-line local-rules/analytics-event-name
    DeviceConnectionConnectButton = 'device-connection/connect-button',
    // eslint-disable-next-line local-rules/analytics-event-name
    DeviceConnectionHintModal = 'device-connection/hint-modal', // The rest of device-connection events are in shared constants.
    // eslint-disable-next-line local-rules/analytics-event-name
    DeviceDisconnect = 'device-disconnect',
    // eslint-disable-next-line local-rules/analytics-event-name
    DeviceSetupCompleted = 'device-setup-completed',
    // eslint-disable-next-line local-rules/analytics-event-name
    DeviceSetupStarted = 'device-setup-started',
    // eslint-disable-next-line local-rules/analytics-event-name
    DeviceUpdateFirmware = 'device-update-firmware',
    GuideFeedbackNavigation = 'guide/feedback/navigation',
    GuideFeedbackSubmit = 'guide/feedback/submit',
    GuideHeaderNavigation = 'guide/header/navigation',
    GuideNodeNavigation = 'guide/node/navigation',
    GuideTooltipLinkNavigation = 'guide/tooltip-link/navigation',
    MenuGuide = 'menu/guide',
    MenuNotificationsToggle = 'menu/notifications/toggle',
    MenuToggleDiscreet = 'menu/toggle-discreet',
    PromoDashboardBanner = 'promo/dashboard-banner',
    PromoDesktop = 'promo/desktop',
    PromoMobile = 'promo/mobile',
    PromoReferralButton = 'promo/referral-button',
    // eslint-disable-next-line local-rules/analytics-event-name
    RemoveToken = 'remove-token',
    // eslint-disable-next-line local-rules/analytics-event-name
    RouterLocationChange = 'router/location-change',
    // eslint-disable-next-line local-rules/analytics-event-name
    SelectWalletType = 'select-wallet-type',
    SendConfirmedOnDevice = 'send/confirmed-on-device',
    SendDetailOpened = 'send/detail-opened',
    SendInitialised = 'send/initialised',
    SendQrScan = 'send/qr-scan',
    // eslint-disable-next-line local-rules/analytics-event-name
    SendRawTransaction = 'send-raw-transaction',
    SettingsAnalytics = 'settings/analytics',
    SettingsCoins = 'settings/coins',
    SettingsCoinsBackend = 'settings/coins/backend',
    SettingsDeviceChangeBrightness = 'settings/device/change-brightness',
    SettingsDeviceChangeHapticFeedback = 'settings/device/change-haptic-feedback',
    SettingsDeviceChangeOrientation = 'settings/device/change-orientation',
    SettingsDeviceChangePassphraseProtection = 'settings/device/change-passphrase-protection',
    SettingsDeviceChangePin = 'settings/device/change-pin',
    SettingsDeviceChangePinProtection = 'settings/device/change-pin-protection',
    SettingsDeviceChangeThpAutoconnect = 'settings/device/change-thp-autoconnect',
    SettingsDeviceChangeWipeCode = 'settings/device/change-wipe-code',
    SettingsDeviceCheckSeed = 'settings/device/check-seed',
    SettingsDeviceDisableWipeCode = 'settings/device/disable-wipe-code',
    SettingsDeviceMultiShareBackup = 'settings/device/multi-share-backup',
    SettingsDeviceSetupWipeCode = 'settings/device/setup-wipe-code',
    SettingsDeviceUpdateAutoLock = 'settings/device/update-auto-lock',
    SettingsGeneralAddressDisplayType = 'settings/general/address-display-type',
    SettingsGeneralAutoEject = 'settings/general/auto-eject',
    SettingsGeneralBioAuth = 'settings/general/bio-auth',
    SettingsGeneralChangeBitcoinUnit = 'settings/general/change-bitcoin-unit',
    SettingsGeneralChangeFiat = 'settings/general/change-fiat',
    SettingsGeneralChangeLanguage = 'settings/general/change-language',
    SettingsGeneralChangeTheme = 'settings/general/change-theme',
    SettingsGeneralEarlyAccess = 'settings/general/early-access',
    SettingsGeneralLabelingProvider = 'settings/general/labeling-provider',
    SettingsGeneralMevProtection = 'settings/general/mev-protection',
    SettingsGeneralNetworkReserve = 'settings/general/network-reserve',
    SettingsTor = 'settings/tor',
    SettingsTorOnionLinks = 'settings/tor/onion-links',
    StakingChangeDelegate = 'staking/change-delegate',
    StakingClaim = 'staking/claim',
    StakingConfirm = 'staking/confirm',
    StakingNavigate = 'staking/navigate',
    StakingStake = 'staking/stake',
    StakingUnstake = 'staking/unstake',
    StakingUpdateProvider = 'staking/update-provider',
    YieldNavigate = 'yield/navigate',
    YieldSupply = 'yield/supply',
    YieldWithdraw = 'yield/withdraw',
    YieldClaim = 'yield/claim',
    // eslint-disable-next-line local-rules/analytics-event-name
    SuiteReady = 'suite-ready',
    // eslint-disable-next-line local-rules/analytics-event-name
    SwitchDeviceEject = 'switch-device/eject',
    // eslint-disable-next-line local-rules/analytics-event-name
    SwitchDeviceForget = 'switch-device/forget',
    // eslint-disable-next-line local-rules/analytics-event-name
    SwitchDeviceRemember = 'switch-device/remember',
    // eslint-disable-next-line local-rules/analytics-event-name
    TradeApproval = 'trade/approval',
    // eslint-disable-next-line local-rules/analytics-event-name
    TradeBuy = 'trade/buy',
    // eslint-disable-next-line local-rules/analytics-event-name
    TradeCompareOffers = 'trade/compare-offers',
    // eslint-disable-next-line local-rules/analytics-event-name
    TradeConfirmTrade = 'trade/confirm-trade',
    // eslint-disable-next-line local-rules/analytics-event-name
    TradeExchange = 'trade/exchange',
    // eslint-disable-next-line local-rules/analytics-event-name
    TradeNavigate = 'trade/navigate',
    // eslint-disable-next-line local-rules/analytics-event-name
    TradeReceivedQuotes = 'trade/received-quotes',
    // eslint-disable-next-line local-rules/analytics-event-name
    TradeSell = 'trade/sell',
    // eslint-disable-next-line local-rules/analytics-event-name
    TradeStatus = 'trade/status',
    TransactionCancel = 'transaction/cancel',
    // eslint-disable-next-line local-rules/analytics-event-name
    TransactionCreated = 'transaction-created',
    TransactionTimeoutRetry = 'transaction/timeout-retry',
    // eslint-disable-next-line local-rules/analytics-event-name
    TransportType = 'transport-type',
}
