name: "[Bot] set PR status To be reviewed"

on:
  pull_request:
    types:
      - ready_for_review
jobs:
  pr_set_status:
    name: Move PR to To be reviewed
    runs-on: ubuntu-latest
    steps:
      - name: Update Project Card Status
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.TREZOR_BOT_TOKEN }}
        with:
          script: |
            // GraphQL query to find the project card associated with the current PR
            const findPRQuery = `
            query FindProjectCard($repoOwner: String!, $repoName: String!, $prNumber: Int!) {
                repository(owner: $repoOwner, name: $repoName) {
                  pullRequest(number: $prNumber) {
                      id
                  }
                }
            }
            `;

            const findPRResponse = await github.graphql(findPRQuery, {
              repoOwner: context.repo.owner,
              repoName: context.repo.repo,
              prNumber: context.issue.number
            });

            const itemId = findPRResponse.repository.pullRequest.id;


            // GraphQL mutation to update the custom field "Status" of the project card
            const updateItemFieldMutation = `
            mutation UpdateItemCustomField($projectId: ID!,$itemId: ID!, $fieldId: ID!, $value: ProjectV2FieldValue!) {
                updateProjectV2ItemFieldValue(input: {projectId: $projectId,itemId: $itemId, fieldId: $fieldId, value: $value}) {
                    clientMutationId
                }
            }
            `;


            await github.graphql(updateItemFieldMutation, {
              projectId: "PVT_kwDOAD9FD84AB-s-" // Suite Pull Requests
              itemId: itemId,
              fieldId: "PVTSSF_lADOAD9FD84AB-s-zgBJWdk", // Status
              value: {
                  singleSelectOptionId: "49f430a3"  // To be reviewed
                  }
            });
