name: "[Bot] stale PR & Issues monitor"

on:
  schedule:
    - cron: "0 17 * * *" # Daily at 5pm UTC
  workflow_dispatch: # Allow manual runs for testing

jobs:
  check-stale:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run stale issues and PRs monitor
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 #v9
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_STALE_REMINDER }}
          STALE_DAYS: "2"
          TARGET_OWNER: "trezor"
          TARGET_REPO: "trezor-suite"
        with:
          script: |
            const script = require('./scripts/stale-monitor.js')
            await script({ github, context, core })
