name: "[Build] suite-native adhoc"

on:
  workflow_dispatch:
    inputs:
      PLATFORM:
        type: choice
        options:
          - all
          - android
          - ios
        description: Select platform to run build
        required: true

jobs:
  adhoc-build:
    if: github.repository == 'trezor/trezor-suite' || github.repository == 'trezor/trezor-suite-private'
    name: EAS adhoc build
    runs-on: ubuntu-latest
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      EXPO_PUBLIC_ENVIRONMENT: preview
    permissions:
      contents: read
      pull-requests: write
      actions: write
    steps:
      - name: Print selected platform
        run: |
          echo "Selected platform: ${{ github.event.inputs.PLATFORM }}"
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: ".nvmrc"
          cache: yarn
      - name: Setup EAS
        uses: expo/expo-github-action@c7b66a9c327a43a8fa7c0158e7f30d6040d2481e # v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN_DEVELOP }}
      - name: Install libs
        run: |
          yarn workspaces focus @suite-native/app
          yarn workspace @suite-native/app exec patch-package # Apply global patches.
      - name: Trigger adhoc build Android
        working-directory: suite-native/app
        if: ${{ github.event.inputs.PLATFORM == 'android' || github.event.inputs.PLATFORM == 'all' }}
        run: |
          eas build --profile adhoc \
            -p android \
            --non-interactive \
            --no-wait \
            --freeze-credentials \
            --message ${{ github.sha }} \
            2>&1 | sed -E 's/UDID: [A-Za-z0-9-]+/UDID: [REDACTED]/g' # remove UDIDs from output
      - name: Trigger adhoc build iOS
        working-directory: suite-native/app
        if: ${{ github.event.inputs.PLATFORM == 'ios' || github.event.inputs.PLATFORM == 'all' }}
        run: |
          eas build --profile adhoc \
            -p ios \
            --auto-submit \
            --non-interactive \
            --no-wait \
            --freeze-credentials \
            --message ${{ github.sha }} \
            2>&1 | sed -E 's/UDID: [A-Za-z0-9-]+/UDID: [REDACTED]/g' # remove UDIDs from output
