name: "Reusable Build Suite Desktop for E2E tests"
on:
  workflow_call:

jobs:
  build-desktop:
    runs-on: ubuntu-latest
    env:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_GHACTIONS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6
        with:
          node-version-file: ".nvmrc"
          cache: yarn

      - name: Cache node_modules
        id: node-modules-cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v5
        with:
          path: node_modules
          key: node_modules-suite-desktop-e2e-${{ hashFiles('yarn.lock') }}

      - name: Install SafeDep PMG
        uses: safedep/pmg@be0a93f10fbec6a5c94dd78bc722abf1b7fbfc2d # v0.26.0
        continue-on-error: true
        with:
          version: v0.19.1
      - name: Install dependencies
        shell: bash
        run: yarn workspaces focus @trezor/suite-desktop @trezor/suite-desktop-core @trezor/suite-build @trezor/suite @trezor/suite-data @trezor/transport-bridge @suite-common/message-system @trezor/suite-desktop-ui

      - name: Build libs
        shell: bash
        run: |
          yarn message-system-sign-config
          yarn workspace @trezor/suite-data build:lib
          yarn workspace @trezor/transport-bridge build:lib

      - name: Build Electron app.js for tests
        shell: bash
        env:
          TEST_BUILD: "true"
        run: |
          yarn workspace @trezor/suite-desktop build:app
          yarn workspace @trezor/suite-desktop build:ui

      - name: Compress build artifacts
        shell: bash
        run: tar -czf app-build.tar.gz -C ${{ github.workspace }}/packages/suite-desktop build dist

      - name: Upload build artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: desktop-app-build-e2e
          path: app-build.tar.gz
          retention-days: 7
