name: "[Build] analytics-docs"

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  DEV_SERVER_URL: "https://dev.suite.sldev.cz"

jobs:
  build-analytics-docs:
    if: github.repository == 'trezor/trezor-suite'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6
        with:
          role-to-assume: arn:aws:iam::538326561891:role/gh_actions_trezor_suite_dev_deploy
          aws-region: eu-central-1

      - name: Setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version-file: ".nvmrc"
          cache: yarn

      - name: Install dependencies
        run: |
          echo -e "\nenableScripts: false" >> .yarnrc.yml
          echo -e "\nenableHardenedMode: false" >> .yarnrc.yml
          yarn workspaces focus @trezor/analytics-docs

      - name: Build analytics-docs
        env:
          BASE_PATH: /analytics-docs/
        run: yarn workspace @trezor/analytics-docs build

      - name: Upload analytics-docs to dev.suite.sldev.cz
        env:
          ANALYTICS_DOCS_DEPLOY_PATH: s3://dev.suite.sldev.cz/analytics-docs
        run: |
          aws s3 sync --delete ./packages/analytics-docs/dist ${ANALYTICS_DOCS_DEPLOY_PATH}
