name: "[Build] components storybook"

permissions:
  id-token: write # for fetching the OIDC token
  contents: read # for actions/checkout

# run only once a day
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  DEV_SERVER_URL: "https://dev.suite.sldev.cz"

jobs:
  build-storybook:
    if: github.repository == 'trezor/trezor-suite'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@254c19bd240aabef8777f48595e9d2d7b972184b # v6
        with:
          role-to-assume: arn:aws:iam::538326561891:role/gh_actions_trezor_suite_dev_deploy
          aws-region: eu-central-1
      - name: Setup node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: ".nvmrc"
          cache: yarn
      - name: Install Socket Firewall
        uses: SocketDev/action@ba6de6cc0565af1f42295590380973573297e31f # v1.3.2
        continue-on-error: true
        with:
          mode: firewall-free
          job-summary: errors
          firewall-version: 1.11.0
      - name: Install dependencies
        run: |
          echo -e "\nenableHardenedMode: false" >> .yarnrc.yml
          $(command -v sfw > /dev/null && echo sfw --verbose) yarn workspaces focus @trezor/components
          $(command -v sfw > /dev/null && echo sfw --verbose) yarn workspaces focus @trezor/product-components

      - name: Build storybook
        env:
          ASSET_PREFIX: /components/develop
        run: |
          yarn workspace @trezor/components storybook-build
      - name: Build product-components storybook
        env:
          ASSET_PREFIX: /product-components/develop
        run: |
          yarn workspace @trezor/product-components storybook-build

      - name: Upload suite storybook to dev.suite.sldev.cz
        env:
          COMPONENTS_DEPLOY_PATH: s3://dev.suite.sldev.cz/components/develop
          PRODUCT_COMPONENTS_DEPLOY_PATH: s3://dev.suite.sldev.cz/product-components/develop
        run: |
          aws s3 sync --delete ./packages/components/.build-storybook ${COMPONENTS_DEPLOY_PATH}
          aws s3 sync --delete ./packages/product-components/.build-storybook ${PRODUCT_COMPONENTS_DEPLOY_PATH}
