name: "Reusable Build Suite Desktop for E2E tests"
on:
  workflow_call:

jobs:
  build-desktop:
    runs-on: ubuntu-latest
    env:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_GHACTIONS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: ".nvmrc"
          cache: yarn

      - name: Cache node_modules
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('yarn.lock') }}
          restore-keys: node_modules-

      - name: Install dependencies, build libs
        shell: bash
        run: |
          yarn workspaces focus @trezor/suite-desktop @trezor/suite-desktop-core @trezor/suite-build @trezor/suite @trezor/suite-data @trezor/transport-bridge @suite-common/message-system
          yarn message-system-sign-config
          yarn workspace @trezor/suite-data build:lib
          yarn workspace @trezor/transport-bridge build:lib

      - name: Build Electron app.js for tests
        shell: bash
        env:
          TEST_BUILD: "true"
        run: |
          yarn workspace @trezor/suite-desktop build:app
          yarn workspace @trezor/suite-desktop build:ui

      - name: Compress build artifacts
        shell: bash
        run: tar -czf app-build.tar.gz -C ${{ github.workspace }}/packages/suite-desktop build dist

      - name: Upload build artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: desktop-app-build-e2e
          path: app-build.tar.gz
          retention-days: 7
