name: "[Build] analytics-docs"

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  DEV_SERVER_URL: "https://dev.suite.sldev.cz"

jobs:
  build-analytics-docs:
    if: github.repository == 'trezor/trezor-suite'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@cbe3b392738ccf3f987d68400dafcf4b0624a56c # v6
        with:
          role-to-assume: arn:aws:iam::538326561891:role/gh_actions_trezor_suite_dev_deploy
          aws-region: eu-central-1

      - name: Setup node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6
        with:
          node-version-file: ".nvmrc"
          cache: yarn

      - name: Install SafeDep PMG
        uses: safedep/pmg@64d9f1409273c9a5e36e5d7b2b883be099f1ea60 # v0.27.0
        continue-on-error: true
        with:
          version: v0.19.1
      - name: Install dependencies
        run: |
          echo -e "\nenableHardenedMode: false" >> .yarnrc.yml
          yarn workspaces focus @trezor/analytics-docs

      - name: Build analytics-docs
        env:
          BASE_PATH: /analytics-docs/
        run: yarn workspace @trezor/analytics-docs build

      - name: Upload analytics-docs to dev.suite.sldev.cz
        env:
          ANALYTICS_DOCS_DEPLOY_PATH: s3://dev.suite.sldev.cz/analytics-docs
        run: |
          aws s3 sync --delete ./packages/analytics-docs/dist ${ANALYTICS_DOCS_DEPLOY_PATH}
