name: "[Check] Validation"

on:
  pull_request:
  push:
    branches:
      - release/2*
      - release-native/*

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_GHACTIONS_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  setup-and-cache:
    name: Setup and Cache Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Install node and yarn
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version-file: ".nvmrc"
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      - name: Yarn Cache
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-cache-folder-${{ hashFiles('**/yarn.lock', '.yarnrc.yml') }}
          restore-keys: |
            yarn-cache-folder-
      # We can skip the build for all dependencies, even for those whitelisted, because this process is used only to validate the yarn.lock file and populate the cache.
      - name: Install deps
        run: |
          yarn --immutable --mode=skip-build

  type-check:
    name: Type Checking
    needs: setup-and-cache
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max-old-space-size=6144
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: true
      - name: "Checkout branches for Nx"
        uses: ./.github/actions/nx-checkout
      - name: "Minimal yarn install"
        uses: ./.github/actions/minimal-yarn-install
      - name: Type Check
        run: yarn type-check --output-style=stream

  lint:
    name: Linting and formatting
    needs: setup-and-cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: "Checkout branches for Nx"
        uses: ./.github/actions/nx-checkout
      - name: "Minimal yarn install"
        uses: ./.github/actions/minimal-yarn-install
      - name: ESlint Cache
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        with:
          # Most of the ESLint cache is handled by Nx. However, it can't handle the root cache.
          # That's why we include only the root .eslintcache (and only root eslint config hash as cache key)
          # (context: https://github.com/trezor/trezor-suite/pull/26006#discussion_r2949341349)
          path: |
            './.eslintcache'
            '!**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('./eslint.config.mjs') }} }}
      - name: Lint JS
        run: yarn lint:js --output-style=stream
      - name: Lint Styles
        run: yarn lint:styles --output-style=stream
      - name: Check rust files changes
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4
        id: changes
        with:
          filters: |
            rust: packages/transport-bluetooth/**/*.rs
      - name: Lint Rust
        if: steps.changes.outputs.rust == 'true'
        run: yarn workspace @trezor/transport-bluetooth lint:rs

  test-madge-circular-imports:
    name: Check for new Circular Imports
    needs: setup-and-cache
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: true
      - name: "Checkout branches for Nx"
        uses: ./.github/actions/nx-checkout
      - name: "Minimal yarn install"
        uses: ./.github/actions/minimal-yarn-install
      - name: Check for new Circular Imports
        run: ./scripts/circular-dependencies/check-circular-dependencies.sh

  unit-tests-suite:
    name: Unit Tests
    needs: setup-and-cache
    runs-on: ubuntu-latest
    timeout-minutes: 90 # FIXME!: this too long, see https://github.com/trezor/trezor-suite/issues/26034
    continue-on-error: true
    strategy:
      matrix:
        include:
          - test-task: suite
            test-command: yarn test:unit:suite --output-style=stream
          - test-task: native-module-trading
            test-command: >-
              AFFECTED_MODULE_TRADING_PROJECTS=$(yarn nx show projects --affected --withTarget=test:unit --projects='@suite-native/module-trading' --sep=,) && if [[ -n "$AFFECTED_MODULE_TRADING_PROJECTS" ]]; then yarn nx run-many --target=test:unit --projects="$AFFECTED_MODULE_TRADING_PROJECTS" --parallel=1 --output-style=stream; else echo "No affected module-trading unit-test projects"; fi
          - test-task: native-trading-rest
            test-command: >-
              AFFECTED_TRADING_PROJECTS=$(yarn nx show projects --affected --withTarget=test:unit --projects='@suite-native/trading-*' --sep=,) && if [[ -n "$AFFECTED_TRADING_PROJECTS" ]]; then yarn nx run-many --target=test:unit --projects="$AFFECTED_TRADING_PROJECTS" --parallel=2 --output-style=stream; else echo "No affected trading native unit-test projects"; fi
          - test-task: native-rest
            test-command: >-
              yarn nx affected --target=test:unit --exclude='@trezor/*,@suite/*,@suite-common/*,@suite-native/module-trading,@suite-native/trading-*' --parallel=2 --output-style=stream
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: true
      - name: "Checkout branches for Nx"
        uses: ./.github/actions/nx-checkout
      - name: "Minimal yarn install"
        uses: ./.github/actions/minimal-yarn-install
      - name: Unit Tests
        run: ${{ matrix.test-command }}

  build-libs-for-publishing:
    name: "Build libs for publishing"
    needs: setup-and-cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: true
      - name: "Checkout branches for Nx"
        uses: ./.github/actions/nx-checkout
      - name: "Minimal yarn install"
        uses: ./.github/actions/minimal-yarn-install
      - name: Build Libs
        run: yarn build:libs:verify --output-style=stream

  other-checks:
    name: Other Checks
    needs: setup-and-cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: "Checkout branches for Nx"
        uses: ./.github/actions/nx-checkout
      - name: "Minimal yarn install"
        uses: ./.github/actions/minimal-yarn-install
      - name: Verify Requirements
        run: yarn requirements:verify
      - name: Check Files for Correct Formatting
        run: yarn format:verify
      - name: Verify TS Project References
        run: yarn verify-project-references
      - name: Detect unused dependencies
        run: yarn depcheck
      - name: Yarn Dedupe check
        run: yarn dedupe --check
      - name: Check dependency domain lists
        run: ./scripts/ci/list-missing-dependencies.sh
      - name: Verify Workspace Resolutions
        run: yarn check-workspace-resolutions
      - name: Msg-system Config Validation
        run: yarn workspace @suite-common/message-system validate-config
      - name: Translation Duplicates
        run: yarn workspace @suite/intl translations:list-duplicates

  releases-revision-checks:
    name: Releases revision Checks
    needs: setup-and-cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Check releases.json files changes
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4
        id: changes
        with:
          filters: |
            releases-json:
              - 'packages/connect-data/files/firmware/t1b1/releases.json'
              - 'packages/connect-data/files/firmware/t2t1/releases.json'
      - name: "Checkout branches for Nx"
        if: steps.changes.outputs.releases-json == 'true'
        uses: ./.github/actions/nx-checkout
      - name: "Minimal yarn install"
        if: steps.changes.outputs.releases-json == 'true'
        uses: ./.github/actions/minimal-yarn-install

      - name: Check releases.json revisions
        if: steps.changes.outputs.releases-json == 'true'
        run: yarn workspace @trezor/connect-data validate-releases.json
