name: "[Check] Test Health"

# run only if there are changes in suite or related libs paths - equal settings as PR e2e test job
on:
  pull_request:
    branches:
      - develop
    paths-ignore:
      - "suite-native/**"
      - "packages/connect*/**"
      - "packages/react-native-usb/**"
      # ignore unrelated github workflows config files
      - ".github/workflows/connect*"
      - ".github/workflows/suite-native*"
      - ".github/workflows/build-desktop*"
      - ".github/workflows/release*"
      - ".github/workflows/template*"
      - "**.md"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  check-test-health:
    name: Check test health & manage quarantine
    runs-on: ubuntu-latest
    # Only run in the canonical repository, not forks.
    if: github.repository == 'trezor/trezor-suite'
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: ".nvmrc"
          cache: yarn

      - name: Cache node_modules
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('yarn.lock') }}
          restore-keys: node_modules-

      - name: Install dependencies
        shell: bash
        run: yarn workspaces focus @trezor/e2e-utils

      - name: Check test health and manage quarantine
        env:
          CURRENTS_API_KEY: ${{ secrets.CURRENTS_API_KEY }}
          E2E_TEST_SLACK_QUARANTINE_BOT_WEBHOOK: ${{ secrets.E2E_TEST_SLACK_QUARANTINE_BOT_WEBHOOK }}
          GITHUB_RUN_ID: ${{ github.run_id }}
        run: |
          yarn workspace @trezor/e2e-utils test-health --verbose
