name: "[Chore] purge android E2E build"

permissions:
  id-token: write # for fetching the OIDC token (needed for aws s3 actions)

on:
  workflow_dispatch:

env:
  NODE_ENV: "test"
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  RN_SRC_EXT: "e2e.ts,e2e.tsx"

jobs:
  prepare_android_test_app:
    if: github.repository == 'trezor/trezor-suite'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: "true"

      - name: Install node and yarn
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: ".nvmrc"
          cache: yarn

      - name: Setup node_modules cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: node_modules
          key: node_modules/${{ github.ref }}/${{github.run_id}}

      - name: Install Yarn dependencies
        run: |
          echo -e "\nenableScripts: false" >> .yarnrc.yml
          echo -e "\nenableHardenedMode: false" >> .yarnrc.yml
          yarn install

      - name: Prebuild native expo project
        working-directory: ./suite-native/app
        run: yarn prebuild --platform android --clean

      - name: Sign message system config
        working-directory: ./suite-common/message-system
        run: yarn sign-config

      - name: get Expo app fingerprint
        id: expo-fingerprint
        working-directory: ./suite-native/app
        # `fingerprint` is the binary for @expo/fingerprint
        run: yarn exec fingerprint ./ > expo-fingerprint.json && node -e "console.log('HASH=' + require('./expo-fingerprint.json').hash)" >> $GITHUB_OUTPUT

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6
        with:
          role-to-assume: arn:aws:iam::538326561891:role/gh_actions_trezor_suite_dev_deploy
          aws-region: eu-central-1

      - name: Remove cached build from AWS bucket if it exists
        run: |
          if aws s3 ls s3://dev.suite.sldev.cz/suite-mobile/${{ steps.expo-fingerprint.outputs.HASH }} --summarize;
           then
             aws s3 rm s3://dev.suite.sldev.cz/suite-mobile/${{ steps.expo-fingerprint.outputs.HASH }} --recursive
          fi
