name: "@trezor/connect-webextension"

on:
  pull_request:
    paths:
      - "packages/connect/**"
      - "packages/connect-iframe/**"
      - "packages/connect-web/**"
      - "packages/connect-examples/**"
      - "packages/connect-webextension/**"
  push:
    branches:
      - develop

jobs:
  connect-webextension-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: yarn install
      - run: yarn build:libs
      - name: Build extension
        # this does not make much sense, in fact, we are testing what is already in production and we cant change that
        # unless we have build and deploys in github
        run: node ./packages/connect-examples/update-webextensions.js --npm-src "https://connect.trezor.io/9/trezor-connect.js"
      - name: Run connect web extension test
        run: "./docker/docker-connect-webextension-ci.sh"
