name: release - connect v9 - staging

on:
  pull_request:
    types:
      - edited
    branches:
      - "release/connect-v9"

jobs:
  approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved"
