name: "[Release] connect init"

permissions:
  id-token: write # for fetching the OIDC token
  contents: read # for actions/checkout

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-$${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  connect-v9-deploy:
    # TODO: this is just a test so we should be able to do it from every branch
    # TODO: for the real thing we probably want to have environment setup
    # if: startsWith(github.ref, 'refs/heads/release/connect/')
    uses: ./.github/workflows/template-connect-build-deploy.yml
    with:
      awsRoleToAssume: "arn:aws:iam::538326561891:role/gh_actions_trezor_suite_dev_deploy"
      awsRegion: "eu-central-1"
      serverHostname: "dev.suite.sldev.cz"
      serverPath: "connect-release/9"
