name: Connect v9 release to staging

on:
  pull_request_review:
    types: [submitted]
  pull_request_target:
    branches:
      - "release/connect-v9"

jobs:
  approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved"
