name: mv/experiment
on: push
jobs:
  create-nightly-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        # run: echo "matrix={\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}" >> $GITHUB_OUTPUT
        run: ls -la && echo $(node ./experiment.js) >> $GITHUB_OUTPUT

  test:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.create-nightly-matrix.outputs.matrix)}}
    steps:
      - run: echo ${{ matrix.project }}
      - run: echo ${{ matrix.config }}
