name: "[Release] suite-native develop"

on:
  push:
    branches:
      - develop
    paths:
      - "suite-native/**"
      - "suite-common/**"
      - "!**.md"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    if: github.repository == 'trezor/trezor-suite' || github.repository == 'trezor/trezor-suite-private'
    name: Install and build
    environment: develop-suite-native
    runs-on: ubuntu-latest
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: ".nvmrc"
          cache: yarn
      - name: Setup EAS
        uses: expo/expo-github-action@c7b66a9c327a43a8fa7c0158e7f30d6040d2481e # v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install libs
        run: |
          yarn workspaces focus @suite-native/app
          yarn workspace @suite-native/app exec patch-package # Apply global patches.
      - name: Build on EAS Android
        run: eas build
          --platform android
          --profile develop
          --non-interactive
          --no-wait
          --message ${{ github.sha }}
        working-directory: suite-native/app
      - name: Build on EAS iOS
        run: eas build
          --platform ios
          --profile develop
          --non-interactive
          --auto-submit
          --no-wait
          --message ${{ github.sha }}
        working-directory: suite-native/app
