name: "[Release] suite-native production"

on:
  workflow_dispatch:
    inputs:
      PLATFORM:
        type: choice
        options:
          - iOS & Android
          - iOS
          - Android
          - Android APK
        description: Select platform to run build
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ios:
    if: ${{ (github.event.inputs.PLATFORM == 'iOS' || github.event.inputs.PLATFORM == 'iOS & Android') && (github.repository == 'trezor/trezor-suite' || github.repository == 'trezor/trezor-suite-private') }}
    name: Build and submit iOS
    environment: production-suite-native
    runs-on: ubuntu-latest
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: yarn
      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install libs
        run: yarn workspaces focus @suite-native/app
      - name: Build on EAS iOS
        run: eas build
          --platform ios
          --profile production
          --non-interactive
          --auto-submit
          --message ${{ github.sha }}
        working-directory: suite-native/app
  android:
    if: ${{ github.event.inputs.PLATFORM == 'Android' || github.event.inputs.PLATFORM == 'iOS & Android' && (github.repository == 'trezor/trezor-suite' || github.repository == 'trezor/trezor-suite-private') }}
    name: Build and submit Android
    environment: production-suite-native
    runs-on: ubuntu-latest
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: yarn
      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install libs
        run: yarn workspaces focus @suite-native/app
      - name: Build on EAS Android
        run: eas build
          --platform android
          --profile production
          --non-interactive
          --auto-submit
          --message ${{ github.sha }}
        working-directory: suite-native/app
  androidAPK:
    if: ${{ github.event.inputs.PLATFORM == 'Android APK' && (github.repository == 'trezor/trezor-suite' || github.repository == 'trezor/trezor-suite-private') }}
    name: Build standalone Android APK and release to S3
    environment: production-suite-native
    runs-on: ubuntu-latest
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: yarn
      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::538326561891:role/gh_actions_mobile_prod_deploy
          aws-region: eu-central-1
      - name: Install libs
        run: yarn workspaces focus @suite-native/app

      - name: Get Suite version
        id: get_version
        run: |
          APP_VERSION=$(jq -r '.suiteNativeVersion' suite-native/app/package.json)
          echo "app_version=$APP_VERSION" >> $GITHUB_OUTPUT

      - name: Build on EAS Android
        working-directory: suite-native/app
        id: eas_build
        run: |
          BUILD_ID=$(eas build --platform android --profile productionAPK --non-interactive --message ${{ github.sha }} --wait --json | jq -r '.[0].id')
          BUILD_URL=$(eas build:view "$BUILD_ID" --json | jq -r '.artifacts.buildUrl')
          echo "build_url=$BUILD_URL" >> $GITHUB_OUTPUT

      - name: Upload APK to S3
        run: |
          wget -O "Trezor-Suite-${{ steps.get_version.outputs.app_version }}.apk" "${{ steps.eas_build.outputs.build_url }}"
          aws s3 cp "./Trezor-Suite-${{ steps.get_version.outputs.app_version }}.apk" s3://data.trezor.io/suite/releases/mobile/
