name: "[Bot] Remove disabled workflows"

on: [workflow_dispatch]

jobs:
  crowdin-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Remove disabled workflows
        run: |
          git config --global user.name "trezor-ci"
          git config --global user.email "${{ secrets.TREZOR_BOT_EMAIL }}"
          ./ci/scripts/remove_disabled_workflows.sh
        env:
          GITHUB_TOKEN: ${{ secrets.TREZOR_BOT_TOKEN }}
          BRANCH_NAME: trezor-ci/crowdin-sync-${{ env.NOW }}
