name: "Android E2E Test Job Template"

on:
  workflow_call:
    secrets:
      SENTRY_AUTH_TOKEN:
        required: true

jobs:
  prepare_android_test_app:
    if: github.repository == 'trezor/trezor-suite'
    runs-on: ubuntu-latest
    env:
      NODE_ENV: "test"
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      RN_SRC_EXT: "e2e.ts,e2e.tsx"
    steps:
      - name: delete unpacked folder
        working-directory: ./suite-native/app/android/app/build/outputs/apk/release
        run: rm -rf unpacked
