name: "[Test] Release Suite Regression test publisher"
# Triggered by push to release branch
# Runs Playwright reporter, creating manual regressions release suite in GitHub"

on:
  push:
    branches:
      - release/2*
      - fix-e2e-workflow-duplicate-check
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check-duplicate-run:
    if: github.repository == 'trezor/trezor-suite' && github.event_name == 'push'
    runs-on: ubuntu-latest
    outputs:
      skip_run: ${{ steps.check-duplicate-run.outputs.skip_run }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate GitHub App token
        id: trezor-bot-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.TREZOR_BOT_APP_ID }}
          private-key: ${{ secrets.TREZOR_BOT_PRIVATE_KEY }}

      - name: Check duplicate run
        id: check-duplicate-run
        uses: "./.github/actions/check-duplicate-run"
        with:
          github_token: ${{ steps.trezor-bot-token.outputs.token }}
          commit_sha: ${{ github.sha }}
          repo: ${{ github.repository }}
          workflow_name: ${{ github.workflow }}
          current_run_id: ${{ github.run_id }}

  run-e2e-suite-manual-tests:
    needs: check-duplicate-run
    if: github.repository == 'trezor/trezor-suite' && needs.check-duplicate-run.outputs.skip_run != 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          ref: ${{ github.sha }}
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: yarn

      - name: Extract Release Build
        id: extract_branch
        shell: bash
        run: |
          echo "release_build=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}-${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Install PW Dependencies
        shell: bash
        run: |
          echo "Installing Playwright dependencies"
          yarn workspaces focus @trezor/suite-desktop-core

      - name: Run Playwright Reporter
        shell: bash
        env:
          GITHUB_ACTION: true
          GITHUB_TOKEN: ${{ secrets.TREZOR_BOT_TOKEN }}
          GITHUB_REPORTER_VERBOSE: true
          RELEASE_BUILD: ${{ env.release_build }}
        run: |
          echo "Starting Playwright Reporter for manual regression suite"
          yarn workspace @trezor/suite-desktop-core test:e2e:manual
