name: "[Test] Release Suite Native Sanity test publisher"
# Runs Native reporter, creating manual regressions release suite in GitHub"

on:
  workflow_dispatch:
    inputs:
      testFilter:
        description: "(optional) Run the publisher for specific tests. Can be multiple tests' filenames separated by whitespace. Ex: test1.test.ts test2.test.ts"
        required: false
        default: ""

concurrency:
  group: manual-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run-e2e-manual-test-publisher:
    if: github.repository == 'trezor/trezor-suite'
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub App token
        id: trezor-bot-token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3
        with:
          client-id: ${{ secrets.TREZOR_BOT_APP_ID }}
          private-key: ${{ secrets.TREZOR_BOT_PRIVATE_KEY }}

      - name: Checkout project
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: "true"

      - name: Install node and yarn
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version-file: ".nvmrc"
          cache: yarn

      - name: Load node modules cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: node_modules
          key: node_modules/${{ github.ref }}/${{github.run_id}}

      - name: Install Yarn dependencies
        run: |
          echo -e "\nenableScripts: false" >> .yarnrc.yml
          echo -e "\nenableHardenedMode: false" >> .yarnrc.yml
          yarn install

      - name: Extract Release Build
        id: extract_branch
        shell: bash
        run: |
          echo "release_build=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}-${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Run Jest Reporter
        shell: bash
        env:
          GITHUB_ACTION: true
          GITHUB_TOKEN: ${{ steps.trezor-bot-token.outputs.token }}
          GITHUB_REPORTER_VERBOSE: true
          RELEASE_BUILD: ${{ env.release_build }}
        run: |
          echo "Starting Jest Reporter for manual regression suite"
          yarn workspace @suite-native/app github:report:manual ${{ inputs.testFilter }}
