name: "[Test] PR Suite Web e2e tests"
# Executed as part of PR checks
# Builds/deploys the web app to dev.suite.sldev.cz/suite-web/<branch-name>/web
# Runs e2e test suite for Suite Web, limited to webOnly tests

permissions:
  id-token: write # for fetching the OIDC token
  contents: read # for actions/checkout
  pull-requests: write # for posting comments

# run only if there are changes in suite or related libs paths
on:
  pull_request:
    branches:
      - develop
    paths-ignore:
      - "suite-native/**"
      - "packages/connect*/**"
      # - "packages/suite-desktop*/**"
      - "packages/react-native-usb/**"
      # ignore unrelated github workflows config files
      - ".github/workflows/connect-analytics"
      - ".github/workflows/connect-common"
      - ".github/workflows/connect-examples"
      - ".github/workflows/connect-explorer"
      - ".github/workflows/connect-iframe"
      - ".github/workflows/connect-mobile"
      - ".github/workflows/connect-plugin-*"
      - ".github/workflows/connect-popup"
      - ".github/workflows/connect-theme"
      - ".github/workflows/connect-ui"
      - ".github/workflows/connect-webextension"
      - ".github/workflows/suite-native*"
      - ".github/workflows/build-desktop*"
      - ".github/workflows/release*"
      - ".github/workflows/template*"
      - ".github/actions/release*/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  DEV_SERVER_URL: "https://dev.suite.sldev.cz"
  STAGING_SUITE_SERVER_URL: "https://staging-suite.trezor.io"

jobs:
  build-web:
    if: github.repository == 'trezor/trezor-suite'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and Upload Suite Web
        uses: ./.github/actions/build-web

  load-e2e-matrix:
    if: github.repository == 'trezor/trezor-suite'
    outputs:
      matrix: ${{ steps.load-matrix.outputs.matrix }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Load e2e Matrix
        id: load-matrix
        uses: ./.github/actions/load-e2e-matrix
        with:
          project: "web"

  post-currents-link:
    if: github.repository == 'trezor/trezor-suite' && github.event_name == 'pull_request' && github.event.action == 'opened'
    runs-on: ubuntu-latest
    needs:
      - build-web
    steps:
      - name: Post Currents link
        uses: actions/github-script@v7
        env:
          CURRENTS_PROJECT_ID: "Og0NOQ"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const projectId = process.env.CURRENTS_PROJECT_ID;
            const branch = context.payload.pull_request.head.ref;
            const currentsUrl = `https://app.currents.dev/projects/${projectId}/runs?branch=${branch}&lookback=7`;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: `🔍🌐 Suite Web test results: [View in Currents](${currentsUrl})`
            });

  run-e2e-suite-web-tests:
    if: github.repository == 'trezor/trezor-suite'
    runs-on: ubuntu-latest
    needs:
      - build-web
      - load-e2e-matrix
    continue-on-error: ${{ !matrix.smoke }}
    strategy:
      fail-fast: true
      matrix: ${{ fromJson(needs.load-e2e-matrix.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2

      - name: Check previous runs
        id: check-previous-runs
        if: github.event_name == 'pull_request' && github.run_attempt == 1
        uses: "./.github/actions/check-previous-test-runs"
        with:
          github_token: ${{ secrets.TREZOR_BOT_TOKEN }}
          pr_branch: ${{ github.head_ref }}
          pr_created: ${{ github.event.pull_request.created_at }}
          repo: ${{ github.repository }}
          workflow_name: ${{ github.workflow }}
          job_name: "${{ github.job }} (${{ join(matrix.*, ', ') }})"

      - name: Run Playwright E2E Tests
        if: steps.check-previous-runs.outputs.skip_tests != 'true'
        uses: ./.github/actions/run-e2e-tests
        with:
          project: "web"
          containers: ${{ matrix.CONTAINERS }}
          test-group: ${{ matrix.TEST_GROUP }}
          additional-grep: ${{ !matrix.SMOKE && '(?=.*@webOnly)' }}
          currents-project-id: "Og0NOQ"
          currents-record-key: ${{ secrets.CURRENTS_RECORD_KEY }}
          e2e-passphrase: ${{ secrets.E2E_TEST_PASSPHRASE }}
