name: "[Test] suite-native performance"

on:
  pull_request:
    paths:
      - "suite-native/**"
  workflow_dispatch:

jobs:
  reassure_performance_tests:
    if: github.repository == 'trezor/trezor-suite'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Install node and yarn
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: yarn

      - name: Setup node_modules cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node_modules/${{ github.ref }}/${{github.run_id}}

      - name: Install Yarn dependencies
        run: |
          echo -e "\nenableScripts: false" >> .yarnrc.yml
          echo -e "\nenableHardenedMode: false" >> .yarnrc.yml
          yarn install

      - name: Sign message system config
        working-directory: ./suite-common/message-system
        run: yarn sign-config

      - name: Run performance tests
        working-directory: ./suite-native/app
        run: ./scripts/reassure-tests.sh

      - name: Run Danger.js
        working-directory: ./suite-native/app
        run: yarn danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
