name: "[Test] request-manager"

on:
  schedule:
    # Runs at midnight UTC every day at 01:00 AM CET
    - cron: "0 0 * * *"
  pull_request:
    paths:
      - ".github/workflows/test-request-manager.yml"
      - "packages/request-manager/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test-request-manager:
    runs-on: ubuntu-latest
    if: github.repository == 'trezor/trezor-suite'
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - run: yarn install --immutable
      - run: yarn workspace @trezor/request-manager test:all
