name: "[Test] Release Suite Desktop e2e tests"
# Triggered by push to release branch
# Builds the desktop app
# Runs full e2e test suite for Suite Desktop

on:
  push:
    branches:
      - release/2*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  load-e2e-matrix:
    if: github.repository == 'trezor/trezor-suite'
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.load-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Load e2e Matrix
        id: load-matrix
        uses: ./.github/actions/load-e2e-matrix
        with:
          project: "desktop"

  run-e2e-suite-desktop-tests:
    if: github.repository == 'trezor/trezor-suite'
    runs-on: ubuntu-24.04
    needs:
      - load-e2e-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.load-e2e-matrix.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: yarn

      - name: Build desktop app
        uses: ./.github/actions/build-desktop

      - name: Run Playwright E2E Tests
        uses: ./.github/actions/run-e2e-tests
        with:
          project: "desktop"
          containers: ${{ matrix.CONTAINERS }}
          test-group: ${{ matrix.TEST_GROUP }}
          currents-project-id: "4ytF0E"
          currents-record-key: ${{ secrets.CURRENTS_RECORD_KEY }}
          e2e-passphrase: ${{ secrets.E2E_TEST_PASSPHRASE }}
