name: "[Test] suite-desktop e2e"
# this workflow builds a desktop version of Suite and runs basic test suite for it

on:
  pull_request:
    branches:
      - develop
    paths-ignore:
      - "suite-native/**"
      - "packages/connect*/**"
      - "packages/react-native-usb/**"
      # ignore unrelated github workflows config files
      - ".github/workflows/connect*"
      - ".github/workflows/suite-native*"
      - ".github/workflows/build-desktop*"
      - ".github/workflows/release*"
      - ".github/workflows/template*"
  push:
    branches:
      - release/2*
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run-e2e-suite-desktop-tests:
    if: github.repository == 'trezor/trezor-suite'
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - TEST_GROUP: "@group=suite"
            CONTAINERS: "trezor-user-env-unix"
          # - TEST_GROUP: "@group=device-management"
          #   CONTAINERS: "trezor-user-env-unix"
          # - TEST_GROUP: "@group=settings"
          #   CONTAINERS: "trezor-user-env-unix bitcoin-regtest"
          # # - TEST_GROUP: "@group=metadata"
          # #   CONTAINERS: "trezor-user-env-unix"
          # - TEST_GROUP: "@group=passphrase"
          #   CONTAINERS: "trezor-user-env-unix"
          # - TEST_GROUP: "@group=other"
          #   CONTAINERS: "trezor-user-env-unix"
          # - TEST_GROUP: "@group=wallet"
          #   CONTAINERS: "trezor-user-env-unix bitcoin-regtest"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Check previous runs
        id: check-previous-runs
        if: github.event_name == 'pull_request' && github.run_attempt == 1
        uses: "./.github/actions/check-previous-test-runs"
        with:
          github_token: ${{ secrets.TREZOR_BOT_TOKEN }}
          pr_branch: ${{ github.head_ref }}
          pr_created: ${{ github.event.pull_request.created_at }}
          repo: ${{ github.repository }}
          workflow_name: ${{ github.workflow }}
          job_name: "${{ github.job }} (${{ join(matrix.*, ', ') }})"

      - name: Setup node
        if: steps.check-previous-runs.outputs.skip_tests != 'true'
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: yarn

      - name: Build desktop app
        if: steps.check-previous-runs.outputs.skip_tests != 'true'
        uses: ./.github/actions/build-desktop

      - name: Run Playwright E2E Tests
        if: steps.check-previous-runs.outputs.skip_tests != 'true'
        uses: ./.github/actions/run-e2e-web-tests
        with:
          project: 'desktop'
          containers: ${{ matrix.CONTAINERS }}
          test-group: ${{ matrix.TEST_GROUP }}
          currents-project-id: '4ytF0E'
          currents-record-key: ${{ secrets.CURRENTS_RECORD_KEY }}
          e2e-passphrase: ${{ secrets.E2E_TEST_PASSPHRASE }} 
