name: "[Test] suite-native Android E2E Nightly"

permissions:
  id-token: write # for fetching the OIDC token (needed for aws s3 actions)
  contents: read # read attached artifacts from tests
  actions: write # upload/download artifacts

on:
  schedule:
    - cron: "0 0 * * 1-5"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare_android_test_app:
    if: github.repository == 'trezor/trezor-suite'
    uses: ./.github/workflows/template-suite-native-prepare-test-app-android.yml
    secrets:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

  run_android_e2e_tests:
    if: github.repository == 'trezor/trezor-suite'
    uses: ./.github/workflows/template-suite-native-e2e-android.yml
    needs: [prepare_android_test_app]
    with:
      runner_config: e2e/trezorDetoxRunner/config/runner-android-release-nightly.config.js
    secrets:
      TREZOR_BOT_APP_ID: ${{ secrets.TREZOR_BOT_APP_ID }}
      TREZOR_BOT_PRIVATE_KEY: ${{ secrets.TREZOR_BOT_PRIVATE_KEY }}
      CURRENTS_RECORD_KEY: ${{ secrets.CURRENTS_RECORD_KEY }}
      CURRENTS_API_KEY: ${{ secrets.CURRENTS_API_KEY }}
      E2E_TEST_PASSPHRASE: ${{ secrets.E2E_TEST_PASSPHRASE }}

  notify_scheduled_failure_to_slack:
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    needs: run_android_e2e_tests
    steps:
      - name: Notify scheduled job failure to Slack
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Nightly Android E2E tests failed :pepe_flame: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} "}' "${{ secrets.SLACK_MOBILE_E2E_WEBHOOK }}"
