name: "[Test] URLs health check"

on:
  schedule:
    # Runs at midnight UTC every day at 01:00 AM CET, same as other nightlies in test-misc.yml
    - cron: "0 0 * * *"
  pull_request:
    paths:
      - ".github/workflows/test-urls.yml"
      - "packages/urls/**"
  workflow_dispatch:

jobs:
  urls-health:
    runs-on: ubuntu-latest
    if: github.repository == 'trezor/trezor-suite'
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6

      - name: Setup node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6
        with:
          node-version-file: ".nvmrc"

      - name: Install SafeDep PMG
        uses: safedep/pmg@64d9f1409273c9a5e36e5d7b2b883be099f1ea60 # v0.27.0
        continue-on-error: true
        with:
          version: v0.19.1
      - run: yarn workspaces focus trezor-suite @trezor/urls
      - run: yarn workspace @trezor/urls test:e2e
