name: "[Test] URLs health check"

on:
  schedule:
    # Runs at midnight UTC every day at 01:00 AM CET, same as other nightlies in test-misc.yml
    - cron: "0 0 * * *"
  pull_request:
    paths:
      - ".github/workflows/test-urls.yml"
      - "packages/urls/**"
  workflow_dispatch:

jobs:
  urls-health:
    runs-on: ubuntu-latest
    if: github.repository == 'trezor/trezor-suite'
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version-file: ".nvmrc"

      - run: yarn install --immutable
      - run: yarn workspace @trezor/urls test:e2e
