name: "[Test] blockchain-link e2e"

on:
  schedule:
    # Runs at midnight UTC every day at 01:00 AM CET
    - cron: "0 0 * * *"
  pull_request:
    paths:
      - "packages/blockchain-link/**"
      - "packages/blockchain-link-utils/**"
      - "packages/blockchain-link-types/**"
      - "packages/e2e-utils/src/fixtures/blockbook.ts"
      - "packages/e2e-utils/src/mocks/backendServer.ts"
      # dependencies of packages/blockchain-link
      - "packages/utxo-lib/**"
      - "docker/docker-blockchain-link-test.sh"
      - ".github/workflows/blockchain-link-test.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    if: github.repository == 'trezor/trezor-suite'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6
        with:
          submodules: true
      - name: Setup node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: ".nvmrc"

      - name: Install Socket Firewall
        uses: SocketDev/action@ba6de6cc0565af1f42295590380973573297e31f # v1.3.2
        continue-on-error: true
        with:
          mode: firewall-free
          job-summary: errors
          firewall-version: 1.11.0
      - name: Install dependencies
        run: $(command -v sfw > /dev/null && echo sfw --verbose) yarn --immutable

      - name: Build dependencies
        run: yarn build:libs

      - name: Build @trezor/blockchain-link workers
        run: |
          yarn workspace @trezor/blockchain-link build:workers

      - name: Run E2E tests
        run: ./docker/docker-blockchain-link-test.sh
