name: "[Test] connect-popup e2e"

permissions:
  id-token: write # for fetching the OIDC token
  contents: read # for actions/checkout

on:
  workflow_run:
    workflows: ["build-connect.yml"]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  methods:
    uses: ./.github/workflows/template-connect-popup-test-params.yml
    with:
      testName: methods.test
      serverHostname: dev.suite.sldev.cz
      runWebextension: ${{ github.event_name == 'schedule' }}
      runCoreInPopup: true
      buildOverview: true

  popup-close:
    uses: ./.github/workflows/template-connect-popup-test-params.yml
    with:
      testName: popup-close.test
      serverHostname: dev.suite.sldev.cz
      runWebextension: true
      runCoreInPopup: true

  passphrase:
    uses: ./.github/workflows/template-connect-popup-test-params.yml
    with:
      testName: passphrase.test
      serverHostname: dev.suite.sldev.cz
      runWebextension: true
      runCoreInPopup: true

  popup-pages:
    uses: ./.github/workflows/template-connect-popup-test-params.yml
    with:
      testName: popup-pages.test
      serverHostname: dev.suite.sldev.cz

  browser-support:
    uses: ./.github/workflows/template-connect-popup-test-params.yml
    with:
      testName: browser-support.test
      serverHostname: dev.suite.sldev.cz

  permissions:
    uses: ./.github/workflows/template-connect-popup-test-params.yml
    with:
      testName: permissions.test
      serverHostname: dev.suite.sldev.cz

  transport:
    uses: ./.github/workflows/template-connect-popup-test-params.yml
    with:
      testName: transport.test
      serverHostname: dev.suite.sldev.cz

  # Disabling it for now since after adding testnet 4 as default it is failing and
  # it runs not in our code so we cannot update it.
  # unchained:
  #   needs: [build-deploy]
  #   uses: ./.github/workflows/template-connect-popup-test-params.yml
  #   with:
  #     testName: unchained.test
  #     serverHostname: dev.suite.sldev.cz
  #     runWeb: ${{ github.event_name == 'schedule' }}

  webextension-examples:
    uses: ./.github/workflows/template-connect-popup-test-params.yml
    with:
      testName: webextension-example.test
      serverHostname: dev.suite.sldev.cz
      runWebextension: true
      runWeb: false
