name: "[Test] Nightly Suite Desktop e2e tests"
# Nightly scheduled check on develop branch
# Builds the desktop app
# Runs full e2e test suite for Suite Desktop with T3T1 and T3W1 emulators
# Runs full e2e test suite for Suite Desktop against FW built nightly from main branch with T3T1 and T3W1 emulators

permissions:
  id-token: write # for fetching the OIDC token
  contents: read # for actions/checkout

on:
  schedule:
    - cron: "0 0 * * 1-5"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-app:
    if: github.repository == 'trezor/trezor-suite'
    uses: ./.github/workflows/build-suite-desktop-e2e.yml

  run-e2e-suite-desktop-tests:
    if: github.repository == 'trezor/trezor-suite'
    needs:
      - build-app
    strategy:
      fail-fast: false
      matrix:
        TEST_GROUP: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    uses: ./.github/workflows/template-suite-run-e2e.yml
    with:
      target: "desktop"
      pw-config: "./playwright-config/playwright-desktop-nightly.config.ts"
      workspace-dependencies: "@trezor/suite-desktop"
      test-group: ${{ matrix.TEST_GROUP }}
      fail-fast: "false"
      currents-project-id: "4ytF0E"
      currents-ci-build-id: "nightly-run-${{ github.run_id }}-${{ github.run_attempt }}"
      download-artifact-name: "desktop-app-build-e2e"
    secrets:
      currents-record-key: ${{ secrets.CURRENTS_RECORD_KEY }}
      e2e-passphrase: ${{ secrets.E2E_TEST_PASSPHRASE }}
      e2e-passphrase-live: ${{ secrets.E2E_TEST_PASSPHRASE_LIVE }}
