name: "[Test] transport e2e"

permissions:
  id-token: write # for fetching the OIDC token
  contents: read # for actions/checkout

on:
  schedule:
    # Runs at midnight UTC every day at 01:00 AM CET
    - cron: "0 0 * * *"
  push:
    branches: [release/connect/**]
  pull_request:
    paths:
      - "packages/transport/**"
      - "packages/transport-bridge/**"
      - "packages/transport-common/**"
      - "packages/transport-test/**"
      - "packages/protobuf/**"
      - "packages/protocol/**"
      - "packages/trezor-user-env-link/**"
      - "docker/docker-compose.transport-test-ci.yml"
      - ".github/workflows/test-transport.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  transport-e2e-test:
    if: github.repository == 'trezor/trezor-suite'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6

      - name: Setup node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6
        with:
          node-version-file: ".nvmrc"

      - name: Install SafeDep PMG
        uses: safedep/pmg@be0a93f10fbec6a5c94dd78bc722abf1b7fbfc2d # v0.26.0
        continue-on-error: true
        with:
          version: v0.19.1
      - name: Install dependencies
        run: |
          yarn workspaces focus @trezor/transport-test

      - name: Setup containers
        run: |
          docker compose -f ./docker/docker-compose.transport-test-ci.yml pull
          docker compose -f ./docker/docker-compose.transport-test-ci.yml up -d

      - name: Run E2E tests (bridge:emu)
        run: yarn workspace @trezor/transport-test test:e2e:bridge:emu

  extract-branch:
    if: github.repository == 'trezor/trezor-suite'
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.extract_branch.outputs.branch }}
    steps:
      - name: Extract branch name
        id: extract_branch
        run: |
          BRANCH_NAME="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT

  build-deploy:
    needs: [extract-branch]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6
        with:
          ref: ${{ needs.extract-branch.outputs.branch }}

      - name: Setup node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6
        with:
          node-version-file: ".nvmrc"

      - name: Install SafeDep PMG
        uses: safedep/pmg@be0a93f10fbec6a5c94dd78bc722abf1b7fbfc2d # v0.26.0
        continue-on-error: true
        with:
          version: v0.19.1
      - name: Install dependencies
        shell: bash
        run: |
          yarn workspaces focus @trezor/transport -A

      - name: Build transport tester
        run: |
          yarn workspace @trezor/transport-test build:e2e:api:browser

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6
        with:
          role-to-assume: arn:aws:iam::538326561891:role/gh_actions_trezor_suite_dev_deploy
          aws-region: eu-central-1

      - name: Upload transport tester
        shell: bash
        env:
          DEPLOY_PATH: s3://dev.suite.sldev.cz/transport-test/${{ needs.extract-branch.outputs.branch }}
        run: |
          echo "DEPLOY_PATH is set to ${DEPLOY_PATH}"
          mkdir -p tmp_build_directory
          cp -R ./packages/transport-test/e2e/dist/* tmp_build_directory/
          aws s3 sync --delete tmp_build_directory/ "${DEPLOY_PATH}"
