name: "[Test] connect misc"

on:
  schedule:
    # Runs at midnight UTC every day at 01:00 AM CET
    - cron: "0 0 * * *"
  push:
    branches: [release/connect/**]
  pull_request:
    paths:
      - "packages/connect-common/**"
      - "packages/connect-data/**"
      - "packages/connect-mobile/**"
      - "packages/connect-web/**"
      - "packages/connect-webextension/**"
      - "packages/connect/**"
      - "scripts/ci/helpers.ts"
      - "scripts/ci/pack-packages.ts"
      - "scripts/publish/**"
      - "packages/connect/e2e/test-connect-local.sh"
      - ".github/workflows/test-connect-misc.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  install-connect:
    runs-on: ubuntu-latest
    if: github.repository == 'trezor/trezor-suite'
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: true

      - name: Setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version-file: ".nvmrc"

      - name: Test npm install (beta)
        run: ./packages/connect/e2e/test-npm-install.sh beta

      - name: Test npm install (latest)
        run: ./packages/connect/e2e/test-npm-install.sh latest
        if: always()

      - name: Test yarn install (beta)
        run: ./packages/connect/e2e/test-yarn-install.sh beta
        if: always()

      - name: Test yarn install (latest)
        run: ./packages/connect/e2e/test-yarn-install.sh latest
        if: always()

  install-connect-local:
    runs-on: ubuntu-latest
    if: github.repository == 'trezor/trezor-suite'
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: true

      - name: Setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: yarn install

      - name: Pack packages
        run: yarn tsx ./scripts/ci/pack-packages.ts

      - name: Check exports
        # For now only testing @trezor/connect-web. `attw` is the binary for @arethetypeswrong/cli
        run: yarn exec attw --pack ./tmp/packed-packages/trezor-connect-web.tgz

      - name: Test local install
        run: ./packages/connect/e2e/test-connect-local.sh

  test-protobuf:
    runs-on: ubuntu-latest
    if: github.repository == 'trezor/trezor-suite'
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version-file: ".nvmrc"

      - run: yarn install --immutable
      - run: yarn workspace @trezor/protobuf update:protobuf
