name: "[Test] Nightly Suite Desktop e2e tests"
# Nightly scheduled check on develop branch
# Builds the desktop app
# Runs full e2e test suite for Suite Desktop

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run-e2e-suite-desktop-tests:
    if: github.repository == 'trezor/trezor-suite'
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - TEST_GROUP: "@group=suite"
            CONTAINERS: "trezor-user-env-unix"
          - TEST_GROUP: "@group=device-management"
            CONTAINERS: "trezor-user-env-unix"
          - TEST_GROUP: "@group=settings"
            CONTAINERS: "trezor-user-env-unix bitcoin-regtest"
          # - TEST_GROUP: "@group=metadata"
          #   CONTAINERS: "trezor-user-env-unix"
          - TEST_GROUP: "@group=passphrase"
            CONTAINERS: "trezor-user-env-unix"
          - TEST_GROUP: "@group=other"
            CONTAINERS: "trezor-user-env-unix"
          - TEST_GROUP: "@group=wallet"
            CONTAINERS: "trezor-user-env-unix bitcoin-regtest"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: yarn

      - name: Build desktop app
        uses: ./.github/actions/build-desktop

      - name: Pull Docker Images
        shell: bash
        env:
          COMPOSE_FILE: ./docker/docker-compose.suite-ci-e2e.yml
        run: docker compose pull ${{ inputs.containers }}

      - name: Run Playwright E2E Tests
        uses: ./.github/actions/run-e2e-tests
        with:
          project: 'desktop'
          containers: ${{ matrix.CONTAINERS }}
          test-group: ${{ matrix.TEST_GROUP }}
          currents-project-id: '4ytF0E'
          currents-record-key: ${{ secrets.CURRENTS_RECORD_KEY }}
          e2e-passphrase: ${{ secrets.E2E_TEST_PASSPHRASE }} 
