name: "[Test] trezor-user-env-link e2e"

on:
  schedule:
    # Runs at midnight UTC every day at 01:00 AM CET
    - cron: "0 0 * * *"
  pull_request:
    branches:
      - develop
    paths:
      - ".github/workflows/test-trezor-user-env-link-e2e.yml"
      - "packages/trezor-user-env/**"
      - "packages/trezor-user-env-link/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  e2e-test-trezor-user-env-link:
    if: github.repository == 'trezor/trezor-suite'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: ${{github.event.after}}
          fetch-depth: 2
      - name: Setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version-file: ".nvmrc"
          cache: yarn
      - name: Install Socket Firewall
        uses: SocketDev/action@2d3f25590c6ed6ba11a9a14c064d962a3a04698f # v1.3.1
        continue-on-error: true
        with:
          mode: firewall-free
          job-summary: errors
          firewall-version: 1.11.0
      - name: Install dependencies
        run: |
          echo -e "\nenableHardenedMode: false" >> .yarnrc.yml
          $(command -v sfw > /dev/null && echo sfw --verbose) yarn workspaces focus @trezor/trezor-user-env-link

      - name: Run e2e tests
        run: |
          docker run -d --network=host ghcr.io/trezor/trezor-user-env:97b797fb349737b93a1d2dbe6bda6673dcc9cafb
          yarn workspace @trezor/trezor-user-env-link test:e2e
