name: "[Test] Release Suite Sanity test publisher"
# Runs Playwright reporter, creating manual regressions release suite in GitHub"

on:
  workflow_dispatch:
    inputs:
      testFilter:
        description: "(optional) Run the publisher for specific tests. Can be multiple tests' filenames separated by whitespace. Ex: test1.test.ts test2.test.ts"
        required: false
        default: ""
  workflow_call:

concurrency:
  group: manual-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run-e2e-suite-manual-tests:
    if: github.repository == 'trezor/trezor-suite'
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub App token
        id: trezor-bot-token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3
        with:
          app-id: ${{ secrets.TREZOR_BOT_APP_ID }}
          private-key: ${{ secrets.TREZOR_BOT_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: true
          ref: ${{ github.sha }}
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version-file: ".nvmrc"
          cache: yarn

      - name: Extract Release Build
        id: extract_branch
        shell: bash
        run: |
          echo "release_build=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}-${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Install PW Dependencies
        shell: bash
        run: |
          echo "Installing Playwright dependencies"
          yarn workspaces focus @trezor/suite-e2e
          # Playwright runtime may indirectly import the built config, and that would crash if message-system is not built
          yarn message-system-sign-config

      - name: Run Playwright Reporter
        shell: bash
        env:
          GITHUB_ACTION: true
          GITHUB_TOKEN: ${{ steps.trezor-bot-token.outputs.token }}
          GITHUB_REPORTER_VERBOSE: true
          RELEASE_BUILD: ${{ env.release_build }}
        run: |
          echo "Starting Playwright Reporter for manual regression suite"
          yarn workspace @trezor/suite-e2e github:report:manual ${{ inputs.testFilter }}
