name: "[Test] Nightly Suite Web e2e tests"
# Nightly scheduled check on develop branch
# Builds/deploys the web app to dev.suite.sldev.cz/suite-web/develop/web
# Runs full e2e test suite for Suite Web with T3T1 and T3W1 emulators
# Runs full e2e test suite for Suite Web against FW built nightly from main branch with T3T1 and T3W1 emulators
# Runs database migration tests

permissions:
  id-token: write # for fetching the OIDC token
  contents: read # for actions/checkout

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  DEV_SERVER_URL: "https://dev.suite.sldev.cz"
  STAGING_SUITE_SERVER_URL: "https://staging-suite.trezor.io"

jobs:
  build-web:
    if: github.repository == 'trezor/trezor-suite'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and Upload Suite Web
        uses: ./.github/actions/build-web
        with:
          instrument-code: "true"

  run-e2e-suite-web-tests:
    if: github.repository == 'trezor/trezor-suite'
    runs-on: ubuntu-latest
    needs:
      - build-web
    strategy:
      fail-fast: false
      matrix:
        TEST_GROUP: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          ref: ${{ github.sha }}
          fetch-depth: 2

      - name: Run Playwright E2E Tests
        uses: ./.github/actions/run-e2e-tests
        with:
          target: "web"
          pw-config: "./playwright-config/playwright-web.config.ts"
          containers: "trezor-user-env-unix bitcoin-regtest electrum-regtest"
          test-group: ${{ matrix.TEST_GROUP }}
          fail-fast: false
          currents-project-id: "Og0NOQ"
          currents-record-key: ${{ secrets.CURRENTS_RECORD_KEY }}
          currents-ci-build-id: "nightly-run-${{ github.run_id }}-${{ github.run_attempt }}"
          currents-tags: "nightly"
          e2e-passphrase: ${{ secrets.E2E_TEST_PASSPHRASE }}
          enable-coverage: "true"

  run-e2e-suite-web-tests-fw-canary:
    if: ${{ github.repository == 'trezor/trezor-suite' && always() && !cancelled() }} # make sure this job runs even if others fail
    runs-on: ubuntu-latest
    needs:
      - build-web
      - run-e2e-suite-web-tests # This ensures that the main web tests complete before running the firmware canary tests
    strategy:
      fail-fast: false
      matrix:
        TEST_GROUP: [1, 2, 3, 4, 5, 6, 7]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          ref: ${{ github.sha }}
          fetch-depth: 2

      - name: Run Playwright E2E Tests
        uses: ./.github/actions/run-e2e-tests
        env:
          CANARY_FIRMWARE: "true"
        with:
          target: "web"
          pw-config: "./playwright-config/playwright-web.config.ts"
          containers: "trezor-user-env-unix bitcoin-regtest electrum-regtest"
          test-group: ${{ matrix.TEST_GROUP }}
          fail-fast: false
          additional-grep-invert: "@specificFirmware"
          currents-project-id: "Og0NOQ"
          currents-record-key: ${{ secrets.CURRENTS_RECORD_KEY }}
          currents-ci-build-id: "nightly-run-fw-canary-${{ github.run_id }}-${{ github.run_attempt }}"
          currents-tags: "fw-canary,nightly"
          e2e-passphrase: ${{ secrets.E2E_TEST_PASSPHRASE }}
