name: "[Test] Release Suite Desktop e2e tests"
# Triggered by push to release branch
# Builds the desktop app
# Runs full e2e test suite for Suite Desktop

permissions:
  id-token: write # for fetching the OIDC token
  contents: read # for actions/checkout

on:
  push:
    branches:
      - release/2*
  workflow_dispatch:
    inputs:
      publish_results_to_github:
        description: "Publish test report to GitHub Project"
        required: false
        default: false
        type: boolean
  workflow_call:
    inputs:
      publish_results_to_github:
        description: "Publish test report to GitHub Project"
        required: false
        default: false
        type: boolean

concurrency:
  group: desktop-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-app:
    if: github.repository == 'trezor/trezor-suite'
    uses: ./.github/workflows/build-suite-desktop-e2e.yml

  run-e2e-suite-desktop-tests:
    if: github.repository == 'trezor/trezor-suite'
    needs:
      - build-app
    strategy:
      fail-fast: false
      matrix:
        TEST_GROUP: [1, 2, 3, 4, 5, 6, 7]
    uses: ./.github/workflows/template-suite-run-e2e.yml
    with:
      target: "desktop"
      pw-config: "./playwright-config/playwright-desktop.config.ts"
      workspace-dependencies: "@trezor/suite-desktop"
      test-group: ${{ matrix.TEST_GROUP }}
      fail-fast: "false"
      currents-project-id: "4ytF0E"
      download-artifact-name: "desktop-app-build-e2e"
      release-build: ${{ github.head_ref || github.ref_name }}-${{ github.sha }} 
      run-reporter: ${{ inputs.publish_results_to_github == true }}
    secrets:
      currents-record-key: ${{ secrets.CURRENTS_RECORD_KEY }}
      e2e-passphrase: ${{ secrets.E2E_TEST_PASSPHRASE }}
      e2e-passphrase-live: ${{ secrets.E2E_TEST_PASSPHRASE_LIVE }}
      trezor-bot-app-id: ${{ secrets.TREZOR_BOT_APP_ID }}
      trezor-bot-private-key: ${{ secrets.TREZOR_BOT_PRIVATE_KEY }}
