name: "[Test] request-manager"

on:
  schedule:
    # Runs at midnight UTC every day at 01:00 AM CET
    - cron: "0 0 * * *"
  pull_request:
    paths:
      - ".github/workflows/test-request-manager.yml"
      - "packages/request-manager/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test-request-manager:
    runs-on: ubuntu-latest
    if: github.repository == 'trezor/trezor-suite'
    timeout-minutes: 60
    env:
      TEST_SCRIPT: ${{ github.event_name == 'workflow_dispatch' && 'test:e2e' || 'test:all' }}
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6
        with:
          lfs: true

      - name: Setup node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: ".nvmrc"

      - name: Install Socket Firewall
        uses: SocketDev/action@ba6de6cc0565af1f42295590380973573297e31f # v1.3.2
        continue-on-error: true
        with:
          mode: firewall-free
          job-summary: errors
          firewall-version: 1.11.0
      - run: $(command -v sfw > /dev/null && echo sfw --verbose) yarn install --immutable
      - run: yarn workspace @trezor/request-manager ${{ env.TEST_SCRIPT }}
