name: "[Test] Release Suite Web e2e tests"
# Triggered by push to release branch
# Builds/deploys the web app to dev.suite.sldev.cz/suite-web/<branch-name>/web
# Runs e2e full test suite for Suite Web

permissions:
  id-token: write # for fetching the OIDC token
  contents: read # for actions/checkout

on:
  push:
    branches:
      - release/2*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  DEV_SERVER_URL: "https://dev.suite.sldev.cz"
  STAGING_SUITE_SERVER_URL: "https://staging-suite.trezor.io"

jobs:
  build-web:
    if: github.repository == 'trezor/trezor-suite'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and Upload Suite Web
        uses: ./.github/actions/build-web

  load-e2e-matrix:
    if: github.repository == 'trezor/trezor-suite'
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.load-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Load e2e Matrix
        id: load-matrix
        uses: ./.github/actions/load-e2e-matrix
        with:
          project: "web"

  run-e2e-suite-web-tests:
    if: github.repository == 'trezor/trezor-suite'
    runs-on: ubuntu-latest
    needs:
      - build-web
      - load-e2e-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.load-e2e-matrix.outputs.matrix) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
          fetch-depth: 2

      - name: Run Playwright E2E Tests
        uses: ./.github/actions/run-e2e-tests
        with:
          project: "web"
          containers: ${{ matrix.CONTAINERS }}
          test-group: ${{ matrix.TEST_GROUP }}
          currents-project-id: "Og0NOQ"
          currents-record-key: ${{ secrets.CURRENTS_RECORD_KEY }}
          e2e-passphrase: ${{ secrets.E2E_TEST_PASSPHRASE }}
