name: "[Test] Release Suite Web e2e tests"
# Triggered by push to release branch
# Builds/deploys the web app to dev.suite.sldev.cz/suite-web/<branch-name>/web
# Runs e2e full test suite for Suite Web

permissions:
  id-token: write # for fetching the OIDC token
  contents: read # for actions/checkout

on:
  push:
    branches:
      - release/2*
  workflow_dispatch:
  workflow_call:

concurrency:
  group: web-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  DEV_SERVER_URL: "https://dev.suite.sldev.cz"
  STAGING_SUITE_SERVER_URL: "https://staging-suite.trezor.io"

jobs:
  build-web:
    if: github.repository == 'trezor/trezor-suite'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and Upload Suite Web
        uses: ./.github/actions/build-web

  run-e2e-suite-web-tests:
    if: github.repository == 'trezor/trezor-suite'
    runs-on: ubuntu-latest
    needs:
      - build-web
    strategy:
      fail-fast: false
      matrix:
        TEST_GROUP: [1, 2, 3, 4, 5, 6, 7]

    steps:
      - name: Generate GitHub App token
        id: trezor-bot-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.TREZOR_BOT_APP_ID }}
          private-key: ${{ secrets.TREZOR_BOT_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          ref: ${{ github.sha }}
          fetch-depth: 2

      - name: Extract Release Build
        id: extract_branch
        shell: bash
        run: |
          echo "release_build=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}-${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Run Playwright E2E Tests
        uses: ./.github/actions/run-e2e-tests
        with:
          project: "web"
          containers: "trezor-user-env-unix bitcoin-regtest"
          test-group: ${{ matrix.TEST_GROUP }}
          fail-fast: false
          currents-project-id: "Og0NOQ"
          currents-record-key: ${{ secrets.CURRENTS_RECORD_KEY }}
          e2e-passphrase: ${{ secrets.E2E_TEST_PASSPHRASE }}
          github-token: ${{ steps.trezor-bot-token.outputs.token }}
          release-build: ${{ env.release_build }}
          run-reporter: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'workflow_call' }}
