import { FiatCurrencyCode } from 'invity-api';

type MapType<T extends FiatCurrencyCode> = { [K in T]: { code: K; label: string } };

export const supportedFiatCurrenciesMap: MapType<FiatCurrencyCode> = {
    aed: { code: 'aed', label: 'United Arab Emirates Dirham' },
    // amd: { code: 'amd', label: 'Armenian Dram' },
    ars: { code: 'ars', label: 'Argentine Peso' },
    aud: { code: 'aud', label: 'Australian Dollar' },
    // azn: { code: 'azn', label: 'Azerbaijan Manat' },
    bdt: { code: 'bdt', label: 'Bangladeshi Taka' },
    // bgn: { code: 'bgn', label: 'Bulgarian Lev' },
    // bhd: { code: 'bhd', label: 'Bahraini Dinar' },
    brl: { code: 'brl', label: 'Brazilian Real' },
    cad: { code: 'cad', label: 'Canadian Dollar' },
    chf: { code: 'chf', label: 'Swiss Franc' },
    clp: { code: 'clp', label: 'Chilean Peso' },
    cny: { code: 'cny', label: 'Chinese Yuan' },
    // cop: { code: 'cop', label: 'Colombian Peso' },
    // crc: { code: 'crc', label: 'Costa Rican Colón' },
    czk: { code: 'czk', label: 'Czech Koruna' },
    dkk: { code: 'dkk', label: 'Danish Krone' },
    // dop: { code: 'dop', label: 'Dominican Peso' },
    // dzd: { code: 'dzd', label: 'Algerian Dinar' },
    // egp: { code: 'egp', label: 'Egyptian Pound' },
    eur: { code: 'eur', label: 'Euro' },
    gbp: { code: 'gbp', label: 'British Pound Sterling' },
    // gel: { code: 'gel', label: 'Georgian Lari' },
    // ghs: { code: 'ghs', label: 'Ghanaian Cedi' },
    hkd: { code: 'hkd', label: 'Hong Kong Dollar' },
    huf: { code: 'huf', label: 'Hungarian Forint' },
    idr: { code: 'idr', label: 'Indonesian Rupiah' },
    ils: { code: 'ils', label: 'Israeli Shekel' },
    inr: { code: 'inr', label: 'Indian Rupee' },
    // isk: { code: 'isk', label: 'Icelandic Króna' },
    // jod: { code: 'jod', label: 'Jordanian Dinar' },
    jpy: { code: 'jpy', label: 'Japanese Yen' },
    // kes: { code: 'kes', label: 'Kenyan Shilling' },
    krw: { code: 'krw', label: 'South Korean Won' },
    kwd: { code: 'kwd', label: 'Kuwaiti Dinar' },
    // kzt: { code: 'kzt', label: 'Kazakhstani Tenge' },
    lkr: { code: 'lkr', label: 'Sri Lankan Rupee' },
    // mad: { code: 'mad', label: 'Moroccan Dirham' },
    mxn: { code: 'mxn', label: 'Mexican Peso' },
    myr: { code: 'myr', label: 'Malaysian Ringgit' },
    // ngn: { code: 'ngn', label: 'Nigerian Naira' },
    nok: { code: 'nok', label: 'Norwegian Krone' },
    nzd: { code: 'nzd', label: 'New Zealand Dollar' },
    // omr: { code: 'omr', label: 'Omani Rial' },
    // pen: { code: 'pen', label: 'Peruvian Sol' },
    php: { code: 'php', label: 'Philippine Peso' },
    pln: { code: 'pln', label: 'Polish Złoty' },
    // qar: { code: 'qar', label: 'Qatari Riyal' },
    // ron: { code: 'ron', label: 'Romanian Leu' },
    rub: { code: 'rub', label: 'Russian Ruble' },
    sar: { code: 'sar', label: 'Saudi Riyal' },
    sek: { code: 'sek', label: 'Swedish Krona' },
    sgd: { code: 'sgd', label: 'Singapore Dollar' },
    thb: { code: 'thb', label: 'Thai Baht' },
    // tnd: { code: 'tnd', label: 'Tunisian Dinar' },
    try: { code: 'try', label: 'Turkish Lira' },
    twd: { code: 'twd', label: 'New Taiwan Dollar' },
    // tzs: { code: 'tzs', label: 'Tanzanian Shilling' },
    // uah: { code: 'uah', label: 'Ukrainian Hryvnia' },
    // ugx: { code: 'ugx', label: 'Ugandan Shilling' },
    usd: { code: 'usd', label: 'United States Dollar' },
    // uyu: { code: 'uyu', label: 'Uruguayan Peso' },
    vnd: { code: 'vnd', label: 'Vietnamese Đồng' },
    // xaf: { code: 'xaf', label: 'Central African CFA Franc' },
    // xof: { code: 'xof', label: 'West African CFA Franc' },
    zar: { code: 'zar', label: 'South African Rand' },
};
