import { FiatCurrencyCode } from 'invity-api';

type MapType<T extends FiatCurrencyCode> = { [K in T]: { code: K; label: string } };

export const supportedFiatCurrenciesMap: MapType<FiatCurrencyCode> = {
    aed: { code: 'aed', label: 'United Arab Emirates Dirham' },
    ars: { code: 'ars', label: 'Argentine Peso' },
    aud: { code: 'aud', label: 'Australian Dollar' },
    bdt: { code: 'bdt', label: 'Bangladeshi Taka' },
    brl: { code: 'brl', label: 'Brazilian Real' },
    cad: { code: 'cad', label: 'Canadian Dollar' },
    chf: { code: 'chf', label: 'Swiss Franc' },
    clp: { code: 'clp', label: 'Chilean Peso' },
    cny: { code: 'cny', label: 'Chinese Yuan' },
    czk: { code: 'czk', label: 'Czech Koruna' },
    dkk: { code: 'dkk', label: 'Danish Krone' },
    eur: { code: 'eur', label: 'Euro' },
    gbp: { code: 'gbp', label: 'British Pound Sterling' },
    hkd: { code: 'hkd', label: 'Hong Kong Dollar' },
    huf: { code: 'huf', label: 'Hungarian Forint' },
    idr: { code: 'idr', label: 'Indonesian Rupiah' },
    ils: { code: 'ils', label: 'Israeli Shekel' },
    inr: { code: 'inr', label: 'Indian Rupee' },
    jpy: { code: 'jpy', label: 'Japanese Yen' },
    krw: { code: 'krw', label: 'South Korean Won' },
    kwd: { code: 'kwd', label: 'Kuwaiti Dinar' },
    lkr: { code: 'lkr', label: 'Sri Lankan Rupee' },
    mxn: { code: 'mxn', label: 'Mexican Peso' },
    myr: { code: 'myr', label: 'Malaysian Ringgit' },
    nok: { code: 'nok', label: 'Norwegian Krone' },
    nzd: { code: 'nzd', label: 'New Zealand Dollar' },
    php: { code: 'php', label: 'Philippine Peso' },
    pln: { code: 'pln', label: 'Polish Złoty' },
    rub: { code: 'rub', label: 'Russian Ruble' },
    sar: { code: 'sar', label: 'Saudi Riyal' },
    sek: { code: 'sek', label: 'Swedish Krona' },
    sgd: { code: 'sgd', label: 'Singapore Dollar' },
    thb: { code: 'thb', label: 'Thai Baht' },
    try: { code: 'try', label: 'Turkish Lira' },
    twd: { code: 'twd', label: 'New Taiwan Dollar' },
    usd: { code: 'usd', label: 'United States Dollar' },
    vnd: { code: 'vnd', label: 'Vietnamese Đồng' },
    zar: { code: 'zar', label: 'South African Rand' },
};
