import type { Account, StellarTokenInfo } from '@suite-common/wallet-types';
import type { TokenDetailByMint } from '@trezor/blockchain-link-types';
import { getTokenMetadata } from '@trezor/blockchain-link-utils/src/stellar';
import {
    STELLAR_DECIMALS,
    fitStellarMemoText,
    isStellarClassicAssetKey,
} from '@trezor/network-stellar/constants';
import stellar from '@trezor/network-stellar/runtime';
import { createLazy, scheduleAction } from '@trezor/utils';

export const lazyStellarTokenMetadata = createLazy(getTokenMetadata);

/** Resolves a pasted Stellar Asset Contract id to the classic asset the definitions list. */
export const resolveStellarContractId = async (contractId: string) => {
    const { resolveClassicAssetFromContractId } = await stellar();

    return resolveClassicAssetFromContractId(
        contractId,
        await lazyStellarTokenMetadata.getOrInit(),
    );
};

/** The token name as trustline memo; the operation already carries code and issuer. */
export const getStellarTrustlineMemoFromMetadata = (
    contract: string,
    tokenMetadata: TokenDetailByMint,
): string | undefined => fitStellarMemoText(tokenMetadata[contract]?.name ?? '') || undefined;

// The definitions are fetched over the network, and this runs on the way to a device prompt.
const TRUSTLINE_MEMO_TIMEOUT_MS = 3000;

/** Bounded: the memo must not delay the device prompt. */
export const getStellarTrustlineMemo = async (contract: string) => {
    try {
        const tokenMetadata = await scheduleAction(() => lazyStellarTokenMetadata.getOrInit(), {
            timeout: TRUSTLINE_MEMO_TIMEOUT_MS,
        });

        return getStellarTrustlineMemoFromMetadata(contract, tokenMetadata);
    } catch {
        // A trustline signs and settles without a memo.
        return undefined;
    }
};

// The definitions spell an asset code the way their source did, a trustline carries the on-chain
// one, and the two files are built by separate runs. Matching them case-insensitively keeps one
// asset from being offered twice, or offered again once its trustline exists.
const getAssetKey = (contract: string) => contract.toLowerCase();

/**
 * Get the list of inactive Stellar tokens for the user account.
 *
 * `knownContracts` is the coin-definitions allow-list, which decides what Suite recognizes; the
 * advanced definitions only add display metadata. The two files are generated by separate runs and
 * do disagree — USDC has been listed by the allow-list and missing from the advanced file — so an
 * asset is offered as soon as either names it.
 */
export const getStellarInactiveTokens = async (
    account: Account,
    knownContracts: readonly string[] = [],
): Promise<StellarTokenInfo[]> => {
    if (account.symbol !== 'xlm') return [];

    const allTokens: TokenDetailByMint = await getTokenMetadata();

    // A trustline exists, so the asset is no longer one to offer.
    const activeAssetKeys = new Set(
        account.tokens?.map(token => getAssetKey(token.contract)) || [],
    );

    const detailByAssetKey = new Map(
        Object.entries(allTokens).map(([contract, detail]) => [getAssetKey(contract), detail]),
    );

    // The allow-list is read first, so where the two files disagree its spelling wins: that is the
    // one a trustline has to carry for Suite to recognize the token afterwards.
    const inactiveContractByAssetKey = new Map<string, string>();
    [...knownContracts, ...Object.keys(allTokens)]
        // A native SEP-41 token has no trustline to activate; it is watched by contract id instead.
        .filter(isStellarClassicAssetKey)
        .forEach(contract => {
            const assetKey = getAssetKey(contract);

            if (!activeAssetKeys.has(assetKey) && !inactiveContractByAssetKey.has(assetKey)) {
                inactiveContractByAssetKey.set(assetKey, contract);
            }
        });

    const inactiveTokens = [...inactiveContractByAssetKey.values()]
        .map(contract => {
            const detail = detailByAssetKey.get(getAssetKey(contract));

            return {
                type: 'STELLAR-CLASSIC' as const,
                standard: 'STELLAR-CLASSIC' as const,
                contract,
                name: detail?.name,
                symbol: contract.split('-')[0],
                decimals: STELLAR_DECIMALS,
                homeDomain: detail?.home_domain,
                rating: detail?.rating,
            };
        })
        .sort((a, b) => {
            // Place tokens without ratings last, otherwise sort high to low
            if (a.rating == null && b.rating == null) return 0;
            if (a.rating == null) return 1;
            if (b.rating == null) return -1;

            return b.rating - a.rating;
        });

    return inactiveTokens;
};
